# PV-UAD → AG-ReID.v2 Aerial→Ground
## E2=60 → E3=25 + trainable TransReID initialization + flip-TTA

Bản này chuyển pipeline WHU-MARS-1000 đã đạt **11.877 mAP** sang
**AG-ReID.v2** tại:

`/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2.`

Protocol mặc định: **aerial → ground**.

Những phần giữ từ pipeline 11.877:

- ViT-Base 768-D, stride `[16,16]`;
- pretrained MSMT17 TransReID → transplant vào UAD backbone và **fine-tune toàn bộ**;
- E2 = **60 epoch**, SGD, LR 0.008, global batch 24;
- VF-ProCA + GPD;
- E3 = **25 epoch**, LR 1e-4, head LR ×5;
- E2 teacher feature-preservation + scenario-hard GPD;
- final horizontal-flip TTA;
- Kaggle T4×2 multi-session resume.

Thay đổi bắt buộc vì AG-ReID.v2 là **RGB-only**:

- bỏ TIR distillation (không có NIR/TIR để distill);
- dùng **view-balanced PKM**: mỗi identity ưu tiên 2 ground + 2 aerial images trong group 4;
- remap camera để view-factorized ProCA hiểu đúng:
  `C2 wearable→0`, `C3 CCTV→1`, `C0 UAV→2`, với `GROUND_MAX_CAMID=1`;
- evaluator chạy đúng query aerial C0 → gallery ground C2/C3.

Ngoài ra notebook **không giả định best checkpoint = last checkpoint**:
E3 được warm-start từ **E2 epoch 60 + prototype cùng epoch 60**, và cuối cùng
report cả **best-E3 + TTA** lẫn **E3 epoch 25 + TTA** để bạn nhìn trực tiếp hai checkpoint có thật sự giống nhau hay không.

> **v6 DDP evaluation fix:** AG-ReID.v2 has only one modality. In the previous
> version, distributed evaluation assigned that single validation loader to
> rank 0 only, while rank 1 entered a NCCL synchronization. That can trigger
> the ~10-minute ProcessGroupNCCL watchdog timeout around an evaluation epoch.
> This version makes both GPUs evaluate the single AG-ReID.v2 loader
> independently with the **unwrapped model** (no DDP collectives during
> inference), then synchronizes only after both ranks have finished.
>
> The internal `PIPELINE_TAG` intentionally remains the v5 tag so an attached
> v5 output containing `pvuad_last_checkpoint.pth` can be resumed instead of
> throwing away the previous 2.5 hours.

In [1]:
# ============================================================
# 0. SETTINGS — AG-ReID.v2 aerial->ground, multi-session
# ============================================================

import time as _time
NOTEBOOK_SESSION_STARTED_UNIX = _time.time()

PIPELINE_NAME = "PVUAD_AGREIDV2_E2_E3_TRANSREID"
PIPELINE_TAG = "agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix"

# Exact Kaggle dataset path supplied by the user.
AGREIDV2_INPUT = "/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2."
AG_PROTOCOL = "aerial_to_ground"

SOURCE_DIR_OVERRIDE = None

# Official MSMT17 full TransReID checkpoint.
TRANSREID_CHECKPOINT_OVERRIDE = None
PRETRAIN_PATH_OVERRIDE = None
RUN_TRANSREID_INIT_SMOKE_TEST = True

# Keep the winning WHU-1000 backbone recipe.
TRANSREID_TARGET_STRIDE = [16, 16]
TRANSREID_TARGET_EMBED_DIM = 768
USE_SOURCE_SIE = False
USE_SOURCE_JPM_LOCAL_BRANCHES = False

# Optional emergency overrides. Normally leave all three as None.
E2_RESUME_PATH_OVERRIDE = None
E2_COMPLETED_DIR_OVERRIDE = None
E3_RESUME_PATH_OVERRIDE = None

AUTO_RESUME = True
ALLOW_LEGACY_E2_BOOTSTRAP = False
RUN_TRAINING = True
RUN_FINAL_FLIP_TTA = True
RUN_METADATA_PAIRING_CHECK = True

# Keep the stage boundary explicit so a Kaggle 12h session can be resumed safely.
ALWAYS_START_E3_IN_NEW_SESSION = True

# Fixed horizons requested by the user.
E2_EPOCHS = 60
E2_GLOBAL_BATCH = 24
E2_BASE_LR = 0.008

E3_EPOCHS = 25
E3_GLOBAL_BATCH = 24
E3_BASE_LR = 1e-4
E3_HEAD_LR_MULTIPLIER = 5.0

# E3 keeps the transferable pieces of the WHU winner.
# TIR distillation is intentionally disabled because AG-ReID.v2 is RGB-only.
FEATURE_PRESERVE_WEIGHT = 0.05
SCENARIO_HARD_WEIGHT = 0.15
SCENARIO_HARD_TOPK = 5
SCENARIO_HARD_MARGIN = 0.05
SCENARIO_HARD_TAU = 0.05
SCENARIO_HARD_START_EPOCH = 3

# AG-ReID.v2 camera remap used by the patched loader:
# C2 wearable -> 0 (ground), C3 CCTV -> 1 (ground), C0 UAV -> 2 (aerial).
GROUND_MAX_CAMID = 1

# One Kaggle session lasts at most 12 h.
SESSION_HARD_STOP_HOURS = 10.5
SESSION_STOP_RESERVE_MINUTES = 15
CHECKPOINT_EVERY_MINUTES = 30
TIME_CHECK_EVERY_STEPS = 10
MIN_EVAL_REMAINING_MINUTES = 25
MIN_E3_START_REMAINING_MINUTES = 75
MIN_TTA_START_REMAINING_MINUTES = 35

NUM_GPUS = 2
NUM_WORKERS = 4
RANDOM_SEED = 1234

if AG_PROTOCOL != "aerial_to_ground":
    raise ValueError("This notebook is locked to AG-ReID.v2 aerial->ground.")
if E2_GLOBAL_BATCH != 24 or abs(E2_BASE_LR - 0.008) > 1e-12:
    raise ValueError("E2 must stay at global batch 24 / LR 0.008.")
if E3_GLOBAL_BATCH != 24 or abs(E3_BASE_LR - 1e-4) > 1e-12:
    raise ValueError("E3 must stay at global batch 24 / LR 1e-4.")
if TRANSREID_TARGET_STRIDE != [16, 16]:
    raise ValueError("Keep UAD stride [16,16] for this transfer experiment.")
if TRANSREID_TARGET_EMBED_DIM != 768:
    raise ValueError("This pipeline must keep the UAD 768-D feature space.")
if USE_SOURCE_SIE or USE_SOURCE_JPM_LOCAL_BRANCHES:
    raise ValueError("Source SIE/JPM local branches must remain disabled.")

SESSION_DEADLINE_UNIX = (
    NOTEBOOK_SESSION_STARTED_UNIX + 3600.0 * SESSION_HARD_STOP_HOURS
)

print(
    PIPELINE_NAME,
    {
        "dataset": "AG-ReID.v2",
        "protocol": AG_PROTOCOL,
        "E2_epochs": E2_EPOCHS,
        "E3_epochs": E3_EPOCHS,
        "init": "MSMT17 TransReID -> trainable UAD ViT",
        "feature_dim": TRANSREID_TARGET_EMBED_DIM,
        "target_stride": TRANSREID_TARGET_STRIDE,
        "TIR_distillation": False,
    },
)

PVUAD_AGREIDV2_E2_E3_TRANSREID {'dataset': 'AG-ReID.v2', 'protocol': 'aerial_to_ground', 'E2_epochs': 60, 'E3_epochs': 25, 'init': 'MSMT17 TransReID -> trainable UAD ViT', 'feature_dim': 768, 'target_stride': [16, 16], 'TIR_distillation': False}

## 1. Kiểm tra môi trường

In [2]:
import base64
import csv
import hashlib
import importlib.util
import io
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zipfile
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import torch

if not torch.cuda.is_available():
    raise RuntimeError("Enable a Kaggle GPU accelerator and restart the session.")
if torch.cuda.device_count() < NUM_GPUS:
    raise RuntimeError(
        f"This run expects {NUM_GPUS} GPUs, but Kaggle exposes {torch.cuda.device_count()}. "
        "Choose GPU T4 x2 in Notebook options."
    )

for package, pip_name in [("yacs", "yacs==0.1.8"), ("timm", "timm>=0.9,<2"), ("gdown", "gdown>=5,<6")]:
    if importlib.util.find_spec(package) is None:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", pip_name],
            check=True,
        )

gpu_rows = []
for index in range(NUM_GPUS):
    props = torch.cuda.get_device_properties(index)
    gpu_rows.append({
        "index": index,
        "name": props.name,
        "memory_GiB": round(props.total_memory / 2**30, 2),
    })
display(pd.DataFrame(gpu_rows))
print("Python:", sys.version.split()[0])
print("PyTorch:", torch.__version__)
print("CUDA runtime:", torch.version.cuda)

   index      name  memory_GiB
0      0  Tesla T4       14.56
1      1  Tesla T4       14.56

Python: 3.12.13
PyTorch: 2.10.0+cu128
CUDA runtime: 12.8

## 2. Khóa AG-ReID.v2 và protocol Aerial→Ground — nested-folder fix

AG-ReID.v2 **không để ảnh trực tiếp trong `train_all/query/gallery`**.
Bản official thường có một tầng thư mục identity ở giữa, ví dụ:

`train_all/P0001T04041A0/*.jpg`  
`query/P0000T02140A0/*.jpg`  
`gallery/P0000T02140A0/*.jpg`

Bản v2 này vì vậy:

- tìm Kaggle mount ở cả path user đưa **và** `/kaggle/input/ag-reid-v2`;
- tự tìm dataset root bên dưới `/kaggle/input` nếu mount name khác;
- quét ảnh **recursive** trong `train_all/query/gallery`;
- vẫn hỗ trợ challenge layout `bounding_box_train/exp3_aerial_to_ground/...`;
- bắt buộc audit đúng **807 train IDs**, **808 query IDs**, **808 gallery IDs**;
- filter protocol đúng **C0 aerial query → C2/C3 ground gallery**.

In [3]:
# ============================================================
# 2. Resolve and audit AG-ReID.v2 aerial->ground
#    FIX: official AG-ReID.v2 stores images inside per-ID folders.
# ============================================================

IMAGE_SPLITS = {
    "train", "train_all", "bounding_box_train",
    "query", "gallery", "bounding_box_test",
    "exp3_aerial_to_ground", "exp3_a2g",
    "gallery_add_on",
}

AG_PID_RE = re.compile(r"P(\d+)T(\d+)A(\d+)", re.IGNORECASE)
AG_CAM_RE = re.compile(r"C(\d+)F(\d+)", re.IGNORECASE)
AG_CAM_REMAP = {2: 0, 3: 1, 0: 2}
IMAGE_EXTS = {".jpg", ".jpeg", ".png"}

def image_files(path):
    """Return images recursively; AG-ReID.v2 uses per-identity subfolders."""
    path = Path(path)
    if not path.is_dir():
        return []
    values = []
    for root, _dirs, files in os.walk(path):
        root = Path(root)
        for name in files:
            p = root / name
            if p.suffix.lower() in IMAGE_EXTS:
                values.append(p)
    return sorted(values)

def has_images(path):
    path = Path(path)
    if not path.is_dir():
        return False
    # Cheap recursive early-exit.
    for root, _dirs, files in os.walk(path):
        if any(Path(name).suffix.lower() in IMAGE_EXTS for name in files):
            return True
    return False

def first_image_dir(root, relatives):
    for relative in relatives:
        candidate = Path(root) / relative
        if has_images(candidate):
            return candidate
    return None

def resolve_ag_layout(root):
    root = Path(root)

    train_dir = first_image_dir(root, [
        "train_all",
        "bounding_box_train",
        "train",
    ])

    query_dir = first_image_dir(root, [
        "query",
        "exp3_aerial_to_ground/query",
        "exp3_A2G/query",
    ])

    primary_gallery = first_image_dir(root, [
        "gallery",
        "exp3_aerial_to_ground/bounding_box_test",
        "exp3_aerial_to_ground/gallery",
        "exp3_A2G/bounding_box_test",
        "exp3_A2G/gallery",
        "bounding_box_test",
    ])

    if train_dir is None or query_dir is None or primary_gallery is None:
        return None

    gallery_dirs = [primary_gallery]
    for relative in (
        "gallery_add_on/exp3_aerial_to_ground",
        "gallery_add_on/exp3_A2G",
    ):
        candidate = root / relative
        if has_images(candidate):
            gallery_dirs.append(candidate)

    return train_dir, query_dir, gallery_dirs

def discover_candidate_roots():
    requested = Path(AGREIDV2_INPUT)

    # Kaggle normally mounts a dataset as /kaggle/input/<slug>.
    starting_points = [
        requested,
        Path("/kaggle/input/ag-reid-v2"),
        Path("/kaggle/input/datasets/thienbao1604/ag-reid-v2"),
    ]

    candidates = []

    def add_candidate(path):
        path = Path(path)
        if path.is_dir() and path not in candidates:
            candidates.append(path)

    for start in starting_points:
        add_candidate(start)

    # Search /kaggle/input by directory NAMES only. Do not descend into the
    # large split trees; this keeps discovery fast even with 100k images.
    kaggle_input = Path("/kaggle/input")
    if kaggle_input.is_dir():
        for root, dirs, _files in os.walk(kaggle_input):
            root = Path(root)
            try:
                depth = len(root.relative_to(kaggle_input).parts)
            except ValueError:
                depth = 99

            lower_dirs = {d.lower(): d for d in dirs}

            if any(name in lower_dirs for name in (
                "train_all", "bounding_box_train", "train"
            )):
                add_candidate(root)

            # If this directory itself is a likely AG root, keep it.
            if root.name.lower() in {
                "ag-reid.v2", "ag_reid_v2", "ag-reid-v2", "agreidv2"
            }:
                add_candidate(root)

            # Never recurse into huge image split folders during root discovery.
            dirs[:] = [
                d for d in dirs
                if d.lower() not in {
                    "train_all", "bounding_box_train", "train",
                    "query", "gallery", "bounding_box_test",
                }
            ]

            if depth >= 7:
                dirs[:] = []

    return candidates

candidate_roots = discover_candidate_roots()

resolved = []
for root in candidate_roots:
    layout = resolve_ag_layout(root)
    if layout is not None:
        resolved.append((root, layout))

if not resolved:
    preview = []
    for base in (
        Path("/kaggle/input/ag-reid-v2"),
        Path("/kaggle/input"),
    ):
        if not base.is_dir():
            continue
        for root, dirs, files in os.walk(base):
            root = Path(root)
            try:
                depth = len(root.relative_to(base).parts)
            except ValueError:
                depth = 99
            if depth <= 4:
                preview.append({
                    "path": str(root),
                    "dirs": sorted(dirs)[:20],
                    "image_files_here": sum(
                        Path(name).suffix.lower() in IMAGE_EXTS for name in files
                    ),
                })
            dirs[:] = [
                d for d in dirs
                if d.lower() not in {
                    "train_all", "bounding_box_train", "train",
                    "query", "gallery", "bounding_box_test",
                }
            ]
            if depth >= 4:
                dirs[:] = []
        if preview:
            break

    if preview:
        display(pd.DataFrame(preview).head(100))

    raise FileNotFoundError(
        "Cannot resolve AG-ReID.v2. The notebook checked both the user path "
        f"({AGREIDV2_INPUT}) and normal Kaggle mounts under /kaggle/input. "
        "Expected a root containing train_all/query/gallery (nested identity "
        "folders are supported) or the challenge exp3 layout."
    )

requested = Path(AGREIDV2_INPUT)
resolved.sort(
    key=lambda item: (
        int(item[0] == requested),
        int("ag-reid" in str(item[0]).lower() or "agreid" in str(item[0]).lower()),
        len(item[0].parts),
        str(item[0]),
    ),
    reverse=True,
)
DATA_ROOT, (TRAIN_DIR, QUERY_DIR, GALLERY_DIRS) = resolved[0]

def parse_ag_filename(path):
    name = Path(path).name
    pid_match = AG_PID_RE.search(name)
    cam_match = AG_CAM_RE.search(name)
    if pid_match is None or cam_match is None:
        raise ValueError(f"Unexpected AG-ReID.v2 filename: {name}")

    p, t, a = pid_match.groups()

    # Keep the same identity key as the official AG-ReID tooling/pipeline:
    # P + T + A together identify the instance identity folder.
    pid = int(p + t + a)

    original_cam = int(cam_match.group(1))
    if original_cam not in AG_CAM_REMAP:
        raise ValueError(f"Unexpected camera C{original_cam}: {name}")

    return pid, original_cam, AG_CAM_REMAP[original_cam]

def summarize(paths, allowed_original_cams=None):
    rows = []
    for path in paths:
        pid, original_cam, remapped_cam = parse_ag_filename(path)
        if (
            allowed_original_cams is not None
            and original_cam not in allowed_original_cams
        ):
            continue
        rows.append((path, pid, original_cam, remapped_cam))

    return pd.DataFrame(
        rows,
        columns=["path", "pid", "camera_original", "camera_remapped"],
    )

print("Scanning nested AG-ReID.v2 split folders...")
train_paths = image_files(TRAIN_DIR)
query_paths = image_files(QUERY_DIR)

gallery_paths = []
for directory in GALLERY_DIRS:
    gallery_paths.extend(image_files(directory))
gallery_paths = sorted(set(gallery_paths))

train_frame = summarize(train_paths)
query_frame = summarize(query_paths, allowed_original_cams={0})
gallery_frame = summarize(gallery_paths, allowed_original_cams={2, 3})

if train_frame.empty or query_frame.empty or gallery_frame.empty:
    raise RuntimeError(
        "Resolved AG-ReID.v2 layout contains an empty required split after "
        "Aerial->Ground camera filtering."
    )

audit = pd.DataFrame([
    {
        "split": "train",
        "images": len(train_frame),
        "ids": train_frame["pid"].nunique(),
        "cameras": sorted(train_frame["camera_original"].unique().tolist()),
    },
    {
        "split": "query_aerial_C0",
        "images": len(query_frame),
        "ids": query_frame["pid"].nunique(),
        "cameras": sorted(query_frame["camera_original"].unique().tolist()),
    },
    {
        "split": "gallery_ground_C2_C3",
        "images": len(gallery_frame),
        "ids": gallery_frame["pid"].nunique(),
        "cameras": sorted(gallery_frame["camera_original"].unique().tolist()),
    },
])
display(audit)

if train_frame["pid"].nunique() != 807:
    raise RuntimeError(
        f"Expected 807 train IDs, got {train_frame['pid'].nunique()}. "
        f"Resolved train dir: {TRAIN_DIR}"
    )
if query_frame["pid"].nunique() != 808:
    raise RuntimeError(
        f"Expected 808 aerial query IDs, got {query_frame['pid'].nunique()}. "
        f"Resolved query dir: {QUERY_DIR}"
    )
if gallery_frame["pid"].nunique() != 808:
    raise RuntimeError(
        f"Expected 808 ground gallery IDs, got {gallery_frame['pid'].nunique()}. "
        f"Resolved gallery dirs: {GALLERY_DIRS}"
    )

missing_gallery_ids = sorted(
    set(query_frame["pid"]) - set(gallery_frame["pid"])
)
if missing_gallery_ids:
    raise RuntimeError(
        f"Query IDs missing from ground gallery: {missing_gallery_ids[:20]}"
    )

print("Resolved AG-ReID.v2:", DATA_ROOT)
print("Train dir          :", TRAIN_DIR)
print("Query dir (C0)     :", QUERY_DIR)
print("Gallery dirs (C2/3):", GALLERY_DIRS)

# Link the real dataset root into the name expected by the patched UAD loader.
DATA_LINK_PARENT = Path("/kaggle/working/pvuad_agreid_data")
DATA_LINK_PARENT.mkdir(parents=True, exist_ok=True)
DATA_LINK = DATA_LINK_PARENT / "AG-ReID.v2"

if DATA_LINK.is_symlink():
    DATA_LINK.unlink()
elif DATA_LINK.exists():
    resolved_link = DATA_LINK.resolve()
    if not str(resolved_link).startswith("/kaggle/working/"):
        raise RuntimeError(f"Refusing to remove unsafe path: {resolved_link}")
    shutil.rmtree(DATA_LINK)

DATA_LINK.symlink_to(DATA_ROOT, target_is_directory=True)

AG_TRAIN_ID_COUNT = int(train_frame["pid"].nunique())
AG_QUERY_ID_COUNT = int(query_frame["pid"].nunique())
AG_GALLERY_ID_COUNT = int(gallery_frame["pid"].nunique())

DATASET_AUDIT = {
    "dataset": "AG-ReID.v2",
    "protocol": "aerial_to_ground",
    "root": str(DATA_ROOT),
    "train_dir": str(TRAIN_DIR),
    "query_dir": str(QUERY_DIR),
    "gallery_dirs": [str(p) for p in GALLERY_DIRS],
    "train_images": int(len(train_frame)),
    "train_ids": AG_TRAIN_ID_COUNT,
    "query_images": int(len(query_frame)),
    "query_ids": AG_QUERY_ID_COUNT,
    "gallery_images": int(len(gallery_frame)),
    "gallery_ids": AG_GALLERY_ID_COUNT,
    "camera_remap": {"C2_ground": 0, "C3_ground": 1, "C0_aerial": 2},
    "recursive_split_scan": True,
}
(Path("/kaggle/working") / "agreid_v2_dataset_audit.json").write_text(
    json.dumps(DATASET_AUDIT, indent=2),
    encoding="utf-8",
)
print("UAD data link:", DATA_LINK)

Scanning nested AG-ReID.v2 split folders...

                  split  images  ids    cameras
0                 train   51530  807  [0, 2, 3]
1       query_aerial_C0    4348  808        [0]
2  gallery_ground_C2_C3   19259  808     [2, 3]

Resolved AG-ReID.v2: /kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2
Train dir          : /kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/train_all
Query dir (C0)     : /kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/query
Gallery dirs (C2/3): [PosixPath('/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/gallery')]
UAD data link: /kaggle/working/pvuad_agreid_data/AG-ReID.v2

## 3. Pin source UAD + patch AG-ReID.v2 + TransReID initialization

Notebook vẫn pin source UAD tại commit gốc của pipeline 11.877, sau đó áp overlay
được đóng gói ngay trong notebook. Overlay thêm:

- loader AG-ReID.v2;
- view-balanced PKM sampler cho RGB aerial/ground;
- dynamic scenario classes = `2 × số modalities` (AG-ReID.v2 = 2);
- source UAD/TransReID 768-D như pipeline cũ;
- multi-session processor và evaluator.

Checkpoint TransReID vẫn là official MSMT17 `vit_transreid_msmt.pth`.

In [4]:
PINNED_UAD_COMMIT = "3e2a07314119402586c76096e87d40420894ad30"
OFFICIAL_REPO_URL = "https://github.com/msm8976/WHU-MARS.git"
WORK_REPO = Path("/kaggle/working/WHU_MARS_official_pinned")
UAD_DIR = WORK_REPO / "CVPR26_UAD"

if WORK_REPO.exists():
    resolved = WORK_REPO.resolve()
    if not str(resolved).startswith("/kaggle/working/"):
        raise RuntimeError(f"Unsafe generated-source path: {resolved}")
    shutil.rmtree(WORK_REPO)

def attached_source_candidates(base="/kaggle/input"):
    candidates = []
    base = Path(base)
    if not base.exists():
        return candidates
    for root, dirs, _files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if root_path.name != "CVPR26_UAD" or not (root_path / "train.py").is_file():
            continue
        repo_root = root_path.parent
        declared_commit = None
        manifest_path = root_path / "PVUAD_patch_manifest.json"
        if manifest_path.is_file():
            try:
                declared_commit = json.loads(
                    manifest_path.read_text(encoding="utf-8")
                ).get("base_commit")
            except Exception:
                declared_commit = None
        if (repo_root / ".git").is_dir():
            try:
                declared_commit = subprocess.check_output(
                    ["git", "-C", str(repo_root), "rev-parse", "HEAD"],
                    text=True,
                ).strip()
            except Exception:
                pass
        if declared_commit != PINNED_UAD_COMMIT:
            # Never auto-select an unverified source tree. With no pinned
            # prior output, fall back to cloning the exact official commit.
            dirs[:] = []
            continue
        score = (
            2,
            1 if manifest_path.is_file() else 0,
            1 if "notebooks" in str(repo_root).lower() else 0,
        )
        candidates.append((score, repo_root, declared_commit))
        dirs[:] = []
    return sorted(candidates, key=lambda item: (item[0], str(item[1])), reverse=True)

source = Path(SOURCE_DIR_OVERRIDE) if SOURCE_DIR_OVERRIDE else None
if source is None:
    attached_sources = attached_source_candidates()
    if attached_sources:
        print("Attached UAD source candidates:")
        display(pd.DataFrame([
            {
                "path": str(path),
                "base_commit": commit,
                "selected": index == 0,
            }
            for index, (_score, path, commit) in enumerate(attached_sources)
        ]))
        source = attached_sources[0][1]

if source is not None:
    if (source / "CVPR26_UAD" / "train.py").is_file():
        shutil.copytree(source, WORK_REPO)
    elif source.name == "CVPR26_UAD" and (source / "train.py").is_file():
        WORK_REPO.mkdir(parents=True)
        shutil.copytree(source, UAD_DIR)
    else:
        raise FileNotFoundError(
            f"Attached/override source is not a WHU-MARS source tree: {source}"
        )
    print("Reusing attached UAD source:", source)
else:
    clone_command = [
        "git", "clone", "--no-checkout", "--filter=blob:none",
        OFFICIAL_REPO_URL, str(WORK_REPO),
    ]
    try:
        subprocess.run(clone_command, check=True)
        subprocess.run(
            ["git", "-C", str(WORK_REPO), "checkout", "--detach", PINNED_UAD_COMMIT],
            check=True,
        )
    except subprocess.CalledProcessError as error:
        raise RuntimeError(
            "Cannot clone the pinned official UAD source. Enable Kaggle Internet or attach "
            "the previous notebook output/source and set SOURCE_DIR_OVERRIDE."
        ) from error

if not (UAD_DIR / "train.py").is_file():
    raise FileNotFoundError(f"Missing UAD train.py under {UAD_DIR}")
if (WORK_REPO / ".git").is_dir():
    head = subprocess.check_output(
        ["git", "-C", str(WORK_REPO), "rev-parse", "HEAD"], text=True
    ).strip()
    if head != PINNED_UAD_COMMIT:
        raise RuntimeError(f"Source commit mismatch: expected {PINNED_UAD_COMMIT}, got {head}")

OVERLAY_ARCHIVE_B64 = 'H4sIAFi7pmoC/+y9a3saSZIwOp/5FTX4mVdgIwTIdruZwc9iCdtsy5JWwvbOanRqSlCSqgUUTYEu49fnt5+45L2yEHLbnpk91tNtoCozMjMyMjJuGTlMp+fJxdYoPo+W40VWn9394av/NeDv+dOn9Al/zmer9fynlnzGz5vNp42nfwgaf/gOf8tsEc2h+T/8//PvfJ5OgrtomNWHRAlBMpml80Wwc36xn47iIMqCnf1S6VGw+TX/AN5OOr2Op4sknQbRWbpcBIN5lEyT6UWwFQzibBFks3iYnCfDYBbNo0m8iOfZN+jGx8t4Gl/H8yCCfswvlhPoUzCEH2dxECeLS3izzOJRcJ7Og4XsIXyn39BN+FkLoBiAGqbzeZzN0ukIy0yhz8FNMh4jpFmaLTbPk1sAdHYXREE4OOr29wlIpMGqgda+EcJxfmGlQ2uI96/eRincCTpALpXqN+j+u4Pd3t5Xhxvu1Amw7vf7DKdiuBxFOM3D2dKaelWhvtv70N/pQb0yli1Dzf5uMF1OzoBi0vPgzeF7t2wIBTrBRmMDyu4jdUCxs2h4dZZOY112v/sOoW5Ai9MMmp7Ec6ywF+GSWMyTUUG9ve7xIDweHPV3sXoTqhxGi8tgkQazeUzdB+KbwJIe++sfHvWIKMPD7uAtdmCjRNiIg/4kuoj340UeEAAnWorGyT9iBRPxBmsmyOLxebCqAiyb4OYyHcf8Fpo7mCFhZu1gI8FGp/FiI6gFGwiJvgDpxovlNN7w9Hvn7QFPiK6LI+iLPsBaBHS82t+Ph1e1IFUNnU2n8GQDO70xTQ3A+72dXxCaKGCCGqdZBgMZjpcwG0PgGDDn+MyEexdnCmg92MMa1AOjeHAJ3HWUnJ/Hc+Q6WHcCeAGqo6W6nEe0TFWP+q/Dj/3B23Cntz/oHWHfsMPG+91w7+D4OBz89ZDwkKXni0l0u5Ev8bHXf/N2gHRSb+i3QDyHe73BqiKHO13ndcN8/eZwN3x38A769/4dvWsZ3XsHE9XfsbsIBD0b40y5EzUBaSTZvIDlNxrNiD5M5A7my3gD6OF1NM5MYtjtwyJg3toJ6GUOMCIlEM3mJq0I7v5B+K579GYF2HF0BvSdTdJ0cWlCTKcILz0/37Dmca/7qrd3/O7ggNcalMpBjObD82gYr93HnYNjAPtXIgzuI4AcaC4C63GxsFnY0cGhXO6NetN5cfA+N73dwSCkd0fdQc99CWjfP359cPSud6Smdz+11iqzp/C4/z/49qT5vBY0n59iP//z8B3wK7H96Qr4WI5GQ3nbfz0I94nCnpmP379+vdcL3xwdvD+EVy2b/0K7e739NzTYp/rVUS/sHkHP32CPELXYm+N+z9cbeBzuHGDBbXPg9Bi49lHX01d496Hf+2jOSZ51vf2IGO0fiNX2DXbP/v7h+8G32D0JsN49j5Gvw/6CrJ3YcDBaznFDNTdQqlNHKlBr9aT1DImh9eJ0JRAQuFwAveOBW/8omo5Aqp3N07PoLBknizvawxnUZTpP/pFOF9E4OB8nMw3u8OjgFdH0s2IQc34cz6PMGgtQkVX9QzRexhludyD8KfmROzCF1Yj7n2Luovn+f/f2wne9LqGjUX/64lkNoD3FccFH4/np74F7PNhlsK3Wzwiv1XrKH88UWMT4LBqR8JrBDBgguru7/f03SJ3fhDh3o0UEzOlbkOdud9A97g2ONYXuJSBICeIaccMkq2eWnFdDxQfknQw3ZuDIM5ClsnAI5cfpBSjJJmwS2bCFysbHt+83YaM43sCWjmAvgO19Hg8X6fwOJB3Y5mWTWZBdpsvxSM1jBSgrGKU303EajeB3cg4TuoA+LaejqtXaEWwa4W7/iBqs17cQIrV3MB9BCyRqRYJix/BEjA7gwPc4GsIWOIPXume1IK5f1HnoW3+RtV9uPa7/Oruwmga21d3rD/pitEdvXuFG1D/CfwcwPKA/6Mm3IpE9xMz8W1HJ3kF3l/ZOQSf7SpRHBAc4LcSCLudxNMrsWnXYjMKPB0e/9I4QMy+Qh0UTkDBYTzQBOBWPu+9A5CJZ7vCXdxtWu8k0W0RTkAAQBsrVZ9FieOlpub9/POjuk+zbfP61sR88wtGk4+uvjnqADGM5Ptj7YOFdaEZKGtaF6geHg/474PpHodCSyt1RNClbWAOBN4hn6fAyzoya77r/HfYOD3beHhMXa0CVV7AOg3EczUn3Blk7Nsq/AoIP97Bb2/HmU7YTCGMAlh5H8wsU4s3aNE3nQ3h3Z3V6DwTHXvh6h8FJ6fF1hGsPO6yAnCWR2eVX/S4IdEfh6+7O4OBI6HT3Vzvu9ZDVN1vb2O13KRo0lhMTFaZ8/jOWgcEAi0OeaIjFFvKE6NuobyMHtUYN1Y7f7OKWRD0ivso6TobvDHXHgMgaDGOEd8xX0RhpfRTcxMnF5eL+qq4S0mg8I9GNhVxqW4AaxcPozoDAtcLd3k73r7qu/32Is2A1QNDU0Ivo50333buuEKtlnWwRz1bVOR70DomxPm3Ugp8auBhuovkkWM6Cc5p2s4/do3fvDzVtQP+wIVWBVkCWr6DWAOIcxNvLdESY4mpSzQAtA1RQ5D6LjdrGGJTuaL6RBwYK3dsDJLYyFymXzHk6OO7v90KDdp7l3x7vdPdInia5gjpt2FCy6JpsMZegf8/SZLqw6OAt6OeHB/39QXjYO+pTP5q4rhMgGpKBiHcnsNkB7pWNDbZvc20evDFrNzyduIbdcKRkKlGv96G75zRr8G0Ux0B6gF/MsUENu0yyAP67GIM8Oa6BEoob/A1Io9F1HLxAa1EWoATQf3eMcMNX3cHOW1rGL2q8aUMRMieSoRHEV1ixzef5tnQfXVDPn5askWstvHwGrLD8TTYOFM+/PlwchxD8c7u1ixFXd8B6dQ+ahf6NlmdSv+fxJkj7VyQLusq3oXsTOBD/QYX8hWVkyeGl+c2ygKkqinWVy7S7JNDT8zhaLOfEV9hO5Qr62LsaPIHvZGWLzpFBQtmpa9SiImx/okK6r2jWCl/3uti2fKe3N9kFoNVpSuoEmqy5QW4d6PYuzuBzgYXi35YJrBCUkqGvwxR2xxgXHQkuqk1sLtw/OMI9hwxj0GKDRjRFuWaRzsKrIAY4S1poMBLszE2SCQt6Oh3fyfeyOMjm6LAiKJPuoWprcHAY/hLiAgWeI+UJLCS4Ccn90MFJtBD4E2b8ugJBVqR3hKEyFg2hbH06uysbiBpG4+FyTN0BgNi3IBvStEgOmrfTEHDsmWkN+OpL7vDD5vvuLuIHWDJQVXy7iKcZEsa3aK0HciFsbbBkcKkJLyKR/SUS8nkyTAA12KGzGJhdki7n9eCX6OJiHLN+BaXjaXQ2xiUDdSbBcDlBxCbXMUx6pdcMNl8GvadV5JkIM8P5HMJaQqZFnhpQ0kdLEJMj2CYTWBRnY6Iims/DD9i0YBPyd73338i7UQzCKe41yvoVSNJkCiqfJ9NoXA6sv0dAD/F1GXfoxhZsF6xJVXGZifIa0G7vQ4hmHtMmpN/g/tHflcKo9er4EFSsUIhxrUbruf36v973jv5KzOuwv4t2J5IMdZnDbv+ot0tGp1BrF04Xjv+6vxOKkt33b/IF0Ii2vxui2AxNkOPiqYkHNucPo0nQ34WdC+geJPV0E+dk1A6GzXp9+MxE6lF/ZyAbRO1FGdtUmQ+vD48Odrr5rtBIQO18s48TZsp8Rgv9/Q/do34X3gNS/EWOQXKEMgfhzp4lOTZ1EVygoQb1aq+3vyvA6EJ70Mu9cOdg/xjYRG9/56/5LueKWJKqCext92g3fHO4m4ch3xSMRr0GfvcLyyD5d4bw5X0PxH40YJlQGXd625uD3bckEW6ia3wRoNNlc7FE8akeoOjH1R6brpwomMY3wGpg201Q4/gz2j96x+/f9djAPI8nsAtmxJXm12I7g7WboIg/X84W8Ki3HcyXUxKDoBjIu2jpIs+q0gW3MhAGR0tQrLeOYLONb0EuHt/plV5/DVLl4P2+Z9XpjpPxVdq9y2VfESDFwQFKR75ig14XhM+jYjhve91d1Nzevd8b9GE10woUht1DYFEw1qM3r7b2+0fI2wbwgbsMbHTMt4I3JCUGgNmLKfmjYaONxjfRHXxcR8kYueWfmV2CPAs7EWxhKL9ngDByHY1i2H03Wf2BxrZvt9GABQx6gv/KvU6Mpn8U4obX39tDE/R+HnNY4s3ewSsgaXPZNOwSTPMmnW/7CvzS6x0qYzdQtAEFpYT3ZEntHfeOPvTcRQPKHaiE0TxJN6MbZDmX0XyE3H+RLu5mcSDEteAqjmdZkCW3yhK2dZ0AdaqSuBGifIh4WqChDEluAlSeMchpfEH7jyyQwAtQKXDbX1wC0Y6WwPaHuPezsFn3MJnihW0XMTH6rKiQWOOF74113igG0n1/TwmbHWx7ir0CKddx8BFVY8DGJqzRnHldCZSg58yjC5yeBLkAxpgAZWYxxjwscKenQBRe7ig9jmgi0k2KnICZG8YZWV5Y7LNXPJDV673+YTgYeLYPeBiy5/E4fN0Hji4sR4tFFIICPE8w9CW7LhtM2WRc9so+7gJZkqe9B0rUX505wZevWC2hzU298bUv2g5BM0QjLPdBd+H9Pszqfv81g7P60Ds+hnUa7gKX2UMl+v1+/7+1M07uuOilE+voXX///aDHwoZZyFChaThGwW2r4ABkpZBKi4LSVGEyAahMYjc0+67b3wdlyIT3zO4drHQbHRnObzoNYe4Xy6z+a5ZOyzkBQkwMbKyv+28klr+BUPsuyYZSm/omIrpQDbVlg1gQaCiwJsbpBdviHLXx4P3g8L20/ANBfJ34Lw41yLYYz3eT8R++d/xf4+lP2w03/q/R2P4R//c9/kiIaZeCwImjMUNwzLfIFOHdr7fhdbIIUd4PZ83nYav1dPNFIx6e/zwa1WeLS6zjxntAtZs5QbMDINoiPoKeGwEubY5vCQLkEW0nIgqeypiMNvOBIFBhVu2gstHYqMIjNygBwKh+J1MEY8QktHVIAozYjnRps4k1CMwQlzZHuJCXFHGoXdpt0yMtXwAvd56j07hNgn0QCB+y/Cmcrm3ksfBLeYfb6MUl1zD/c6reHg928y9L0nnXFog8BhR032wexf3d+nULMSAdivBi64o0862bdI6i1NbsehmNwuhiHiejkByNOK/KCwjNkRNQNMMuKUIEK55t4dWClg03VTt4Kp4Ilxk+KLFdEivbXh6Acfxml9pVPhxASguxIrw0NDeNF0hApl2vjSbPILCM1QBNmrPVGwkTsW44a9pCkgiCnKlZlFXGY/iN3TGswmLaTFdCOwia6Euyn5KDoS3f2D6fdtCiZtT6IUPtk9kwenIxG4HEQhQlGlarwMEBkBsTl7BQ6mFJwt6gCZJmQW09hKfKcCcC2nBFKfsaoL1Uon2D+qBsKlC21+Cl1X2D80emkQ1eoKQ16T4YtpA2mUL4kbaBtNkEwo9ztg+oQ0slZ/LQLTimDv3CNXEwrLypQiFWWCg0BK9lQq5fj0VCvvJYItpkiAgCnwVCVstZFXRPigwObZb3g0CqI7qKY1+QjVh2BUHFjj2hzdqf8dxQHEQVqYcb1ObRvwXtFend4nVe3xYv8np2m9TsIHCVWt2NnDKrRuMqsW3WYc0XWnlts+7KK8SjtCrE5xRCgzI9imCb9UD3JU9G/rmeEE9joPAVvLHma9t8bSl4bdbvaDYNHctApke3wo3aVq1oj9EqlZg8R5USo5MqlFp0HvAezYmaMFQm2YZPVSKc0ErPq0ht1pAslm+pRm3WjJAofCqRoP5iVajNmhDxRlMFamOQc04D2tAMyVJ9BHZKWiWA+vUt0ByEIL+xtnYg45G2xCZ/3fr6R4DuO/+z/fQnR/5vNRrNH/L/9/h7FMTTYYqRSe1guTjffFESB4DQVS2/Iy3K72mmv9UxLA4j5dJsJp/O4xKZcobpeBwPSYWWZ4qEe2iUDBclLlRHgUa9x4gcOmwgAwJLpeE4yrKg++aoB7voh1bFLVJF0SMAdbisZVoKtRKhV2gijeJ5Eo03X17MMZiOzYDQu3qJqg6ghPBHDdPZHdtax+kNqN6goeM5BnEMiBxa8+QChRnQ3KFQPL2IMdwnXS64G0Fwhk0AMsOz9DbkiDrxJr6dbYfclXCRhtyZrd+W8fxudREbZJwtZPEL7ML8LoxGozCdbvlrQ7kKWzKicZUq0pkjGSyK9gZrANTnECBvQT0RD7lVFS+t3ormtxiNOxGoZZHyBqG9fzZDCx977YRTkuywwKaSIXnuELtRgHa9cUyRddllOh7Jrihk77SCGxDZ0eyNBvNGUOHBVXMFt4OdncEHeggFm8UFG8H7LpfDgq2gwoirSpKYs8s75wabALtAl3yzLumOhy/YaDhK5hSWpoixTK+lITqkU2FQALQmfhPOgOnO8dk8rg/TySwZx5V5+bDyt9GT6oD+7dK/5RqWAFnz4Aj0huMedzUcRhNP9R2q8vq+ijBHUPNTC7bEWrANmxcojSBwfxZjis+DMEQnTxhW8AgOAErTRacMEK/j+VmaxR3ch2oBjuEsBtR2AI4YaxJnHQz/r5UC94+1yuH5BRcIgPxmS8KdePD48dVNNL/Iqm1VOVvO4nmlWlcdqqpXukEYzBiEgorxBGj45FSXTc7N4n/sBCc4sLo1P6dtq8uwAoBMKUS6N5+n80puQCbviUbRbMHhR+gNGy6ywBM+2xF6cy24SBfBp8/lOto1okUetj3A3Otqyf/LHtUYMeOBQqVs0gVOXv81TaYVnOparoSFSQxQxvJJBm8quaI+NB4tp+gmYESWNz593uBQk4X2bClc5AA6w1NUB91OpouK+l0t2QWZpwEEMR5iY8ZvyUjhCSKKnsGiyjDoNWT2aJDbPLphzq6KCvcE1a+c2E3CFFOQQKdMj2gx0lmhDgnRGizXgDFQF8g9UvmULOLJSfOUo/zhO4aiq/Z9pPtZAwRQLT6VBEvcmgp40xYHlp64qMSW6BWtamwvni6RtS/iiu6ibuWzPYBcW/k+toOTHBlXUJCo6S6fwDfAHPCoZEQcJRlVc5Wwq6qeXfhePFnATo3RqK9EJKumWFGRnmJ6VDzFgs78QHOUqKCKh3m4JR2P0ZsCNoaFsk4QX8dTXLLWzs/buewVnxYwYIoww0yG1JHEdpaCxMdHB1C0q9v48qEaz53YJEGh8SImi77CbBVXT85FsZMWwOqQTcydNzGGL29+FQCrA3/pkJlIdsBA1248gj0qkMKWmm0QzzZhN8Bz32fAUpaLmKi2bvComHmJyWVGBG2EvdfDXLvPNuu9iu8EZ5/H0Rgbr4gBNU7tZQVDxcLIj6EB7Fg7t+xEz+oo301HAlJ+dWLlOoy9AgCra06UAG0sQmaHXj5YSDGaJV2sqL6iJxrAJGGvs+LI1KFNAmwLFVzw3i3PIzvYK5bZjhF4ILtAq090un2/yMC1Ttqtxum9QoM5ECHY2QOZzXF/LXdeBq6WNZKSM4rRQtguV32V5Q7RLtecXbmoOKFCFVfstqi4xE3Zs6tX83sSVQyleIFGF4zBGWa8y9W49ZqE6hUpgCzo034lNw76tF/pDUB8s1/DRhvqPbbmPkwmF/mHsOvlH14LKYLahNERA8ehgvB8nvIIq/m2GcVO2/zQaZsfOm3zw3vapkKetuVsOa3Lx0778rHTA/n4nj7k5xRZfH4GUD940fjpCxZ1j0R/WB1Q3VwzTDagJOcEf0/zRbK92Vk9ZdzZF6jweJEq3v++wbzgAHnU8mEcJAtYQgQPix51Pn2WVN65j1utpkBzFA/iZVqvtEedZvVJdBWT2KXL1EBhw2Dv9Iq0WofNRHfI73LiLSFIMJFy21L884pvWYpjWNK11PjKKxYJFRxNJl9YMUhZWKs5+cImc5TlLeGzqDMwB7K8w64Ka5D0mK9ES7poGE4zBl0U1sg1Y3CuYgQ4DVlsaEWtXGMWo8pXHJJ5LCSzGFT7VN5pyXkn40t5Z1v/buLvhrDlldEgY0P8bP2i0yopyGL5taWUeZPKy8rSL3RbDraqenp9A3upNA93ymQeLtvrDY2/l9F0NI7zgiKCrY+Wk1lFrJ6aKFoD5oECTqcl1ut/0PY75PNo2vZEWA6HgJUFKYiGRaFcLu/gc6mbgD6ynGfizIA6dmBw3inwrQyFcBn0Wa2j8a7QmuG0R8wyXizn06ChHlLPMPLOEtDZcCJUuPNkHBOvBJ5zE42vfHAZzBPYr5YT/xySIhjfLioonlZBkq2jgXpeqSLkT2U8pw0zhZ8xf5lNL8qfvQozGSBRz8eOFWwwYqDUL8MUeA4jWoTEJNEcLW0+rJZivKxpryNMiOekjcsyztiBIPB4XWyanlzDj24hp63oCVOQqhxLRxq2SUFGgZdBI0+uctSymIsONE0a2HDsQ9ieMXzFqJWy78GerZeW874DZ08oK+O894Xx0FDr1C6wfk/URJS9PgWkMLZ0ODzDqddtvSksKk0lvh6DZD6JoM+uueRr9DvnTLlnDD4Y0h6z1ugf2qCoVtCGtgWtIh1sxYtZweU0cdIJvIVBI+KBMwVfIDTuUHYLhCUWSk4M3rLNT5yfAi3C9aC8QggtdMEF0l1F3isLeH0N8dPgN2tb2R3D8YmDttNCblhEt7ZLDwnBT4WFNFQAAKnKqHP6L8uETYxKC5Ou47Jkw7Bv2PRNGAbDnkXzLCYDj9i2nK1YuOZwMOiVpoJUxLSoh3SCRltwyXlX55OWvDtr6YAcbGZp9tX5SwMaNfgko92GEhAqKOLhPc6p8vtpLJeKseJwu2fju6GLUQ+M4dUCEFwi6K7qSR3pbZYZdkkMjseG7POdoiXheW+j6RjPx0yRpg63Bltd9KVT5skYlMe6iVHpvAmeBCAEBZFuSq50xJsopbDBHas0qxYGrRrKiClRD6L3gz17fmyyNB/sgIqLApjGqNmBWmDPsM06yFthUQZ078Ssf+pSu/ZymFTt+hBqKrFPEksfgus50Gi45oRSOSuzTlsEAzQAOnZBzIpkV5YAQFrFqpXyYymdPlbi6WOST+nLfx6+kV964tvhPvCqPGegtup0mHnkZ+MYsVLHf/yvLUZpJD8qP36Mas7twqMB6RkQ6gU7vL3lqvdsG9JdRUTJ1mQ0+dO4qr4Bq+nW7EazMJsz2dMpGWcl7x1zFgyuEa7zBVv8fqo8Q2S6xgEai4SzTLGLd3qvwVrQqUFqa+/CYnl88rkaeXCfS3/48XdP/B9FYn2T9N/3xP81G61n2+75n1br2Y/4v++W//uwvydj8Ci4rsYfr0FoEIF6sCRh010uknFGQqEsLiP1/CGBCkodj4aEg6P3+zvdQW837L/rvqFzgRzHWsKtDPOqsaxYSSYXoSGdlcvlX+J4RiXoBCnlO0TmNA6y5XAYx6O6CNwCIQkDy6LrFNhm/4BYF2bqXc7nnHv7Mo6u7+BNIDZOZQW6SNFPcKEOkDpWIVI7M7dnmleKtiplkAlGacwxLVRJ8T1Vl1nXzSUghoqJpk3rgaNycccInXUy9SlYmLb9Op4vOBufzSL1kEQwtQwzHMazheyx19OXw9zNZTxV+Gcl7SNmZoF3aT3YTacbi+AmnYOqFfwnhsgNYXDjetHQ9Z6eMZsXLByKqZhPjPQU1FVJz36FXUFTA31S/jYumyL1wIQLZuaE5gFteZxAQlaC38ZcmoJpRpsm/AtaxvCKxZya+F8rDcsJmXzJCmhJUFckOQH4+lV8BxK0jWdZ70kH5PIKFju5Os3LC6G9e1NPOLpFVPGKDRkaEymEJvcWR0RvCWL+vRgrlhCNnVo4EXEKtnuKgPIL/GrFNDHm8BX/qFqoEyARBzZIfCnA4ksbLL7ESFL51oUsqEk2UFPYrim4NQ1EU0mhS9gx7vGK308XfQx9wAwN8YjWi0W8ZphyxaDmlWTMrG01Ma/sZi3w+6/bFvZML7PrYHZ9y6ZbmXG+pl/Zdei53mTXkbx+Q44TOe8/zruO817j9ZvL+4sFmxQzGug5aJerpVxowrpnw311s+UZthAE/xdUb1wt9MliN35lVTT72s2yo5qa/dR+NvpMny/E588jw4bwIGqqeprieIk1m1qfnnxNSVvjWk09lKKqv28KBOewuIbNMTzx2IIJmEHXxAD4nDRFUxsr/5Es3w7wDEZFJQrefElx08iA1Fadi6pktSoZuWG4Molyx+JYbuynNzq7mguq4Y5zYA1/N2PRgdmLoZvcmLk9Os9wMzD7dDI5rXKCOGUJMhs3IMOqx8AwhVh0UN4ajYAkmGQyIW+F3gKilxj5lpPUPBYRwqLnOdu/yLPkbv2wY41uNeLtSFx3KHkxQE8jSHChOZWh5HQKSaKJ0xMa1wm1fJqXDdhE6bdD2gMSTfo6RScV8oK+r6iyY8D3qk+SAZRqG/HEDRGWYTKaqkSkub/3CUmJ0WIhItlVtVqwAY2MAc3SAD/bqAWuIc1DAzYYHEWWH0Y8zuKVUE7yYKoi6/sFEgUWO/X5qZlL6ZnPfCwGE/c8nM3crcdk1uQpX8RP7vSJhruvyEVyHMRqU0jov5dvwOaQ5xorEOQuWLtPvGpPS1+w0B66RAiqhx5t5iVcDa4vxd8FTaz+sdcUvB82vG9q/8OIOFIq2IfzNS2B99j/njYbzxz73/YP+993+hOGO7Lvlcwf1wmeRtcLPUOj3uB+a6C4pcF3vtfceGq5bUiATiYTglnnu1ZCcdeKhMEXs/TEBSzcSCbuWhBFDn95J25fEO/5vKFTit0QnI7xAyiAulbN+3R395D9PvhYZqs3K/mfU7Wq1REDpaIvx3fT4eU8neKpHG5b3dskat5cLsNJNFc1Pr59j8kfjsVrFdIn36sT0zaKQrxMK4emEDppzX0d81HOk7Ml+j3pjjKYnlIYchr6OxUFq+87aaseMZLMFENt3Zta6bOw9gqdMMWkl3F4Pq1Qsm6xLaLoEo5Zesmk+MKnGP+RzCqPuWxJ6v62isHWUSyujrdIUYoHBwt+eFU5EUdgJqfOsRpR+RSdUZNOw1AgYE5gK7VbrPLGKwxZ3ADmW07nFe78CDNOdvgFbPzPn3KXtEZg1SnslcLBqQ/kWn105cJMC4Y0Jdfody6eELuOOGiHicDFvu6bHSq7cBEjIRSgRgZ3GJPF7fN8uP3gNjz9EcNyNrbK8PxCjuo8gB/+lMhuKJ+xaDur1qvt3cR7lDrYhnvlle1CxkyZ6Mk/M8piLrCaYy2ny5nMMpwjzC42iaOpWUZlDrOLZYtRrtTxYNcuhMw3dnsmEpXpkjxttibjwdqgvpMCk8liJ2wPIMaIqIoXUZwieJZyctzOtuOlh8q0I7xVeUdfAzIrMweTuVqH0aiSQ2QB7J15OvN2Lld+kA6YxHNv9uWxy0rx/BTNiQPM2gIrxhVlnjmi9JGdjVlyG49Ba51EtxyI1WnCcoqvkyG8HM6WG1UrXrAkYgnun7/CuesdDwyYfsx8FazI7iLLw7R1MYXiYXn//Uwlf8oAWcE5qF+10jtAYbUJnlg1KLPeqV78lCjBKiGz7NU8eQs6hvmulM+SoJiUfmmkTMC3OhEQFxHd5kXIHbcMi2I8deEr8PfE0PHd1az3XjIpEBolTNsiLLeBEB57C6HplOkN5KfCUte0TRlMO3+HVn05oxQReNCJ0g66DpuiQK/yAV4vATUCJSJmmG+CcxTXAhCD3NNa/h5US845JNFX927StmMo3jCuLaXUXIYfd5JMk5B21BDXmSBt7xUvW1skqJEHA1bCeEQ1KlbAj97vfEnzPOek5zDDOLv5qJ1CeddnWssvFjzK7SSizFvGiiTxUnFcELlt5ER2zFHkh2Avg7yJsQDT/pIFl7LlC9+z7pX3nkJ9Q2LZKOJoNpC7nSFfGcX34cKoks9rWCtAYt4i6aDUVhz+jbCqxygWlBqSq9BKfan+CguK0VZMPNTclVkL7FODzLdEKipPC1pXtjGoeHYtFzAgtreO8d0uZA2rY/2qOUeOpJjfcRUxR+aEd5N4AvudE/nok/m+B3/51sxlBWf5wVS+JlPx8ZN/S17iLPQHrmvNQDrrDUaubu+6XotLrLX4DSWAh2Z4L5WjXTwrKZ+l4azUiLOizUkTRwOSLNtWc0wgUXqpaOP/yWk1eKJKyOM8uTKfrSbyAi+5uWTrpnPBVnKqFph7p1S0tXJC89fNOdN5uTw/H8ccmP/7JtO237is2plN6TjVjzyBO6qUDFJbMU1VQTHz+DzM++iADE5EJhKmOU5DpKjBrNW2Vz01Zb43ZlwtKgHPN+259mqBDc1HA+ai1rB9hOB2oVb6AkoooIJ7KeCe2bftacaQar4B1kz6MMJpZNgca3o1qc3VlMb2wzP3v8D/ZzlJvu45gNX+v6fPnzefuv4/ePzD//c9/srlMovBvJzFzVqGMYRv2JSOnnqpdDCNg7skHtMt9ZRMKwsijoWi+7cFX93MZvEwOU+GGBORDOOsHnTHY/kDJQS87ImrAT/GBLvGBY8VmaahJiIca8H5HI/T1TBunk9DztIsSzAn7Fk8jJZZXJKd3GwCFVEJvmwtGs6hqLxzbWvQP6oHfZ1hKz0Td9LJlDYcFozJac/krdRvOJsuJ+sK+FTkn800XSYQuq4Uz29Sulu++q6UTPUlxItLAHBxSUPd5LvJuKcMuF6ieF/hkcOsxPL7JFooLy37Rx+advleN5/Xweu6WKWyVOxdzC6BjkahcOJmMWZ1K4Wvj0A7C496br7a8LwgVS27cEKa+/AqvpPp5lim5JAZO7qN8z9KHY2tveIUrmpeHsHV4SiYws1/yjZ/wnYnmtIZeTyMpxYGkydQBCVqs47ZGgcfpAuOj7Imoyq5NyrukVYx6uHdcByPKrM0hb2ZzPaAn6nhvaJuwNtcGNOJ9PjhZWlacOcjJyjM8Ztq8BeGqwFQm9IojrCNsPrpRV0IKhUqZkbc061s4nSm8VL0h9+ftKmxUxUmH1oaOEbCVwRlrY5FC7N0OR/GtcA0v1CQv4i0yqyI2Hx4XU4NflqT2i1nNDZWRu7MLCLebAuQ2KLECdbDPwWt+45qi7sgiQEQufIFd78tE7z6Mppy1k5TVQ1edoJW2U1GZ6BEGM/FL7uYZUVGstMPPAnZ9Ei4sPWs+sUxvi7mBXT3sVOL5wbKngFFVviXGzZo8DJRznjkFOZL3q0zO/Rcm80RkT5juoqZM9sja1LTBoW3UZpA8Peq6o1cfjdjvv7kdu8+0hJXiPIN6ARCZi4fJRjZQ9vmXUAA6X3ZwRDdK2o7HtxObW25vcoNIQflTx4Cu3eZxPPNN4fvxWC84zDXSNlDzOiJCmewQxkdkiPK9VGOy+qkmekVg5w3XwZm+Dzv35uYPNV4s8m3s0rvIQVqavWQjhZQ1lO1P1fG0eRsFLWtZ/iPEXTvGlqcFdjORZKLqFMdS+LEkRsMQ8eCe0KbzQjVcMV2m089m9+/fWZcLIsiGOGFjq/p7vhDpPO0squuZhUSFQKlk/fA5D99VojD7/Dq3syE6iC+NhdANf/5//ygvEM5AQCnxPaQGpyU5tzpDogPebY5C2XCMePtMKWLVeNwnt44Bwwuo/G5JHKbowOFtyx6Eqm+RVoC7nYuS9lkkk4LTyusS5CCKOShQC+GPMH+snGqiiZ/fiATpRAHFc/+DxXy910MUPx27gbQggHiURKOoErZIJHpSYMSQXs3NDsQWyTHXQPeyyJw3ohtsSFikp0KHSHmfov0TeIyC0+OszXyOnCmSl4uYzq/KaiSl25mq0lt0TSUrol2119UKImKpMH8w7yF46H5NYQ8zIhte0gIBj1dxjY+L6MsxMGoM4AkOAhsInZ9PYKW7Hptr59lRrcuRLd+JDT9WUSEOnBZH8bJuGIgKNgKzscpoBSXdbVaXbe6GMD91T0pvOliFhpi/uiS/+DKo2A3pWkA+WaIVziTUUGZAvhYoVab60KTxAwicw8wuhd9OlxssSokKZG2k0xdGZ3M9e0R1GANp84Dbgyb8IfXm4fzdKcLM5NdkcFhOdW1yVLAKjneqV6/Byck6+q1V0S+X5EajPb1nOZZ/BozbGw4xH/9uW0n0QzznH4Cldbi1aeF5+o++/KmytSm/MVTQiU75S+eEsbIMfGq/uUpay9PKG4/WJVO1d1uJW54Dp1txdh7ddIdydmYE1WL2VxNAK26Cp19C4gxUVYsjzqrREfnQQtdKe7efxvLPmasmJJhyjBs4TTjFosmQQJkyNcXpGXggaqLBcnTy0nFxV+dU/BUqtXgsU+utrUOCcmGnNc0ivUoq6YN/Xw5NjurG3SVzWi+CJMFisgJiQ0NuwCZs1xJSOSoxFs4Rt4CoyV0i1wmYnbdbK+42N1FeeKSsjjQKgU2Of0eZx/HltmRbpa9BY1UlMq7gjlLoHebzDvhF68u+g1UaqdjLH9q1z7bMkGQjdNFtkVaNdU/7O8GtwGlR5MyJ5BjAFpcsWRgk3PNxlfNpfZN533Jlw1M0UFt9dqoeQizyN1vHBtGpx+NWZim6LshdUkrA84DvzOXL7/9Y8ewSLTznGgVRWmK5TwQJtVWGgUmD/q0x+BWFUcZ5W/zFi7/+sBtrcGmTF2rWrC0c3tgo5Zfnpv+ph77VXbv5CzQE0oKtHPUU6DSWMqSmYhf+gwks5TcRORSj9kLhFAMm45a0Dz5Ts5WBKQKAWvnXvjaz1+jVnYQYzbmvDKaNe51Qy9v6KCoxjhzLJ0pp7eIfbmw/RRGPcEq5LkX2KgZZSzS4LnQxQkt1ZVsdU2Ule5dI2azDkJrQaNqZgigUySYF1NkxBSZr5U1/gEKt7LKG2q8j6c7R4Sn56kEbmwQdsRIqCRNrxjjajEIM7/DtAuixtCQI1wSXFFIdac13fBjQgIjJgdGKcM2GCH6rQ0GFGY9zhN/Kkjq2QmPPxndCoDtin7yJGhWxeNTL4wnor+/DwpOrC6uD2iJEeRHt46WZSshEpsFGgSi2JSdbTx7Nj7E+hra4RrTYDR7UmgJMNF7n3HY/MvPwgrpshjDX2miNCbyuVDZaDU1MOaxzBjONSxfpERKNcOPT3Kni2VFmhtqamxwLE6DUoQNYanKWdOcpOJu7334Ev4/vypl+QgNlhuhOKB3+lgyXWL9bdMtie5kcjSLA1sVvUMAaTQaP0vicKQwzc+VPODyeYsDaTtBh9zy9VEcz/CLIZna4V+xGSJpu2AVsCp69R6gu0FRzkjcYbyTCK7B3SPrVvPRin6q1dsRtZYnWaorfb4aZTTL9Vk6q1S9Zn5yWtul/Ytcjag+jyegamMbOUMcYpLHpURpVzpcywxa7uMxQ8wrL1w5MuKB4GySzhljybIHgTrlroNiQdqikHWtLrSWz0KiBFFT4CnMyWEJsj7xdC0twhOazaXyG0o+qKPinWJXM/eH34slix+4XkENaAWPHwfbTZD+mysvts0Jgp5FxwV9PMQxo7idtXGxzMR6V4QWk/Zp/fxToSPU7pP4dtJmqKcnylPcbjsQjHTcdNsBJgLSF1fysk0UZTmHxenp6SrjB3afABuYvUpmEm8P1bsQjVj9Za6tL8grfQQbAYbSqNY/faacpfFIuiI20RjF6oYY0Vo3jDmjqhWXNJEljU/u4GtrJ6iWM0ifJ4io9mmBcuyZFxkzBN2Wr9ZNiWZYuGTIje/MSyUfh1Mcf/MYL+b2XtHND07Kxloqn1r5dGm87kXeLsCVXcUDZ9+2t1aq3PU7GzrHlTzBTOVy+Zjtaspbah46VbGGIlyRdZgtoTSRblbnme9FQPgqBBPdyByDCVx9M+aEpCIeM0uteHiQ5WKQddDpEd9GQ86sNQGpK1Fd2sSgPFgeZ8RJgObOo2EMXJCzJx9+2MRzP8FrDCvIBz9yXJrpHqwFMXbWimGijV/fLkxas+Fxo9886pI+8IKuIm2UNBvHeNUrTGicj6qU4ZS5FKrfJaasqWLKOKz/vqAyXPuGXI7yTPPBF1Y4ZKguoaf5FmGpOpbhG90+/7Ui5O4f3hrRckUXRD4kdM440OKGt500Tr9XmN2P2LkfsXMPi53LL6CHBtOtEsNXRNZV8jrImnF2npXqj5QDIrCD4h4S5+akdbTR6EnFuCrOzfCLKyewzvQoAr1zPl5hz1070OvrRnPpOCeWHwz8MWuxA/EKjHAYiEWlHxoM9VUafblOm/+UgClveNQ/PToqF9X0vzBsaZW9XFgezVCdIvsUV/CbpVQg2TdCXiFR6PCflZE/BcGpa4UDkeW4OBjo64XxKBh6LlaE8UDpgri83xHJc2/IDSLjXyTg5jtE3Nh0d1/8Tekei9+qWJzqv0JUjhWWIxCpXOhqGWjnaFHgzep4G0dd+V0RN9841KYgwua+wJqS135WGGhTXPxH4M0/IfCmtMryab18WEBO7UdEzo+InH+fiByGECo984sDc9TG8RXDctYKyFkR+7E6SmeNQI9c2M6KxlbH8qzRWFEcxTohGn55XR5b8Tk0v2a80NeLGfKL8GaMhRhTtTD4yQgUIbGG76WoVbXOTRTNYE4fpEOtHW4EVOAtszr6qGjstX8y8fCY/uXDmL4bldwX8mPx1NWRP1bRHwFAXxgAVCqMn7knImhFysMf4UErjX4qZsh1S+WChu5hXj+iiH5EEf2IIvpuUUR0KPVHDNGXxhD5M/NWfCEw/wpxRIWJyr95jx8YS/QvkP9P58H8iikAV+f/a2w3n267+f+e/bj/67vl/zNvswku4nQSo680iJYXGEnGzJMkPj7yaaTREwfx62a6OpGWbvVdYsAcp5SkDngaXiv2+osv/yq4q0zeOGbeHfMuHYEorK90UQxixXU+KnKvO5uN74SbBnP64JU9W0OAIjF2R24pVJpQhMMQPNl5NMfLUIO6CkNz7xSV7KKI+3BAmropqCavA6rRhT90S0rNuK8nZzvmOBQ+IOKJRVKAcY8h16J6UnVz1FC7QnASv9yEYNAlFSsF33MhSSP5Fr5Wc8E/5tR3nPtu7PT0xuU33GsDA+LymzJdflP2X35THs6WZZ+xOgyHKPWpez3pxu28Ida83JOK1AKKTJGXA1dlhAG/9ckxg7uZdAiuIEQVyBcBuOlmPJlhsh26LR7bM+yzfDVM7kzW4DXoSRSHRbVqmizcK5Zyi6b+qr/zHv6v5lNLUQfo0jQcXilvmwA8GRI6aObKb6roy0aK7j70+BILcYerdoNc7DQngkvqfBk0VsCFUhYaJBWvbmORztBLdg6zexknF5fweZOMSObSXIUC1mYRMMaswgBOGqcGtn0TBT1CViK7VNTOPd2z4E3VzUrwA3iMuHqNUVnTq7SmVuQ90GVmSc8arTBwBsDfTQg/kiz/O+R/NnK4ft3sz/fJf9uNn7bd+19bT7ebP+S/7/H3oHS/62QY9mQtni4nszuU86YzXyLj4lzEvstpZ8nwagxiUvhm7+BVdw8/DkK8u+RQhXbQ/o1sWIQqwIcQsir6KAZ9HjFTi1CQGMbi0MUswFtrRwGIvVgTfg2vQKSrySMLuL2AbEDHKNDqwtveAH/xyf4kC4bR8DIe1a3GuDdBvuMyna+KdxYtwl7Z6QTl6XA4LluSh2fsubzFFMjqwxG1Mo1vBEZEW50yjrWcMxkU9NY294my3H+EWv94cLS3K2YiI5cYbEWh3of4HgYqK6ZE9MMM+5Zo4GIsNWcAbaEKwy5zwh2vCTydCgkOpTt17RL/rJCwh/hTbQF2qTabEsvD5SiS0VZny/Nzuv2DCa4+AiLOqN8qYzRZ76hYFeSNZqP1lCyP7ZUhQUcY2/7pcwAaA6UCT5GWNi9gPUBrn9r11vnn4M0rzKROd2MAEYrBrDJPOZHyNatrW0FF9a0qJd/CIBuOaF7EYTSfR3jgYTqr47pnaAKovLsV3i1hiC/EpRm89Tu3vWpg9o2vVFEJ4vxhX1hB9QURzdA4kYbjaA5y5kKSEX/YhGSvbUPkRjn5BBo9bXNUP6AYl7CEAZims0qIQn1FJb1sk7IFLEGMcHEZLTClGNUHtSJQZkzZ+L2HIajHnTxl23NrgHnZEackMDwMU4vVmWa2UE0R5CPD+VF1iTkTOXMokB8Xl5xyP7hI8JwMtfxH7ixbJaWGaF1HzJ/oOorHlarv7mE1g6KoOZEIMkS0W9oIV/5HPE+zyknzATBJvgy171Zjh5sTax+xrZFSUZ2oGQMVJGNOgNVZ8gnAgzrecICRlGQap8RjU11SuPVQsRTYwxgr9VpwkkfBDaajHRnUJq8sYFwExhSO0pgdNeICSgGB3xLDIAAZMYgE1yKaGrLLaCbUL+RLej7/2FG9M9iS0uDNqaioYWyaiKquWrWeOfcwgiGwLLVUpaolr3M2V7wxVebiNybT2Dc6uN+5a345NZEJSzqanyWLeTS/Yz5ObhhirHQKYBrjrh/Nk/GdRGyVN+3u/MJgHVijHURTE0p69mssjlAqf3cbb8KgKbUEinrw6k4KSajLgfCAkx8JcYNutCi5MeZ0OBLlDF7BjjRSX8HjsLfA5IiW5T7CGJFMwWZ0EnumCGKd2+pYJxGlJkjNlIzDBbO8FCJNW0Xi2Kp2eW2ubNzedu6VNEr2Qq8ZVdfZX9Zb7HOgqeQa1xdvHoxxNZFGl4tYIxl39Hp8yBLULFJ1bAVrNLpRC6yxdkyE0cEp2ddTddsb81Gt7+Pl7zncMm70/CmxSvQbRLJKtU4aAnwuUpQWskr1pG27L1UXpItcSGUYNZlJSUfdQMbSqKzCTMTndb5HYAA844LmKqjFnMVi708yfVWNOK6NEyzu57KzxvbP5XNgN6jciK4ER/tvagjmDvbrKTEE2KMz+Zac04vUZgvzGFObwwoTTEq3yXv/kPUSgCIN7CDX4FTfoKUxWTDvGcXRCDj8la2ewGgzFvccl7rwpwsxBahHlDQICZ9YnFwWw9OxwsrOJjJx786deYNs7pg8TweVB8YsPNL7xiEJwht7JYiVqduCuA9OzV8C4ww3sUGoGJsHPJFvPf7F5fyb5oFgtutWNVutJJOL3ElBsXtsOkedEUFQVZBQeu4E68vu4yqKROCMgGOcl8wBiW91Rm6r2u8/6+66D77kihGPh3/Ng8Krj0mvOM2Svy37AQdv80FS1j0RLuzVx1dFOPAovsVwbu/ZVd/h1UooL1iA/6qrD7FW274DXKJF6zgqx/V5DzyxE8aqWseMXxXzwOqjAPbEZIK8p4D6puJ4gz8iofGQcOrRbabDqc3RuJdjilAHrJDPBA+v/7JWHCYDuifm0hzOE6JAXuLeM9mldQ6za9x+0ZpQcSWdHDnfGx4mA75WhWHpXYBe2OFO90RPUYBJaM4j82HajI02FHnkT39qEBgQ26w3gtyyNaIHH1kt6h86MAqAiECiin4mwm35xemK7ofheYzLfrico7YVTtNRTAWMftYEnOp9QTmhTa+5yBzx3pzGotaZoXv60DYEygW81IvF14UzlAVEmYoTsOQwPSPkjZbmAsXlhR0gStxMK+mNmtHAY3cWa7lpdQ9XYBByR8Dy8uHHgTmlBUUSuq/9dwCoJE+a1ZrGpxO8aqJDxrw6XNcsEk5nwrRGhrGK+a5gIdHiURWMeTxxAZ/mqEuXNujKXJQOh3iUW/5ywduh0KHYRNYLhaYO0OEmPmLjvhU3Q1rEZEdLh3wy0RstvSJOWnZTj2p4maJBWMGsFQHECwln42goruZFDcXhYgXx0GF+ZxNbExakiICpixZ/nLOYfw+O7e3RH+YvzNTMSv/yoJMJouEc1pjV0L3G3uyxAmEYzVKAL88uI04S5DfzAhKSJwqYqH2x4XLh+Cp6T4cYlkXPsfr2ql6JG06FuKVapzD3hilJOdOiShbMjV5lVpC7NzJc9uKLIjtFxjUVHenRy75K3qwfesUX6hVrKhae6+NI2fBf2HgXjotvbPReOBdO6ZbTaQ5M4bVzD9FoTqxmfHfQefieU2kNnUckeVih+rjJejyajAQYqrAyorqhyevu13awMktejcI71dbEOduNuR/qKP9KVFUL66NlU1w4u06GET0KrCh+iStrq97xbnbU1z+tpXxZmJbMX4BYparJIg/Sye5Tsb4kf4VOm/bN01r8SJHwT7ybxGHnPxIh/EiE8I0TITzwFGDxCcBVBqHC832/89zgSkPTo+Dfxwj1Vc1GBcfsHMPNGmftirjRdztq9884ZecM+oGH7Hx2xLWO261p2VOy9Q/j3v8e455FOScG6SSnGmcmnNNVNro1THR5i9oD9cD7dZOpweDz4ndeXVlPRVnXnHUy8ekny3mh10fmBoUiLzvU+ZX2tFVmLazsWv68p8/9LVxBXdIurgETFQYG3fLbtZieYHc07bxy07kqsunN8wdcioE+WT3a+XpGTgd/VhOlL7Xs6YwtvFrayZO8NngaFA7Ux5EUeXiV19PSOpZFvOA2nylyhaH6Qebw/21W7UU8oQw2Wacg8c6avMGMGCuYFWFS9d9+JbshbUBG2Fax0VYwdIxeeqwg+HOTqHQNbr/coZ00Tk8pcq1RnLvkO5h1H3L+5+ZyCRx+nn3twz/3nv9pPnvWeuqc/2n+9Hz7x/mf7/H3KIinwxQjctvBcnG++UKd3MZoTfn91yydyu9ppr/VMf4Jj+ukmTraM4/XOifkOxzEFet4/EbVwZwM5h0m6tT2x7fvw3fdo+OKW0LHkUGRTSxCNoV4TlHwGKuSzsTZc7qPfrO/i8GU8Tid0dUp2QxWsbhq5TWl3cBzxKg64znZKVcd3wV49cR1NKbbVlKKB0zPz5Mh5srj9urBrgbLwaMI6DIdA+NOlwsr66+4y17DoL5hGCkMqYY3uUDlJWwb8mr7GzoaGjDTx9jCaxghRxGaUOLMbMeND2OMASdDgUXhqzh6bJ6mi065XAugsbM0Yy8fGfjDs/gimXYaprenkzcPcQA65ZoYnl9wAXFSFHshHnhybOTSZ1gGS92m38SRv+VhtzvoHvcGx/V3B7vdvf6g3zumq2TIqhQvyl/gMTGdWhqrsDTqv6agnyDuarkSTl2adbemW6cWlKmc28nflvH8bo3KVM6tfIGHRtaqjjSVs4MNL2PQA88otDKcL6eVvO+FSYSOVInvxpYX3YQ0JmU9ERH02GbFRo2GDMs2pDUlbi0BxSpaLOYVRWDQ293ehxDmuAdEy9IO2eZUibyBjvPMmNQlm7FpCta+cvxQKgQJso5Nfujuhf3dYyfJOrIW02hl1zk+BEIMj3u9XbsazyuKb1I6ytf9r/e9o7+Gh72j8LC/G+5039kgMCDXdn99Yu3ypMkaKicNZ0FaTIVKJO4khuLHn/NBd4DGRvAXAzF/YSFXtF14v4K1LjXu1Hmms3hxE8fToEk5NlCeZVoAmJvNci4voSUUcxjx8YL8jQr91dxM2sjBvHpSnBa9F9qSGlyhEO2FHWZkSoF/K7I1uxyPSPQCpUpT/lazZ8ePGLBPS3lo2jqbjNFEDJgI5/E4OovHFTXJNaNlD9XVAsEX7ASJuCKYKsXrimdqVQtGP2suMZfuuZIgvJknC25wEk2Tc+A9+bb0BlIz1pg5NNWJrOYMbEUHPOc3afvka9DyQkObD3Yi6jHL+xb+hGaTEZtF4dlq2ycuFmM2WJX1k8sqM2beMvHNV/9D6E2xgzy1FTN/tbU5WUYd4szVM3a1qsXThQDT9kx4ufMysEXHUdlDmVQ4lFsjOmxg+SfDrCLGaZOZG1IgMUafnm0cXtGnd5NG24RDvUrVN2neeZhMLvIPh9Ek//BaEAu1CaOjtCAUqYEZfnmEnnAasbbttvmh0zY/dNrmh/e0TYU8bcuZdlqXj5325WOnB/LxPX2w55Tk5Jz846jnnEFrQfkWPUKVLeHUHHmulhPRXFM6774otcW3QIZZBdta70Kj8sanzxtSDFJZVRWnIkDmSN01hic556HTnhicnUwdymDCVDT5x3W8aDIZx5V5ufK30ZNqOKSPsm2hnogoolwsjBNEZIjntaDpjFu9dERb2W0HvCPXiFM+Bu9EzbiO/1QUKLMJkDkf13+dXZSrVa+IpCCuNzv7aQDARIYlQMqS8x7gpKk5MpvPyx/LuOBietkTzuBU2KuJCFcT01fP4mg+vKTBo6qOOFOHofyGM4bg1cyKJcH3U855BcKy4saws1B7bdOPuKJtfTKLojtmeIaqxt2piwTPnlqMM32Zm+egF2aXrQnydCAI0neCraB9BpvLmiHtGmqBebZPoX1HNzXbFmtQOvxsUWFcc/CjHfCvJ67+hTNPr2pSvDQWk7r/yGijat1RJ1NPoyhrl8tnonIuUtAXj1ryBh2yzypVX8IuhcXTXEYzyp6u5oXHTuZYdWsfXdpX9Vqk81f88Q1/SsApCt02rOElfzp2Ma/cf/fCirzgbEytI6JqIdlATU4q//S59rvwrFwwxbcrqhO/jhCYX8lFaPVenGhjVQ5+hVsgO6kYRy1VqCeDdsTJkLsImAoNFljzscGr+M64L7HwPgDjLgCz5AlUB7jwb4fdrujyn7Tp35OGx4m5ADpAbgTbhjPNNRmtRvGbIns/5bH2clUG1AGdG9ViUd6PvkfB4TymS5ox64CgHa5RD/4LemHZIOV51I2sABidKcZpwAxwAUi94zFmPACpKQ7oOPQmvwtixD1pP3X/tIrJkV6YwisLir2tv/lBnLQRPQWnIgqaPcEq7VOPYmKxIdmiTxOxCspmtOj/m1TDCvUvau4e3UunV7gXnOjWugAnSSayboqeboo2LGMrF7r/gjvD/E3jQiKTLUgi1LZpa08XS0yUNiUpwV4dJV6zWY+9gFmsZSRY2zyQjznUcFYGHqZZHTk+FJOJILlpks/D9IoPyBiy8R2qmrmLF8vanmGGZDpBl8oeBmUoeQ06FE0Lkh6qcytLWRsoVtWX6HFrS+UOhVOo+wkYHxktuPIE8KqJWmw/nx0QWkNbDUSSch6Mpl/y8KSwK2jR3MR9GcmC/Tvo0ipjLqWbck35wDpl8oGVq+iQugSu6l4CirUoFVhFzFdNFKtRdM900WlV/60SXqJZe7yFSWXOQDTPtq6B1mZ3nGjka3mCV/t/nzWbzYab//un5vMf/t/vlP87+EDpswOVaxi29sqHZECHdQ7vBpR9sdSVX9ExO46Jp6fnnroZpW+Ms+E8OcOI42lpozsNyEEb9LPgIzD2y6D5PLjFf+AXSHx2dVzzXPwoHqYX04SMp9EiOB5G43gDtqTLxWKWtbe2ovltcl1P5xdb0Vm21Wo0G/Vm8+fWz6XSwPSB/hrdBkPhwgWFKqbsjnSJrLrOB/O5CaAXwEKWZ2ie2LpIU7yUEyUn1Hi3OM+4TpIfz0sl9Cwss63Bwe5Bu/Q4wHzJ4yxYzoClUgIXyseWTkAwpvvVmUHJniEq65RxJBAJ5lKZ+IsSPd1E85GozffCjkdqGtj/m9Wh0Y/8NZjRpslynDV6bIcAbL94egv/U4ZLlhonmDKGuABaTp7fwqTg8+3W7XYLxXm6lwbaGOAGAsAr5IgFTHCGTJqo/Xix2byqBpO7YAjrCVrfILgbDIDB49h++qn+cy3YwNY36PfP9aeY7nizyYih1DU4VdjiW+DjGN57h7GRI0wOz11+c/ieieT4eA/Tay+nRpdmsAtLxzl07wC2gj5bTm62VGcRYLy5WE5JBjpfwr4NLZa6w6tpejOOR5T4PsPpRDqaRZijJVouLlNBnUxE2ASRFXZKzAbml8EsT3+Eun1o5ha6hFihiIVFehVPeS5UhtHDy2QcfIymFxuZjwLHy2EywvEQZ94UnDmo1+sBGRwxpw9scCWS6lJAUJxM01m2BR/ZcoJZgKAjx7RiA4NsQWS/IwEwm1FO/7O7oDsdzeNfg1+iOepwd/7uXIm3W6C8vDkcAOxXMYV8UB66Ycz4oJ4BRV9gvxfB2+XFBeDqPIL3Np8AvHGOrPNxekOgSqW3mN8MF8JFTEoGdG0r2Elnd3MKd2g1Wo3gCBMufcTfIOKVMJrBTCtL5E/5j9J0rOJIZtF8gTd+01sMyrbezuNZHC1K3oyzvBlOpxSkMnWfOlcZvNYJcFX4Sz06G+I7kdUNTTtnQzyK/yh4jb1RjFVcJ5VxysspJ+ufGudvYRBZXLm1ZVIjB/1tzWmk3scYerxjzCerBreuVM1NMjYQmjwqJV5T+6VS/133TW+/Nwh3e6+77/cG4btedx8DzBv1py+e1QL4ePacPhrPq/nSx4NdLtxq/YylWq2n/PGsWlqkYYs6gUnZBAZApCKMjObpjAxx2DP+genj+b4CPDlXr6moGb4xXN4ao0OCdvHKBrbnVo4X6fAyQp9NsBvPML86LnShHFVuMMMU39JAEvAE/TVkLYVtD1Pp083RFP6OSQNFEuAks5OD8XdsdSedToEgeP33RS4v9vL2iFcDz9lHB2m8GAbTeIGJvYCfXKY3GNnDwi6F9sBCoKgkNoWTRgXsiDI6QnMbNELRGJn1IyNRJF0lkDIqKQIJM0dlMearXwhOB7yF2jqOYzwgCQwdN722jx0s1OLdAhl7C3Q1UCa3nv789BF9xSyl0Ojms+3Wz89f/PzsOfGt/sZ1jBFYPHZqCmZhekHJLWF84+gO2S1uz/OLJckZOFJkn8HGSE7fBiicxB+Q3wIKbi0cRzhqBkRYQmhLcXnQRraEvQL0GYQA25CYItmYmEkzJ6KkNLK11OWNDorSSt5FdRXH6kINvItMQSmJO9BmSOKV2zp9xTsC8K7CSrOGcd/weDpKJmT6oQSiQAu8Q+JUYuZMma6yRn35FQMlWrs47ddAQ5mRBi1UOQ51j54I7oUlKtS+zDB4W6dPlV3w1srtaUGsw7yn87BCHTwDipzLA0bK/Au1k+uKahdHZoEoecylvFXiZB7iSgcG+47i3r5gCT94DZsT70t3IKfQTD2qY9Nkn9lZ541UY7+fpieDKlSjsChQ7BNt3uYjfC02aEM0/Yh0K4tAZ//Vfg6TngHOxtE0zgfdQe0VY8J7bJsyJIkAbLWcEYtrmKmkVa+FXiWqg1K99Zoq9nFXgY73xQa3D+yrNapQyVoQnaMc59hRqN4rUe8Vip9GpVZ1HTyTgUBlr6VfCtV8l3HT8nU0pae4v88hRrCa67gPJxfLdGl5mKB0S5Z+JUs3V5S2k+hiY2TIalWtTug1JGf83Xi2zown0/Ac9iGQf3GrSUAH0Q90cKb7KBouQuKuHWjiTW/vPa+NTqO+XsCmCRIdsuZPyhyhfmpqsfuG1OQ8KajIpwSHTSaIPSCYCPNVFg/bIaWIDlepEbuL+XzYsiA7wGz0eRgBV97l7biCT9Yi0VtJRDCyinEOTT2HDnufYwveFzCQtSqoTU5SWnchgqLXoTfYuTg7zCVILFnnRS347eo6PEuijKPo8HeYoZ4vSW2xmIaCuGroY/g1fBCpqcgOalBkeaHvmrTgV4hbaoc21q0tT5lHwf7BoBdQzwLQZGBNBjcgOdzMU7yebIpKnhLMQFzLKPUq5nXFIAjQUpYUMm6aA3g/B331WiqPzqlwaqujEIIErrr6+HGw2ag/c2KKAJcWMRK2qXiwXQsIyxLdLpVLNNv0qB67wbwwD96WPOU8YNXjtWj9VS2A/WeH5AkSVrQ3hcYrhw5UildcYYkK19muOfOPYMz8OvSwWgfqmSwXoGjUMOED1AIm+1QP5bcaHum7prm4ptuc8LMpPlunRB9o62dWjZavGd4PMJvdBRWgAZTQKDCfJTEUOOlyMD17iGeUBn8L/iO44nvsZiloepvQo81mVd0KToTg1sKPepaeL9B5iEnVN42dQZSxJ5nm1WgeFzs9g+avq0b7gIeWi9QdD5PACfVyDzXTK1nIKxTALPaxHv+oBZPxLKQz4p2n9Xt5iWIjFlPJOwiVgMWF85sdXq6ln+3hFxQyHsKRoDhtSQpSJb96xNxpBmuHmdis1ECKQoP8YmBCfjGRoL6ZDNZe9cz/2oHSv9iPqKXvEUrfNbzpAGhlPEYHG7mohUJ8FmPoECtrUvfERMw+yTiiY/VKA1APq1oZwyIvURejgH0UEIXH2ofn1go8I/2ILZt3AJRimWMq0nJPgoyRm6F8ZUgRHZoNV4CyoZukpL4JqnzQxn8rY3q0JqDopaLJC5ZctbpWReinrtey6+UW6yHK1L3JWTzyKWfCcg8bHZULqCDZJtjyDXvjGBgj3Ysp7jO/R+vC6CuKvCcz0Uyd2+80n2NamHkyisV7SvMTojEh6wATj7FpRHznp+cv1jxJJNoiqVsYoiryoemrNTLB6YIzTyoFo4OhtGvpGsZbj8hCbFm2jq79TaNl+F2lvcxtAAs+CZp5cHcWuIYDrlEErmGD4xDpjSWZv7l0m2KQ0MbC5n6RIxojSrHZT59hNdF4Pn3eUP593Y6xSd8Z382wOjrCbF/Kzgh6bNR1UuTpqZRf3XtMjUmcFeQUtBs2fpWKBCI0wbQwPwQTokGGGCM0n8Z8r0pnZqRLZGR0vNSQOz4Nyy0Xw2VbgXFfkB3xxDFRVqy60Rec4sfOoyY/Qu0FxwHP87FAkzoLrnxnHN84GWL4EuXRyX6bLyqterAVTJ3wpXjs66+hq3s6bbd1noyhpaYnE10d9zsuhNfahJV1mrbNC1+39fUE3J1a8LYWfDRkXGPrfd3/73e9YJymV+inxJDQW1p8SLrDFPqO5h5DfRBXSb1Fe6W1FnCicZl+zL9BafZvdmRcuT9FMx7fCMo3EHx6+/nxp4+fq3RN0XRjIQJ72b9X+eQ2BoXdVj5X6+Vi+dHerernY4w4nlZaOZkUsHKC90SBAgnM/dSzW7mbVdjfOf6CDQtqfbUNCn//2KD+V25Qns3i2+5SJdcyxuLr86fGxMaTkEcBL1q+CbdAWj8QqYRsBcPuFrAdYWo4jn9bouwdjW31xLcVmrKwuRf+ZGyBqkF1VRgsFa3UOYFvaNjWUJ2X0IWjeO89dMDISF0r6KXZt6J+bqt+Nmuyc81/08651vEv7KeZNIynWZtmAdg3F5MeYitFoi20Urgvft/uI7YfCnc4ivu73p3HCIbY5ICQA7pTLjiKN1mhPU+GFJn5zbYgZEnUVdBWm41Gw9mUaqzXd5otj5lE2x7g9cMtMVg6ts0x+hGHj2M2ieskvoHPFVYaXSsZZmEs92/ZdIGxRt4GKZR1WTpL4vA2yS6XnWYdWr+8EYNqPtDcLJAqlAbxK1/M8GdwElKJfcywpb4DvVmFUSdAwS8Bdjkd3gnVmq8ApUguJ1WhOVDMXmH+tiJJTPx5Ev4yYVEJAOPIVvkTCpIo5ReLMvMLm59b+64iVQ+f6Khvq7OUruj3P7XPq5Rbo8P1YqVzOM5CjikjlnoYzWHVYLpJ81rPJlmzdbuuhT7NFGJWwTA7+WQlRFi6It8kL2L7LS5n8Rq/Oi4PufgQD/K740oWCxJ3GfHV0JT6GCxKN0AGx/2eluVNIhcnU16KbBLYC/zhIRvswr24EeAeE6BCXPMZ+eV0GEo12W4B6WnUqTdavgQEG6INLbZSogHZ+1maTBfOSyXGclVmo1UvcBaUAV3hnji+5IBQM1E1F5qFyd+HvO+JNQcxXxslv5eaviER3UsqX4lE8vzF4wDsqO3eSOYzwyilk1tx5zLtcrd0doUQNMZoVZBA0cBk7/1CSqmeIgtwfRLw7zC6C+Ygejld47Af7hjLZnuYv8U+ZMquKc+F6wYvL3DDaIlIfVvTN1PyyToaZV7fjcSE8l0BOk+SU1v+UV/zZzuNHJoCm+5UYm3bleLbzR4FOyjsgOgas7/ajZew/MYODoWcVBVX+Ckp6mXQWOXq8SwKtTd6FoWnuNoGjeKOM242G4tkniz2Cae9mRnBfC4k80lhrC6bHhkPjsnR7qA0PhYs7xVQaYtgo6SZ5spjEp7Wse91siZG0wU2ysTZcBhcvimP93NtkEUF5YBBBhf4/Q9mAr9CweQCMBMrrE9TgfKQVnpBWsxPG2qKN2rBhiKPDePmAUz0MVTEuyq/JtG1qofnQ3I1LYKuBeLu61majjsbG+61FWtqDM7isTWGL1pBrvqsdAypR0tVLBRnuSlHNYsT9IWxwriUhgbDsq0N2ngTcF7x1nKuZf5V06MkYvWkHt/OMGz1FUZGUHSE4Prj2KzGJ14oul6esJBnM2wrs46uO9HVYeCnfEF9084aZEm4L+XJa0uwzSVmtjyvWt5+4sq8jx054URhXr5SbTyRE3Bqr063e1+7I77mvsHAPYNz9To/7JKHxIQAQvYdy6t2Nr5SfjWWBfJNQJmcX0JthtYbTMptrgX/eYuTNvA/IC360mznTUdcoNCsRcsxpFQXwpTCa9J8QtgzHuSzzKxcszoi0GUJNnaMrli9MDtQKxW3a/3yGRS1Nc26GgbPKkzk7orWDjf1EBWQWfGF7AgVK7oweihnIZpB0LjW2RjOlhs1GYUXptPxnZv0nTL+dRrmbG8QvI2AIspli046MbMn+seJqHpqgdNX3nwZTKO+DXiBV6THcxdq8OjRI1oHoCDb18ynZ7/asMsCRPnUpx2gKRf9jQiHZ6ROfxvOPh/fsJ/QSgujcnCIQ97Qtj9NiRjNFd8NkqHJq1Jmd3i9XHA7I97xdVUXaRp16VpQLnsTaqCAZDcgD0YXNkGB29NlPrFJOh6F1H7pnl7pJvz9kng7uaIcQp6UKwZByMIlH251ST+KkVhQsiFKucJ40w28Ic34OZvHsGwukkXGD3030HnwgYBNkxba24WMJ4DjNkpH/llYwOswn+aBPwpei0OwbObEDX0R9PkoDh3+TOD9Ig3IPcUmdWrXNqSbfwe1oK987znbm9FRJ/RUpYrCOVERkgcslCA4T9zBFbrdDTmULTgMWF22pl7zcx8SBimdXflHHEDhINYOazztwro6r7RoYRz9ogokEckzsvEoF3lszhjOfTIex0wPmnv6F4JgBqISXx6CM3GZpiB18uHN4Vgdgp3SoSvQMzf8GVqubdHsmvbFNkYp0NdW+1QLaL66jKBQYbNyXQtymp7P1HpX8FwdALlxowJZY7sruKzSuMmsCku4jndChJXrorsXn3SaNuHcDkEb9yRaYnR3iv96R0cHR4VvPWgXIJkcRylxQ5G4DZdo+9PntsFCMLVplh+iYRRCtlMXp8u8qOClXnU993uYBuVPo2AL/yFDQ1bf+JO4j1LdbGkCU9d24r3pQiOzZx99d5OzWsCf4RStbJesY94kI5QIcp6eR8FRzIH3SKkXcxDD03MEwPkI1LLLeN2hiIErj1aY7lw96I6imTyVLwB/UaqBLZBRz7YajRcvtkej5z83h8+3o+cvths/PWs+e77909MXz59vP2s9j180m8M4pkQev0a3W3QYm+x+9dndo71WiyMEprAOEQ240SucCE2tKeRP8UKYUcQvQoSshEuRFqX42dBCrWpgsxM0Gd4FyFawK1q3rVGUGE6qAb76WC2yqlkRO6tgbG3ZDgBBPEc08yPPPImZgbdtzNKb8lc0pJP77JI4YZt+AkFY5k3um6RlF182JYku+7BFv9ReAfuEHIz6dkMKrTqPoA4jtHxAX9fpwPgsHWPmPuOdyFRdsbrFwnJn4ywZk/Vg475+Gp1ocT+qZt8JOKhuYvnIMwcMwWbehXRks3B5xpzei4WMVIz7eJhMVWRQp9LC0+XN1otq3rltupEbHtdyzngMz5oef/P93uFnuWsKpHirvf6l9fyKrpfe8icWOeSL/e+GlZmuZ9BxfWKYplOowy4HByk5A7tCoc8KzW9cU7TXG6/7YtilRW6Giu2fj2cwsnjzedXEu/rmzpD1y2TnxjSVTDpjOVlRGfZ2vJz9oLJ/ayrj60i+O5G17iEykdAjBa4XjULbvM+nwgC1ccTOChhyLThTUsjOchH8H5jHbCHEd5kuRGX4meA7zIMDkneQLDYyTutwDpuvKiPyHuE566OPAvK7eHGZjnQuGimWzOIU80Jmw/p5tqzHo+XW//vr2XJ+Fc1Hi60ZiijTBWlT2RYNBfNYiOHUZ6NzwzIPyB+Ozq2EJTCgdDKDjQXzRoIChBmOuG4wXE6WsJcl15R4AqjzbElbuMyw4lqGKs168ISDzeM5tAISoxl5DuIgPGmJhA6g0VQQxaBZRoCEFlodF6MqqrX8/GWAiRHk87YjlZapDGbbSOcxn2NqYUGekhOcsVNEu/RmWHNcD8oFN9iVMcGQNViQMUX2xkl0h6dFk+kwnc9jECXLNUFcnCuJE9AwTVUsDH9gAHidzUU8pcy+lOOHdcMoULMGNJNQShCrC/KGIQa20Fol5QZFYw9odDu7r8m4gM/E/JlA6gaEN/EiWM5mIqvHOL3B3KGjczfR7lg6F5FkKjhJiHOcQ5wQVWxpFTtzixntvufBUQKp8VgevyTkCRTz5I1rwfK0xgMlgRsFKsCvAeqkNUbFvrXcbJ7qoYlEGAKJYQWJZ8yZofHrkvJ3WD3KNAIRA0q8J1R60IhyKl7CqmbMAOYsH7dXsCSgKXUEQZgOVIMAeAZcFEPGJONxIcBqDCtI44+ddeUWjEajkBaR6weezLAdKISBZ5IzkeLPTZO/2YU2xHoAL5l2IsqI2znLGYVF/hBmrMX8lKIC0WvaxDDDzmYLPs46rbpirpjspB1UBqIOZRLyflSDzZciWRXz93K5/BqoKhOLAk9KDPIENppHN1Mms8iZRN+ioXxj13r1xufnmEPqOgYaNkBBk0UggjZOVfvvf8MP2Kw+7X+u/G0R3y4+IT4+w95IPwAnn/+fVvXvmp2IVtPlIsOIcQGGGdvfAe3cPO8x0P4d9Q9ritsrEA1nmJw+41FMeHNZZiLHkWBEko1wHhjZKuU6IjBneF8ZKdSiB1Hwt3H8W2CMgR+c/Z3XISbPazsk1MZL3qabIM3AT07N9XdmlzxFf9fnPwFgmzpE/D09L+JnRvj8iCuo5YcZciLJu++rHonWYJOYLCew5S1gi2Y06GtGRZno1l+md+umen758mVwo5SueDJb3FVAY3tWtUp496bKTdWKLhYL7IHCSukPP/7+Lf84/yulpmfXzde//vOe/K9PG63nz9z7P5+1ftz/+V3+zMSJXyH5obrBU+QTrhv5hGWuRcOmUzNVb6kmLac382gWasMl3a0Uy4zLYu+2Y5FUNma0udohV2Wi6zI7wDjHNoqh+conouRpDoqdn9stbsdElLXtd602jeJrN2zWKZk3y9yPkPw1K8qOEGiM0/lOAinSSWKWQN2oZa8DWWJeuYrvqgWO1jbvXPKmBXEnhYEaldBbEkAyPY/nIao8IB6CRjgnY2HFCEEHYR107XiBplPx7UYfrOljfd6j0+V8GAdvbz+Kk39k5xTimDjfYxiLgYqVKaFuZAA0g9//Yl3qnEenWVbeX8jwr2OBONFjGcdO8mVFDggVGeuJ2J+HQECYp928y2ecTBJ5+6TZ7uPHQaMuNv9zkkhHfMkPx3eCesI1n1hXJTkD/ZMwhJdWunfZbG6fjUfbPNW1vNCYHYQuv6pcxrZhuiJdMPS86qYqtdBk4OfGuZNtmNLplugsY9fCOL2oYEocEXnbjDebLaxtot+Jd9ZIVpf/ENgaQb0EfU5P0xN6dqOf3cBQcJACpliTGuQqqtnhLEEis5Smx03tvmACJi+YoKNQ9C1ESRNXvUShQK24ZET3wFq3SDQC4zX6wdMhF6FwoZmrULvTeF3Jtbd6NbJHBtbbyc7e8ekTWoG+BYedGI6XNNZW87bZQI2r+fz2hbkSxalkal6GCnQ64jG3LR7nAzepkgQkQFCWzT92gu2AEihrsHgA9o+YudN9vtmkF2Zb+GzF5Nq3HRi3WvmwwJlB247B6LzMfeh88iDgs8S6fGvh4XPZCa3iuurgEP8UjjyzgHAJ6ffSsyfeY55L/oaaRxHTNo6HLioGZOVqFMSn1pX1UyzxamG/bJeaaqxZ8/SylptIBl7obrMbtN1tWh/UhXQQGzsQVo3LOEJLfrnyWTJcwv9l/TwaJxfTEJY4KM7yIOVa6FjluTNRZPUveGx3sAhbgoWwl9Vy85mEVTM7ZLv51CoWQOQy/uN9yzh/wYyzRg5960lEypxHyTgGzf2Tr+3P2Li74tZaTIK3CHCCd1KYIkXYYOZt9uHPY7x/TYjFFfmlZshcZhij5HjGeTbDsPDT8xebuwHeQPshGQQSlhRrjOgezJ7PeamljLf5n4fvjDZho7gEvFBqYGmZ4QETeIxEAOFsSOdGoTjsTsKa3idRPkJJMQb5cNym2D3pbMBGZA7aGvkX7DOo5KbBmO2ZNPqcs1Udsz+DyGTeREGRuWxSeizHxcH0jzGNv0zfu4W4EULRNUmXZ02qNReweVRUNmg2YffmynSoJaICyA8Jh2fNmjCvLfSdWJM0W4zvNpdTsmjRmDhouN5sbtFPAjVMZwlemGDOohUcpMV5IzTVFkJsknCCVcvD2bLsC1Z1KJMDh4LB3YwXyz09WKNRk+0gx79PTzNkXYyklmGOZuAOExNfsavF2uwqAeFrFKqmxPNJklE8kllWrLzQPMeKUc9cISI4OIehOIBxBqRFl1meGEHWFJOlxCS5TZGyIvihVlwMjjQF5CNZ5ztRsm5pkxDktd38xDkiaI1Z3WynelJdddWU6rq8ZLKgfZCUyqqPZVJJmckpAAXM+EQDOc0xZrcHq0XHfNybrFrz3JTnNp4vo+gqH8i3ftnb2opbwH0k9il/KbiYK8JOuR3QXfA0GQJh+e6UxcCsKoUIL66Peyze2+X1MeKmXowjD9R7K916KjkT89kiwK9DYnr1y9VRPAkABBBirONC3HFJY5WvN7HuaL7u5H5eudo9QDioVHVKV2fWKhGmqwjO+wjvF6DdFrOwL9hmchnRlTBy+kEIwQ29JtLkB416HXSzSOzXXFoAkxfB05VK6DiAjftjDCx2nJyRFxrdWBxYSndXCgZ/3O/V1M5c07CU6hXo/RU39LoybJicWpmVBAvNhbgPx+ji6RiVrLQA+NaJ/c/ycf8mN+U6Jxi9qAo71kBus4Dn52GtSmTh3SCoVtVvolmxCaijVuXf24i3DRuNUkoC9OCUFhTD2c1hG2NwyaYI9BjjHUFndyyjWoIgyZtiYwepb3VHnb2exubb5uUCaVWDAynX2mI0dYL9v6IfhjwKAiaLlpnqEtH0u2iGDxr1x2jeMKVSQtFj2pShQNMqQMh5/L3oHru3ku7NOYWBmstA1PUtA7eR5j2NMEXk4Ddd+O5KyU25UC86dMKEOWL14fRg4MyAg2FDBN7ZrIokz0JWPI9/W9JdXKZwUVZHUg27gCHCmQ/9x1bMImLWGpQoGDOmF5dprlWouaoQTZ/1+HPJuGI2NAYsLntVTzbpcnGBYWU1cCuubxowfByJ1KjZY4/ZqaeYj38cL+I/q8tpVU+Ucu1aB4T+hZeVOt3K2QgEwZhDCv4SNJ8+e4ht4wD0vOCTC+ezZkm6q+JmIFARgei55J+d/peVDRJDwcfMVNFagBaFzVd68zfHQl+j5YhcDiaNKgUQZa7F3NUlDeGmzN0R1/+EbMzmW23doZm1xGIpqMVvrQpSVsyV1UKkVT4n4kOV3DOjvBQJEzwOh/2F8oaBzizz62wSsvGDGUCcFVcRnAKrcOEQjQ0hsJdQoIB2mJDWXxmvzVx6qouqggWtQHUhk7Kxr2xpGB4MIDBA2OAFglS0wSvfMTHrcoWQaG6t+KrJIETApaZs3AeVWIl2KUXq9mpul2tMnybLENOdi+d8ncylpYka4WNPqkKGwHT1k/azU8viR+0Ie5+0xVD6j6somQCuKjIfBiVgoEvIMOtyyAkZwhC+4cMwLKl9WJSr422XlTLneCiTnrRp5BOSQTyiHU+WEAowZ6PyeTQN0+WibO1e9yUEWZG5oy5yd4hN3e4xngP+Cv1Npt+nuyr7peyzyJbCt0rlB1CYn2TNjnhoxUgZMvGGNRTkiJEt+TPEQGuN5tdEocxmeSQuTOtPr6N5AuX4aNvcl9zyf+J5uqmWJ2w06ra1iCv9WS5e2H14TbEojetbmInJ8bfyJpCzdLEAbgbbDR1daP7cekCaxlF6M81fYmODFLfmONkAjIuhxJ0gLuzlzILsAi2EXLRaVIfVTBctcAmB8omJisuZqFZ9wDVzKrvGUlwOgVdKqX7wJRGSMs6WyXhkHlZc5y4oKz+OSDECz0T+CPo2PL+oCaf43Xozq48po059flF/d7Db26sfHvUGR93+fnjYHbw1tgJ2lYTDyzQhS7Onxs7bg/5Oz01/nPGpEqvKzsFxuNf9a+/ISe6D9/Sa5fZ7O7/ki5BzRJQb9I4HVCx83esOnJTR01BcmdfBrdihuywOr89B/h9GaHNP03EF4R1+gGVV//D68Ohgp1vNV2EBxUwpmqu8BzX3wp2D/eP+8aC3v/NXD5hFMg/FAXAWr3NQBv2jcBcA9Pf2uoP+wb4HCCsyKvtPJZ9Jz99jVIuLOuLJLsIXJcbZAmhIsDOQq0A1U6EmRq9hOsL+/ofuUb+7Pwhf7fX2dz05XykJCvA0mhrSEclUCGB2u4PucW9wjATQ3esP+r1jX/LwbBjjNZop1m+ZWcM15JIrx/DJDMNjFnJMOyaIxFtQpaxUVokPFR0Cfe8fvz44etc7Cgd/PeyZyfsoQE8vSpXNk37gbqqgYFrAnS7A6HKCqYYNw0n46a//od/76NbmvDx4T3lHsoCT4r6f2nSiTsJhjf7+4fsBtPM/vZCWtG1s1ce+nDEd9GqOj4OOtTmYscvQWTdr3E5jxvk7o7nBUX+3F2IP7eLOeTldY/fo4JB4mae8r+jB+4Fd0jlVp4t3B4OQqhx1B72aq/7plaOc2sSCpVqoXG9C8shx2E5QpgslpvGi7EmSKXzFKs2PkeDHk3qmvCcO3Rs+byMBDfluP31WlG8Ac7La+bqpRujrZ8Hw7/f8+5NE4LDNbEYrvFE88ry7oW/IWihDcZBAPkDAQJVSfv7sOZ9WpgMdsuo8npCxk9ZPFxggnhc0ogXwyhNQKevlgp57sSzcoZ/KU+RPGCz62Q39c+Pk3k9h75+R8hh49+m2OeGeFBdWD+zO5vJdrpeUTwvx+eR8aq+u5UCukCw1RJF1skBpcKppIdO5/LY5cnpTWJHvrxFaecYHQCq+LhpVPF0U0qsndZ4hn3hWld6JhZIAAylUOoqG5IH2JZhZCWYdPK0GsAprKyAUEJufq6xJfSuYTWHr9xGmE5nLYo3Iaw9amic7siyDtuuYomBXXi8iVJ2ixWa0aC20mg+IRQ5GTX9pVvdq92EtP6CHzbmqv/aUW2POy5QPmXJP42vNuEexFEkJzQSFIDwlo0znL4w7DTsMHZ/hHuzJJ6njDUm4vq1ybKGTU5YkMHUNvdpi80i7dTOYetWQFegyGZtZJZ+xSVhYUcuTaRmUkmP010kblsVfDKnG0pjtSGAd0+HhFQOi4+cdZ6EMrHf2pgqXdrHhWaawzbvMP1cIbW9WwZyCd3+VQq2Pps2XSe2XOJ6RGKNCF1F0kgHjycWUr8xAl2t8iwafXgNTYCWLu3pBVk2NsZo9T/ivjaxoiQT9qWzOYLltTejnQlrzbqIcuiO5tTnXuZ21eMptIGfTPAiDcOzW8oBgjPXljDyrn7yRRmUbAnkozAe1+2oRrtGjULRVVczBFMQ7lRXD4+yGEp6HD1YKMjkUsv3VmCbSzHfKGwG0krbQ9XGrCcx4b3HA2+oqmUynM/ZaRnIZfqXBBI+Z0H05eN6G0t8UAnFO3PxucrUHir0INrlfGNJuvn0iuvvYabT0JcxRIs+w3IHOGJ1DX8ve1L9WS+KZAVlkOcfg2GTIZ+e13ZQ2PXIbVpxct7m8gzI/go7sfUgMsaGwFYYPP6yV6orsvUIPXZm/lxPuGwiwKhWk1tcQvCcq3UOh/kS7q5Lt5o5+rjj++QXQc+c7dShfTcZoQRVYZtpcNlzOKc1nJ59r0U4G6xzBXJ0SVsYOYbTWGnl0EQGaVRICCIInN6YYxZNO0Fw7iayKppODRXYlvp/QSxFPiYvRiL31pKm1K4mknHagj434fE/9wpl3YPeYqwJhqQpE9EMHr6sUgOB71W/QMFdCzSWPkmvWsFcgBhLAGp7GayfSzi1En2luvZW19qqi2eGQqGICXHW+2CXuz+7FaIAPY6WI9jhN2nDBdx2uP4nQAYFWlW6yyPpYKoWhMGqHA7LYq5iasnE+HuQQ87S8fi+OzIv34letJI9Q63wOFXKhKc3f72hzMsvlvXnWXWUrAAmPnTs24+SYQKKRiZZao8NHukHjtX3YnPOp/Ujb8dX+UOyLsyydb6lvXz0FyMr8H63G9nZr28n/0dp+3viR/+M75v8YZtcytwfuhfL7r1mqcn6AZnSBV+mJn2kmv3EqJ/mLtOaxShSSTOKS/AEMYnZHiURmK3KNqLRJwFihLP78wmQkfHaPDUZLvLWMy0eTmchTslwk46xOt7DJl91rYGoX8Tt85hSCLSGTxY6a4aR7GMaw1wiWe7jTrbAeJg/F245bUNnm6XLGrr+nOlDmwLQ8HM7TizksQjzCuBPjceOgi6eAJyjsVK5QIsddptfY6jWFIaKqjsezdRX7oPM4szHMvAzcPLcuruTBKuHZnezsnYQizwy7AzkzrsFU128OqbtGcgrsqIKock/YsMwodSW/vhZxTQC/4nbtRH7JZ3/nDqCjmiGp7mPiPo177nIdE1hVcrVV2gezD/xKticyUrPmpto0y2vljEgP+AsokQK+tFZy+w1hvWyKg+h4lnZ4KQT2cZrR7UfLiYYowICGa3WgWp+lN3hPMRZu8s15oiQKy9y0aIMaxjQYTlwBiW+jTJOIH31VvqAGRKfpRcXamrG/NQRRszunMjmDiMBiAYfVor3BWTFsGF61cmqF1peASk1H4SS6DQmQEEtE5JNacLSgAiNWAxMRpmdZPL+OxXWg8mZNkdr9LF1c0oGn6DpKxujZFaegP759v/mue3QcXEaZovXNWUSh4+f/X3tf/9zGkSN6P/OvmGPKZzKhaMl2snfKMnWyRSuqSLJOkrN3T6eaGpEjiWuK5HJI21qX929/DaA/gP4YklrncvXeunYjzkx/otFoAI0PyO9IuXpLRVQeiF9XAKLkW2obLRW1nN7rkBT0GsYzHSgMRn9qsPk+wFmBdQs+7pVzRSzAsxnSKrBaqPZsGOmJCKjbf4WhIh2n/Ng63MeZHpzu4+KVVTd7PVc/tmxmVlsNbAfhAmCEkWLBYHxqZ0LLU5lQQcDKIcTmpaJqCEbpDv1oOqWkC1bmCUOLutAqp78cUzXKgKGNIIcjiLAPBsXXD9nJu+P88OT8Yu/kdV/zm4CCel493uuzZ6zbhkE7MKOObh7XjNhEPEAMUYliPG6xlrrlX/ijDs/Rrg+HgFOdzocKRdQa2HW2sQ/8BQOUNjGeRrfL6bIy6hqWljpK2TY6HojGbRkil6oWBxU7YWhH9gRZtSO6bNlstD4daGtiRWSRSgFZRGKjz5HtRw1OQ8sdfQiXiSI6lM01aOa5bMmld1V8xMh55FNtR/VrmwH4gpDVo7pgcNfBmJSDsofjod9MBtvwZIbiSBZt0ee+a25Rvdf2XZU7oQGHMadsI0xz0sM6eF5FkrggNGxDRMch+RHW7d4uWt51H5F4VBSE6nmDy25gGM9W9b6cVH9ZluVf4YxrdxfTlinaRYDKPtqpwVoewI7imR4oBbJF3XibdRatX0Wmm2ZCGg5pcjRWJMf/0RBmYVgZNgnTdm6gz6raeW27bZYbfJQVGeg18XKFu8XkQTeDxGyDyC3NX1UrW28sbwBs8Os9dX4MyhGcycXEI10UsXYylcd24KuEg3ObM0rJDLQggTeDiUCNtg8i+PfMh01itVV9x7QQIeRRfIjlU1QeB0unR2VsJe1Kar6QNbvtLawJASa2gJnbVrwbE/7I8Y4mi4dtVjOhLW5f7XUoANdwWwV4TB/N2gJKfJUMXjp8CjDZXwWDEyu48FZgoJlzjtj8+7a+b7GgjZAoCMxwU3okVmAD0SUVOL3lw6AGU6LrDIZVhBKW1+E7Wm1jDu+boDxuerbTKfMj4YyYAzAwfuUrLYs0QmU6b4cYRUQoCGtIJ/ViuijGnD5h4e+05Tbn+83CQgEm5HjMVVSiwU60SJMCdEcOocM6I7mHpIHQnKHF7/lDkccxUSyS3sGrZyeHZ1lxOy9L5Mpn42WVqdffwWudpDHjRvFwdl+obzoyox/UkklBEASvlo0mqYYC3vAutLiNbjxkD5fpgT5TPZuQl8Y+hc86DEpWx0qKmkZwiL5+LkKV3V4r6I7U0bkYYX55TiSo2uVoMixNwt8tLT/jO8fyvGhfmebyCTZEN80t9UKhmHrlaIHZXWZBEoRpu/u9qgkNWGyCqAEjh1we60yNjua5a1gPAqb2rekvHIjGZ9chTMFoAr7jTeqXNgokQRcj+SGsiKrFQq2yaD9odUyJqGbzUhWYm9hi2kz4aZU9393JimqGaS00TsYinMajl2KgOjccE+80jGfKCz0xQTEDuzIbw5QXD2KYJuKDYmBQasAGJsVAmpBkpAsaHhnu9PHBQTHCoohjq4CDqczQcsjcM/F10nFCf4P4oJqs+SZXnkGQ3J4BlatR5mRi70N8Op1qRy30tsM/SKih9S2WOoLXi+F37B7UhFArbi5czA5FzO9Jz2FSORix2WX4o/BzRPqw/A04D2NLMLLKkFdQFymZWo0EFSuWVuvcImNg7WA8jiTrBItkD/fi0ws73glA/nq6nN9Np5hIExKcg6tGVik6Ms4qyjVxP6rm5S1ozAuXdeXxRB7GJRy4YiSdsl1UTYvJwgRxVHkOpjFFRbofIB0EGY3Wmktk6RYT5FRi3lraCeDCQgoL9JGQAw8O+3thf6shuPFwffDaFF835BF+/21sdLonw5i7A8CM7VtvMOI4MPrfhjyVo6OtP6pXHNfehf/6RzdzOarjkAGGlqrA+aV/L+xvQ88rrU0fbLQ+elTe+nhvY+vjmLNevKVvoy2JM9tSFhsj3Dew+16npWm5Um1N7fGN07J8MgcmasVadnh2HdSAwkYUg3cDLC+cGblihUaD0qneFtPZe9eQos4916e4llncAdpAvuYeaxH47a2d3St53TEvxyMM8NBzIOyq4962gRqaBQOdU29ATjG0GJouK9ZRVnyYArdfYJSyGaWnKeYPWXGveH0MfbK1GJkc0SZqp7aKwxzCekgKJ9x8gctQ53pGPAcT8GBZ9Nr5xyznowQmujDInGOE2B3oTcZLBjuQUzLRYSeL9bE63rHs/U13BuZ27l0nA1TS/zP5RJtglAPJtU1we3FwEW1ZTm7U+rF7Md7m+3I+Kcd0LfoCaAIl8jMKWTQKgZSgLRznOlBwSUkTYOhk/xZCYgeBYSI/j+5HY7heJV9eNnSHf07Cfo6bWsy7IbUDhhGH7Ea5bRwuWnlPXditUFzNk+VGo1kEmhhj6iqbhKHwpN5OF6PfhnoYE8NCGqWSNOv61nyfVpHmmAZw/oGYvmqxBPHYnpTm2R7JNZyeQQZ7yupnW9cxe9Za/2Mxv9/CaGJq0DwhISSpgA07XJLIgXouuIsbTcotssuy4oYctHck+DNiRC2YXKKqm7wgiWK6XlX5kekYIg2kug++x5uRbITmIjyQfOuNNlCBO5ZLtsOSZfmw+jacQCOqXpcyKxuuk1tl90x0paAUp/PpYgqHxKti8n7jgBRoeYCuVPdTIPvLeyV6PLc3K02wKGluEG1kTW9S061WfMFPWeAetV40IvmFBAEF2evlzY3vqNCcGWhUzY64ZkrMWs+T/rR91fq/e9knLUi1swcBVB2+pPjqGFW0eRwOZ2RdycR1UxgSmpjfcObj5Nzw9X1Wu+uuLVuBHYdtSTxv3BqoPIczFOZAXOmOqtzaACgU5O9ZrBvfiPrjdI4sEBbF6PrwAs+slmc/DfNWpUABwnK5qXfvy5YFCimocqcSwfbaV5FrpXRrAjBrtYjDV7JnflsoIjxvmcGydW7XVmBD8hAihALIuNzbz3UWcfczbfmVRIdevdB6W3fb8ZpLITGPxKGwKa8wxgXbWQRnD9/aXi3DqEcvfmPEw+7MOCJHIp3Y4XVRp5ljts7tTnS+0eHxemJsvBGaAOT8ctiKH+hymjfn3a6y4D10j8wh8xNzcZiI67z1Ic3qXUIXV8E9sQWR/v6Mj4HexS9w24nB8ROZfQmM1kg28kZOHUri7n9NibDEGWIETTgsgB2EPr4zh8e3ITS4DZom8foEPdfObPUnqWKojvWBlLlhkgKd8g7b21t0Lxt9coZT1ju5NtaXQH/PqdmeWCGL+Vsc3CbVln6zIoiPKW3ftZOnPRQ1j+3wyCdp38yo/diTXzqQpGhOnO7EXMrFLMIlEEyE5zLfSQVlqp8NbsmvP5Nw6MymBq4GO2tPZiMGydjvmSPGjsi8MDYp+tkfZ5SRko3iGSZfASMUnjI1h4m+HY1zSd6YgaDJN1+3OwmROkIoS7rL8TQbGNDC/y18oVs/zdCFyTJCflEueoLJEw1dRQN3bNKrt/Sbd+oWbe0+5Tpv3mXI2Qpwh/u0ns+VYAv2dH1lMX1/+6ewwmOVvdFHOGZ+SLma/sAjFZllqKvnjXkNTtuMkAGnw9sOqfjGpNIL2uHIx7gAhQTc7nPCyMPtOeh853qRDWgz5YBDiLXiU65QVPDIlumg9nylAyqgY/BnhYwQO3nN0FbKI2xwySNybdGEAcQTTtwquXVNjLZOPOHN+BIK/+ZPJcbhG5tI2bm0RjVmkdYisr1bl8plQrZWy7SltQelS2wZBBQxCv1ayCghWy+WkHHqgQDSBSOmVgoNvYaIIbPxYfDJa0DIO27C3jj0JNiFroto1+N9mdki6ONy2f3oUzmsl5FQVSmkJDMyT1iit2uD0yyR2UNoE+BFp3Qz69BQO6ynVBdi8uBfHkMBraa3YUjuivkwv50NLY3upKjvtZLtUnp6uPHrfQ+3j/Pb0aRHF5CLYom/nBh4fj8Fxw/oc2tSqgMN/NjUGfwelPHTD+COxPoeTMfjYgbZ9IoBuJ14wiCFDtKLN4z4hdFsmEAtUJqXhqkx9LaGXsL0Hgtp9HWb2rsJ0qzHaALa6ub1sDOohls/XQ9AqeoG28l8NYTXjHfrU72HMPyjMYtx9jciIdyM01z5NrdGk5umyYzKXGfMoaY9Soj5YdnqzPCsV40l2Oxb4C1gklcLwZZP4JL1zrHrqjsYQ8hLc0d7PJpgVqgyw+XeMu3ZHqofjS0P2Illt0uYwqJUECsUUVXbSDdkfRemcMlLcSon79EJC26GVP3lrAvJFcYYwBKtZyBVFQThN512E3PrVgPICj7PZTJZ+1lS2NiC8HZBmRV2Ya75dsQ1340aLw63l/2NVnBU3QClKFumDWtxY8r6R4wpeGkKXPlr1QhNrHDhXA2+hPytHb972XDstLTI3vSKM1IxvhBuaGuuhBXLckOQ3Da28I10H9xHvddWGGR7OHuvjeIi7XehWBtDTrTa3L8nn08/Rnq3q5v9S2y40uniPSagB3dAy2dgsz4msKhD6NHiG1DjuWBptLDs8BUJHCyXrscrNPyQDqxsSSNbgFcOj211nGiDFVpL9dzGrO0vnT+spuzV9GYBps/sMlzrx/B8grtBOb+tzAEZEsAvabxwG6l/MyfWsrJGUtoI1hDz/L5YzEef8DzRduFak6ohL04g79QR1BAIbmVU3fQZXnGEM7mIelT4EpzVIG9QufWDlxEpoAKOFwHzdl3q6spdh9l3fO78xPQPS9hi8bECesKYDLQOTvc9r94QWqG5u+YlXuhZ6Gw383LGXSpnqlnfTW01myBYBHQc8lRzMcB1shzNdtZYeY2cEDYOBFc2ln/nIFsoWsBwz8Icz8JctTWfzh5a1E6HAcDAVTByGwG3EbJyO9uMl9vZ/t8DdaIQYhutvwgek1WzEj6FEkeUVsTs8FUAmzUwa9V2WvqiqvU3f7yCYWt3y0+zYjLMi6rFe2gLUkCOkOawi/fayVwoIn6OJflI+O0disljjNkIBtMhYyF9lCkyauIfIDZaQY4dHnZ0/HSQfA6eeuExyJoUNvL0ueZ8C842dlLMy/EyfjbowbOTITwHLqnvK+88AJVdPp1AaCU9Il2Led658PuH5xeUdqDBA5dG1MbR70J9HJbwtcbZT5kxRtWDBfErHKmtjJ/bAGsxLZOMQTeiU31TRCn8r2yOgu5TWC5oS7HiCp/nVLST6YBdTd0sBXFqNPLzC8gz0P+Pd/3zi/4+LBgGJ9ad3qlZKkYI0sTnFFWmBX8gylSOwRX0GLS1ktcaeT4EPcA+MhQbwtkAEI7UT7XhXcT/LoZqaLa7SpwAmzG3rs0z45RKI8qeKKGlgORGy3u0PHO57xTVAwGkzD6q/bkoJ1lB+XUn5aeFkkVulCyyKGfsIktPTi4fxjQcjwkKBJG5jdKHqUCxFii7WzSk7vnhweHJRSdzjxf9s2N+40kffJiG8LajoKD5SoCaqe4pBCNlsTNZqaTvjotCWi4QD3gNhQ66oSZRN3Z5Zson6mlbT692oj3nQKQ/k9N/6HADoTxNCZchy4UXpm+R1G08oam8pHRRy8/10BqJOMQm1jAV43uKgjcbDrScFaABjKxAJytn08Fdx7RBAe10dG0cYa5oGPmH2EDbZsK92rVthOCRvh3wTfYQS+Dg+X6Y/L222QH5N+EmAgecSgke4PSN82IRJpnylNEY3QqggaJnug5Ddr189mML/+vPjaCGix427MUJjDXvhxIUzbbrx+yBMDV6r1jLe2ap7pJrsjpR6p1a4/i6KPJlW+RxDaPDEDRMwCJGPR6NjWKzRoAbXTK55cJIqZH9Vyym96OBjn5ZFR8gxOwDDAudWEzMTMUlzaZzcDBAP9c7xWo0u4v7WdMxwdMZJCw15dQQP16rU7GoMiK+u37sKNEVlXEApufujZKE7xhzMK26N9XDZNAy30fjcjJtac5tWtk4mmwcFMZTzhaCv33lySoKXU4GU7Twby4XN1v/Gp89dN0dLu9n/uQ7aFY0WfSe//ZgmE9uNcpKZoelvp09LO6mEKWTYuABM6Fr8ETIEPZOlZnMuq5YHpbDJVflaOmROXMjcOW+yc4XEJCfwjDBft3fP0Ut+9PKRlF7/W5/L4MsS2pTTufd7D+W5fwBtAkYioq1ZaIgHZy+o4ilFKtKB4MEEpAN5iWQRsUDgjZ2qLW30CF2wxoDWwnF3VS4HT8Wir/JLl5m9+X9dM4C5pMF1q53x+vi9HlTZx/07HLSUbfaQfBhVjbBW5sLaZmpyuafNUtfVgBjGEWLKPguF0nw1W7sXNILXBk8wP9eGjzR0qNDhMoigi5IuHLFYvYOZsv8+kFRKErkS0GKdT4N39mZ5ClRMs5uUGxkbg+TMt3SocL5/ehSMbf/6sXGSVnJsKDceuBq8uCENS8e2jUxxTEnMQIjkk9i1lWUHlowbdLo1HscWvvRY2sBoOEqTP2hIdaNUYMZ85AQrCNwantnrw2o7h28n79kZycHhFnZ/bJagORAPTzT8HqmR3erMLAuyRWiRieDkehxyWTD4fWiRrdveEB3Ecr9j7ClfmrDBlfkQW3widogihS8VlQDhm1Sji+mSBK6urnThwtoUNElKAhEAekSTrRcoKmsjhSH3r9Y6pWa5AU1122wk1DQBH9T6N1DFPRKnTSqpaZztU+SBTJIhcpAdFraNjSeKBe+aS6xl+kOsfxVAqlcBYVZZBmzWCqWw0eqb7JXxeA95MzJIBO9gvj1CK+38BD9sMNkyqqbopkCPmB43QrtpnyogVoHYKXWpKmDXqg3FF/dDF1aTdUZ9aQG01o5Dg4oPZqkKWnNaeCnZDLcjJKe4bDKp9eQkKOiiNicOGqqHtHrsD1/iTWuzG0OKb4ukfn0zM2iihntS+FZe+kxtYyJAYtAzyl1xZU5po6bBphO6Ss5FPuiqaRNSYmJFOoSPwUzpteXoC10WqQOJjbVajpUCIo7BDMOy/orBiy/GRe3bLjm1tkoMdRXp0MkjLjcgdFTIHfSRF1J2qr2wovnUSel0U1qIS3s5+VwOUD7HzWk6ayHH87w5dtZ93jvP8UKYAZbKGvUoGZuGGQdU79VgwKkFcMZ85wc4sRQEkf3QFU4p/Ka3DRYvo3W3kLH7sRDouPOixAjvdbsuHA7FcuFIt7qZFprULY0QRKDtmtLeeDYgVgOWTT8Rw7W9iJbdDyXEjNzm3WJrZ7bSMI0sN5uFmx0N7HNFaQtEwEhAr6//DQr5yOwxYdMQUrmdLmC+/952j87PO6fXHDeXm3C2zIoe36xd9DnxSBmJaonKkyERMl6z98e/do/A7zM+6dvX/98zmu4qesa7gUvpv0nUYEWNn14fJ6rUeev9i5e/8yrYeKB8VzVcCmRdZ1Xe+f9/OiMl57OFqN71fGcTVSXfnt6cXh8+H9UHyd7x31POsoNkWIjg4zJR2/39lVdHp1VwLQsh+Fczvv9fV4KNPmIz+Ggjt6en1PiY1Z+NijQnVTHDxNT1xlHX+/lWPVP/cODn8Uy386GufHRiNQ8ON3Pj98Cbrw7Fstub9ZUpdqk0XygFIEH440ZBeiun2/7dO/wrL+P+ZXz873j06P+WaqN2XQ8GoCc2sRAbQpdYEkAlSa3Y0huR0V3mgKtIU+G+QZWO+EQILnx64tcjwQmJSDmBWtlC0rVD87evjtRYFPY/3rv+FCsLZ4uuvNieRvp+79OXpue994d8Lo641VYx2RJD8vm+tbch5e+eKObXIqfJ6CEr2wo5Rhi6Z5hldRKH5wAikTQyzk8j4bpZlyi8sP9SCMsp1mVbuT8df9EtfI2f30UQ/RYZq9IK9HE6WJzelHxwuUI887X1fcnJN1E043qKcZizzTNzXs4tp/3zvZztaljpdOgNbUiYLWV4S412Aq24sXb01+i1eiOs67P472zg8OTaGVS5JICPdm1IsNnF3QO8UZMOqEQRm8OT/oX704Ejb0rFdM0nuf3y/FiBEHF57Eh9/f21QGTH787ujg8PTqUlMsPPBZ2fHF4lsPl6+HR0d7F4dsTv7Y+EpPLBPUPjt6+UogSwX/VACFfbX3Cs7rqLvRObRO/9PuYkf3wrYC6DMZRron9b/p7F+/O+vnpWf+8f/Zrvw75A0PiCJE1pCK2HWT91eQG26ghWthMdHfIJvwtIhtI7hPZSLhZvHEUy5VtXOy9SzcQbrnEksk22SasXzSwlAkZklV9vNo7+cXyKUkdKdqKgLIhxrjDbeSHcuipTeHVLkto95gbeJzgUXlbQOhRd9kOxr+TqbmrsmP5EXOegeIblSmKX1kO1HsIYQp1K9SiNyMW90yn6zKTxGUULdiDrypEnapsJi+KxvWwm31uupECGwpwQIWT+gr317oH9cnkLjEfv/i5+1j2O3mBzZuEOH9+S3rxrGRkh+sW5L6sKiWmqPE3zwiOGEvrdqkv/RT7g+EKd5PqR3tvU7VYDwoZpgrN1SgqL6WakNYCllGRp3fHfTim3xwerLxY1qNvPw6/bG1j8WAT3eWD2ZKn3UxL0o9Mt5lOtblRmk2tlMAsc6QFRCW6vkAzF2lR3ZC9ZMNkmSgiizR++JXnBcQXePGHv2TmPryCXtF6kCVzdRdBUkxNVZI91QW6PMZUd6YXre8ttPodakMaqflDM6EAAEESNlV9SsLavJvYs8lLKCkrYh0tJFxaGisqneeRXfxoCOD1q7YIn1ZdeESzunHpp4slQLxRX06mizcgeWl4fP5CtnbwSmxvfZmg0xbKpYluEh0ji9Tkq9GRzLQi9mWhRQUpiIPUjGtt89Hkht1xYQ7Hcpg9qejOU/1tPRmaW4x2s5OxaZPGk9lxtMU6gccJHuN07Jm1wvAhcPzKpQr54ug1YoACPP4+tO/a+dPe2THxA6hjUNLuxc8KCfvPeZQ02p4iDaOxqUXk6XmKKdeokoUv3oKOBBt2IV9F/V3f/9HHQlG6HSPlIU4GNwAwJ9sSP/vjmOt1mrj6qsHmRH08ah0L4EgUXSH5LIJCps9f2sFZzRoAguiFR5AlqGGmc8QDXoGjKWppChCtbLQdnczL89xeea6G6/Anh1hsFSwRhUusMYbd6z9/9uubLZ3NYzlpptbAQtrQDQFR9xn2U1PA0q8aWKitPSmFXCE7Kbv+MSsWcGOeNcPqsw9LkGmLapG7ZrqzxV1q0mbw2HL8xtFFJkJXEp8genNPZK19BHnkJFKBRdvXuq2HI9aEs9nxaEFo/oXjpm1BNFIzMUTJrNKY/cxNtpsKYngvwZgrdEylSxdOap2Pmn4U90zssHQgXpOG+xzZZwkrI8DtyGE2wdSX2fXtZtudSMXcbBhVAHenV8gCIQeD4RkqvaPl1NcqV0TCCpRoAyoLaa0Hmh6H48Fgovd7p+rTFoQbjnw1bfsfIRo+6EYhJebSzDcyANwiqwoJi8F4kY9wkwcbOq9KJaYMqxzTdcDIgoFXkFJzOiFPR7lOXxo1x9aazJMRllaeSI6J+iaD/aWkT7R5wHDy3QyZ0mdun3kbHg8Ku0d0M34ZyN4KZuajOTfKALvz6UdMzYcWGJgZuyRvoY93aka6NW7LMZjOIacD5vW4B3PdqHUGm3QdQ6gtPDCVt94uHSNjdPjNEVht4sZufkkw+a5HI1Hog8/0oZavWl5X6uhwReuEAYkrxABp0RN4HrLGoSkqUCYJfcc7Fpp0GuIct9BYTx4HmvVdoUZhfcTZi/YGLLRrzEpskVPDLkZtfbdkV5Yr9AfrE3Ruhet/W68z01C6T0sthRm1eVnbi6uqmydMXFGnGIvxxA913Lv+UH3GxnOJi5/6vHOvgdhijm7kobhyULZ0enSiwWCAUrsoQBVvWQ7b2x9o8TJHN1hh/cI9rSK7RB1E1w9YodmOfhZO4sLe0/SojeJmOiUzOM+G64efmnzx8c2uJy0gxdNB/kyZS00HuVGVYAfAhRg07aaCFgMky2AYeh6IkjMdXqfUhseXdLLtNmdxkMKYIfMJfJehXY43TLSXYMU4iyuLStY2GOh2JBPYN54BXPYRMqwYlyokq8WCiRw0UB3pf1Qyg7lwJThyrl4LgZyJsa+GH9/iBq8+f2lwNwgrBW2A8KZqDdJLnqpdb9+imTw+F26z4fO18kWnkWZw5QtxZxFyuRH0D4vZHSDsEnxW2GvF+x4xldEcssQTqs1L4N7hFjOOg9b3Ql5lW6CDLHZYWVzAxiob9knWjfLfAcUKC4nr9IA39xvwSwige0y7eOYmS0nOPXY95Q0gVbkDbH87fhvmcf8xwMoyCFvYrd6VF+xl8lACILo2aMiwMcWR0XE5H9SCsye2n0jWlHyX92ik4YbgZDqMQ+k0JNNgvnFhWN9dML9BngcAcFm3EqAIvfdW3nSpJOzpssrtsuiuNThRqC5Bk6l4julkNJCfKWSQ1RgvNcTmZVFBD8btxh3mQBTj9rzcV6YtqOnqqjX+aW0x3lLHq+plMNWunVWrjaHEEnN2CStZA4TqIfzaGH1MdEfYsFzMlgujrTWC6p+nI7Ry7b59d3H67iLfPzzr1OminImsNej18uE5fain4yAZNv+gZEYiDc87nhX7L3CLhTm2o1bsalWHkFA1e6OKFCCCgu2lPrDBj8lrbkT52MztK5b7MSuWi7upOv0prgudlGOMhgC3KobIx9Uzce6rE0RLJqZuNzNaNnxu1ypSoGn2pp3Wq9DCmxftOhULNOpetNdRuKR2bw2Jj25sbppYAmmOypfcddKrx21BnUC5TgUj4u2GImJNdSe77TJpr7ZCYUoXK4p68spuJDopE9h4QzUCYeiE5p1b0pJjjTFIsSxwa/Vc5dJS4Xoj4yLWLqfRCVWeK+u98dv1FRy7CbOLtfWBgvSu0AzClhPvggVBdl4RwuVkBBXwIID/hAiGJ5q2OqaHAIZ40Oki9OAXIQsM4MQUlUeP2LavvEQJtsZDmR0d7BYLB5Qnyf3XGb1eOCD9YNoJIpQ/P24Yw0bqK8o3NLjfwOj+t6f6IGgMaOjhrt3ZVoxr9q1/LsAWNQ/ZTxDybb1tWXeA2DbpzLUN/i4Hy+Y7T3JF+d10OUcE9ZizZ9mLH7bDOwBHH7BinDqkKq+168Pd6Dzo5fWu2Huyq1rOTiDxxbvz/M3hUd9zqFjLC+q6mM9H3GcIJRuyNwCdirgHQ8d5F25nHRbUVmkkiNNqdsILSYDZlvP7EhSFmm+fTz9uMCQHu+M+mJcx4GkrLAWYirXCL4G8mAZ0gdmE6/RJ+XE8mpS95rqhDUB1haEuBtWH7r6a65/wRcvEN7gZleMhwK7qoSeImmUXLOdsKEl2K0Jj9pIKYHNd/HOHLDc7//lH1TA0bkGsd2op1v4DJl1Dxp3iyv0FAglgYkC4S4YQY6NZvlgU2qCNxqKbmsI0z3aQBMIrZsVSfMKzv/c922kYXxqCtvVgrcB1AC2V85O3Z8cdpl7TAYVdqbN+frZ38svhyUGHxc+Y5e9dEQgD9Uve/3XvqCNuxst5T8+E6cPs8CHbZGn4J4pxhfNoW19Ocn9D8xG+3azq2mjx3FvhyxaP4aU910zbzB+NLrStt6T2fDWOerWREvQNn828AxYOkFu1dOF07UJXdGOoZDLV5AiSbLgVHRQT3ZQbY/bxbjq2DUH0PR3RGaauJL69g62z8nC/++E5dlt+KvBe0ZxlLqLvMxqCqlEBs0dp44uFHpkOeTElyG5n47IAwQ+fdkANXNiRke2pYmhfvz7CQNNK3AeBES87TX11LN9gHM4ig5jvmTurfoT5Gyd2CoVxMJ8uZ9jcR7CBHU5vKal3cT0Fh/jiBnb133a2IbrecmEUz9/oRkjmJVeqTF/5geLYhHB69fbiZ4KWGUXpYhZjNOSpATtd7k4/TjBmx7IiIGF8jjmQyWGmbREzDOajzlWIRDWdqPPvIRsudbbWSreGSeUxWa5CwfeZWk2d0hzOy63BeArxk9VBh1fGCoxjuDRS1HS+HIygxY5Osqubg5jLEI5EwVU7tBvQV88onU92PVdzBjfQyqTpdHDvZq+m2oTkGw0OcJMubyDgyRxTp8NUZ9NqseVqZfo4U6ih9hKketVqJD1X68Om0agnthdcgmmfZkPqUCmyY2kBnVLC9TR2fnHqnOpbOplSIDxxaicHDcMkiiL0NUS9YgY8ewca37Z0C7AuDmi7titYAocGCpwUAsa7zca+KZCnj2wKNmpTIh5k3g5RmKOY+qYfaQK0RFCxkzGwswOmDdqcUj1iyns3sb+OZq3EkdTWwc5MLGIHIkfOIS4BlobQIi0agOuTr18ryNGi0UW8NyHiVq62KYx9otd89oSfBP/cw7VNWeUNKLu1NCge3SvpRrFJI9iO4DrZycCFUgdVwBMc3yFzNJqwo9xjGFxwVosFiNd+7goEzT05COBfiBujM4ooMEzya6AWcDJLCzQvjYWq7TZVS88Cc0nDf6K6CsNk7EbTE8DXGQQ+jbWfTDys48youmYMw9F91bt8cdVmw4lWb8eHYbuPJCowgVCz79IpKWrm5CefSI/GIbtONOZGwDEFkUNPVO9Jtk0UNi8whohOBn8/UCXLYpJDwm5zVqPjrdqC3+Ya4lQZlL+QUrvd8IKCUL6mAST/lYHW6prXzOlwStcugjfV2T0HyMyCgCmvNwTvKiG3ps0hRoHNbyaC85UtkRPf3Nl5Ez3G5O2r7S4bPgVvklWtuWLSJVJBQKNXLSChmgsKklDrb2QilxlrsJps3ow5tvQgFnlHh5bADBsUqJbsTyKRcnelubsdxGTSNWyIEp0sTd5X/NGpfi+3lMYU3bViU3qXbuRXIGxNAGJL0Cc4m7iYHYqMRAT4AMxzMaxaOz/ARF2zeEDT+f5Sby0SrFXjBcgDKdaBJYM08U9dxQ54f+ezcTHBBM5/+EFHlpLZKaP1WBFV8/vtbRdPHwMjgCwaCYrQHU8/YmJMgPNMY4WCVF4sP+XEYlaI56YZsEmHgBFN7zZSME4ylai0B3Hj7PF0jUEuJABSL54Uy6b8jAdd8DJoxRM6CkbAn7DUwrk1cLJPrroGuCiWsjaUg6vrEplR1eeQeChoM7zTFYCN52rdHMBiQL1geI9fjTon083Xpcb9OLpGdMuDLklB2J6GM9uBAtxeXVjdNEKfWWYn2vF8dEJLx07S+LETWiryV4V49u/5E3f9DpJct7EAIUr1awirBZOAacJDHLIxB74+PNrD3uuf+2fMEekRfhg1XRsL3yoLe0q5WfjzBftodRSVM/jB6GTbP7zq3bCCpjsJp+pwpJ5q+WY+/Ws5AT8L3V4zhvGiry4QpSD0hQ2fnq7jB01Yo8oMQ24vpu+VVLGiOFONGRnFnqkggMjS7rj15Qz7pWvWm7Zri7kuMcd5bcxHG9Yz5NP3T741pCnr2bHJSoGlmbHHNLVDUzSvAc+cz9YTdlJXvhmON0Z+46Tbt/dCxozElLVmBrxgDEjslkgXDe932IgjN0JXJpdDMTZaeVbBvwy6SlgLBTNI3eJetUPDIW9O8kLJhFAVZI1R63U0KNqvQzecPRmCjpHAqX47pFIP+hoQQ/qr5w6CPoM1etJ9edP20lVH7J/Y3dB84RtcxlBZfg3MuGyKL2F9xlQwxrUf4jYpPhYuMexqsMO1f35++PYk3+/v7R8dnvTzdyeHNjwexRzRC6Uq/8BvMvldFeZgIGp+fHjy7kJxP9pE60bnG9BSCztvI8Pb8vsUDEGkwk/MLDfGFMCdshKEB6vnoGj4619O3x6eXOR9xSX/l5wH0hHbmHCJaTX8RQ8lsO+CgQgvQX+Qwax0mhc/9RmOIydlXo9neeEBZiC+AsxNT+v8on9qWNN7JYPeK/4PtSkJCEVYIgUZvGhRS36sZLnDkwMDLJ6xsM4GLb0jfyluQYFudiRkCBzuZhqiaqtt33Qwu0tmUYDeYboNti6Ac/gpsTG5MN3xVXE+mnlNSJxWh+DWTrD56OATVhdw5beb7anVKm7LY/jeopis8AHTe3j37UruAm+pYjBYzovBA/wegTV0E8S1cbnAjyboGDxA8J7QuouULVgQCrlYZdjg5ENOjRoG028B2RAoYOMDdXh4JfOki3msjxe+iPeD8XECVoiu2CFm3MxcodUEC3RBtI05R0unyvDs1TPPHryTNFPPAj7dHP6k9Nxd01MUtmHUqi8wrYeS8mV7pd9nJHs2WFfIcm3K3iHePcIOLLDwRx5Jvm2v4dGK1YIPwrzCLidaKzDza7O8zhEajYmNIbFhbnhwXGTv6+25GWnrBZKv6bLn9R09fHvhKSzZs55vFi5EyV5EwrASZC8iXsZEzF5a5hT43Ev4XJMU2vOFUSmQ9mKyaSCf9hLSqm+h3gvN1SP8Ti/J+4Rsa0+/kuU8brUnuFp/qj4L20vZwK8893srrOSj3GKvnndUaN/jpvSOGsFO6BnLeu84gj2FNiGQYvy+mD+0gh0ksFzmHWDn+D+Lc9wLaoJDpPZ/K3vD39pMUKfm2yhEb619oYbnV7ItN7aEVkBMGxHWmQ0ysVHxH2v58NdsGWMEKi09ualWGCB+fY+G1Nm0vjEeYWRnhU+FPSV0+S4012zHdhIyf6C6wBwJXLtBOhtkPnvRfHVxzpiyFEi+MhkwRPTBHtRKsjshwAbZos+4+KHbXVM2rgbjr0LZJx8uy3Du6qUQisj7Vsw2uDQPfG3U2FMSVzKSX2I+QxaO3k3HmODkkLxzriSf+VBza7ssnfoEm3ASNvftkhvCSUniqjOXd52AE9YIz+dA1rXIi2vLYwilxpLGovn0Y0CjQwobo64hr2wJrEdcIyVXsccktAhap5N7Ekxjxc/U1Ld2ghpq+pfbV8kK30crvExX2NmO1vg3v8YXifspw1ZvTycEYuz+V2dOZpRTu1r19PwmO9vRf783z9v4oxlOJMJ/aly4RKBfJb5pCNd+/n5F7W3/u4RAoGicfvRzP2kUyH6yOzI0Fwk0pwZv4iW56pRlDfQ6Zmi992s/f6XIedxQpdbKWp9xNELSkC/uZLCrhEV3zKqbLOgOb8hcTpGwEoOgGsUJkHHQaP+ZEg2heV1hZYBh5lvtf8OtEkEJChacxteeqg/uismtsUWk25ab5dxZ46EmK9AxRwmQLcejJgR120F55lJvBf64QBAi+nZM27rSWRz+hU4t8g2LzDBVKDWZLm/vjPJ7s4MwzQKsKrolzv4/RlV7iZPDOza9OdjDE/iLNONj4i8kZezYMkYo7axAUw28IBgraXYRoWJNb4i5Qs88coPRSQ2gV4Mm7dDW3spMv9NwE/Bq14lhwubobDlBS2vF+ZTzudj9qIA0h0qzIzdQ27ewFPxSomj0nkmgcC2e1M+5OaepcFnDK2EmyQZg1VS+epSrjSL3J7oS53lNXBJ+UepAaDNE8UueLCo/QvABbsKK6jQyDgttu6xFrblpJfWyTrru70NztUqeDQ3PxhSBS67Zlv7KJdBve/yqKmEVy25knYbwKrSKDa5p4bJfTSh1ExsNIG0q59ObGzU3exvJmjUBabzRm2TnDgNjF7fefW5tWwKhg+zNSYVXp7GCHZMpnhMBNtw1osv77EMnYVWD9hwJRNiN6wu7sCY+d+SrlX0cEve23vF6FWT1jMIZ7eFTTSTPRlydAFW+Q2utMNkw2+4OqCu5jMi6pcEfgZb8GIn0GL97SCzp33koyzk/9kg2Sku8sMuJYzRxbJLHcKh4+rtP3/qReJNdfZxKiy+y6uU0NQzF5eGBIN+kkWC3UmSYrkT7EaQ8Hi0etPl25blHRDJqB4gX6RzQXnYZv0Doqv9P0QSnBbavi2k+USsTMfIP4jWsW5HmCfkU1/ArcM4PAAWqKs8UAhI0p36pqa3RHhXE5ApYWTZIal8AoV6IDTwfpCGnNgylUbcjnaitCoo7eoDw8qWSUmUbDMGs/0Y86Z8MqKL4PBTOtMWZNsei4KPg8jdaVCyrdwFeW4gVVaYOr0h783JcFuA0rSVAaBsWe6RgtDVQsigmnK4WSwCa9QibFX58Fm5Jps1oevaFzTHls4mMxEkbv6ROK+LwMtHo2d5N+4noxik2ARsZ819RW5QWzG7QZHNgKo5Z0XmreHHyMj2GdY0nQ2NK37iQgpmWn2ZTiIFqYnPri/iqWdtielK5mU6lWH+1JeRqdtz364n7WCw/BXxBPfAbm48shkZsAJcspRoAQTGnQVN24TdbcL3QZoEV9/IivsCQhk3DTd/ywEgU0OAP+KOn504g/Pwl1OQF2XnX6q2jW9RdhpmlpxWeRjn90IYm+GQ8AW4mrY36dVSvsXpVSa65BDuXK+PfpEejk7PyBrvVXTErQcmbbMiYytjW+JTqmwwXHI8cOvmqFLVyYXz06jJgxFDIcz+Ir6nQQer0hWliEgwhvg9S1dE2KDeYUBk3rAoVmWQ51MmcFdHKLY5Fb9RpM51DHtYc8xSsJm3RQXdWVtO7dmU52tWry8mTeXV5Z7q0xhiSOTA3qRtNKtl5JKFPfzE7yrMosxvLIofdVTurG2PGaLYh925VS2kiWIfHCmFPX+/VI2CEgnV8VGBLvSE4zeyd8Z6dvBs0n3y0FcjoqAnzwel+a01y4KbD0yqIfd5Ycy+olpa97e72i05j87mDIaGdtZnKqgVXdBDS92JGKeuWlsYAdmwpUciBNvs2Syb7TfYLA35Uv2ZyjXQ8N1qSqoYDXpP88/yx6KdMKWvVws7BG6axJrHFcxzCdtcc3ukljkxLe4kqSecyOYYWkeRLQ2Cusp9qKCTEvp/cttIkxvewUythWk47ZVPUAgqWYpW5vnAWq3m1AhQaJTZbEFb7VsluGEfdg+0Gy6KH0KpF2+TH77La/MMK3Bz31momkoFYNSNA9gjCoi2aHfvIhrWKvpg2rC20bUWMqpY0i80apCHeTSzNAI0+SOdI6a4D968VyML9uABTQmKNCgfD3/4uiJPKyqyW3YHgEWtOxud2sVxb66+Un0w4vlAsrbCWkGyeX7l6viPe2qR3FZ8bW+t1D+xGPdNscSNd0CUz7tUnMe78LvgVZHRWiOUt2drt8MzOupm/C0eZy4QTRuXY1iVPzt9CtLQ+2m+oT7PZp/VKeW4dKxCc89Jfaxd4+qf1tUO/D16mXJ6/laB9BFYFHjYWI2rkAdalw5RE5zH0SSiAglzycZXWxOTw+KmX1eefDxVGcfxEzyS9WsZL6XeQh2oiEc3e9yJThRTm6VqUwjxWj7KWPwKVtUQSadIipIVlLdpZXzCLbrbeKtqzCnmCaA+bYNHqLOorUInHzTbii045iQZQfkztNNF8jEq/aWJ8kI8jhLqwERGsLt+MARajgMiBzQ3VDzJDvUYN+XKTDbSCqwDhMV3GB/YaJUOXopq9JhFiww0nK9ftOpruMt3x3rvf5+SRw6hRcZDIHKLGI84k6eG5+kAKO93sVDLx/eFPC6q3u9fF4D1cRnr6AV1yOcEfecveZ3sXtSYW1VLx71V3AMHpMEAFxHXLW2F4iw7Gu8XItjs8SQ0fHRjRJPozwyI4ebNb545g/QtPlsZg1bJI3f9wOOvFInltgB91OQl219v3Kwe9Lt3ZjPZsQvXgXwpYnRpKLY3mtM93lAjYm7Yuuvy3L3euuuVfWm7a7S7Zvre7YP3eatfYuTgJuqq4AL3JfZtVZxtHdafN1m9Sgg0PivJdz9vtadsaTLPmbxKv+BMZ8uwgB/eVt/teIIKYuWx0jZp9YDYunwyvskPTh3p6Bi+OgFo/6b64yfYGA/oRP5Kbh/v0+eLsUFfAGzT8CYd9XV0lk24d6Orq5xH9/KWEcCTw63zrZ+AZ8PfRGXiAlM04vq3pIr9C44L4UnwA/4Zw/eF9vZZu6Nd2N7UrK/N7E9EGcaQr6wtRXA6CSdYrm4nIXivr+GdjsoIzv8xh943n2gIzqp5pr7EbeKyQ6B4AwxHjVujbFIY0SLgBgt4r5SAYkwFcV2CZJSokjBp0tPOVppkrzDTT9KWG8VxnXyQMOTcx6lzrALWQqzkwV1l81gG2/lxbyxZUVDDWmK5GPp1Tnp/xirppK9H1LqxXWI/+bvNaH+TpuXneHo9a/vXHsdrrQgLTkILRJNeuAevUW73ecXisFZspVOR7Lsc1IZoSlLYuwNFKnoL4CQgsNgTVwgiYgJ2b6kcS/SCk2I/ABOKvpCOn8Pna4j4kncbXOriFA4lxiHmMhbznfwesaxCUpzYMTkgt1zeTN/5LcCmuvZ04f4jRrBiD2PiK9vUh1L6OjT3mo1hpYq/9km4YBBIRIr666b0YYAQMG1jf8/F7KaZXeFzCvzqvS6NLXNPzMlF8I+/LcLobeGGGx/5a9H4dJNzoIGwy7zrrcQeOjQYH6ioL5OysYRa6xlH+PzPydeAYDj9yWqcDUDSkn2QsnoahYDLUH/qmH+2d6wCGEWS3foq9XtwpMUI515IKRjdusNN5iklV5OAevPwtDU4NwzoY2oZ+A5LrfELpRlSPDanj2igmhRmsG2OWQhyJDMiFKdt8ZFHK61yLV0oTSfNKF8ptGPJy60xrXV+vFd62BgqN1bLQV/HZXgHQzsY4V3/ARcIYb/sfY+GKZbTmRFhicYqlfHZVOZEUIe15qRtk4YFr2cHoDnewYWyhRBHJytWxejYXBTm3pvFodz0XdDmpIF1r3JU8tn3XczZfJUusE1QEA2f5QUXWThEZ7ho+zfjUPCi1XR4Xm2NonTyDmyVVUedOLKdKf0Ju8dSvS6tSl+FkvQQmYZ6SyaQrspGw9B7RFCleQKiaOFCbxoCKAIIFCoLQ1uNFFQMXBM7JPu92nz/50uxS1ncbJqdtIxpgphOISrvTyb7vZDvb7Xj83ubr49egS/igmFSM9PN5948vvux67WMeaADGJba7le1ctduRtASHJ0oSe3N0eJpfXOzt1oezgDTxf51OFsV4C7Ip2fxMBYbYdWiAvMeiyHEp4Mc9LgX8+nphuViizERyGTGHN6rwlppiFlsMPca2DP5QtyCr9Q22Q7VcdQvViNsxwOppGLoVXMH6sghtkWBjTRFesOkWMzeADGIZR8KCGVB5RRMhwcwMgrBgqZBgpsLLeIVISDBTQ4QFc/57sUS2QWKJeFZbtXi5n9k2gmZBEtuPj0lia4+EvzeRrWsokbHWL2Cz1jo+KaM1I/rx8qrxT//4t/4/PLy7s4ffso9t9e+Hly/xr/rn/d15/vL7P5h3+v0fXr78/p+y7f8JACxBI6q6/P90/W/m0/uMDFk0lzWCCACLrFJ7a5ZrhgJLgTFZhRZvVAITKcFLnewSC2mbYVaCkpzix2o6/uB6wK/W5oWX6Dp+njxDH0ydwbwEtYj9TrVQK85bRdMk/DSj7L1T26tJJdjQz+q4Gk7vzROye+ZBHeOzByB/k5l5Na3Mr2J+OyvmSrz6JsOO1DTu3bjrx0tJBGyZm1vNHhPMMZTDh1E1uh6XOoFzxTj0cvLBvKWjQr0YzacTDFb39PW7/b3818Pzw1dH/Xy//+vh6/75U6KWivsrqs2qPrVMGOvVj3Fvioj2XSHXzWV8dCAziro0zbFm/bSVDBbOD/c3bDjSgga2kksA2XKXua+l1rRiUOY5/QJokQMA5B2XQGKVogZM+szCkJKiuG0FRtGNN4OqL//7T0IeZO17BcWZuW0xLq/KEgK0lEM9dRJ57ovJEtXT5qOfz3OTAphM1BWazLq07bpe7fhbahOM9pSMXEHjSswalqT0AS+aAVdPREtfK7bmTsmu701Jmn4xm40fciWrKqBMFCrM83slFo1m4xEY7nH+3tnmEZCaTcXjgfnu0RmlJQcevP88K4bFTA3sGTAyLpNVZWKkOAKBlAFSXpOq5OKuzKY3NyPIqu06y66Xo/GwgkzpLJcWehbDhWRGuX672bGaiI696TJk6K8ZgAISNEN8F0wmYixSMLl2pjjrW9QgXqst+OxjObq9W2wNy0FBjpBzTHtIedPVKk4/Qj8FkDDt3PGhxB6uYYwKGACHj8X8fkumMu0aqAltDJfs+hfvTvpR2uLWJJKh6Of+3n5+dJYfvzu6ODw9Ouyf2Y3E6v1R7hFcuV8hPB6ZXTdTbVG8lGtMOT6CuWqhEflaEFpGw5ZdmPYuwddkbenI/GekAIAPPNloq03sPyCMy7PmuP4mZmkcKW56DsqW6+liMS4n5eC9zs+iXWI03jGhiH2UlayRkTob/1zC8drsiLRB4NY6tDpGmA3hk5qDCwqFM8jxAyP2DON7VItiqOJ7yFdzeSXuBcYoiJg6GAdnZ0XuawRxj1YAG+dLUKHwpvBM9FJMHloIWpiCXSL7hoHeE5pxBpfN8RwVm4R67F1byXUOyfxLO7UAIwyfp4pCN1gxvKHT7bHCQV/8W02fZuWsrSScoGY1IxtAeB403ygquAVkEHYx2zrDkb5tAa9CAKXm8SzMNaxnc6EqZe1ZpNkVlOLzbvdF+aWD4OcdgsrhRr13FwjNz1988lcpSgvRi8thXDfhyITWLr/aO++rvQ3G2LarjgGPJyi3Gw3QjuaAKnkOsHua5/cQZC1/ukv0Gnk/oEeGD+zuzW+XYHV4il9aw7IazEczjL7YPCsP97NXinvGnFQXMr0zNdUthuqY1G0wMG5tEbeICSibcNN7U6gJoKx+V45nvSYqDRR911ylLge2yL1qMedJt2I9NdXqVLatYyX73zyYpqYziv+1rExg58H0Xh3rwy2YBxtMvRHWBBiRngUU5QXbN4Q6OqitLce3sH62dvTEFKqlaz/Vtbeg9lNXA9qpFr2nrmnDGavxoXMutoV/oLWq5ZKVIS/FVgKzHTd3xT3GfTm/LXPg8ClbqF9H01dZEnUjWBIWwhW5mZflX625/wrJwM6iK3jWFItr2yTuje2S835/X2ZOTOfmZqweNKX15wHTieUpolQ+HM01T+6UWKYzVsRc8Bo9WPlJAalquRJtIQWAyKdeigINeXHApVl2Z6BQy9XpqFGQbMjC+Am17HnxATaClnEpmh7uvt3PTkUqZ9cOm2FLsAZiiQEcgaQ9tEnodIxmqMUGEKCdOwu/Yfo/v1gnezp/itq+wc0uq6EPYSimyImCZfO/J030IupCAvRW2yvLB+zqtX2+z8crsAzwcKfX216h48fZUCe7/z2Ri9Cux2OLZPr2x6WT746qXJ+4EJGKm3RFyqqCuVYyEDfU0qJH7+lkMBg/hZSLqog6uu6m6p2S+XafPXuqx7aYP7DGeSRg8YS+Q0XdLQNP562DWUKSeh2JS/3CDJBCX0OEI7jBcjobbWpkWu4l+uglujM/WR8UIW45GRjPoXyAOl260raaG69jma2cNecynwWhR01z9r0Q5vzOWZuPkQgb4T00UDlP9UOVY7WMSiq8XQpzwXnZKL2JdNYMLc3xKB7CtT6ZXMLQ0kurZlc7CIhq0Nbb8B4bhnfI4weRbCy6W4sPxWhcqEOx1aaMQRts6fi2BkZhPn3wdnb7H3cL//j3j3//+Pf/zr//C574MeQA+AIA'
overlay_bytes = base64.b64decode(OVERLAY_ARCHIVE_B64)
with tarfile.open(fileobj=io.BytesIO(overlay_bytes), mode="r:gz") as archive:
    members = archive.getmembers()
    for member in members:
        destination = (UAD_DIR / member.name).resolve()
        if not str(destination).startswith(str(UAD_DIR.resolve()) + os.sep):
            raise RuntimeError(f"Unsafe overlay member: {member.name}")
    archive.extractall(UAD_DIR)

OVERLAY_HASHES = {'config/defaults.py': '839faddc24b14d21f073c0a2b588406cd24ac50651304c7d7dcdbe8d7416b89e', 'configs/PVUAD.yml': '2ce61c2c87eced2377c6b290fa5cfc14dc17511eb85dbeee4c18e6054c727440', 'datasets/agreid_v2.py': 'f2dc8f1bb9f85ae5ea7b6d2602c38ddf22bec14b935853773e337b588e27c051', 'datasets/bases.py': '7712bac25aee214f38a913cf3aad1ce4ef33b9a713d7e177ad67ec17932c016d', 'datasets/make_dataloader.py': 'edd99ebc3248edac65a689f79b390cecec14a58e947a1c19fdc44506c159df09', 'datasets/pvuad_sampler.py': '93d21613c90372d10fca9d4b1a0ffbb34ec1a6f4849c9f6eb10671d736261d75', 'datasets/pvuad_transforms.py': '056fc9f25aba6361d4612bcc313f0cc2d175e2b695757f6912e09fc7b5fc61c0', 'datasets/sampler_ddp.py': 'e4c455f7c7afbfac09a503a924c7b09586dbdb8eda6c88735ad1a3e37599bf7c', 'datasets/whu_mars.py': '11d3a0c501912a9887d78601df01afb6495d2f859835a6b69d2079135dba24b3', 'model/backbones/vit_pytorch.py': '723305c1a05e204b744ddb0ff7873b5e02840329e01787200173c9064ed3ad05', 'model/make_model.py': 'bcdfef10d3a75cbb25da27eb688bb6834e97baec8b4221bbef15cf9bf472e3b5', 'processor/processor.py': 'e9a5dc613a374fde37874a4bf838789c7b359ff44c2e0d051db4e7e8fb987d7c', 'train.py': '8da1552749d67272ca6d8078ac3dd8c1df4183924d7795a6e7b0355eecf18ff5'}
for relative, expected_hash in OVERLAY_HASHES.items():
    actual_hash = hashlib.sha256((UAD_DIR / relative).read_bytes()).hexdigest()
    if actual_hash != expected_hash:
        raise RuntimeError(f"Overlay hash mismatch: {relative}")
patch_manifest = {
    "base_repo": OFFICIAL_REPO_URL,
    "base_commit": PINNED_UAD_COMMIT,
    "overlay_variant": "agreidv2_a2g_transreid_init_trainable_768_global_b1_v6_ddpevalfix",
    "overlay_sha256": OVERLAY_HASHES,
}
(UAD_DIR / "PVUAD_patch_manifest.json").write_text(
    json.dumps(patch_manifest, indent=2), encoding="utf-8"
)
subprocess.run([sys.executable, "-m", "compileall", "-q", str(UAD_DIR)], check=True)
print("Pinned and patched source:", UAD_DIR)



TRANSREID_MODEL_NAME = "vit_transreid_msmt.pth"
TRANSREID_GDRIVE_ID = "1x6Na97ycxS0t2Dn_0iRKWe1U5ccIqASK"
TRANSREID_SOURCE_STRIDE = [12, 12]

def find_named_file_without_images(base, filename):
    base = Path(base)
    if not base.exists():
        return []
    found = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if filename in files:
            found.append(root_path / filename)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
    return sorted(found, key=lambda item: str(item))


def torch_load_cpu(path):
    try:
        return torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(path, map_location="cpu")


def unwrap_checkpoint_state(payload):
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("Checkpoint does not contain a state_dict")
    return {str(key).replace("module.", ""): value for key, value in payload.items()}


TRANSREID_CACHE = Path("/kaggle/working") / TRANSREID_MODEL_NAME
checkpoint_override = TRANSREID_CHECKPOINT_OVERRIDE or PRETRAIN_PATH_OVERRIDE
if checkpoint_override:
    source_checkpoint = Path(checkpoint_override)
    if not source_checkpoint.is_file():
        raise FileNotFoundError(source_checkpoint)
    if source_checkpoint.resolve() != TRANSREID_CACHE.resolve():
        shutil.copy2(source_checkpoint, TRANSREID_CACHE)
elif TRANSREID_CACHE.is_file():
    pass
else:
    attached = find_named_file_without_images("/kaggle/input", TRANSREID_MODEL_NAME)
    if attached:
        print("Caching attached pretrained TransReID checkpoint...")
        shutil.copy2(attached[0], TRANSREID_CACHE)
    else:
        print("Downloading official MSMT17 TransReID* ViT checkpoint with gdown...")
        try:
            import gdown
            result = gdown.download(
                id=TRANSREID_GDRIVE_ID,
                output=str(TRANSREID_CACHE),
                quiet=False,
            )
            if not result:
                raise RuntimeError("gdown returned no output path")
        except Exception as error:
            raise RuntimeError(
                "Cannot obtain vit_transreid_msmt.pth. Enable Kaggle Internet, "
                "or attach the official checkpoint as a Kaggle Dataset and set "
                "TRANSREID_CHECKPOINT_OVERRIDE."
            ) from error

if not TRANSREID_CACHE.is_file():
    raise FileNotFoundError(TRANSREID_CACHE)
if TRANSREID_CACHE.stat().st_size < 300_000_000:
    raise RuntimeError(
        "TransReID checkpoint is unexpectedly small; this is likely an HTML/"
        "partial download: {} bytes".format(TRANSREID_CACHE.stat().st_size)
    )

payload = torch_load_cpu(TRANSREID_CACHE)
tr_state = unwrap_checkpoint_state(payload)
required_transreid_keys = {
    "base.cls_token",
    "base.pos_embed",
    "base.patch_embed.proj.weight",
    "base.blocks.0.attn.qkv.weight",
    "base.blocks.11.attn.qkv.weight",
    "base.norm.weight",
    # These two are validated only to make sure this is the official full
    # TransReID checkpoint; they are intentionally NOT transplanted into UAD.
    "base.sie_embed",
    "b1.0.attn.qkv.weight",
    "b2.0.attn.qkv.weight",
}
missing = sorted(required_transreid_keys - set(tr_state))
if missing:
    raise RuntimeError(
        "Attached/downloaded file is not the expected full MSMT17 TransReID "
        f"checkpoint; missing keys: {missing}"
    )
if tr_state["base.cls_token"].shape[-1] != 768:
    raise RuntimeError("Expected ViT-B hidden dimension 768.")
if tuple(tr_state["base.sie_embed"].shape) != (15, 1, 768):
    raise RuntimeError(
        "Unexpected MSMT17 source SIE shape: "
        + str(tuple(tr_state["base.sie_embed"].shape))
    )
print(
    "Validated pretrained TransReID source:",
    {
        "path": str(TRANSREID_CACHE),
        "size_MiB": round(TRANSREID_CACHE.stat().st_size / 2**20, 1),
        "source_pos_embed": tuple(tr_state["base.pos_embed"].shape),
        "source_SIE": tuple(tr_state["base.sie_embed"].shape),
        "source_has_JPM": True,
        "target_embedding_dim": 768,
        "target_stride": TRANSREID_TARGET_STRIDE,
        "target_SIE": False,
        "target_JPM": False,
        "backbone_will_be_trainable": True,
    },
)
del payload, tr_state

TRANSREID_PATH = TRANSREID_CACHE
PRETRAIN_PATH = TRANSREID_PATH
print("Persistent TransReID initialization checkpoint:", PRETRAIN_PATH)


if RUN_TRANSREID_INIT_SMOKE_TEST:
    print("Running AG-ReID.v2 trainable 768-D TransReID-initialized UAD smoke test...")
    TRANSREID_INIT_AUDIT_PATH = Path(
        "/kaggle/working/transreid_trainable_init_audit.json"
    )
    smoke_script = r"""
import json
import sys
from pathlib import Path
import torch

uad_dir = Path(sys.argv[1])
checkpoint = Path(sys.argv[2])
audit_path = Path(sys.argv[3])
sys.path.insert(0, str(uad_dir))

from config import cfg
from model import make_model

def load_state(path):
    try:
        payload = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(path, map_location="cpu")
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    return {str(k).replace("module.", ""): v for k, v in payload.items()}

cfg.merge_from_file(str(uad_dir / "configs/PVUAD.yml"))
cfg.MODEL.PRETRAIN_CHOICE = "transreid"
cfg.MODEL.PRETRAIN_PATH = str(checkpoint)
cfg.MODEL.STRIDE_SIZE = [16, 16]
cfg.MODEL.SIE_CAMERA = False
cfg.MODEL.SIE_VIEW = False
cfg.DATASETS.NAMES = "AG-ReID.v2"
cfg.DATASETS.MODALITIES = ["RGB"]
cfg.PVUAD.GROUND_MAX_CAMID = 1
cfg.PVUAD.VFPROCA = True
cfg.PVUAD.LOCAL_CONSISTENCY = False
cfg.PVUAD.TIR_DISTILLATION = False

model = make_model(cfg, num_class=807, camera_num=3, view_num=0).cuda().train()
if model.transreid_init_audit is None:
    raise RuntimeError("Missing TransReID initialization audit")
if model.in_planes != 768:
    raise RuntimeError("UAD backbone must remain 768-D")
if hasattr(model.base, "sie_embed"):
    raise RuntimeError("Source-camera SIE must not be copied into target UAD")
if not all(parameter.requires_grad for parameter in model.base.parameters()):
    raise RuntimeError("TransReID-initialized backbone is unexpectedly frozen")

source = load_state(checkpoint)
source_qkv = source["base.blocks.0.attn.qkv.weight"]
target_qkv = model.base.blocks[0].attn.qkv.weight.detach().cpu()
init_qkv_max_abs = float((source_qkv - target_qkv).abs().max())
source_global_final_qkv = source["b1.0.attn.qkv.weight"]
target_final_qkv = model.base.blocks[11].attn.qkv.weight.detach().cpu()
global_final_qkv_max_abs = float(
    (source_global_final_qkv - target_final_qkv).abs().max()
)
if init_qkv_max_abs > 1e-7 or global_final_qkv_max_abs > 1e-7:
    raise RuntimeError(
        "TransReID weights were not transplanted exactly: "
        f"shared_qkv={init_qkv_max_abs}, global_final_qkv={global_final_qkv_max_abs}"
    )

SMOKE_BATCH = 2
images = [
    torch.randn(SMOKE_BATCH, 3, 256, 128, device="cuda"),
]
output = model(x=images, mode=0)
cls_score, global_feat = output[0], output[1]
if tuple(global_feat.shape) != (SMOKE_BATCH, 768):
    raise RuntimeError(f"Unexpected UAD feature shape: {tuple(global_feat.shape)}")
loss = cls_score.float().square().mean() + 0.01 * global_feat[:, :16].float().square().mean()
loss.backward()

qkv_grad = model.base.blocks[0].attn.qkv.weight.grad
patch_grad = model.base.patch_embed.proj.weight.grad
if qkv_grad is None or patch_grad is None:
    raise RuntimeError("No gradient reached the TransReID-initialized backbone")
qkv_grad_norm = float(qkv_grad.float().norm().detach().cpu())
patch_grad_norm = float(patch_grad.float().norm().detach().cpu())
if not (qkv_grad_norm > 0 and patch_grad_norm > 0):
    raise RuntimeError(
        f"Backbone gradients must be nonzero; qkv={qkv_grad_norm}, "
        f"patch={patch_grad_norm}"
    )

audit = dict(model.transreid_init_audit)
audit.update({
    "smoke_test": "OK",
    "feature_shape": list(global_feat.shape),
    "smoke_batch_size": SMOKE_BATCH,
    "batchnorm_train_mode_checked": True,
    "init_qkv_max_abs": init_qkv_max_abs,
    "global_final_qkv_max_abs": global_final_qkv_max_abs,
    "qkv_grad_norm": qkv_grad_norm,
    "patch_grad_norm": patch_grad_norm,
    "backbone_all_trainable": True,
    "source_sie_used": False,
    "source_jpm_local_branches_used": False,
    "source_jpm_global_final_branch_used": True,
    "target_stride": [16, 16],
})
audit_path.write_text(json.dumps(audit, indent=2), encoding="utf-8")
print("TRANSREID_TRAINABLE_INIT_SMOKE_OK", audit)
"""
    smoke_env = os.environ.copy()
    smoke_env["CUDA_VISIBLE_DEVICES"] = "0"
    smoke_env["PYTHONPATH"] = str(UAD_DIR) + os.pathsep + smoke_env.get(
        "PYTHONPATH", ""
    )
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            smoke_script,
            str(UAD_DIR),
            str(TRANSREID_PATH),
            str(TRANSREID_INIT_AUDIT_PATH),
        ],
        cwd=UAD_DIR,
        env=smoke_env,
        text=True,
        capture_output=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(
            "Trainable TransReID initialization smoke test failed. "
            "Do not start E2 until the initialization path is fixed."
        )

Attached UAD source candidates:

fatal: detected dubious ownership in repository at '/kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/WHU_MARS_official_pinned'
To add an exception for this directory, call:

	git config --global --add safe.directory /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/WHU_MARS_official_pinned

,path,base_commit,selected
0,/kaggle/input/notebooks/thienbao1604/pvuad-agr...,3e2a07314119402586c76096e87d40420894ad30,True

Reusing attached UAD source: /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/WHU_MARS_official_pinned
Pinned and patched source: /kaggle/working/WHU_MARS_official_pinned/CVPR26_UAD

/tmp/ipykernel_23/3906047045.py:116: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  archive.extractall(UAD_DIR)

Caching attached pretrained TransReID checkpoint...
Validated pretrained TransReID source: {'path': '/kaggle/working/vit_transreid_msmt.pth', 'size_MiB': 399.8, 'source_pos_embed': (1, 211, 768), 'source_SIE': (15, 1, 768), 'source_has_JPM': True, 'target_embedding_dim': 768, 'target_stride': [16, 16], 'target_SIE': False, 'target_JPM': False, 'backbone_will_be_trainable': True}
Persistent TransReID initialization checkpoint: /kaggle/working/vit_transreid_msmt.pth
Running AG-ReID.v2 trainable 768-D TransReID-initialized UAD smoke test...
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
TransReID -> trainable UAD backbone initialization: {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed']}
Initialized UAD 768-D ViT backbone from pretrained TransReID; the backbone remains TRAINABLE on the target dataset.
===========building transformer===========
TRANSREID_TRAINABLE_INIT_SMOKE_OK {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed'], 'smoke_test': 'OK', 'feature_shape': [2, 768], 'smoke_batch_size': 2, 'batchnorm_train_mode_checked': True, 'init_qkv_max_abs': 0.0, 'global_final_qkv_max_abs': 0.0, 'qkv_grad_norm': 0.0065332744270563126, 'patch_grad_norm': 0.032782863825559616, 'backbone_all_trainable': True, 'source_sie_used': False, 'source_jpm_local_branches_used': False, 'source_jpm_global_final_branch_used': True, 'target_stride': [16, 16]}

## 4. View audit + multi-session state machine

Notebook audit số identity có cả ground/aerial trong train set rồi tự chọn:
**E3 resume → E2 completed → E2 resume → E2 fresh**.

Pipeline tag mới hoàn toàn tách khỏi output WHU-MARS và reranking cũ, nên sẽ
không resume nhầm checkpoint dataset khác.

In [5]:
FILENAME_RE = AG_PID_RE

PIPELINE_ROOT = Path("/kaggle/working/pvuad_runs") / PIPELINE_TAG
E2_RUN_DIR = PIPELINE_ROOT / "e2_final"
E3_RUN_DIR = PIPELINE_ROOT / "e3_tdh"
PIPELINE_ROOT.mkdir(parents=True, exist_ok=True)
E2_RUN_DIR.mkdir(parents=True, exist_ok=True)
E3_RUN_DIR.mkdir(parents=True, exist_ok=True)
PIPELINE_STATE_PATH = PIPELINE_ROOT / "pipeline_state.json"

INIT_AUDIT_SOURCE = Path("/kaggle/working/transreid_trainable_init_audit.json")
INIT_AUDIT_DEST = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if INIT_AUDIT_SOURCE.is_file() and not INIT_AUDIT_DEST.is_file():
    shutil.copy2(INIT_AUDIT_SOURCE, INIT_AUDIT_DEST)


def read_json(path):
    path = Path(path)
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        print("Ignoring unreadable JSON:", path, error)
        return {}


def write_pipeline_state(status, active_stage, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "status": status,
        "active_stage": active_stage,
        "updated_at_unix": _time.time(),
        "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
        "session_deadline_unix": SESSION_DEADLINE_UNIX,
        "remaining_minutes": max(
            0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0
        ),
        **extra,
    }
    temporary = PIPELINE_STATE_PATH.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    os.replace(temporary, PIPELINE_STATE_PATH)
    return payload


def remaining_minutes():
    return max(0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0)


def copy_if_present(source_dir, destination_dir, filenames):
    if source_dir is None:
        return
    source_dir = Path(source_dir)
    destination_dir = Path(destination_dir)
    destination_dir.mkdir(parents=True, exist_ok=True)
    for filename in filenames:
        source_path = source_dir / filename
        destination_path = destination_dir / filename
        if source_path.is_file() and source_path.resolve() != destination_path.resolve():
            if not destination_path.exists():
                print("Preserving:", filename)
                shutil.copy2(source_path, destination_path)


def status_progress(status):
    return status.get("progress") or {}


def candidate_sort_key(candidate):
    status = candidate["status"]
    progress = status_progress(status)
    path_text = str(candidate["root"]).lower()
    return (
        int(PIPELINE_TAG.lower() in path_text),
        int(status.get("status") == "completed"),
        int(progress.get("epoch") or 0),
        int(bool(progress.get("epoch_complete", False))),
        int(progress.get("next_iteration") or 0),
        int(status.get("global_step") or 0),
        float(status.get("saved_at_unix") or candidate["checkpoint"].stat().st_mtime),
    )


def scan_stage_candidates(base, experiment):
    base = Path(base)
    if not base.exists():
        return []
    candidates = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if "pvuad_last_checkpoint.pth" not in files:
            continue
        checkpoint = root_path / "pvuad_last_checkpoint.pth"
        status = read_json(root_path / "session_status.json")
        summary = read_json(root_path / "training_summary.json")
        manifest = read_json(root_path / "run_manifest.json")
        declared = status.get("experiment", summary.get("experiment"))
        lowered = str(root_path).lower()
        legacy_match = (
            experiment == "E2" and "final_e2" in lowered
        ) or (
            experiment == "E3-TDH" and "e3_tdh" in lowered
        )
        if declared != experiment and not legacy_match:
            continue
        if status.get("stage", summary.get("stage")) not in (None, "final"):
            continue
        # Reject a manifest that clearly belongs to a different batch/LR
        # recipe. Missing legacy fields are tolerated, but contradictory
        # fields are not.
        recipe = manifest.get("recipe") or manifest.get("effective_training") or {}
        expected = (
            {"global_batch": E2_GLOBAL_BATCH, "epochs": E2_EPOCHS}
            if experiment == "E2"
            else {"global_batch": E3_GLOBAL_BATCH, "epochs": E3_EPOCHS}
        )
        incompatible = any(
            key in recipe and int(recipe[key]) != int(value)
            for key, value in expected.items()
        )
        lr_value = recipe.get("base_lr", recipe.get("backbone_lr"))
        expected_lr = E2_BASE_LR if experiment == "E2" else E3_BASE_LR
        if lr_value is not None and abs(float(lr_value) - expected_lr) > 1e-12:
            incompatible = True
        if incompatible:
            print("Skipping incompatible stage candidate:", root_path)
            continue
        candidates.append({
            "root": root_path,
            "checkpoint": checkpoint,
            "model": root_path / "pvuad_best_model.pth",
            "last_model": root_path / "pvuad_last_model.pth",
            "status": status,
            "summary": summary,
            "manifest": manifest,
        })
        dirs[:] = []
    return sorted(candidates, key=candidate_sort_key, reverse=True)


def candidate_table(candidates, label):
    if not candidates:
        return
    print(label)
    display(pd.DataFrame([{
        "root": str(item["root"]),
        "status": item["status"].get("status", "legacy_checkpoint"),
        "epoch": status_progress(item["status"]).get("epoch"),
        "next_iteration": status_progress(item["status"]).get("next_iteration"),
        "global_step": item["status"].get("global_step"),
        "best_mAP": item["status"].get("best_mAP_percent"),
        "selected": index == 0,
    } for index, item in enumerate(candidates)]))



# View-coverage audit is invariant across sessions. Reuse it when possible.
PAIRING_AUDIT_PATH = PIPELINE_ROOT / "pairing_audit.csv"
pairing_frame = None

if RUN_METADATA_PAIRING_CHECK:
    by_pid = defaultdict(lambda: {"ground": 0, "aerial": 0})
    for row in train_frame.itertuples():
        if int(row.camera_original) == 0:
            by_pid[int(row.pid)]["aerial"] += 1
        else:
            by_pid[int(row.pid)]["ground"] += 1

    pairing_rows = []
    for pid in sorted(by_pid):
        ground = int(by_pid[pid]["ground"])
        aerial = int(by_pid[pid]["aerial"])
        pairing_rows.append({
            "pid": int(pid),
            "paired_frames": int(ground + aerial),
            "ground": ground,
            "aerial": aerial,
            "view_coverage": (
                "Ground+Aerial" if ground > 0 and aerial > 0
                else "Ground-only" if ground > 0
                else "Aerial-only" if aerial > 0
                else "No sample"
            ),
        })

    pairing_frame = pd.DataFrame(pairing_rows)
    if len(pairing_frame) != AG_TRAIN_ID_COUNT:
        raise RuntimeError(
            f"Expected {AG_TRAIN_ID_COUNT} train identities in view audit, "
            f"got {len(pairing_frame)}"
        )
    pairing_frame.to_csv(PAIRING_AUDIT_PATH, index=False)
    print("AG-ReID.v2 train view coverage:")
    display(
        pairing_frame["view_coverage"]
        .value_counts(dropna=False)
        .rename_axis("view_coverage")
        .reset_index(name="identities")
    )


if E3_RESUME_PATH_OVERRIDE:
    E3_CANDIDATES = [{
        "root": Path(E3_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E3_RESUME_PATH_OVERRIDE),
        "model": Path(E3_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "last_model": Path(E3_RESUME_PATH_OVERRIDE).parent / "pvuad_last_model.pth",
        "status": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E3_CANDIDATES = scan_stage_candidates(E3_RUN_DIR, "E3-TDH")
    if AUTO_RESUME:
        external_e3 = scan_stage_candidates("/kaggle/input", "E3-TDH")
        external_e3 = [
            item for item in external_e3
            if PIPELINE_TAG.lower() in str(item["root"]).lower()
        ]
        E3_CANDIDATES += external_e3
        unique = {str(item["checkpoint"]): item for item in E3_CANDIDATES}
        E3_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_RESUME_PATH_OVERRIDE:
    E2_CANDIDATES = [{
        "root": Path(E2_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E2_RESUME_PATH_OVERRIDE),
        "model": Path(E2_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "last_model": Path(E2_RESUME_PATH_OVERRIDE).parent / "pvuad_last_model.pth",
        "status": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E2_CANDIDATES = scan_stage_candidates(E2_RUN_DIR, "E2")
    if AUTO_RESUME:
        external_e2 = scan_stage_candidates("/kaggle/input", "E2")
        if not ALLOW_LEGACY_E2_BOOTSTRAP:
            external_e2 = [
                item for item in external_e2
                if PIPELINE_TAG.lower() in str(item["root"]).lower()
            ]
        E2_CANDIDATES += external_e2
        unique = {str(item["checkpoint"]): item for item in E2_CANDIDATES}
        E2_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_COMPLETED_DIR_OVERRIDE:
    override_root = Path(E2_COMPLETED_DIR_OVERRIDE)
    E2_CANDIDATES.insert(0, {
        "root": override_root,
        "checkpoint": override_root / "pvuad_last_checkpoint.pth",
        "model": override_root / "pvuad_best_model.pth",
        "last_model": override_root / "pvuad_last_model.pth",
        "status": read_json(override_root / "session_status.json"),
        "summary": read_json(override_root / "training_summary.json"),
        "manifest": read_json(override_root / "run_manifest.json"),
    })

candidate_table(E3_CANDIDATES, "E3 resume candidates (highest priority):")
candidate_table(E2_CANDIDATES, "E2 candidates:")

SELECTED_E3 = E3_CANDIDATES[0] if E3_CANDIDATES else None
SELECTED_E2 = E2_CANDIDATES[0] if E2_CANDIDATES else None

# Preserve compact E2 evidence even when a completed legacy E2 is used only as
# the warm-start for E3. Large model/checkpoint files stay at their selected
# input path until E3 has created its self-contained teacher/resume artifacts.
if SELECTED_E2 is not None:
    copy_if_present(
        SELECTED_E2["root"], E2_RUN_DIR,
        [
            "metrics_history.csv", "session_status.json", "training_summary.json",
            "pvuad_last_model.pth", "pvuad_best_model.pth",
            "pairing_audit.csv", "ablation_summary.csv", "effective_command.txt",
        ],
    )

if SELECTED_E3 is not None:
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None and SELECTED_E2["status"].get("status") == "completed":
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None:
    ACTIVE_STAGE = "E2"
else:
    ACTIVE_STAGE = "E2"

print("Selected pipeline stage:", ACTIVE_STAGE)
write_pipeline_state(
    "ready", ACTIVE_STAGE,
    selected_e2=str(SELECTED_E2["root"]) if SELECTED_E2 else None,
    selected_e3=str(SELECTED_E3["root"]) if SELECTED_E3 else None,
)

(PIPELINE_ROOT / "RESUME_NEXT_SESSION.txt").write_text(
    "PV-UAD AG-ReID.v2 A2G TransReID-init E2 -> E3 multi-session pipeline\n\n"
    "1. A partial session ends normally with e2_paused or e3_paused.\n"
    "2. Start every run with Save Version -> Save & Run All; Kaggle then commits "
    "the output automatically after this notebook exits cleanly.\n"
    "3. In a new session, add the immediately preceding version output as Input.\n"
    "4. Use this exact notebook, keep Settings unchanged, and Run All.\n"
    "5. The state machine resumes E3 first, otherwise completed/partial E2.\n\n"
    f"Pipeline folder: pvuad_runs/{PIPELINE_TAG}\n",
    encoding="utf-8",
)
print("Pipeline output:", PIPELINE_ROOT)

AG-ReID.v2 train view coverage:

   view_coverage  identities
0  Ground+Aerial         807

E2 candidates:

,root,status,epoch,next_iteration,global_step,best_mAP,selected
0,/kaggle/input/notebooks/thienbao1604/pvuad-agr...,completed,60,0,186202,72.677799,True

Preserving: metrics_history.csv
Preserving: session_status.json
Preserving: training_summary.json
Preserving: pvuad_last_model.pth
Preserving: pvuad_best_model.pth
Preserving: effective_command.txt
Selected pipeline stage: E3
Pipeline output: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix

## 5. Train E2=60 → E3=25 → evaluate Aerial→Ground

- **E2 fresh:** TransReID MSMT17 → UAD ViT 768-D → AG-ReID.v2.
- **E2→E3:** dùng **last E2 epoch 60 model + last E2 prototype checkpoint**,
  bảo đảm model/prototype cùng epoch.
- **E3:** TIR loss tắt; giữ feature preservation và scenario-hard GPD phù hợp
  với hai view ground/aerial.
- **Final:** flip-TTA cho cả best E3 và fixed epoch-25 E3 khi cần.

In [6]:
environment = os.environ.copy()
environment.update({
    "CUDA_VISIBLE_DEVICES": ",".join(map(str, range(NUM_GPUS))),
    "PYTHONPATH": str(UAD_DIR) + os.pathsep + environment.get("PYTHONPATH", ""),
    "PYTHONUNBUFFERED": "1",
    "OMP_NUM_THREADS": "2",
    "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
    "TORCH_NCCL_ASYNC_ERROR_HANDLING": "1",
})


def stage_status(run_dir):
    return read_json(Path(run_dir) / "session_status.json")


def display_stage_status(name, status):
    progress = status_progress(status)
    display(pd.DataFrame([{
        "stage": name,
        "status": status.get("status"),
        "reason": status.get("reason"),
        "epoch": progress.get("epoch"),
        "next_iteration": progress.get("next_iteration"),
        "epoch_complete": progress.get("epoch_complete"),
        "global_step": status.get("global_step"),
        "best_mAP": status.get("best_mAP_percent"),
        "remaining_minutes": round(remaining_minutes(), 1),
    }]))


def run_command_checked(command, run_dir, stage_name):
    command_text = shlex.join(command)
    (Path(run_dir) / "effective_command.txt").write_text(
        command_text + "\n", encoding="utf-8"
    )
    print("\nLaunching", stage_name)
    print(command_text)
    if not RUN_TRAINING:
        print("RUN_TRAINING=False — command prepared but not launched.")
        return {}
    result = subprocess.run(command, cwd=UAD_DIR, env=environment, check=False)
    if result.returncode != 0:
        # A DDP/NCCL process can abort after a periodic checkpoint has already
        # been written. Treat that as a resumable session rather than throwing
        # away hours of work. A missing/invalid checkpoint still fails hard.
        checkpoint = Path(run_dir) / "pvuad_last_checkpoint.pth"
        status_path = Path(run_dir) / "session_status.json"
        recovered_status = stage_status(run_dir) if status_path.is_file() else {}
        if (
            checkpoint.is_file()
            and recovered_status.get("status")
            in {"running_checkpoint", "paused_time_limit"}
        ):
            print(
                f"{stage_name} subprocess exited with code {result.returncode}, "
                "but a valid resumable checkpoint exists. "
                "Ending this notebook cleanly so the next Kaggle session can resume."
            )
            write_pipeline_state(
                "recoverable_stage_crash", stage_name,
                returncode=result.returncode,
                run_dir=str(run_dir),
                checkpoint=str(checkpoint),
            )
            display_stage_status(stage_name, recovered_status)
            return recovered_status
        write_pipeline_state(
            "failed", stage_name,
            returncode=result.returncode,
            run_dir=str(run_dir),
        )
        raise subprocess.CalledProcessError(result.returncode, command)
    required = [
        Path(run_dir) / "pvuad_last_checkpoint.pth",
        Path(run_dir) / "session_status.json",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise RuntimeError(f"{stage_name} ended without required outputs: {missing}")
    status = stage_status(run_dir)
    if status.get("status") not in {
        "paused_time_limit", "completed", "running_checkpoint"
    }:
        raise RuntimeError(f"Unexpected {stage_name} status: {status}")
    display_stage_status(stage_name, status)
    return status


def make_stage_manifest(run_dir, stage_name, recipe, resume_path=None, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "stage_name": stage_name,
        "recipe": recipe,
        "dataset_variant": "AG-ReID.v2",
        "dataset_protocol": "aerial_to_ground",
        "dataset_root": str(DATA_ROOT),
        "dataset_counts": DATASET_AUDIT,
        "source_commit": PINNED_UAD_COMMIT,
        "overlay_sha256": OVERLAY_HASHES,
        "resume_path": str(resume_path) if resume_path else None,
        "python": sys.version,
        "torch": torch.__version__,
        "cuda": torch.version.cuda,
        "gpus": gpu_rows,
        "seed": RANDOM_SEED,
        "session_guard": {
            "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
            "session_deadline_unix": SESSION_DEADLINE_UNIX,
            "hard_stop_hours": SESSION_HARD_STOP_HOURS,
            "stop_reserve_minutes": SESSION_STOP_RESERVE_MINUTES,
            "checkpoint_every_minutes": CHECKPOINT_EVERY_MINUTES,
            "time_check_every_steps": TIME_CHECK_EVERY_STEPS,
            "min_eval_remaining_minutes": MIN_EVAL_REMAINING_MINUTES,
        },
        **extra,
    }
    manifest_path = Path(run_dir) / "run_manifest.json"
    manifest_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    shutil.copy2(
        UAD_DIR / "PVUAD_patch_manifest.json",
        Path(run_dir) / "PVUAD_patch_manifest.json",
    )
    return manifest_path


def e2_command(resume_path, strict_resume=True):
    # Fresh E2 receives pretrained TransReID backbone initialization exactly
    # once. Resume sessions reconstruct the model from the saved UAD checkpoint,
    # so they must NOT apply the source initialization again.
    pretrain_choice = "none" if resume_path else "transreid"
    recipe = {
        "experiment": "E2", "stage": "final", "epochs": E2_EPOCHS,
        "global_batch": E2_GLOBAL_BATCH, "base_lr": E2_BASE_LR,
        "view_balanced_sampler": True, "vfproca": True,
        "local_consistency": False, "hard_gpd": False,
        "dataset": "AG-ReID.v2", "protocol": "aerial_to_ground",
        "initialization": "MSMT17_TransReID_trainable_backbone",
        "pretrain_choice_this_session": pretrain_choice,
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
        "source_sie_used": False,
        "source_jpm_local_branches_used": False,
        "source_jpm_global_final_branch_used": True,
    }
    manifest_path = make_stage_manifest(
        E2_RUN_DIR, "E2", recipe, resume_path=resume_path
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", pretrain_choice,
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "AG-ReID.v2",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E2_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E2_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E2_BASE_LR),
        "SOLVER.EVAL_PERIOD", "10",
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E2_RUN_DIR),
        "PVUAD.EXPERIMENT", "E2",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.SYNC_PAIRED_AUG", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "False",
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "False",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", str(bool(strict_resume)),
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


E2_STATUS = SELECTED_E2["status"] if SELECTED_E2 else {}
E2_RESUME_PATH = None
E2_MODEL_PATH = None
E2_CHECKPOINT_PATH = None
E2_STRICT_RESUME = True
E2_COMPLETED_THIS_SESSION = False

if ACTIVE_STAGE == "E2":
    if SELECTED_E2 is not None:
        E2_RESUME_PATH = SELECTED_E2["checkpoint"]
        selected_hashes = (
            SELECTED_E2.get("manifest", {}).get("overlay_sha256") or {}
        )
        selected_processor_hash = selected_hashes.get("processor/processor.py")
        current_processor_hash = OVERLAY_HASHES.get("processor/processor.py")
        # E2 v2.3 checkpoints predate E3's gated fields in the resume
        # signature. Their known E2 structure is compatible; disable only the
        # signature-key comparison while retaining strict state_dict/optimizer
        # structural loading. New combined checkpoints remain fully strict.
        if (
            selected_processor_hash
            and selected_processor_hash != current_processor_hash
        ):
            E2_STRICT_RESUME = False
            print(
                "Known legacy E2 overlay detected; structural resume checks "
                "remain enabled, signature-only strictness is relaxed."
            )
        copy_if_present(
            SELECTED_E2["root"], E2_RUN_DIR,
            [
                "metrics_history.csv", "pvuad_best_model.pth", "pvuad_last_model.pth",
                "pairing_audit.csv", "ablation_summary.csv",
                "training_summary.json",
            ],
        )
    else:
        print("No checkpoint found: starting E2 from pretrained TransReID ViT weights; backbone is TRAINABLE.")

    write_pipeline_state(
        "e2_running", "E2",
        resume_path=str(E2_RESUME_PATH) if E2_RESUME_PATH else None,
    )
    E2_STATUS = run_command_checked(
        e2_command(E2_RESUME_PATH, E2_STRICT_RESUME), E2_RUN_DIR, "E2"
    )
    if not RUN_TRAINING:
        write_pipeline_state("dry_run", "E2")
    elif E2_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e2_paused", "E2", e2_status=E2_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E2 PAUSED SAFELY. Save Version and continue in a new session.")
    elif E2_STATUS.get("status") == "completed":
        E2_MODEL_PATH = E2_RUN_DIR / "pvuad_last_model.pth"
        E2_CHECKPOINT_PATH = E2_RUN_DIR / "pvuad_last_checkpoint.pth"
        required = [E2_MODEL_PATH, E2_CHECKPOINT_PATH, E2_RUN_DIR / "metrics_history.csv"]
        missing = [str(path) for path in required if not path.is_file()]
        if missing:
            raise RuntimeError(f"Completed E2 is missing: {missing}")
        E2_COMPLETED_THIS_SESSION = True
        ACTIVE_STAGE = "E3"
else:
    if SELECTED_E2 is not None:
        E2_MODEL_PATH = (
            SELECTED_E2.get("last_model")
            if SELECTED_E2.get("last_model") is not None
            and Path(SELECTED_E2["last_model"]).is_file()
            else SELECTED_E2["model"]
        )
        E2_CHECKPOINT_PATH = SELECTED_E2["checkpoint"]


def create_teacher_cache(source_model, destination):
    source_model = Path(source_model)
    destination = Path(destination)
    if destination.is_file():
        return destination
    if not source_model.is_file():
        raise FileNotFoundError(source_model)
    try:
        payload = torch.load(source_model, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(source_model, map_location="cpu")
    if isinstance(payload, dict) and "model" in payload:
        payload = payload["model"]
    elif isinstance(payload, dict) and "state_dict" in payload:
        payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("E2 model file does not contain a state dictionary")
    teacher_state = {}
    for key, value in payload.items():
        clean = str(key).replace("module.", "")
        teacher_state[clean] = value.half() if torch.is_floating_point(value) else value
    temporary = destination.with_suffix(".pth.tmp")
    torch.save(teacher_state, temporary)
    os.replace(temporary, destination)
    del payload, teacher_state
    return destination


E3_STATUS = SELECTED_E3["status"] if SELECTED_E3 else {}
E3_RESUME_PATH = SELECTED_E3["checkpoint"] if SELECTED_E3 else None
TEACHER_CACHE = E3_RUN_DIR / "e2_teacher_model_fp16.pth"

if SELECTED_E3 is not None:
    copy_if_present(
        SELECTED_E3["root"], E3_RUN_DIR,
        [
            "metrics_history.csv", "pvuad_best_model.pth", "pvuad_last_model.pth",
            "e2_teacher_model_fp16.pth", "tta_best_metrics.csv", "tta_last_metrics.csv",
            "training_summary.json", "TRAINING_COMPLETE_BEFORE_TTA.json",
            "FINAL_TTA_FAILED.txt", "effective_test_command.txt",
        ],
    )


def e3_command(resume_path, student_model, prototype_checkpoint, teacher_cache):
    recipe = {
        "experiment": "E3-TDH", "stage": "final", "epochs": E3_EPOCHS,
        "global_batch": E3_GLOBAL_BATCH, "backbone_lr": E3_BASE_LR,
        "head_lr_multiplier": E3_HEAD_LR_MULTIPLIER,
        "tir_global_weight": 0.0,
        "tir_local_weight": 0.0,
        "feature_preserve_weight": FEATURE_PRESERVE_WEIGHT,
        "scenario_hard_weight": SCENARIO_HARD_WEIGHT,
        "initialization_origin": "MSMT17_TransReID_then_AGReIDv2_E2_epoch60",
        "dataset": "AG-ReID.v2", "protocol": "aerial_to_ground",
        "tir_distillation": False,
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
    }
    manifest_path = make_stage_manifest(
        E3_RUN_DIR, "E3-TDH", recipe, resume_path=resume_path,
        e2_model_path=str(E2_MODEL_PATH) if E2_MODEL_PATH else None,
        e2_checkpoint_path=str(E2_CHECKPOINT_PATH) if E2_CHECKPOINT_PATH else None,
        teacher_model_path=str(teacher_cache),
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "AG-ReID.v2",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E3_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E3_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E3_BASE_LR),
        "SOLVER.WARMUP_EPOCHS", "1",
        "SOLVER.EVAL_PERIOD", "5",
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "INPUT.RE_PROB", "0.0",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.SYNC_PAIRED_AUG", "True",
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "True",
        "PVUAD.WARMSTART_MODEL_PATH", str(student_model),
        "PVUAD.WARMSTART_PROTOTYPE_PATH", (
            str(prototype_checkpoint) if prototype_checkpoint else ""
        ),
        "PVUAD.TEACHER_MODEL_PATH", str(teacher_cache),
        "PVUAD.HEAD_LR_MULTIPLIER", str(float(E3_HEAD_LR_MULTIPLIER)),
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.TIR_GLOBAL_WEIGHT", "0.0",
        "PVUAD.TIR_LOCAL_WEIGHT", "0.0",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", str(float(FEATURE_PRESERVE_WEIGHT)),
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.SCENARIO_HARD_WEIGHT", str(float(SCENARIO_HARD_WEIGHT)),
        "PVUAD.SCENARIO_HARD_TOPK", str(int(SCENARIO_HARD_TOPK)),
        "PVUAD.SCENARIO_HARD_MARGIN", str(float(SCENARIO_HARD_MARGIN)),
        "PVUAD.SCENARIO_HARD_TAU", str(float(SCENARIO_HARD_TAU)),
        "PVUAD.SCENARIO_HARD_START_EPOCH", str(int(SCENARIO_HARD_START_EPOCH)),
        "PVUAD.SCENARIO_BANK_MOMENTUM", "0.2",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", "True",
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


can_enter_e3 = (
    ACTIVE_STAGE == "E3"
    and (E3_STATUS.get("status") != "completed")
    and RUN_TRAINING
)
if (
    can_enter_e3
    and E2_COMPLETED_THIS_SESSION
    and ALWAYS_START_E3_IN_NEW_SESSION
):
    write_pipeline_state(
        "e2_completed_e3_pending", "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action=(
            "Kaggle will save this completed E2 output. Attach it to a new "
            "session and use Save & Run All; E3 will start automatically."
        ),
    )
    print(
        "E2 COMPLETE. This Kaggle version now ends cleanly by design. "
        "Attach its output to the next session; E3 will start there."
    )
    can_enter_e3 = False
elif can_enter_e3 and remaining_minutes() < MIN_E3_START_REMAINING_MINUTES:
    pending_status = "e3_paused" if E3_RESUME_PATH else "e2_completed_e3_pending"
    write_pipeline_state(
        pending_status, "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action="Save Version; attach this output and Run All in a new session.",
    )
    print(
        "Only {:.1f} minutes remain. E3 will start/resume in the next "
        "session.".format(remaining_minutes())
    )
    can_enter_e3 = False

if can_enter_e3:
    if E3_RESUME_PATH is not None:
        teacher_source = (
            SELECTED_E3["root"] / "e2_teacher_model_fp16.pth"
        )
        if not teacher_source.is_file() and E2_MODEL_PATH is not None:
            teacher_source = E2_MODEL_PATH
        if not TEACHER_CACHE.is_file():
            if teacher_source.name == "e2_teacher_model_fp16.pth":
                shutil.copy2(teacher_source, TEACHER_CACHE)
            else:
                create_teacher_cache(teacher_source, TEACHER_CACHE)
        student_model = TEACHER_CACHE
        prototype_checkpoint = None
    else:
        if E2_MODEL_PATH is None or not Path(E2_MODEL_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs a completed E2 final model. Attach the "
                "previous combined/E2 output or use E2_COMPLETED_DIR_OVERRIDE."
            )
        if E2_CHECKPOINT_PATH is None or not Path(E2_CHECKPOINT_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs E2 pvuad_last_checkpoint.pth for prototype warm-start."
            )
        create_teacher_cache(E2_MODEL_PATH, TEACHER_CACHE)
        student_model = E2_MODEL_PATH
        prototype_checkpoint = E2_CHECKPOINT_PATH

    print("Frozen E2 teacher:", TEACHER_CACHE)
    write_pipeline_state(
        "e3_running", "E3",
        e2_status=E2_STATUS,
        e3_resume_path=str(E3_RESUME_PATH) if E3_RESUME_PATH else None,
    )
    E3_STATUS = run_command_checked(
        e3_command(
            E3_RESUME_PATH, student_model, prototype_checkpoint, TEACHER_CACHE
        ),
        E3_RUN_DIR,
        "E3-TDH (AG adaptation)",
    )
    if E3_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e3_paused", "E3", e2_status=E2_STATUS, e3_status=E3_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E3 PAUSED SAFELY. Save Version and continue in a new session.")


def run_final_tta(model_path, metrics_filename, label):
    model_path = Path(model_path)
    metrics_path = E3_RUN_DIR / metrics_filename
    if metrics_path.is_file():
        print(f"{label}: already evaluated -> {metrics_path}")
        return True

    test_opts = [
        "MODEL.DIST_TRAIN", "False",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "AG-ReID.v2",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "TEST.WEIGHT", str(model_path),
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.VFPROCA", "True",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.FINAL_FLIP_TTA", "True",
        "PVUAD.TTA_METRICS_FILENAME", metrics_filename,
    ]
    test_command = [
        sys.executable, "test.py", "--config_file", "configs/PVUAD.yml",
        *test_opts,
    ]
    safe_label = re.sub(r"[^A-Za-z0-9_-]+", "_", label)
    (E3_RUN_DIR / f"effective_test_command_{safe_label}.txt").write_text(
        shlex.join(test_command) + "\n", encoding="utf-8"
    )
    print(f"Running AG-ReID.v2 A2G flip-TTA: {label}")
    result = subprocess.run(
        test_command, cwd=UAD_DIR, env=environment, check=False
    )
    if result.returncode != 0 or not metrics_path.is_file():
        warning = (
            f"{label} TTA failed after E3 training; checkpoint remains valid. "
            f"returncode={result.returncode}."
        )
        (E3_RUN_DIR / f"FINAL_TTA_FAILED_{safe_label}.txt").write_text(
            warning + "\n", encoding="utf-8"
        )
        print("WARNING:", warning)
        return False
    return True


E3_COMPLETED = E3_STATUS.get("status") == "completed"
if E3_COMPLETED:
    if SELECTED_E3 is not None:
        copy_if_present(
            SELECTED_E3["root"], E3_RUN_DIR,
            [
                "pvuad_last_checkpoint.pth", "pvuad_last_model.pth",
                "pvuad_best_model.pth", "session_status.json",
                "training_summary.json", "metrics_history.csv",
                "tta_best_metrics.csv", "tta_last_metrics.csv",
            ],
        )

    best_model = E3_RUN_DIR / "pvuad_best_model.pth"
    last_model = E3_RUN_DIR / "pvuad_last_model.pth"
    if not best_model.is_file():
        raise FileNotFoundError("Completed E3 is missing pvuad_best_model.pth")
    if not last_model.is_file():
        raise FileNotFoundError("Completed E3 is missing pvuad_last_model.pth")

    best_tta_path = E3_RUN_DIR / "tta_best_metrics.csv"
    last_tta_path = E3_RUN_DIR / "tta_last_metrics.csv"

    best_tta_ok = best_tta_path.is_file()
    last_tta_ok = last_tta_path.is_file()

    if RUN_FINAL_FLIP_TTA and not best_tta_ok:
        if remaining_minutes() >= MIN_TTA_START_REMAINING_MINUTES:
            best_tta_ok = run_final_tta(
                best_model, "tta_best_metrics.csv", "best_checkpoint"
            )
        else:
            print(
                "E3 complete but insufficient time for best-checkpoint TTA; "
                "continue next session."
            )

    # If the best checkpoint is the requested final epoch 25, best and last
    # are the same training state. Reuse the already-computed TTA metrics.
    e3_summary = read_json(E3_RUN_DIR / "training_summary.json")
    best_epoch = int(e3_summary.get("best_epoch") or 0)
    if (
        RUN_FINAL_FLIP_TTA
        and not last_tta_ok
        and best_epoch == E3_EPOCHS
        and best_tta_path.is_file()
    ):
        shutil.copy2(best_tta_path, last_tta_path)
        last_tta_ok = True
        print(
            f"best_epoch == final epoch == {E3_EPOCHS}; "
            "best and last checkpoint are the same training state. "
            "Copied TTA metrics instead of repeating inference."
        )

    if RUN_FINAL_FLIP_TTA and not last_tta_ok:
        if remaining_minutes() >= MIN_TTA_START_REMAINING_MINUTES:
            last_tta_ok = run_final_tta(
                last_model, "tta_last_metrics.csv", "last_epoch25"
            )
        else:
            print(
                "E3 complete but insufficient time for last-epoch TTA; "
                "continue next session."
            )

    tta_ok = (
        (best_tta_ok and last_tta_ok)
        if RUN_FINAL_FLIP_TTA else True
    )
    final_status = "completed" if tta_ok else "e3_complete_tta_pending"
    write_pipeline_state(
        final_status,
        "DONE" if final_status == "completed" else "TTA",
        e2_status=E2_STATUS,
        e3_status=E3_STATUS,
        best_epoch=best_epoch or None,
        tta_best_complete=bool(best_tta_ok),
        tta_last_complete=bool(last_tta_ok),
        next_action=(
            None if final_status == "completed"
            else "Attach this output and Run All; training is skipped and pending TTA resumes."
        ),
    )
elif ACTIVE_STAGE == "E3" and not can_enter_e3 and not RUN_TRAINING:
    write_pipeline_state("dry_run", "E3")
elif ACTIVE_STAGE == "E3" and not can_enter_e3 and not RUN_TRAINING:
    write_pipeline_state("dry_run", "E3")

Frozen E2 teacher: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth

Launching E3-TDH (AG adaptation)
/usr/bin/python3 -m torch.distributed.run --standalone --nproc_per_node=2 train.py --config_file configs/PVUAD.yml MODEL.DIST_TRAIN True MODEL.PRETRAIN_CHOICE none MODEL.PRETRAIN_PATH /kaggle/working/vit_transreid_msmt.pth MODEL.STRIDE_SIZE '[16, 16]' MODEL.SIE_CAMERA False MODEL.SIE_VIEW False DATASETS.NAMES AG-ReID.v2 DATASETS.MODALITIES '['"'"'RGB'"'"']' DATASETS.ROOT_DIR /kaggle/working/pvuad_agreid_data DATALOADER.NUM_WORKERS 4 SOLVER.SEED 1234 SOLVER.MAX_EPOCHS 25 SOLVER.IMS_PER_BATCH 24 SOLVER.BASE_LR 0.0001 SOLVER.WARMUP_EPOCHS 1 SOLVER.EVAL_PERIOD 5 SOLVER.CHECKPOINT_PERIOD 5 INPUT.RE_PROB 0.0 TEST.IMS_PER_BATCH 256 TEST.RE_RANKING False TEST.TOP_K_EVAL 0 OUTPUT_DIR /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh PVUAD.EXPERIMENT E3-TDH PVUAD.STAGE final PVUAD.DEV_MODE False PVUAD.PAIRED_VIEW_SAMPLER True PVUAD.STRICT_PAIRED_DATA False PVUAD.GROUND_MAX_CAMID 1 PVUAD.SYNC_PAIRED_AUG True PVUAD.VFPROCA True MODEL.PCA_LOSS_WEIGHT 0.01 PVUAD.VIEW_ALIGNMENT_WEIGHT 0.5 PVUAD.INVARIANT_ID_WEIGHT 0.5 PVUAD.SCENARIO_CLS_WEIGHT 0.1 PVUAD.TEST_INVARIANT_BLEND 0.5 PVUAD.LOCAL_CONSISTENCY False PVUAD.HARD_GPD False PVUAD.FINETUNE True PVUAD.WARMSTART_MODEL_PATH /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth PVUAD.WARMSTART_PROTOTYPE_PATH /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth PVUAD.TEACHER_MODEL_PATH /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth PVUAD.HEAD_LR_MULTIPLIER 5.0 PVUAD.TIR_DISTILLATION False PVUAD.TIR_GLOBAL_WEIGHT 0.0 PVUAD.TIR_LOCAL_WEIGHT 0.0 PVUAD.FEATURE_PRESERVE_WEIGHT 0.05 PVUAD.SCENARIO_HARD_GPD True PVUAD.SCENARIO_HARD_WEIGHT 0.15 PVUAD.SCENARIO_HARD_TOPK 5 PVUAD.SCENARIO_HARD_MARGIN 0.05 PVUAD.SCENARIO_HARD_TAU 0.05 PVUAD.SCENARIO_HARD_START_EPOCH 3 PVUAD.SCENARIO_BANK_MOMENTUM 0.2 PVUAD.FINAL_FLIP_TTA False PVUAD.SAVE_LAST_EVERY 5 PVUAD.RUN_MANIFEST /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/run_manifest.json PVUAD.SESSION_DEADLINE_UNIX 1789395136.7769897 PVUAD.STOP_RESERVE_MINUTES 15.0 PVUAD.CHECKPOINT_EVERY_MINUTES 30.0 PVUAD.TIME_CHECK_EVERY_STEPS 10 PVUAD.MIN_EVAL_REMAINING_MINUTES 25.0 PVUAD.STRICT_RESUME_CONFIG True

[W914 04:02:09.886074992 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

2026-09-14 04:02:23,121 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh
2026-09-14 04:02:23,122 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'AG-ReID.v2', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_agreid_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '5', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '1', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.0', 'PVUAD.TIR_LOCAL_WEIGHT', '0.0', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1789395136.7769897', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '25.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=0)
2026-09-14 04:02:23,122 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-14 04:02:23,122 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB',)
  NAMES: AG-ReID.v2
  ROOT_DIR: /kaggle/working/pvuad_agreid_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.0
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: True
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.05
  FINAL_FLIP_TTA: False
  FINETUNE: True
  GROUND_MAX_CAMID: 1
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 5.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 25.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/run_manifest.json
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 1789395136.7769897
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 15.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: True
  TEACHER_MODEL_PATH: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.0
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.0
  TTA_METRICS_FILENAME: tta_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH: /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth
  WARMSTART_PROTOTYPE_PATH: /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 5
  GAMMA: 0.1
  IMS_PER_BATCH: 24
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 25
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 1
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT:
2026-09-14 04:02:23,131 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh
2026-09-14 04:02:23,131 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'AG-ReID.v2', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_agreid_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '5', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '1', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.0', 'PVUAD.TIR_LOCAL_WEIGHT', '0.0', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1789395136.7769897', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '25.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=1)
2026-09-14 04:02:23,131 transreid INFO: Loaded configuration file configs/PVUAD.yml

[W914 04:02:23.413111646 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W914 04:02:23.420626125 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

=> AG-ReID.v2 loaded (aerial -> ground)
   train: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/train_all
   query: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/query
   gallery: ['/kaggle/working/pvuad_agreid_data/AG-ReID.v2/gallery']
=> AG-ReID.v2 loaded (aerial -> ground)
   train: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/train_all
   query: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/query
   gallery: ['/kaggle/working/pvuad_agreid_data/AG-ReID.v2/gallery']
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   807 |    51530 |         3
  query    |   808 |     4348 |         1
  gallery  |   808 |    19259 |         2
  ----------------------------------------
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   807 |    51530 |         3
  query    |   808 |     4348 |         1
  gallery  |   808 |    19259 |         2
  ----------------------------------------
DIST_TRAIN START
DIST_TRAIN START
ViewBalancedPKM: 807 IDs (807 dual-view, 0 single-view), 75,584 sample slots/epoch, 3 PID x 4 instances per GPU
ViewBalancedPKM: 807 IDs (807 dual-view, 0 single-view), 75,584 sample slots/epoch, 3 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
===========building transformer===========
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-14 04:05:40,461 transreid.train INFO: start training
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-14 04:05:40,476 transreid.train INFO: start training
2026-09-14 04:05:41,599 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth (173 tensors)
2026-09-14 04:05:41,621 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_model.pth (173 tensors)
2026-09-14 04:05:45,382 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth
2026-09-14 04:05:45,382 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/thienbao1604/pvuad-agreidv2-a2g-e2-60-e3-25-transreidfd4dd43eb8/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e2_final/pvuad_last_checkpoint.pth
2026-09-14 04:05:45,646 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
2026-09-14 04:05:45,694 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
2026-09-14 04:05:45,695 transreid.train INFO: Kaggle session guard: started 1789358740, hard deadline 1789395137, safe checkpoint stop 1789394237
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
2026-09-14 04:05:58,525 transreid.train INFO: Epoch[1] Iteration[50/3149] Loss 0.671 Acc 0.965 ID 0.320 TRI 0.017 Align 0.044 GPD 0.006 TIR-G 0.000 TIR-L 0.000 Keep 0.027 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:05:58,525 transreid.train INFO: Epoch[1] Iteration[50/3149] Loss 0.662 Acc 0.980 ID 0.308 TRI 0.018 Align 0.043 GPD 0.006 TIR-G 0.000 TIR-L 0.000 Keep 0.026 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:07,966 transreid.train INFO: Epoch[1] Iteration[100/3149] Loss 0.747 Acc 0.953 ID 0.353 TRI 0.022 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:07,966 transreid.train INFO: Epoch[1] Iteration[100/3149] Loss 0.702 Acc 0.970 ID 0.328 TRI 0.017 Align 0.044 GPD 0.006 TIR-G 0.000 TIR-L 0.000 Keep 0.028 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:17,354 transreid.train INFO: Epoch[1] Iteration[150/3149] Loss 0.770 Acc 0.954 ID 0.362 TRI 0.022 Align 0.045 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:17,354 transreid.train INFO: Epoch[1] Iteration[150/3149] Loss 0.747 Acc 0.969 ID 0.346 TRI 0.017 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:26,637 transreid.train INFO: Epoch[1] Iteration[200/3149] Loss 0.767 Acc 0.969 ID 0.354 TRI 0.019 Align 0.045 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:26,637 transreid.train INFO: Epoch[1] Iteration[200/3149] Loss 0.741 Acc 0.959 ID 0.348 TRI 0.021 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:36,158 transreid.train INFO: Epoch[1] Iteration[250/3149] Loss 0.741 Acc 0.961 ID 0.348 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:36,158 transreid.train INFO: Epoch[1] Iteration[250/3149] Loss 0.756 Acc 0.969 ID 0.350 TRI 0.019 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:45,653 transreid.train INFO: Epoch[1] Iteration[300/3149] Loss 0.737 Acc 0.963 ID 0.347 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:45,653 transreid.train INFO: Epoch[1] Iteration[300/3149] Loss 0.745 Acc 0.969 ID 0.346 TRI 0.019 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.029 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:55,170 transreid.train INFO: Epoch[1] Iteration[350/3149] Loss 0.730 Acc 0.964 ID 0.343 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:06:55,170 transreid.train INFO: Epoch[1] Iteration[350/3149] Loss 0.737 Acc 0.969 ID 0.343 TRI 0.019 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:04,758 transreid.train INFO: Epoch[1] Iteration[400/3149] Loss 0.733 Acc 0.964 ID 0.345 TRI 0.020 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:04,758 transreid.train INFO: Epoch[1] Iteration[400/3149] Loss 0.736 Acc 0.970 ID 0.343 TRI 0.020 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:14,338 transreid.train INFO: Epoch[1] Iteration[450/3149] Loss 0.736 Acc 0.964 ID 0.346 TRI 0.021 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:14,339 transreid.train INFO: Epoch[1] Iteration[450/3149] Loss 0.733 Acc 0.969 ID 0.342 TRI 0.020 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:23,862 transreid.train INFO: Epoch[1] Iteration[500/3149] Loss 0.743 Acc 0.963 ID 0.350 TRI 0.021 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:23,863 transreid.train INFO: Epoch[1] Iteration[500/3149] Loss 0.718 Acc 0.971 ID 0.334 TRI 0.020 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:33,277 transreid.train INFO: Epoch[1] Iteration[550/3149] Loss 0.732 Acc 0.965 ID 0.344 TRI 0.021 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:33,277 transreid.train INFO: Epoch[1] Iteration[550/3149] Loss 0.711 Acc 0.971 ID 0.331 TRI 0.019 Align 0.044 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:42,694 transreid.train INFO: Epoch[1] Iteration[600/3149] Loss 0.730 Acc 0.966 ID 0.344 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:42,694 transreid.train INFO: Epoch[1] Iteration[600/3149] Loss 0.705 Acc 0.973 ID 0.328 TRI 0.019 Align 0.045 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:52,157 transreid.train INFO: Epoch[1] Iteration[650/3149] Loss 0.725 Acc 0.967 ID 0.341 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:07:52,157 transreid.train INFO: Epoch[1] Iteration[650/3149] Loss 0.701 Acc 0.973 ID 0.326 TRI 0.019 Align 0.045 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:01,635 transreid.train INFO: Epoch[1] Iteration[700/3149] Loss 0.692 Acc 0.974 ID 0.322 TRI 0.019 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:01,635 transreid.train INFO: Epoch[1] Iteration[700/3149] Loss 0.717 Acc 0.968 ID 0.337 TRI 0.020 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:11,167 transreid.train INFO: Epoch[1] Iteration[750/3149] Loss 0.710 Acc 0.969 ID 0.335 TRI 0.020 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:11,167 transreid.train INFO: Epoch[1] Iteration[750/3149] Loss 0.685 Acc 0.975 ID 0.319 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:20,596 transreid.train INFO: Epoch[1] Iteration[800/3149] Loss 0.685 Acc 0.974 ID 0.319 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:20,597 transreid.train INFO: Epoch[1] Iteration[800/3149] Loss 0.705 Acc 0.969 ID 0.332 TRI 0.020 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:30,043 transreid.train INFO: Epoch[1] Iteration[850/3149] Loss 0.696 Acc 0.970 ID 0.328 TRI 0.020 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:30,043 transreid.train INFO: Epoch[1] Iteration[850/3149] Loss 0.682 Acc 0.975 ID 0.318 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:39,459 transreid.train INFO: Epoch[1] Iteration[900/3149] Loss 0.676 Acc 0.975 ID 0.316 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:39,460 transreid.train INFO: Epoch[1] Iteration[900/3149] Loss 0.688 Acc 0.970 ID 0.324 TRI 0.020 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:48,882 transreid.train INFO: Epoch[1] Iteration[950/3149] Loss 0.682 Acc 0.970 ID 0.321 TRI 0.020 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:48,882 transreid.train INFO: Epoch[1] Iteration[950/3149] Loss 0.667 Acc 0.975 ID 0.311 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:58,296 transreid.train INFO: Epoch[1] Iteration[1000/3149] Loss 0.678 Acc 0.971 ID 0.320 TRI 0.020 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:08:58,297 transreid.train INFO: Epoch[1] Iteration[1000/3149] Loss 0.664 Acc 0.976 ID 0.310 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:07,740 transreid.train INFO: Epoch[1] Iteration[1050/3149] Loss 0.672 Acc 0.971 ID 0.317 TRI 0.020 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:07,740 transreid.train INFO: Epoch[1] Iteration[1050/3149] Loss 0.657 Acc 0.976 ID 0.307 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:17,231 transreid.train INFO: Epoch[1] Iteration[1100/3149] Loss 0.669 Acc 0.972 ID 0.316 TRI 0.020 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:17,231 transreid.train INFO: Epoch[1] Iteration[1100/3149] Loss 0.651 Acc 0.976 ID 0.304 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:26,700 transreid.train INFO: Epoch[1] Iteration[1150/3149] Loss 0.645 Acc 0.977 ID 0.301 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:26,700 transreid.train INFO: Epoch[1] Iteration[1150/3149] Loss 0.662 Acc 0.972 ID 0.313 TRI 0.020 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:36,170 transreid.train INFO: Epoch[1] Iteration[1200/3149] Loss 0.656 Acc 0.972 ID 0.310 TRI 0.020 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:36,170 transreid.train INFO: Epoch[1] Iteration[1200/3149] Loss 0.644 Acc 0.977 ID 0.301 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:45,618 transreid.train INFO: Epoch[1] Iteration[1250/3149] Loss 0.651 Acc 0.973 ID 0.307 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:45,618 transreid.train INFO: Epoch[1] Iteration[1250/3149] Loss 0.637 Acc 0.977 ID 0.298 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:55,111 transreid.train INFO: Epoch[1] Iteration[1300/3149] Loss 0.633 Acc 0.978 ID 0.296 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:09:55,111 transreid.train INFO: Epoch[1] Iteration[1300/3149] Loss 0.645 Acc 0.973 ID 0.305 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:04,603 transreid.train INFO: Epoch[1] Iteration[1350/3149] Loss 0.641 Acc 0.973 ID 0.303 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:04,603 transreid.train INFO: Epoch[1] Iteration[1350/3149] Loss 0.627 Acc 0.978 ID 0.293 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:14,148 transreid.train INFO: Epoch[1] Iteration[1400/3149] Loss 0.634 Acc 0.974 ID 0.299 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:14,148 transreid.train INFO: Epoch[1] Iteration[1400/3149] Loss 0.622 Acc 0.978 ID 0.291 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:23,616 transreid.train INFO: Epoch[1] Iteration[1450/3149] Loss 0.629 Acc 0.974 ID 0.297 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:23,616 transreid.train INFO: Epoch[1] Iteration[1450/3149] Loss 0.617 Acc 0.978 ID 0.289 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:33,086 transreid.train INFO: Epoch[1] Iteration[1500/3149] Loss 0.614 Acc 0.978 ID 0.287 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:33,086 transreid.train INFO: Epoch[1] Iteration[1500/3149] Loss 0.625 Acc 0.975 ID 0.295 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:42,535 transreid.train INFO: Epoch[1] Iteration[1550/3149] Loss 0.609 Acc 0.979 ID 0.285 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:42,535 transreid.train INFO: Epoch[1] Iteration[1550/3149] Loss 0.620 Acc 0.975 ID 0.293 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:51,986 transreid.train INFO: Epoch[1] Iteration[1600/3149] Loss 0.608 Acc 0.979 ID 0.285 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:10:51,986 transreid.train INFO: Epoch[1] Iteration[1600/3149] Loss 0.617 Acc 0.975 ID 0.292 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:01,397 transreid.train INFO: Epoch[1] Iteration[1650/3149] Loss 0.603 Acc 0.979 ID 0.282 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:01,397 transreid.train INFO: Epoch[1] Iteration[1650/3149] Loss 0.612 Acc 0.975 ID 0.290 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:10,893 transreid.train INFO: Epoch[1] Iteration[1700/3149] Loss 0.608 Acc 0.975 ID 0.288 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:10,893 transreid.train INFO: Epoch[1] Iteration[1700/3149] Loss 0.598 Acc 0.979 ID 0.280 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:20,362 transreid.train INFO: Epoch[1] Iteration[1750/3149] Loss 0.602 Acc 0.976 ID 0.285 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:20,362 transreid.train INFO: Epoch[1] Iteration[1750/3149] Loss 0.595 Acc 0.979 ID 0.279 TRI 0.018 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:29,791 transreid.train INFO: Epoch[1] Iteration[1800/3149] Loss 0.597 Acc 0.976 ID 0.283 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:29,791 transreid.train INFO: Epoch[1] Iteration[1800/3149] Loss 0.592 Acc 0.979 ID 0.278 TRI 0.019 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:39,234 transreid.train INFO: Epoch[1] Iteration[1850/3149] Loss 0.594 Acc 0.976 ID 0.281 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:39,234 transreid.train INFO: Epoch[1] Iteration[1850/3149] Loss 0.589 Acc 0.980 ID 0.276 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:48,720 transreid.train INFO: Epoch[1] Iteration[1900/3149] Loss 0.584 Acc 0.980 ID 0.274 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:48,720 transreid.train INFO: Epoch[1] Iteration[1900/3149] Loss 0.591 Acc 0.976 ID 0.280 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:58,193 transreid.train INFO: Epoch[1] Iteration[1950/3149] Loss 0.579 Acc 0.980 ID 0.272 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:11:58,193 transreid.train INFO: Epoch[1] Iteration[1950/3149] Loss 0.587 Acc 0.977 ID 0.278 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:12:07,669 transreid.train INFO: Epoch[1] Iteration[2000/3149] Loss 0.574 Acc 0.981 ID 0.270 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:12:07,669 transreid.train INFO: Epoch[1] Iteration[2000/3149] Loss 0.583 Acc 0.977 ID 0.276 TRI 0.019 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05
2026-09-14 04:12:17,137 transreid.train INFO: Epoch[1] Iteration[2050/3149] Loss 0.578 Acc 0.977 ID 0.274 TRI 0.019 Align 0.043 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.000 LR 9.96e-05

/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

2026-09-14 04:35:50,241 transreid.train INFO: Epoch[3] Iteration[3100/3102] Loss 0.436 Acc 0.985 ID 0.205 TRI 0.016 Align 0.040 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.002 LR 9.65e-05
2026-09-14 04:35:50,241 transreid.train INFO: Epoch[3] Iteration[3100/3102] Loss 0.443 Acc 0.984 ID 0.209 TRI 0.016 Align 0.040 GPD 0.007 TIR-G 0.000 TIR-L 0.000 Keep 0.030 S-Hard 0.002 LR 9.65e-05
2026-09-14 04:35:50,705 transreid.train INFO: Epoch 3 done in 617.7s; loss 0.4356; acc 0.9847
2026-09-14 04:36:02,381 transreid.train INFO: Epoch[4] Iteration[50/3102] Loss 0.948 Acc 0.938 ID 0.455 TRI 0.021 Align 0.044 GPD 0.017 TIR-G 0.000 TIR-L 0.000 Keep 0.035 S-Hard 0.004 LR 9.38e-05
2026-09-14 04:36:02,381 transreid.train INFO: Epoch[4] Iteration[50/3102] Loss 0.922 Acc 0.947 ID 0.465 TRI 0.017 Align 0.045 GPD 0.017 TIR-G 0.000 TIR-L 0.000 Keep 0.036 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:12,251 transreid.train INFO: Epoch[4] Iteration[100/3102] Loss 0.898 Acc 0.945 ID 0.444 TRI 0.017 Align 0.045 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.034 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:12,251 transreid.train INFO: Epoch[4] Iteration[100/3102] Loss 0.917 Acc 0.935 ID 0.444 TRI 0.020 Align 0.045 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.033 S-Hard 0.004 LR 9.38e-05
2026-09-14 04:36:22,152 transreid.train INFO: Epoch[4] Iteration[150/3102] Loss 0.840 Acc 0.954 ID 0.410 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.033 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:22,152 transreid.train INFO: Epoch[4] Iteration[150/3102] Loss 0.850 Acc 0.948 ID 0.410 TRI 0.019 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.033 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:32,030 transreid.train INFO: Epoch[4] Iteration[200/3102] Loss 0.831 Acc 0.956 ID 0.403 TRI 0.017 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:32,030 transreid.train INFO: Epoch[4] Iteration[200/3102] Loss 0.800 Acc 0.955 ID 0.384 TRI 0.018 Align 0.045 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:41,912 transreid.train INFO: Epoch[4] Iteration[250/3102] Loss 0.786 Acc 0.959 ID 0.376 TRI 0.018 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:41,913 transreid.train INFO: Epoch[4] Iteration[250/3102] Loss 0.816 Acc 0.958 ID 0.394 TRI 0.017 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:51,856 transreid.train INFO: Epoch[4] Iteration[300/3102] Loss 0.764 Acc 0.962 ID 0.365 TRI 0.018 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:36:51,856 transreid.train INFO: Epoch[4] Iteration[300/3102] Loss 0.801 Acc 0.958 ID 0.385 TRI 0.017 Align 0.045 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:01,818 transreid.train INFO: Epoch[4] Iteration[350/3102] Loss 0.772 Acc 0.961 ID 0.370 TRI 0.017 Align 0.044 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:01,818 transreid.train INFO: Epoch[4] Iteration[350/3102] Loss 0.753 Acc 0.963 ID 0.357 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:11,690 transreid.train INFO: Epoch[4] Iteration[400/3102] Loss 0.753 Acc 0.961 ID 0.356 TRI 0.018 Align 0.045 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:11,690 transreid.train INFO: Epoch[4] Iteration[400/3102] Loss 0.757 Acc 0.964 ID 0.362 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:37:21,528 transreid.train INFO: Epoch[4] Iteration[450/3102] Loss 0.753 Acc 0.964 ID 0.359 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:37:21,528 transreid.train INFO: Epoch[4] Iteration[450/3102] Loss 0.734 Acc 0.964 ID 0.346 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:31,281 transreid.train INFO: Epoch[4] Iteration[500/3102] Loss 0.724 Acc 0.965 ID 0.341 TRI 0.018 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:31,281 transreid.train INFO: Epoch[4] Iteration[500/3102] Loss 0.748 Acc 0.964 ID 0.356 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:37:41,143 transreid.train INFO: Epoch[4] Iteration[550/3102] Loss 0.707 Acc 0.967 ID 0.333 TRI 0.017 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:37:41,143 transreid.train INFO: Epoch[4] Iteration[550/3102] Loss 0.733 Acc 0.965 ID 0.348 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:37:51,012 transreid.train INFO: Epoch[4] Iteration[600/3102] Loss 0.720 Acc 0.967 ID 0.341 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:37:51,012 transreid.train INFO: Epoch[4] Iteration[600/3102] Loss 0.703 Acc 0.967 ID 0.330 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:38:00,900 transreid.train INFO: Epoch[4] Iteration[650/3102] Loss 0.693 Acc 0.968 ID 0.326 TRI 0.017 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:38:00,900 transreid.train INFO: Epoch[4] Iteration[650/3102] Loss 0.710 Acc 0.968 ID 0.336 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:10,785 transreid.train INFO: Epoch[4] Iteration[700/3102] Loss 0.684 Acc 0.969 ID 0.321 TRI 0.017 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:38:10,785 transreid.train INFO: Epoch[4] Iteration[700/3102] Loss 0.702 Acc 0.969 ID 0.332 TRI 0.018 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:20,708 transreid.train INFO: Epoch[4] Iteration[750/3102] Loss 0.672 Acc 0.970 ID 0.316 TRI 0.017 Align 0.045 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.003 LR 9.38e-05
2026-09-14 04:38:20,708 transreid.train INFO: Epoch[4] Iteration[750/3102] Loss 0.696 Acc 0.970 ID 0.329 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:30,663 transreid.train INFO: Epoch[4] Iteration[800/3102] Loss 0.693 Acc 0.970 ID 0.328 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:30,663 transreid.train INFO: Epoch[4] Iteration[800/3102] Loss 0.665 Acc 0.971 ID 0.312 TRI 0.017 Align 0.045 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:40,527 transreid.train INFO: Epoch[4] Iteration[850/3102] Loss 0.659 Acc 0.971 ID 0.310 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:40,527 transreid.train INFO: Epoch[4] Iteration[850/3102] Loss 0.684 Acc 0.971 ID 0.323 TRI 0.018 Align 0.045 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:50,436 transreid.train INFO: Epoch[4] Iteration[900/3102] Loss 0.653 Acc 0.971 ID 0.307 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:38:50,437 transreid.train INFO: Epoch[4] Iteration[900/3102] Loss 0.680 Acc 0.972 ID 0.321 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:00,335 transreid.train INFO: Epoch[4] Iteration[950/3102] Loss 0.671 Acc 0.972 ID 0.317 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:00,335 transreid.train INFO: Epoch[4] Iteration[950/3102] Loss 0.644 Acc 0.972 ID 0.302 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:10,220 transreid.train INFO: Epoch[4] Iteration[1000/3102] Loss 0.636 Acc 0.973 ID 0.298 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:10,220 transreid.train INFO: Epoch[4] Iteration[1000/3102] Loss 0.665 Acc 0.973 ID 0.314 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:20,088 transreid.train INFO: Epoch[4] Iteration[1050/3102] Loss 0.630 Acc 0.973 ID 0.296 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:20,088 transreid.train INFO: Epoch[4] Iteration[1050/3102] Loss 0.658 Acc 0.973 ID 0.311 TRI 0.017 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:29,927 transreid.train INFO: Epoch[4] Iteration[1100/3102] Loss 0.624 Acc 0.974 ID 0.293 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:29,927 transreid.train INFO: Epoch[4] Iteration[1100/3102] Loss 0.657 Acc 0.973 ID 0.310 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:39,863 transreid.train INFO: Epoch[4] Iteration[1150/3102] Loss 0.619 Acc 0.974 ID 0.291 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:39,863 transreid.train INFO: Epoch[4] Iteration[1150/3102] Loss 0.654 Acc 0.973 ID 0.309 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:49,798 transreid.train INFO: Epoch[4] Iteration[1200/3102] Loss 0.615 Acc 0.975 ID 0.289 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:49,798 transreid.train INFO: Epoch[4] Iteration[1200/3102] Loss 0.649 Acc 0.973 ID 0.307 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:59,681 transreid.train INFO: Epoch[4] Iteration[1250/3102] Loss 0.612 Acc 0.975 ID 0.288 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:39:59,681 transreid.train INFO: Epoch[4] Iteration[1250/3102] Loss 0.643 Acc 0.974 ID 0.304 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:09,556 transreid.train INFO: Epoch[4] Iteration[1300/3102] Loss 0.638 Acc 0.974 ID 0.302 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:09,556 transreid.train INFO: Epoch[4] Iteration[1300/3102] Loss 0.609 Acc 0.975 ID 0.286 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:19,502 transreid.train INFO: Epoch[4] Iteration[1350/3102] Loss 0.605 Acc 0.976 ID 0.285 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:19,502 transreid.train INFO: Epoch[4] Iteration[1350/3102] Loss 0.632 Acc 0.974 ID 0.299 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:29,449 transreid.train INFO: Epoch[4] Iteration[1400/3102] Loss 0.601 Acc 0.976 ID 0.283 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:29,449 transreid.train INFO: Epoch[4] Iteration[1400/3102] Loss 0.629 Acc 0.975 ID 0.297 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:39,310 transreid.train INFO: Epoch[4] Iteration[1450/3102] Loss 0.599 Acc 0.976 ID 0.282 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:39,311 transreid.train INFO: Epoch[4] Iteration[1450/3102] Loss 0.624 Acc 0.975 ID 0.295 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:49,232 transreid.train INFO: Epoch[4] Iteration[1500/3102] Loss 0.595 Acc 0.976 ID 0.280 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:49,232 transreid.train INFO: Epoch[4] Iteration[1500/3102] Loss 0.621 Acc 0.975 ID 0.294 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:59,106 transreid.train INFO: Epoch[4] Iteration[1550/3102] Loss 0.591 Acc 0.976 ID 0.278 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:40:59,106 transreid.train INFO: Epoch[4] Iteration[1550/3102] Loss 0.617 Acc 0.976 ID 0.292 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:09,013 transreid.train INFO: Epoch[4] Iteration[1600/3102] Loss 0.587 Acc 0.976 ID 0.276 TRI 0.017 Align 0.044 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:09,013 transreid.train INFO: Epoch[4] Iteration[1600/3102] Loss 0.611 Acc 0.976 ID 0.289 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:18,935 transreid.train INFO: Epoch[4] Iteration[1650/3102] Loss 0.583 Acc 0.977 ID 0.275 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:18,935 transreid.train INFO: Epoch[4] Iteration[1650/3102] Loss 0.607 Acc 0.976 ID 0.287 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:28,842 transreid.train INFO: Epoch[4] Iteration[1700/3102] Loss 0.604 Acc 0.976 ID 0.286 TRI 0.018 Align 0.044 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:28,842 transreid.train INFO: Epoch[4] Iteration[1700/3102] Loss 0.580 Acc 0.977 ID 0.273 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:38,731 transreid.train INFO: Epoch[4] Iteration[1750/3102] Loss 0.598 Acc 0.977 ID 0.283 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:38,731 transreid.train INFO: Epoch[4] Iteration[1750/3102] Loss 0.574 Acc 0.977 ID 0.270 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:48,683 transreid.train INFO: Epoch[4] Iteration[1800/3102] Loss 0.592 Acc 0.977 ID 0.280 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:48,683 transreid.train INFO: Epoch[4] Iteration[1800/3102] Loss 0.570 Acc 0.978 ID 0.268 TRI 0.017 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:58,604 transreid.train INFO: Epoch[4] Iteration[1850/3102] Loss 0.565 Acc 0.978 ID 0.266 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.032 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:41:58,605 transreid.train INFO: Epoch[4] Iteration[1850/3102] Loss 0.588 Acc 0.977 ID 0.278 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:08,377 transreid.train INFO: Epoch[4] Iteration[1900/3102] Loss 0.558 Acc 0.979 ID 0.263 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:08,378 transreid.train INFO: Epoch[4] Iteration[1900/3102] Loss 0.581 Acc 0.978 ID 0.275 TRI 0.018 Align 0.044 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:18,050 transreid.train INFO: Epoch[4] Iteration[1950/3102] Loss 0.576 Acc 0.978 ID 0.273 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:18,050 transreid.train INFO: Epoch[4] Iteration[1950/3102] Loss 0.555 Acc 0.979 ID 0.261 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:27,820 transreid.train INFO: Epoch[4] Iteration[2000/3102] Loss 0.571 Acc 0.978 ID 0.270 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:27,820 transreid.train INFO: Epoch[4] Iteration[2000/3102] Loss 0.551 Acc 0.979 ID 0.259 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:37,537 transreid.train INFO: Epoch[4] Iteration[2050/3102] Loss 0.567 Acc 0.978 ID 0.268 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:37,537 transreid.train INFO: Epoch[4] Iteration[2050/3102] Loss 0.546 Acc 0.979 ID 0.257 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:47,248 transreid.train INFO: Epoch[4] Iteration[2100/3102] Loss 0.541 Acc 0.980 ID 0.255 TRI 0.017 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:47,248 transreid.train INFO: Epoch[4] Iteration[2100/3102] Loss 0.563 Acc 0.979 ID 0.267 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:56,986 transreid.train INFO: Epoch[4] Iteration[2150/3102] Loss 0.536 Acc 0.980 ID 0.252 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:42:56,986 transreid.train INFO: Epoch[4] Iteration[2150/3102] Loss 0.557 Acc 0.979 ID 0.264 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:06,719 transreid.train INFO: Epoch[4] Iteration[2200/3102] Loss 0.530 Acc 0.980 ID 0.250 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:06,719 transreid.train INFO: Epoch[4] Iteration[2200/3102] Loss 0.551 Acc 0.980 ID 0.261 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:16,485 transreid.train INFO: Epoch[4] Iteration[2250/3102] Loss 0.546 Acc 0.980 ID 0.259 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:16,485 transreid.train INFO: Epoch[4] Iteration[2250/3102] Loss 0.525 Acc 0.981 ID 0.247 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:26,465 transreid.train INFO: Epoch[4] Iteration[2300/3102] Loss 0.520 Acc 0.981 ID 0.245 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:26,465 transreid.train INFO: Epoch[4] Iteration[2300/3102] Loss 0.540 Acc 0.980 ID 0.256 TRI 0.018 Align 0.043 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:36,419 transreid.train INFO: Epoch[4] Iteration[2350/3102] Loss 0.535 Acc 0.980 ID 0.253 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:36,419 transreid.train INFO: Epoch[4] Iteration[2350/3102] Loss 0.515 Acc 0.981 ID 0.243 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:46,360 transreid.train INFO: Epoch[4] Iteration[2400/3102] Loss 0.512 Acc 0.981 ID 0.241 TRI 0.017 Align 0.042 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:46,360 transreid.train INFO: Epoch[4] Iteration[2400/3102] Loss 0.530 Acc 0.980 ID 0.251 TRI 0.017 Align 0.043 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:56,254 transreid.train INFO: Epoch[4] Iteration[2450/3102] Loss 0.507 Acc 0.981 ID 0.239 TRI 0.017 Align 0.042 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05
2026-09-14 04:43:56,255 transreid.train INFO: Epoch[4] Iteration[2450/3102] Loss 0.524 Acc 0.981 ID 0.248 TRI 0.017 Align 0.042 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.031 S-Hard 0.002 LR 9.38e-05

,stage,status,reason,epoch,next_iteration,epoch_complete,global_step,best_mAP,remaining_minutes
0,E3-TDH (AG adaptation),completed,training_completed,25,0,True,77574,73.354912,326.8

Running AG-ReID.v2 A2G flip-TTA: best_checkpoint
2026-09-14 08:45:36,964 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'False', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'AG-ReID.v2', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_agreid_data', 'DATALOADER.NUM_WORKERS', '4', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'TEST.WEIGHT', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/pvuad_best_model.pth', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '1', 'PVUAD.VFPROCA', 'True', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.0', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.FINAL_FLIP_TTA', 'True', 'PVUAD.TTA_METRICS_FILENAME', 'tta_best_metrics.csv'])
2026-09-14 08:45:36,965 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-14 08:45:36,965 transreid INFO:
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'wrt'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_in'
  STRIDE_SIZE: [16, 16]
  PCA_LOSS_WEIGHT: 0.01
  GPD_MOMENTUM: 0.2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: 'AG-ReID.v2'
  ROOT_DIR: '/kaggle/working/pvuad_agreid_data'
  MODALITIES: ['RGB']

DATALOADER:
  SAMPLER: 'PKM'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  LOSS_TYPE: "base+pca+gpd"

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TOP_K_EVAL: 0

PVUAD:
  EXPERIMENT: 'E0'
  STAGE: 'final'
  DEV_MODE: False
  DEV_VAL_IDS: 100
  DEV_SPLIT_SEED: 2026
  DEV_QUERY_PER_PID_CAM: 1
  PAIRED_VIEW_SAMPLER: False
  SYNC_PAIRED_AUG: False
  GROUND_MAX_CAMID: 1
  STRICT_PAIRED_DATA: True
  VFPROCA: False
  VIEW_ALIGNMENT_WEIGHT: 0.5
  INVARIANT_ID_WEIGHT: 0.5
  SCENARIO_CLS_WEIGHT: 0.1
  TEST_INVARIANT_BLEND: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  HARD_GPD: False
  HARD_GPD_WEIGHT: 0.5
  HARD_GPD_TOPK: 10
  HARD_GPD_MARGIN: 0.10
  HARD_GPD_START_EPOCH: 10
  FINETUNE: False
  WARMSTART_MODEL_PATH: ''
  WARMSTART_PROTOTYPE_PATH: ''
  TEACHER_MODEL_PATH: ''
  HEAD_LR_MULTIPLIER: 1.0
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.10
  TIR_LOCAL_WEIGHT: 0.03
  TIR_LOCAL_KEEP_RATIO: 0.50
  FEATURE_PRESERVE_WEIGHT: 0.05
  SCENARIO_HARD_GPD: False
  SCENARIO_HARD_WEIGHT: 0.15
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_BANK_MOMENTUM: 0.20
  FINAL_FLIP_TTA: False
  TTA_METRICS_FILENAME: 'tta_metrics.csv'
  RESUME_PATH: ''
  SAVE_LAST_EVERY: 5
  SAVE_BEST: True
  METRICS_FILENAME: 'metrics_history.csv'
  RUN_MANIFEST: ''
  SESSION_DEADLINE_UNIX: 0.0
  STOP_RESERVE_MINUTES: 10.0
  CHECKPOINT_EVERY_MINUTES: 30.0
  TIME_CHECK_EVERY_STEPS: 10
  MIN_EVAL_REMAINING_MINUTES: 35.0
  STATUS_FILENAME: 'session_status.json'
  STRICT_RESUME_CONFIG: True

OUTPUT_DIR: './logs/PVUAD'

2026-09-14 08:45:36,966 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB',)
  NAMES: AG-ReID.v2
  ROOT_DIR: /kaggle/working/pvuad_agreid_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: False
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.0
  FINAL_FLIP_TTA: True
  FINETUNE: False
  GROUND_MAX_CAMID: 1
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 1.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 35.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST:
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 0.0
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 10.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: False
  TEACHER_MODEL_PATH:
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.1
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.03
  TTA_METRICS_FILENAME: tta_best_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH:
  WARMSTART_PROTOTYPE_PATH:
SOLVER:
  BASE_LR: 0.008
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT: /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/pvuad_best_model.pth
=> AG-ReID.v2 loaded (aerial -> ground)
   train: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/train_all
   query: /kaggle/working/pvuad_agreid_data/AG-ReID.v2/query
   gallery: ['/kaggle/working/pvuad_agreid_data/AG-ReID.v2/gallery']
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   807 |    51530 |         3
  query    |   808 |     4348 |         1
  gallery  |   808 |    19259 |         2
  ----------------------------------------
ViewBalancedPKM: 807 IDs (807 dual-view, 0 single-view), 75,584 sample slots/epoch, 16 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
Loading pretrained model from /kaggle/working/pvuad_runs/agreidv2_a2g_e2_60_e3_25_transreid768_b24_v5_manifestfix/e3_tdh/pvuad_best_model.pth (loaded=170, skipped=3)
2026-09-14 08:49:36,627 transreid.test INFO: Enter inferencing
2026-09-14 08:51:20,157 transreid.test INFO: => Split mode 1: query 4348, total query 4348
2026-09-14 08:51:20,192 transreid.test INFO: The test feature is normalized
2026-09-14 08:51:20,229 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-14 08:51:28,010 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1)], Gallery mods: [np.int64(1)]
2026-09-14 08:51:35,641 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 73.64%, Rank-1: 84.61%
2026-09-14 08:51:35,739 transreid.test INFO: Validation Results
2026-09-14 08:51:35,739 transreid.test INFO: mAP: 73.64%
2026-09-14 08:51:35,739 transreid.test INFO: CMC curve, Rank-1  :84.61%
2026-09-14 08:51:35,739 transreid.test INFO: CMC curve, Rank-5  :89.86%
2026-09-14 08:51:35,740 transreid.test INFO: CMC curve, Rank-10 :91.95%
2026-09-14 08:51:35,740 transreid.test INFO: Running horizontal-flip feature averaging
2026-09-14 08:55:08,101 transreid.test INFO: => Split mode 1: query 4348, total query 4348
2026-09-14 08:55:08,132 transreid.test INFO: The test feature is normalized
2026-09-14 08:55:08,163 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-14 08:55:15,853 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1)], Gallery mods: [np.int64(1)]
2026-09-14 08:55:23,501 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 73.79%, Rank-1: 84.50%
2026-09-14 08:55:23,599 transreid.test INFO: Flip-TTA mAP: 73.79%
2026-09-14 08:55:23,599 transreid.test INFO: Flip-TTA CMC, Rank-1  :84.50%
2026-09-14 08:55:23,599 transreid.test INFO: Flip-TTA CMC, Rank-5  :89.86%
2026-09-14 08:55:23,599 transreid.test INFO: Flip-TTA CMC, Rank-10 :92.04%
best_epoch == final epoch == 25; best and last checkpoint are the same training state. Copied TTA metrics instead of repeating inference.

## 6. Tổng hợp kết quả

Report cuối chứa:

- E2 best và E2 epoch 60;
- E3 best raw và E3 epoch 25 raw;
- E3 best + flip-TTA;
- E3 epoch 25 + flip-TTA;
- dataset/layout audit;
- `checkpoint_relation.json` để xác nhận best epoch có bằng last epoch không.

File report:
`/kaggle/working/pvuad_agreidv2_a2g_e2_60_e3_25_transreid_reports.zip`

In [7]:
def metrics_history_row(run_dir, epoch=None, best=False):
    path = Path(run_dir) / "metrics_history.csv"
    if not path.is_file():
        return None
    frame = pd.read_csv(path)
    required = {"experiment", "stage", "epoch", "mAP", "Rank-1", "Rank-5", "Rank-10"}
    if frame.empty or not required.issubset(frame.columns):
        return None
    frame = frame.drop_duplicates(
        subset=["experiment", "stage", "epoch"], keep="last"
    ).sort_values("epoch")
    frame.to_csv(path, index=False)
    if best:
        row = frame.loc[frame["mAP"].idxmax()]
    elif epoch is not None:
        matched = frame.loc[frame["epoch"].astype(int) == int(epoch)]
        if matched.empty:
            return None
        row = matched.iloc[-1]
    else:
        row = frame.iloc[-1]
    return {
        "epoch": int(row["epoch"]),
        "mAP": float(row["mAP"]),
        "Rank-1": float(row["Rank-1"]),
        "Rank-5": float(row["Rank-5"]),
        "Rank-10": float(row["Rank-10"]),
    }

def tta_metrics(path, label, epoch_label):
    path = Path(path)
    if not path.is_file():
        return None
    frame = pd.read_csv(path)
    if frame.empty:
        return None
    row = frame.iloc[-1]
    return {
        "method": label,
        "epoch": epoch_label,
        "mAP": float(row["mAP"]),
        "Rank-1": float(row["Rank-1"]),
        "Rank-5": float(row["Rank-5"]),
        "Rank-10": float(row["Rank-10"]),
    }

state = read_json(PIPELINE_STATE_PATH)
print("Pipeline status:", state.get("status"))
print("Active stage   :", state.get("active_stage"))
print("Next action    :", state.get("next_action"))
print("Dataset        :", DATASET_AUDIT)

init_audit_path = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if init_audit_path.is_file():
    print("TransReID initialization audit:")
    display(pd.DataFrame([read_json(init_audit_path)]))

comparison = []

e2_best = metrics_history_row(E2_RUN_DIR, best=True)
e2_last = metrics_history_row(E2_RUN_DIR, epoch=E2_EPOCHS)
if e2_best:
    comparison.append({
        "method": "E2 best checkpoint (diagnostic)",
        **e2_best,
    })
if e2_last:
    comparison.append({
        "method": f"E2 fixed final epoch {E2_EPOCHS}",
        **e2_last,
    })

e3_best = metrics_history_row(E3_RUN_DIR, best=True)
e3_last = metrics_history_row(E3_RUN_DIR, epoch=E3_EPOCHS)
if e3_best:
    comparison.append({
        "method": "E3 best checkpoint (no TTA)",
        **e3_best,
    })
if e3_last:
    comparison.append({
        "method": f"E3 fixed final epoch {E3_EPOCHS} (no TTA)",
        **e3_last,
    })

best_tta = tta_metrics(
    E3_RUN_DIR / "tta_best_metrics.csv",
    "E3 best checkpoint + horizontal-flip TTA",
    e3_best["epoch"] if e3_best else "best",
)
last_tta = tta_metrics(
    E3_RUN_DIR / "tta_last_metrics.csv",
    f"E3 fixed final epoch {E3_EPOCHS} + horizontal-flip TTA",
    E3_EPOCHS,
)
if best_tta:
    comparison.append(best_tta)
if last_tta:
    comparison.append(last_tta)

comparison_frame = pd.DataFrame(comparison)
comparison_frame.to_csv(
    PIPELINE_ROOT / "combined_results.csv", index=False
)
if not comparison_frame.empty:
    display(comparison_frame.round(4))

best_epoch = int(e3_best["epoch"]) if e3_best else None
best_equals_last = bool(best_epoch == E3_EPOCHS) if best_epoch is not None else None
checkpoint_relation = {
    "E2_fixed_horizon": E2_EPOCHS,
    "E3_fixed_horizon": E3_EPOCHS,
    "E3_best_epoch": best_epoch,
    "E3_best_epoch_equals_last_epoch": best_equals_last,
    "primary_protocol": "AG-ReID.v2 aerial_to_ground",
    "note": (
        "E3 is warm-started from the final E2 epoch-60 model and the same "
        "epoch-60 prototype checkpoint. Both best-E3 and fixed epoch-25 "
        "flip-TTA metrics are reported so best-vs-last is empirical, not assumed."
    ),
}
(PIPELINE_ROOT / "checkpoint_relation.json").write_text(
    json.dumps(checkpoint_relation, indent=2), encoding="utf-8"
)
print("Checkpoint relation:", checkpoint_relation)

REPORT_ZIP = (
    Path("/kaggle/working")
    / "pvuad_agreidv2_a2g_e2_60_e3_25_transreid_reports.zip"
)
if REPORT_ZIP.exists():
    REPORT_ZIP.unlink()

report_suffixes = {".csv", ".json", ".txt", ".log", ".yml", ".yaml"}
with zipfile.ZipFile(
    REPORT_ZIP, "w", compression=zipfile.ZIP_DEFLATED
) as archive:
    for path in sorted(PIPELINE_ROOT.rglob("*")):
        if path.is_file() and path.suffix.lower() in report_suffixes:
            archive.write(
                path,
                arcname=str(path.relative_to(PIPELINE_ROOT)),
            )
    dataset_audit_path = Path("/kaggle/working/agreid_v2_dataset_audit.json")
    if dataset_audit_path.is_file():
        archive.write(dataset_audit_path, arcname="agreid_v2_dataset_audit.json")
    patch_manifest = UAD_DIR / "PVUAD_patch_manifest.json"
    if patch_manifest.is_file():
        archive.write(patch_manifest, arcname="PVUAD_patch_manifest.json")

print("Report zip:", REPORT_ZIP)

Pipeline status: completed
Active stage   : DONE
Next action    : None
Dataset        : {'dataset': 'AG-ReID.v2', 'protocol': 'aerial_to_ground', 'root': '/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2', 'train_dir': '/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/train_all', 'query_dir': '/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/query', 'gallery_dirs': ['/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2/gallery'], 'train_images': 51530, 'train_ids': 807, 'query_images': 4348, 'query_ids': 808, 'gallery_images': 19259, 'gallery_ids': 808, 'camera_remap': {'C2_ground': 0, 'C3_ground': 1, 'C0_aerial': 2}, 'recursive_split_scan': True}
TransReID initialization audit:

,checkpoint,loaded_tensor_count,target_tensor_count,mismatch_count,resized_pos_embed,source_sie_loaded,source_jpm_local_branches_loaded,global_jpm_branch_used_for_target_final_block,global_branch_mapped_tensor_count,embedding_dim,...,batchnorm_train_mode_checked,init_qkv_max_abs,global_final_qkv_max_abs,qkv_grad_norm,patch_grad_norm,backbone_all_trainable,source_sie_used,source_jpm_local_branches_used,source_jpm_global_final_branch_used,target_stride
0,/kaggle/working/vit_transreid_msmt.pth,152,152,0,"{'source_shape': [1, 211, 768], 'target_shape'...",False,False,True,14,768,...,True,0.0,0.0,0.006533,0.032783,True,False,False,True,"[16, 16]"

,method,epoch,mAP,Rank-1,Rank-5,Rank-10
0,E2 best checkpoint (diagnostic),60,72.6778,84.3376,87.9715,89.6734
1,E2 fixed final epoch 60,60,72.6778,84.3376,87.9715,89.6734
2,E3 best checkpoint (no TTA),25,73.3549,84.6136,88.2475,89.8574
3,E3 fixed final epoch 25 (no TTA),25,73.3549,84.6136,88.2475,89.8574
4,E3 best checkpoint + horizontal-flip TTA,25,73.7924,84.4986,89.8574,92.0423
5,E3 fixed final epoch 25 + horizontal-flip TTA,25,73.7924,84.4986,89.8574,92.0423

Checkpoint relation: {'E2_fixed_horizon': 60, 'E3_fixed_horizon': 25, 'E3_best_epoch': 25, 'E3_best_epoch_equals_last_epoch': True, 'primary_protocol': 'AG-ReID.v2 aerial_to_ground', 'note': 'E3 is warm-started from the final E2 epoch-60 model and the same epoch-60 prototype checkpoint. Both best-E3 and fixed epoch-25 flip-TTA metrics are reported so best-vs-last is empirical, not assumed.'}
Report zip: /kaggle/working/pvuad_agreidv2_a2g_e2_60_e3_25_transreid_reports.zip

## Cách chạy trên Kaggle

1. Chọn **GPU T4 ×2**.
2. Attach dataset:
   `/kaggle/input/datasets/thienbao1604/ag-reid-v2/AG-ReID.v2/AG-ReID.v2.`
3. Phiên đầu: bật Internet để tải official `vit_transreid_msmt.pth`,
   hoặc attach checkpoint đó làm Kaggle Input.
4. Chọn **Save Version → Save & Run All**.
5. Nếu notebook dừng an toàn vì giới hạn phiên, ở phiên sau attach **output của
   chính version ngay trước đó** làm Input rồi chạy lại **Save & Run All**.
6. E2 hoàn tất ở epoch 60 thì notebook chủ động kết thúc version; phiên sau mới
   bắt đầu E3.
7. Sau E3 epoch 25, notebook chạy flip-TTA. Nếu best epoch = 25 thì best/last là
   cùng training state và metrics được reuse; nếu best epoch khác 25, notebook
   evaluate cả hai checkpoint.
8. Khi xong gửi lại:
   `pvuad_agreidv2_a2g_e2_60_e3_25_transreid_reports.zip`
   để mình đọc kết quả và so với các baseline AG-ReID.v2.