# PV-UAD → LAGPeR-S3CLIP — E2=60 → E3=25, LAST-only, A→G / G→A / G→A+G

Notebook này chuyển **đúng pipeline TransReID-init → E2 → E3** đã dùng cho WHU/AG-ReID.v2 sang **LAGPeR-S3CLIP** (RGB-only).

**Policy để report paper:**
- E2 train cố định **60 epoch**; E3 nhận **`pvuad_last_model.pth` + prototype bank từ `pvuad_last_checkpoint.pth` của E2**.
- E3 train cố định **25 epoch**; final evaluation chỉ dùng **`pvuad_last_model.pth` của E3**.
- Intermediate checkpoint không dùng để chọn model. `EVAL_PERIOD` được đặt bằng đúng horizon (60/25), nên mỗi stage chỉ evaluate ở epoch cuối.
- Final Flip-TTA chạy trên **3 protocol LAGPeR**: A→G, G→A, G→A+G.
- Re-ranking OFF.

Notebook giữ các fix RGB/DDP đã cần cho AG-ReID.v2: single-modality view-balanced PKM sampler, trainable TransReID ViT-Base 768-D stride 16×16, ProCA/GPD/E3 refinement, và DDP single-loader evaluation không gây NCCL watchdog.

### Dataset layout
Notebook tự tìm root chứa:
`bounding_box_train`, `query_aerial`, `query_ground`, `bounding_box_test_aerial`,
`bounding_box_test_ground`, `bounding_box_gallery`.

Nó audit chặt split LAGPeR trước khi train để tránh chạy nhiều giờ trên split sai. Với bản chuẩn, kỳ vọng:
train 40,770 ảnh / 2,708 IDs; A→G query 3,046 và gallery 15,533;
G→A query 3,046 và gallery 7,717; G→A+G gallery 20,204.

> LAGPeR-S3CLIP chỉ thay ảnh bằng bản đã làm nét; filename/split phải được giữ nguyên để so sánh benchmark hợp lệ.

In [1]:
# ============================================================
# 0. SETTINGS — LAGPeR-S3CLIP, multi-session, LAST-only
# ============================================================

import time as _time
NOTEBOOK_SESSION_STARTED_UNIX = _time.time()

PIPELINE_NAME = "PVUAD_LAGPER_S3CLIP_E2_E3_TRANSREID_LAST_ONLY"
PIPELINE_TAG = "lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix"

# Optional hint only. Automatic discovery under /kaggle/input is authoritative.
LAGPER_S3CLIP_INPUT = "/kaggle/input/datasets/cpkimhianh/lagper-s3clip"

# If automatic camera-view inference fails, set ALL raw aerial camera IDs here,
# e.g. [3, 6, ...]. Normally leave None.
AERIAL_CAMERA_IDS_OVERRIDE = None

SOURCE_DIR_OVERRIDE = None

# Official MSMT17 TransReID checkpoint used by the WHU winner.
TRANSREID_CHECKPOINT_OVERRIDE = None
PRETRAIN_PATH_OVERRIDE = None
RUN_TRANSREID_INIT_SMOKE_TEST = True

TRANSREID_TARGET_STRIDE = [16, 16]
TRANSREID_TARGET_EMBED_DIM = 768
USE_SOURCE_SIE = False
USE_SOURCE_JPM_LOCAL_BRANCHES = False

# Emergency / multi-session resume overrides. Normally leave None.
E2_RESUME_PATH_OVERRIDE = None
E2_COMPLETED_DIR_OVERRIDE = None
E3_RESUME_PATH_OVERRIDE = None

AUTO_RESUME = True
ALLOW_LEGACY_E2_BOOTSTRAP = False
RUN_TRAINING = True
RUN_FINAL_FLIP_TTA = True
RUN_METADATA_PAIRING_CHECK = True

# Finish E2, save the Kaggle version, then begin E3 in a fresh session.
ALWAYS_START_E3_IN_NEW_SESSION = True

# Fixed paper horizons.
E2_EPOCHS = 60
E2_GLOBAL_BATCH = 24
E2_BASE_LR = 0.008

E3_EPOCHS = 25
E3_GLOBAL_BATCH = 24
E3_BASE_LR = 1e-4
E3_HEAD_LR_MULTIPLIER = 5.0

FEATURE_PRESERVE_WEIGHT = 0.05
SCENARIO_HARD_WEIGHT = 0.15
SCENARIO_HARD_TOPK = 5
SCENARIO_HARD_MARGIN = 0.05
SCENARIO_HARD_TAU = 0.05
SCENARIO_HARD_START_EPOCH = 3

# LAGPeR has 14 ground + 7 aerial cameras across all seven scenes.
# Cell 2 verifies the inferred mapping and keeps all ground remapped IDs first.
GROUND_MAX_CAMID = 13

SESSION_HARD_STOP_HOURS = 10.5
SESSION_STOP_RESERVE_MINUTES = 15
CHECKPOINT_EVERY_MINUTES = 30
TIME_CHECK_EVERY_STEPS = 10
MIN_EVAL_REMAINING_MINUTES = 25
MIN_E3_START_REMAINING_MINUTES = 75
MIN_TTA_START_REMAINING_MINUTES = 25

NUM_GPUS = 2
NUM_WORKERS = 4
RANDOM_SEED = 1234

FINAL_PROTOCOLS = ("A2G", "G2A", "G2AG")

if E2_GLOBAL_BATCH != 24 or abs(E2_BASE_LR - 0.008) > 1e-12:
    raise ValueError("E2 must stay at global batch 24 / LR 0.008.")
if E3_GLOBAL_BATCH != 24 or abs(E3_BASE_LR - 1e-4) > 1e-12:
    raise ValueError("E3 must stay at global batch 24 / LR 1e-4.")
if TRANSREID_TARGET_STRIDE != [16, 16] or TRANSREID_TARGET_EMBED_DIM != 768:
    raise ValueError("Keep the winning UAD ViT at stride [16,16], 768-D.")
if USE_SOURCE_SIE or USE_SOURCE_JPM_LOCAL_BRANCHES:
    raise ValueError("Source SIE/JPM local branches must remain disabled.")

SESSION_DEADLINE_UNIX = NOTEBOOK_SESSION_STARTED_UNIX + 3600.0 * SESSION_HARD_STOP_HOURS

print(PIPELINE_NAME, {
    "dataset": "LAGPeR-S3CLIP",
    "E2_epochs": E2_EPOCHS,
    "E3_epochs": E3_EPOCHS,
    "checkpoint_policy": "LAST E2 -> LAST E3 -> final tests",
    "protocols": FINAL_PROTOCOLS,
    "init": "MSMT17 TransReID -> trainable UAD ViT",
    "TIR_distillation": False,
})

PVUAD_LAGPER_S3CLIP_E2_E3_TRANSREID_LAST_ONLY {'dataset': 'LAGPeR-S3CLIP', 'E2_epochs': 60, 'E3_epochs': 25, 'checkpoint_policy': 'LAST E2 -> LAST E3 -> final tests', 'protocols': ('A2G', 'G2A', 'G2AG'), 'init': 'MSMT17 TransReID -> trainable UAD ViT', 'TIR_distillation': False}

## 1. Kiểm tra môi trường

In [2]:
import base64
import csv
import hashlib
import importlib.util
import io
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import tarfile
import urllib.request
import zipfile
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
import torch

if not torch.cuda.is_available():
    raise RuntimeError("Enable a Kaggle GPU accelerator and restart the session.")
if torch.cuda.device_count() < NUM_GPUS:
    raise RuntimeError(
        f"This run expects {NUM_GPUS} GPUs, but Kaggle exposes {torch.cuda.device_count()}. "
        "Choose GPU T4 x2 in Notebook options."
    )

for package, pip_name in [("yacs", "yacs==0.1.8"), ("timm", "timm>=0.9,<2"), ("gdown", "gdown>=5,<6")]:
    if importlib.util.find_spec(package) is None:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-q", pip_name],
            check=True,
        )

gpu_rows = []
for index in range(NUM_GPUS):
    props = torch.cuda.get_device_properties(index)
    gpu_rows.append({
        "index": index,
        "name": props.name,
        "memory_GiB": round(props.total_memory / 2**30, 2),
    })
display(pd.DataFrame(gpu_rows))
print("Python:", sys.version.split()[0])
print("PyTorch:", torch.__version__)
print("CUDA runtime:", torch.version.cuda)

   index      name  memory_GiB
0      0  Tesla T4       14.56
1      1  Tesla T4       14.56

Python: 3.12.13
PyTorch: 2.10.0+cu128
CUDA runtime: 12.8

## 2. Khóa LAGPeR-S3CLIP + audit split/camera trước khi train

Notebook chỉ chấp nhận root có đủ 6 folder trong ảnh bạn gửi. Nó đọc filename dạng `PID_Cxx_FRAME...`,
kiểm tra số ảnh/ID/camera theo benchmark, suy ra camera aerial/ground, rồi tạo camera remap:
**ground → 0..13, aerial → 14..20** để ProCA/view-balanced sampler dùng đúng view.

**Folder compatibility fix:** accepts both `bounding_box_*` and `bouding_box_*` spellings, then normalizes them to canonical loader paths.

**v3 noise-gallery fix:** this LAGPeR copy stores the 179 `PID=-1` distractors separately in `bounding_box_gallery`. The notebook now reconstructs the published A→G / G→A / G→A+G gallery sizes instead of incorrectly expecting 7,717 / 15,533 / 20,204 images inside the physical folders themselves.

**v4 camera-map fix:** raw camera numbering has a gap at C10, so a global `camera_id % 3` rule is wrong. Training cameras are grouped by their four actual 3-camera scenes; the highest camera ID in each scene is aerial. This yields train aerial cameras `C3, C6, C9, C13` and test aerial cameras `C16, C19, C22`, which correctly reconstructs the 45 aerial + 134 ground distractors.

In [3]:
# ============================================================
# 2. Resolve + audit LAGPeR-S3CLIP
# ============================================================

# Canonical split names used by the pipeline. Some public/Kaggle copies of
# LAGPeR contain the historical typo "bouding_box_*" (missing "n").
# We accept both spellings, then create canonical symlinks for the loader.
SPLIT_ALIASES = {
    "bounding_box_train": (
        "bounding_box_train",
        "bouding_box_train",
    ),
    "query_aerial": (
        "query_aerial",
    ),
    "query_ground": (
        "query_ground",
    ),
    "bounding_box_test_aerial": (
        "bounding_box_test_aerial",
        "bouding_box_test_aerial",
    ),
    "bounding_box_test_ground": (
        "bounding_box_test_ground",
        "bouding_box_test_ground",
    ),
    "bounding_box_gallery": (
        "bounding_box_gallery",
        "bouding_box_gallery",
    ),
}
IMAGE_SPLITS = {
    alias.lower()
    for aliases in SPLIT_ALIASES.values()
    for alias in aliases
}
IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
LAGPER_FILENAME_RE = re.compile(
    r"(?P<pid>-?\d+)_C(?P<camid>\d+)_(?P<frameid>\d+)",
    re.IGNORECASE,
)

# IMPORTANT: the released/Kaggle LAGPeR layout stores the 179 PID=-1
# distractor images separately in bounding_box_gallery. Therefore the two
# positive test folders are smaller than the published protocol galleries.
#
# Physical folders in this copy:
#   aerial positives  = 7,672
#   ground positives  = 15,399
#   noise/distractors = 179
#
# Published protocol galleries are reconstructed below after camera-view
# inference:
#   G->A   = 7,672 + 45 aerial noise  = 7,717
#   A->G   = 15,399 + 134 ground noise = 15,533
#   G->A+G = aerial positives + ground positives excluding the 3,046
#            ground queries + all 179 noise = 20,204
EXPECTED = {
    "bounding_box_train": {
        "images": 40770, "ids": 2708, "cams": 12, "noise": 0,
    },
    "query_aerial": {
        "images": 3046, "ids": 1523, "cams": 3, "noise": 0,
    },
    "query_ground": {
        "images": 3046, "ids": 1523, "cams": 6, "noise": 0,
    },
    "bounding_box_test_aerial": {
        "images": 7672, "ids": 1523, "cams": 3, "noise": 0,
    },
    "bounding_box_test_ground": {
        "images": 15399, "ids": 1523, "cams": 6, "noise": 0,
    },
    "bounding_box_gallery": {
        "images": 179, "ids": 0, "cams": None, "noise": 179,
    },
}
PUBLISHED_PROTOCOL_COUNTS = {
    "A2G": {"query": 3046, "gallery": 15533},
    "G2A": {"query": 3046, "gallery": 7717},
    "G2AG": {"query": 3046, "gallery": 20204},
}
REQUIRED_DIRS = tuple(EXPECTED)

def image_files(path):
    path = Path(path)
    if not path.is_dir():
        return []
    values = []
    for root, _dirs, files in os.walk(path):
        root = Path(root)
        for name in files:
            p = root / name
            if p.suffix.lower() in IMAGE_EXTS:
                values.append(p)
    return sorted(values)

def parse_lagper_filename(path):
    match = LAGPER_FILENAME_RE.search(Path(path).name)
    if match is None:
        raise ValueError(
            f"Unexpected LAGPeR filename: {Path(path).name}. "
            "Expected PID_Cxx_FRAME... format."
        )
    return (
        int(match.group("pid")),
        int(match.group("camid")),
        int(match.group("frameid")),
    )

def split_frame(directory):
    rows = []
    bad = []
    for path in image_files(directory):
        try:
            pid, camid, frameid = parse_lagper_filename(path)
            rows.append((path, pid, camid, frameid))
        except Exception as exc:
            bad.append((str(path), str(exc)))
            if len(bad) >= 20:
                break
    if bad:
        display(pd.DataFrame(bad, columns=["path", "error"]))
        raise RuntimeError(
            "LAGPeR filename parsing failed. S3CLIP must preserve the original "
            "LAGPeR filenames."
        )
    return pd.DataFrame(rows, columns=["path", "pid", "camera_original", "frameid"])

def resolve_split_path(root, canonical_name):
    root = Path(root)
    for alias in SPLIT_ALIASES[canonical_name]:
        candidate = root / alias
        if candidate.is_dir():
            return candidate
    return None

def is_lagper_root(root):
    root = Path(root)
    return (
        root.is_dir()
        and all(resolve_split_path(root, name) is not None for name in REQUIRED_DIRS)
    )

def discover_lagper_roots():
    roots = []
    def add(path):
        path = Path(path)
        if is_lagper_root(path) and path not in roots:
            roots.append(path)

    add(LAGPER_S3CLIP_INPUT)

    base = Path("/kaggle/input")
    if base.is_dir():
        for root, dirs, _files in os.walk(base):
            root = Path(root)
            lower = {d.lower(): d for d in dirs}
            if all(
                any(alias.lower() in lower for alias in SPLIT_ALIASES[name])
                for name in REQUIRED_DIRS
            ):
                add(root)
                dirs[:] = []
                continue
            # Never recurse through image folders.
            dirs[:] = [d for d in dirs if d.lower() not in IMAGE_SPLITS]
            try:
                depth = len(root.relative_to(base).parts)
            except ValueError:
                depth = 99
            if depth >= 7:
                dirs[:] = []
    return roots

roots = discover_lagper_roots()
if not roots:
    preview = []
    for root, dirs, files in os.walk("/kaggle/input"):
        root = Path(root)
        try:
            depth = len(root.relative_to("/kaggle/input").parts)
        except Exception:
            depth = 99
        if depth <= 4 and any(
            key in {d.lower() for d in dirs}
            for key in (
                "bounding_box_train", "bouding_box_train",
                "query_aerial", "query_ground",
            )
        ):
            preview.append({
                "path": str(root),
                "dirs": sorted(dirs)[:30],
                "images_here": sum(Path(n).suffix.lower() in IMAGE_EXTS for n in files),
            })
        dirs[:] = [d for d in dirs if d.lower() not in IMAGE_SPLITS]
        if depth >= 4:
            dirs[:] = []
    if preview:
        display(pd.DataFrame(preview))
    raise FileNotFoundError(
        "Cannot find LAGPeR-S3CLIP under /kaggle/input. Attach the Kaggle dataset "
        "that contains bounding_box_train/query_aerial/query_ground/"
        "bounding_box_test_aerial/bounding_box_test_ground/bounding_box_gallery."
    )

hint = Path(LAGPER_S3CLIP_INPUT)
roots.sort(
    key=lambda p: (
        int(p == hint),
        int("s3clip" in str(p).lower()),
        int("lagper" in str(p).lower()),
        -len(p.parts),
        str(p),
    ),
    reverse=True,
)
DATA_ROOT = roots[0]
print("Resolved LAGPeR-S3CLIP root:", DATA_ROOT)

SPLIT_PATHS = {
    split: resolve_split_path(DATA_ROOT, split)
    for split in REQUIRED_DIRS
}
missing_split_paths = [
    split for split, path in SPLIT_PATHS.items() if path is None
]
if missing_split_paths:
    raise RuntimeError(
        f"Resolved root but missing split aliases: {missing_split_paths}"
    )

print("Resolved split folders:")
display(pd.DataFrame([
    {
        "canonical_split": split,
        "actual_folder": path.name,
        "actual_path": str(path),
    }
    for split, path in SPLIT_PATHS.items()
]))

frames = {}
audit_rows = []
for split in REQUIRED_DIRS:
    frame = split_frame(SPLIT_PATHS[split])
    frames[split] = frame
    non_noise = frame.loc[frame["pid"] >= 0]
    row = {
        "split": split,
        "images": int(len(frame)),
        "ids_non_noise": int(non_noise["pid"].nunique()),
        "noise_images": int((frame["pid"] < 0).sum()),
        "cameras": sorted(frame["camera_original"].unique().tolist()),
        "camera_count": int(frame["camera_original"].nunique()),
    }
    audit_rows.append(row)

audit = pd.DataFrame(audit_rows)
display(audit)

# Strict logical split lock: sharpened images must preserve benchmark membership.
for row in audit_rows:
    split = row["split"]
    expected = EXPECTED[split]
    if row["images"] != expected["images"]:
        raise RuntimeError(
            f"{split}: expected {expected['images']} images, got {row['images']}. "
            "Do not train until the S3CLIP copy is confirmed to preserve LAGPeR splits."
        )
    if expected["ids"] is not None and row["ids_non_noise"] != expected["ids"]:
        raise RuntimeError(
            f"{split}: expected {expected['ids']} non-noise IDs, got {row['ids_non_noise']}."
        )
    if row["noise_images"] != expected["noise"]:
        raise RuntimeError(
            f"{split}: expected {expected['noise']} PID=-1 noise images, "
            f"got {row['noise_images']}."
        )
    if expected["cams"] is not None and row["camera_count"] != expected["cams"]:
        raise RuntimeError(
            f"{split}: expected {expected['cams']} cameras, got {row['camera_count']} "
            f"({row['cameras']})."
        )

train_frame = frames["bounding_box_train"].copy()
query_aerial_frame = frames["query_aerial"].copy()
query_ground_frame = frames["query_ground"].copy()
gallery_aerial_frame = frames["bounding_box_test_aerial"].copy()
gallery_ground_frame = frames["bounding_box_test_ground"].copy()
noise_gallery_frame = frames["bounding_box_gallery"].copy()
if not (noise_gallery_frame["pid"] < 0).all():
    raise RuntimeError(
        "bounding_box_gallery is expected to contain only PID=-1 distractors "
        "in this LAGPeR release."
    )

train_ids = set(train_frame.loc[train_frame.pid >= 0, "pid"])
qa_ids = set(query_aerial_frame.loc[query_aerial_frame.pid >= 0, "pid"])
qg_ids = set(query_ground_frame.loc[query_ground_frame.pid >= 0, "pid"])
if len(train_ids) != 2708 or len(qa_ids) != 1523 or len(qg_ids) != 1523:
    raise RuntimeError("Unexpected LAGPeR ID split after filename parsing.")
if qa_ids != qg_ids:
    raise RuntimeError("query_aerial and query_ground do not contain the same 1,523 test IDs.")
overlap = sorted(train_ids & qa_ids)
if overlap:
    raise RuntimeError(
        f"Train/test identities overlap ({len(overlap)} IDs, e.g. {overlap[:20]}). "
        "This usually means the filename parser or dataset split is wrong."
    )

def require_query_coverage(query_frame, gallery_frame, protocol):
    qids = set(query_frame.loc[query_frame.pid >= 0, "pid"])
    gids = set(gallery_frame.loc[gallery_frame.pid >= 0, "pid"])
    missing = sorted(qids - gids)
    if missing:
        raise RuntimeError(
            f"{protocol}: {len(missing)} query identities have no gallery positive: {missing[:20]}"
        )

# Positive-only folders must already cover every query identity. The PID=-1
# distractors are added to protocol galleries only after camera-view inference.
require_query_coverage(query_aerial_frame, gallery_ground_frame, "A2G positives")
require_query_coverage(query_ground_frame, gallery_aerial_frame, "G2A positives")

# ---------------- camera-view inference ----------------
test_aerial_cams = set(query_aerial_frame.camera_original) | set(gallery_aerial_frame.camera_original)
test_ground_cams = set(query_ground_frame.camera_original) | set(gallery_ground_frame.camera_original)
if len(test_aerial_cams) != 3 or len(test_ground_cams) != 6 or test_aerial_cams & test_ground_cams:
    raise RuntimeError(
        f"Unexpected test camera split: aerial={sorted(test_aerial_cams)}, "
        f"ground={sorted(test_ground_cams)}"
    )

all_cams = set()
for frame in frames.values():
    all_cams.update(map(int, frame.camera_original.unique()))
if len(all_cams) != 21:
    raise RuntimeError(f"Expected 21 total LAGPeR cameras, got {len(all_cams)}: {sorted(all_cams)}")

train_cams = set(map(int, train_frame.camera_original.unique()))

if AERIAL_CAMERA_IDS_OVERRIDE is not None:
    aerial_cams = set(map(int, AERIAL_CAMERA_IDS_OVERRIDE))
else:
    # LAGPeR uses 3 cameras per scene: two ground cameras followed by one
    # aerial camera. Camera numbering is NOT globally modulo-3 because raw
    # camera C10 is absent in this release. Therefore the old `cam % 3`
    # heuristic misclassified C1/C4/C7 as aerial and C3/C6/C9 as ground.
    #
    # Infer the four training scenes from their 12 raw camera IDs, grouped as
    # four consecutive 3-camera scene blocks. The aerial camera is the highest
    # ID in each block, exactly as confirmed by the held-out scenes:
    #   test ground  = {14,15,17,18,20,21}
    #   test aerial  = {16,19,22}
    train_sorted = sorted(train_cams)
    if len(train_sorted) != 12:
        raise RuntimeError(
            f"Expected 12 training cameras, got {len(train_sorted)}: {train_sorted}"
        )

    train_scene_groups = [
        train_sorted[i:i + 3]
        for i in range(0, len(train_sorted), 3)
    ]
    if len(train_scene_groups) != 4 or any(len(group) != 3 for group in train_scene_groups):
        raise RuntimeError(
            f"Cannot partition training cameras into four 3-camera scenes: "
            f"{train_scene_groups}"
        )
    bad_groups = [
        group for group in train_scene_groups
        if not (group[1] == group[0] + 1 and group[2] == group[1] + 1)
    ]
    if bad_groups:
        raise RuntimeError(
            "Unexpected LAGPeR training-camera scene grouping. "
            f"Expected consecutive triples, got {train_scene_groups}. "
            "Set AERIAL_CAMERA_IDS_OVERRIDE explicitly if needed."
        )

    train_aerial_inferred = {group[-1] for group in train_scene_groups}

    # Independently validate the three held-out scenes from the supplied
    # query/test folders rather than guessing their view from camera numbers.
    test_sorted = sorted(test_aerial_cams | test_ground_cams)
    test_scene_groups = [
        test_sorted[i:i + 3]
        for i in range(0, len(test_sorted), 3)
    ]
    if (
        len(test_scene_groups) != 3
        or any(len(group) != 3 for group in test_scene_groups)
        or any(
            not (group[1] == group[0] + 1 and group[2] == group[1] + 1)
            for group in test_scene_groups
        )
        or {group[-1] for group in test_scene_groups} != test_aerial_cams
    ):
        raise RuntimeError(
            "Held-out LAGPeR camera grouping is inconsistent with "
            f"query_aerial/query_ground. groups={test_scene_groups}, "
            f"aerial={sorted(test_aerial_cams)}, ground={sorted(test_ground_cams)}"
        )

    aerial_cams = train_aerial_inferred | test_aerial_cams

ground_cams = all_cams - aerial_cams
train_aerial_cams = train_cams & aerial_cams
train_ground_cams = train_cams & ground_cams

if (
    len(aerial_cams) != 7
    or len(ground_cams) != 14
    or len(train_aerial_cams) != 4
    or len(train_ground_cams) != 8
    or test_aerial_cams != (aerial_cams - train_aerial_cams)
    or not test_ground_cams.issubset(ground_cams)
    or train_aerial_cams != {3, 6, 9, 13}
    or test_aerial_cams != {16, 19, 22}
):
    raise RuntimeError(
        "Camera-view inference does not match the published 7 aerial / 14 ground "
        "and train 4 aerial / 8 ground setup.\n"
        f"all aerial={sorted(aerial_cams)}\n"
        f"train aerial={sorted(train_aerial_cams)}\n"
        f"train ground={sorted(train_ground_cams)}\n"
        f"test aerial={sorted(test_aerial_cams)}\n"
        f"test ground={sorted(test_ground_cams)}\n"
        "Set AERIAL_CAMERA_IDS_OVERRIDE if this LAGPeR copy numbers cameras differently."
    )

ground_sorted = sorted(ground_cams)
aerial_sorted = sorted(aerial_cams)
camera_remap = {
    int(raw): int(index)
    for index, raw in enumerate(ground_sorted + aerial_sorted)
}
derived_ground_max = len(ground_sorted) - 1
if derived_ground_max != GROUND_MAX_CAMID:
    raise RuntimeError(
        f"Expected GROUND_MAX_CAMID={GROUND_MAX_CAMID}, derived {derived_ground_max}."
    )

for name, frame in frames.items():
    frame["camera_remapped"] = frame["camera_original"].map(camera_remap).astype(int)
    frame["view"] = np.where(
        frame["camera_original"].isin(aerial_cams), "aerial", "ground"
    )

train_frame = frames["bounding_box_train"]

# ---------------- reconstruct the PUBLISHED protocol galleries ----------------
# SeCap's LAGPeR protocol includes PID=-1 distractors in the gallery. In this
# Kaggle copy those 179 images live in a separate bounding_box_gallery folder.
noise_gallery_frame = frames["bounding_box_gallery"].copy()
noise_aerial_frame = noise_gallery_frame.loc[
    noise_gallery_frame["view"].eq("aerial")
].copy()
noise_ground_frame = noise_gallery_frame.loc[
    noise_gallery_frame["view"].eq("ground")
].copy()

# Ground query images are a subset of bounding_box_test_ground. For G->A+G
# they must not also appear in the gallery. Match by the preserved
# (pid, raw camera, frame id) key rather than by filesystem path.
def lagper_keys(frame):
    return set(
        zip(
            frame["pid"].astype(int),
            frame["camera_original"].astype(int),
            frame["frameid"].astype(int),
        )
    )

query_ground_keys = lagper_keys(query_ground_frame)
ground_positive_keys = list(
    zip(
        gallery_ground_frame["pid"].astype(int),
        gallery_ground_frame["camera_original"].astype(int),
        gallery_ground_frame["frameid"].astype(int),
    )
)
ground_keep_mask = [key not in query_ground_keys for key in ground_positive_keys]
g2ag_ground_remaining = gallery_ground_frame.loc[ground_keep_mask].copy()

protocol_gallery_a2g = pd.concat(
    [gallery_ground_frame, noise_ground_frame],
    ignore_index=True,
)
protocol_gallery_g2a = pd.concat(
    [gallery_aerial_frame, noise_aerial_frame],
    ignore_index=True,
)
protocol_gallery_g2ag = pd.concat(
    [gallery_aerial_frame, g2ag_ground_remaining, noise_gallery_frame],
    ignore_index=True,
)

PROTOCOL_FRAMES = {
    "A2G": (query_aerial_frame, protocol_gallery_a2g),
    "G2A": (query_ground_frame, protocol_gallery_g2a),
    "G2AG": (query_ground_frame, protocol_gallery_g2ag),
}

protocol_rows = []
for protocol, (query_frame, gallery_frame) in PROTOCOL_FRAMES.items():
    expected = PUBLISHED_PROTOCOL_COUNTS[protocol]
    require_query_coverage(query_frame, gallery_frame, protocol)
    row = {
        "protocol": protocol,
        "query_images": int(len(query_frame)),
        "gallery_images": int(len(gallery_frame)),
        "gallery_noise_images": int((gallery_frame["pid"] < 0).sum()),
        "query_ids": int(query_frame.loc[query_frame.pid >= 0, "pid"].nunique()),
        "gallery_positive_ids": int(
            gallery_frame.loc[gallery_frame.pid >= 0, "pid"].nunique()
        ),
    }
    protocol_rows.append(row)
    if row["query_images"] != expected["query"]:
        raise RuntimeError(
            f"{protocol}: expected {expected['query']} query images, "
            f"got {row['query_images']}."
        )
    if row["gallery_images"] != expected["gallery"]:
        raise RuntimeError(
            f"{protocol}: expected published gallery size {expected['gallery']}, "
            f"got {row['gallery_images']}."
        )

if len(noise_aerial_frame) + len(noise_ground_frame) != 179:
    raise RuntimeError("Noise gallery view split does not sum to 179.")
if len(noise_aerial_frame) != 45 or len(noise_ground_frame) != 134:
    raise RuntimeError(
        "LAGPeR noise split must reconstruct the published gallery sizes: "
        f"expected aerial=45, ground=134, got "
        f"aerial={len(noise_aerial_frame)}, ground={len(noise_ground_frame)}. "
        f"aerial_cameras={sorted(aerial_cams)}"
    )
if len(g2ag_ground_remaining) != 15399 - 3046:
    raise RuntimeError(
        "G2AG ground gallery exclusion is inconsistent with query_ground."
    )

print("Reconstructed official protocol galleries:")
display(pd.DataFrame(protocol_rows))
print(
    "Noise split:",
    {
        "aerial_noise": len(noise_aerial_frame),
        "ground_noise": len(noise_ground_frame),
        "total_noise": len(noise_gallery_frame),
    },
)

print("Camera mapping audit:")
display(pd.DataFrame([
    {
        "view": "ground",
        "raw_cameras": ground_sorted,
        "remapped_range": f"0..{GROUND_MAX_CAMID}",
        "train_cameras": sorted(train_ground_cams),
    },
    {
        "view": "aerial",
        "raw_cameras": aerial_sorted,
        "remapped_range": f"{GROUND_MAX_CAMID+1}..{len(all_cams)-1}",
        "train_cameras": sorted(train_aerial_cams),
    },
]))

# Build a normalized writable dataset view for the loader. This deliberately
# uses canonical split names even when the Kaggle source folder is misspelled
# as "bouding_box_*".
DATA_LINK_PARENT = Path("/kaggle/working/pvuad_lagper_data")
DATA_LINK_PARENT.mkdir(parents=True, exist_ok=True)
DATA_LINK = DATA_LINK_PARENT / "LAGPeR"

if DATA_LINK.is_symlink():
    DATA_LINK.unlink()
elif DATA_LINK.exists():
    resolved = DATA_LINK.resolve()
    if not str(resolved).startswith("/kaggle/working/"):
        raise RuntimeError(f"Unsafe generated data link path: {resolved}")
    shutil.rmtree(DATA_LINK)

DATA_LINK.mkdir(parents=True, exist_ok=True)

for canonical_split, actual_path in SPLIT_PATHS.items():
    link = DATA_LINK / canonical_split
    link.symlink_to(actual_path, target_is_directory=True)

# Preserve the experiment-definition text files in the normalized view too.
for txt in sorted(DATA_ROOT.glob("exp*.txt")):
    link = DATA_LINK / txt.name
    if not link.exists():
        link.symlink_to(txt)

print("Normalized loader view:")
display(pd.DataFrame([
    {
        "canonical_split": split,
        "source_folder": SPLIT_PATHS[split].name,
        "loader_path": str(DATA_LINK / split),
    }
    for split in REQUIRED_DIRS
]))

CAMERA_MAP_PATH = DATA_LINK_PARENT / "lagper_camera_map.json"
CAMERA_MAP = {
    "dataset": "LAGPeR-S3CLIP",
    "raw_to_remapped": {str(k): v for k, v in camera_remap.items()},
    "ground_raw_cameras": ground_sorted,
    "aerial_raw_cameras": aerial_sorted,
    "ground_max_camid": GROUND_MAX_CAMID,
    "train_ground_raw_cameras": sorted(train_ground_cams),
    "train_aerial_raw_cameras": sorted(train_aerial_cams),
}
CAMERA_MAP_PATH.write_text(json.dumps(CAMERA_MAP, indent=2), encoding="utf-8")

LAGPER_TRAIN_ID_COUNT = len(train_ids)
DATASET_AUDIT = {
    "dataset": "LAGPeR-S3CLIP",
    "root": str(DATA_ROOT),
    "split_folder_mapping": {
        split: SPLIT_PATHS[split].name
        for split in REQUIRED_DIRS
    },
    "train_ids": LAGPER_TRAIN_ID_COUNT,
    "train_images": int(len(train_frame)),
    "train_cameras": int(train_frame.camera_original.nunique()),
    "physical_folder_counts": {
        split: int(len(frame)) for split, frame in frames.items()
    },
    "noise_gallery": {
        "total": int(len(noise_gallery_frame)),
        "aerial": int(len(noise_aerial_frame)),
        "ground": int(len(noise_ground_frame)),
    },
    "A2G": {
        "query_images": int(len(query_aerial_frame)),
        "query_ids": int(query_aerial_frame.loc[query_aerial_frame.pid >= 0, "pid"].nunique()),
        "gallery_images": int(len(protocol_gallery_a2g)),
        "gallery_noise_images": int((protocol_gallery_a2g.pid < 0).sum()),
    },
    "G2A": {
        "query_images": int(len(query_ground_frame)),
        "query_ids": int(query_ground_frame.loc[query_ground_frame.pid >= 0, "pid"].nunique()),
        "gallery_images": int(len(protocol_gallery_g2a)),
        "gallery_noise_images": int((protocol_gallery_g2a.pid < 0).sum()),
    },
    "G2AG": {
        "query_images": int(len(query_ground_frame)),
        "query_ids": int(query_ground_frame.loc[query_ground_frame.pid >= 0, "pid"].nunique()),
        "gallery_images": int(len(protocol_gallery_g2ag)),
        "gallery_noise_images": int((protocol_gallery_g2ag.pid < 0).sum()),
    },
    "camera_map": CAMERA_MAP,
    "checkpoint_selection": "last_only",
}
(Path("/kaggle/working") / "lagper_s3clip_dataset_audit.json").write_text(
    json.dumps(DATASET_AUDIT, indent=2), encoding="utf-8"
)

# Preserve a compact audit table.
audit.to_csv("/kaggle/working/lagper_s3clip_split_audit.csv", index=False)

# Keep previews of the supplied experiment txt files for provenance; the
# materialized image folders above are used as the actual protocol.
EXP_PREVIEW = {}
for txt in sorted(DATA_ROOT.glob("exp*.txt")):
    try:
        lines = [
            line.strip() for line in txt.read_text(encoding="utf-8", errors="replace").splitlines()
            if line.strip()
        ]
        EXP_PREVIEW[txt.name] = lines[:8]
    except Exception as exc:
        EXP_PREVIEW[txt.name] = [f"<read error: {exc}>"]
(Path("/kaggle/working") / "lagper_exp_txt_preview.json").write_text(
    json.dumps(EXP_PREVIEW, indent=2), encoding="utf-8"
)
print("Experiment txt files:", sorted(EXP_PREVIEW))
print("UAD data link:", DATA_LINK)

Resolved LAGPeR-S3CLIP root: /kaggle/input/datasets/cpkimhianh/lagper-s3clip
Resolved split folders:

,canonical_split,actual_folder,actual_path
0,bounding_box_train,bounding_box_train,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...
1,query_aerial,query_aerial,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...
2,query_ground,query_ground,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...
3,bounding_box_test_aerial,bouding_box_test_aerial,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...
4,bounding_box_test_ground,bounding_box_test_ground,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...
5,bounding_box_gallery,bounding_box_gallery,/kaggle/input/datasets/cpkimhianh/lagper-s3cli...

,split,images,ids_non_noise,noise_images,cameras,camera_count
0,bounding_box_train,40770,2708,0,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13]",12
1,query_aerial,3046,1523,0,"[16, 19, 22]",3
2,query_ground,3046,1523,0,"[14, 15, 17, 18, 20, 21]",6
3,bounding_box_test_aerial,7672,1523,0,"[16, 19, 22]",3
4,bounding_box_test_ground,15399,1523,0,"[14, 15, 17, 18, 20, 21]",6
5,bounding_box_gallery,179,0,179,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 14, 15, 16, 17, 18...",17

Reconstructed official protocol galleries:

,protocol,query_images,gallery_images,gallery_noise_images,query_ids,gallery_positive_ids
0,A2G,3046,15533,134,1523,1523
1,G2A,3046,7717,45,1523,1523
2,G2AG,3046,20204,179,1523,1523

Noise split: {'aerial_noise': 45, 'ground_noise': 134, 'total_noise': 179}
Camera mapping audit:

,view,raw_cameras,remapped_range,train_cameras
0,ground,"[1, 2, 4, 5, 7, 8, 11, 12, 14, 15, 17, 18, 20,...",0..13,"[1, 2, 4, 5, 7, 8, 11, 12]"
1,aerial,"[3, 6, 9, 13, 16, 19, 22]",14..20,"[3, 6, 9, 13]"

Normalized loader view:

,canonical_split,source_folder,loader_path
0,bounding_box_train,bounding_box_train,/kaggle/working/pvuad_lagper_data/LAGPeR/bound...
1,query_aerial,query_aerial,/kaggle/working/pvuad_lagper_data/LAGPeR/query...
2,query_ground,query_ground,/kaggle/working/pvuad_lagper_data/LAGPeR/query...
3,bounding_box_test_aerial,bouding_box_test_aerial,/kaggle/working/pvuad_lagper_data/LAGPeR/bound...
4,bounding_box_test_ground,bounding_box_test_ground,/kaggle/working/pvuad_lagper_data/LAGPeR/bound...
5,bounding_box_gallery,bounding_box_gallery,/kaggle/working/pvuad_lagper_data/LAGPeR/bound...

Experiment txt files: ['exp1_A2G.txt', 'exp2_G2A.txt', 'exp3_A2G.txt', 'exp4_G2A.txt', 'exp5_G2AG.txt', 'exp6_G2G.txt']
UAD data link: /kaggle/working/pvuad_lagper_data/LAGPeR

## 3. Pin source UAD + patch LAGPeR RGB-only + TransReID initialization

Giữ nguyên pinned UAD/TransReID path đã chạy được trên AG-ReID.v2, thêm loader LAGPeR,
single-modality view-balanced sampler và DDP single-loader eval fix. Riêng LAGPeR evaluator dùng
quy tắc standard ReID: chỉ bỏ gallery **same PID + same camera**, cần thiết cho G→A+G.

**v5 metrics fix:** the LAGPeR evaluator patch now indents the original WHU fallback `remove = ...` line under `else:` correctly. The generated `utils/metrics.py` is also compiled in-memory before being written, so this exact indentation failure cannot pass silently.

**v6 session-2 fix:** when a previous Kaggle notebook output is attached, `utils/metrics.py` is already patched. The source preparation is now idempotent: it validates and reuses an existing LAGPeR evaluator patch instead of applying the text replacement twice. The internal pipeline tag intentionally remains `v5_metricsindentfix` so the completed E2@60 checkpoint from session 1 is still eligible for automatic resume/handoff to E3.

**v7 session-2 multipatch fix:** the reused `metrics.py` from session 1 contains two legitimate LAGPeR evaluator patch blocks. v6 incorrectly rejected `sentinel_count == 2` even though the file compiled successfully. v7 validates each block structurally and accepts the expected one-or-two evaluator variants. The internal pipeline tag stays unchanged so E2@60 from session 1 remains reusable.

**v8 session-2 structural fix:** `same PID + same camera` can legitimately appear elsewhere in upstream `metrics.py`, so global occurrence counts are not used anymore. v8 validates the actual LAGPeR `if/else` blocks locally. The internal pipeline tag is unchanged so the completed E2@60 checkpoint from session 1 remains reusable.

In [4]:
PINNED_UAD_COMMIT = "3e2a07314119402586c76096e87d40420894ad30"
OFFICIAL_REPO_URL = "https://github.com/msm8976/WHU-MARS.git"
WORK_REPO = Path("/kaggle/working/WHU_MARS_official_pinned")
UAD_DIR = WORK_REPO / "CVPR26_UAD"

if WORK_REPO.exists():
    resolved = WORK_REPO.resolve()
    if not str(resolved).startswith("/kaggle/working/"):
        raise RuntimeError(f"Unsafe generated-source path: {resolved}")
    shutil.rmtree(WORK_REPO)

def attached_source_candidates(base="/kaggle/input"):
    candidates = []
    base = Path(base)
    if not base.exists():
        return candidates
    for root, dirs, _files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if root_path.name != "CVPR26_UAD" or not (root_path / "train.py").is_file():
            continue
        repo_root = root_path.parent
        declared_commit = None
        manifest_path = root_path / "PVUAD_patch_manifest.json"
        if manifest_path.is_file():
            try:
                declared_commit = json.loads(
                    manifest_path.read_text(encoding="utf-8")
                ).get("base_commit")
            except Exception:
                declared_commit = None
        # Kaggle mounts attached notebook outputs read-only and with a
        # different owner. Calling git directly there can emit
        # "detected dubious ownership". Prefer the patch manifest, which was
        # written by our previous session; use git only when no manifest commit
        # is available, and explicitly mark that repo safe for this one call.
        if declared_commit is None and (repo_root / ".git").is_dir():
            try:
                declared_commit = subprocess.check_output(
                    [
                        "git",
                        "-c", f"safe.directory={repo_root}",
                        "-C", str(repo_root),
                        "rev-parse", "HEAD",
                    ],
                    text=True,
                    stderr=subprocess.DEVNULL,
                ).strip()
            except Exception:
                pass
        if declared_commit != PINNED_UAD_COMMIT:
            # Never auto-select an unverified source tree. With no pinned
            # prior output, fall back to cloning the exact official commit.
            dirs[:] = []
            continue
        score = (
            2,
            1 if manifest_path.is_file() else 0,
            1 if "notebooks" in str(repo_root).lower() else 0,
        )
        candidates.append((score, repo_root, declared_commit))
        dirs[:] = []
    return sorted(candidates, key=lambda item: (item[0], str(item[1])), reverse=True)

source = Path(SOURCE_DIR_OVERRIDE) if SOURCE_DIR_OVERRIDE else None
if source is None:
    attached_sources = attached_source_candidates()
    if attached_sources:
        print("Attached UAD source candidates:")
        display(pd.DataFrame([
            {
                "path": str(path),
                "base_commit": commit,
                "selected": index == 0,
            }
            for index, (_score, path, commit) in enumerate(attached_sources)
        ]))
        source = attached_sources[0][1]

if source is not None:
    if (source / "CVPR26_UAD" / "train.py").is_file():
        shutil.copytree(source, WORK_REPO)
    elif source.name == "CVPR26_UAD" and (source / "train.py").is_file():
        WORK_REPO.mkdir(parents=True)
        shutil.copytree(source, UAD_DIR)
    else:
        raise FileNotFoundError(
            f"Attached/override source is not a WHU-MARS source tree: {source}"
        )
    print("Reusing attached UAD source:", source)
else:
    clone_command = [
        "git", "clone", "--no-checkout", "--filter=blob:none",
        OFFICIAL_REPO_URL, str(WORK_REPO),
    ]
    try:
        subprocess.run(clone_command, check=True)
        subprocess.run(
            ["git", "-C", str(WORK_REPO), "checkout", "--detach", PINNED_UAD_COMMIT],
            check=True,
        )
    except subprocess.CalledProcessError as error:
        raise RuntimeError(
            "Cannot clone the pinned official UAD source. Enable Kaggle Internet or attach "
            "the previous notebook output/source and set SOURCE_DIR_OVERRIDE."
        ) from error

if not (UAD_DIR / "train.py").is_file():
    raise FileNotFoundError(f"Missing UAD train.py under {UAD_DIR}")
if (WORK_REPO / ".git").is_dir():
    head = subprocess.check_output(
        ["git", "-C", str(WORK_REPO), "rev-parse", "HEAD"], text=True
    ).strip()
    if head != PINNED_UAD_COMMIT:
        raise RuntimeError(f"Source commit mismatch: expected {PINNED_UAD_COMMIT}, got {head}")

OVERLAY_ARCHIVE_B64 = 'H4sIAJ+1qWoC/+y963rbOLIoOr/1FBzlm20poWlJzq01o+zl2Eqi1Y7tZTvJmu3x5tASbbMtiWpR8mVycp791AUAARCU5LSTnl4n/rojiQQKQKFQqCoUqvrp+Dy52BjE59F8OMuCyd2fHvyvAX/Pnz6lT/izPlut5y9a8hk/bzafNp7+yWv86Tv8zbNZNIXm//T/z7/zaTry7qJ+FvSJErxkNEmnM2/7/GIvHcRelHnbe5XKI2/9If8A3nY6vo7HsyQde9FZOp95x9MoGSfjC2/DO46zmZdN4n5ynvS9STSNRvEsnmbfoBufLuNxfB1PvQj6Mb2Yj6BPXh9+nMVenMwu4c08iwfeeTr1ZrKH8J1+Qzfhp+9BMQDVT6fTOJuk4wGWGUOfvZtkOERIkzSbrZ8ntwDo7M6LvPD4cKu3R0CiHKwaqP+NEI7zCysdWkO8P3gblXDb6wC51OrfoPvv93e6uw8ON9wOCHDe7w8ZTkV/PohwmvuTuTH1qkKw0/3Y2+5CvSqWrULN3o43no/OgGLSc+/twQe7bAgFOt5aYw3K7iF1QLGzqH91lo7jvOze1nuEugYtjjNoehRPscJuhEtiNk0GJfV2t46Ow6Pjw94OVm9ClYNodunNUm8yjan7QHwjWNJDd/2Dwy4RZXiwdfwOO7BWIWzEXm8UXcR78awICIATLUXD5F+xgol4gzXjZfHw3FtUAZaNd3OZDmN+C83tT5Aws7a3lmCj43i25vneGkKiL0C68Ww+jtcc/d5+t88TktfFEfREH2AtAjpe7+3F/SvfS1VDZ+MxPFnDTq+NUw3wXnf7Z4QmCuighmmWwUD6wznMRh84Bsw5PtPh3sWZAhp4u1iDeqAV9y6Buw6S8/N4ilwH644AL0B1tFTn04iWqepR7034qXf8Ltzu7h13D7Fv2GHt/U64u390FB7//YDwkKXns1F0u1Ys8anbe/vuGOkkaORvgXgOdrvHi4ocbG9Zrxv667cHO+H7/ffQvw/v6V1L6957mKjettlFIOjJEGfKnqgRSCPJ+gUsv8FgQvShI/d4Oo/XgB7eRMNMJ4adHiwC5q0dj14WACNSPNFsYdLK4O7th++3Dt8uADuMzoC+s1Gazi51iOkY4aXn52vGPO5uve7uHr3f3+e1BqUKEKNp/zzqxyv3cXv/CMD+nQiD+wggj3MuAutxNjNZ2OH+gVzujaBpvdj/UJjerePjkN4dbh137ZeA9r2jN/uH77uHanr3UmOtMnsKj3r/B9+eNJ/7XvP5KfbzPw/eA78S219eAR/L0eRQ3vXeHId7RGHP9Mcf3rzZ7YZvD/c/HMCrlsl/od3d7t5bGuzT/NVhN9w6hJ6/xR4harE3R72uqzfwONzex4Kb+sDpMXDtwy1HX+Hdx173kz4nRdb17hNitLcvVts32D17ewcfjr/F7kmA893zCPk67C/I2okNe4P5FDdUfQOlOgFSgVqrJ61nSAytl6cLgYDAZQPoHh3b9Q+j8QCk2sk0PYvOkmEyu6M9nEFdptPkX+l4Fg2982EyycEdHO6/Jpp+Vg5iyo/jaZQZYwEqMqp/jIbzOMPtDoQ/JT9yB8awGnH/U8xdNN/77+5u+L67RehoBE9fPvMB2lMcF3w0np/+FrhHxzsMttX6CeG1Wk/545kCixifRAMSXjOYAQ3E1s5Ob+8tUuc3Ic6daBYBc/oW5Lmzdbx11D0+yil0NwFBShDXgBsmWT0z5DwfFR+QdzLcmIEjT0CWysI+lB+mF6Ak67BJZMMWamuf3n1Yh43iaA1bOoS9ALb3adyfpdM7kHRgm5dNZl52mc6HAzWPNaAsb5DejIdpNIDfyTlM6Az6NB8P6kZrh7BphDu9Q2owCDYQIrW3Px1ACyRqRYJih/BEjA7gwPc46sMWOIHXec98Lw4uAh76xt9k7Vcbj4NfJhdG08C2tnZ7xz0x2sO3r3Ej6h3iv8cwPKA/6Mm3IpFdxMz0W1HJ7v7WDu2dgk72lCiPCPZwWogFXU7jaJCZtQLYjMJP+4c/dw8RMy+Rh0UjkDBYT9QBWBWPtt6DyEWy3MHP79eMdpNxNovGIAEgDJSrz6JZ/9LRcm/v6Hhrj2Tf5vOHxr73CEeTDq8fHPUAGcZytL/70cC70IyUNJwXCvYPjnvvgesfhkJLqm4NolHVwBoIvF48SfuXcabVfL/132H3YH/73RFxsQZUeQ3r0BvG0ZR0b5C1Y638ayD4cBe7tRmvP2U7gTAGYOlhNL1AIV6vTdN03od3d0and0Fw7IZvthmclB7fRLj2sMMKyFkS6V1+3dsCge4wfLO1fbx/KHS65dWOul1k9c3WJnb7fYoGjflIR4Uun/+EZWAwwOKQJ2pisYE8Ifo2gk3koMaoodrR2x3ckqhHxFdZx8nwnabuaBBZg2GM8I75OhoirQ+8mzi5uJwtr2orIY3GMxLdWMiltgWoQdyP7jQIXCvc6W5v/T2v634f4iwYDRA0NfQy+nm79f79lhCrZZ1sFk8W1Tk67h4QY33a8L0XDVwMN9F05M0n3jlNu97HrcP3Hw5y2oD+YUOqAq2ArFhBrQHEOYi3l+mAMMXVpJoBWgaooMh9Zmv+2hCU7mi6VgQGCt27fSS2KhepVvR52j/q7XVDjXaeFd8ebW/tkjxNcgV1WrOhZNE12WIuQf+epMl4ZtDBO9DPD/Z7e8fhQfewR/1o4rpOgGhIBiLencBmB7hXNjbYvvW1uf9Wr91wdOIadsOBkqlEve7HrV2rWY1vozgG0gP8Yo4Nathlknnw38UQ5MmhD0oobvA3II1G17H3Eq1FmYcSQO/9EcINX28db7+jZfzS500bipA5kQyNIL7Cim0+L7aV99EG9fxpxRh5roVXz4AVVr/JxoHi+cPDxXEIwb+wW9sYsXUHrBc40Cz0b7Q8k/o9jddB2r8iWdBWvjXdm8CB+A8q5M8sI0sOL81vhgVMVVGsq1ql3SWBnp7H0Ww+Jb7Cdipb0Mfe+fAEvpOVLTpHBgllx7ZRi4qw/YkK5X1Fs1b4pruFbct3+fYmuwC0Ok5JnUCTNTfIrQPd3sUZfM6wUPzrPIEVglIy9LWfwu4Y46IjwUW1ic2Fe/uHuOeQYQxabNCIxijXzNJJeOXFAGdOCw1Ggp25STJhQU/Hwzv5XhYH2RwPrAjKaOtAtXW8fxD+HOICBZ4j5QksJLgJyf3QwVE0E/gTZvxAgSAr0nvCUBWLhlA2GE/uqhqi+tGwPx9SdwAg9s3L+jQtkoMW7TQEHHumWwMefMkdfFz/sLWD+AGWDFQV387icYaE8S1a64JcCFsbLBlcauIUkcj+Egn5POkngBrs0FkMzC5J59PA+zm6uBjGrF9B6XgcnQ1xyUCdkdefjxCxyXUMk17rNr31V173aR15JsLMcD77sJaQadFJDSjpgzmIyRFskwksirMhURHN58FHbFqwCfk76P438m4Ug3CKu41q/gokaTIFVc+TcTSsesbfI6CH+LqKO3RjA7YL1qTquMxE+RzQTvdjiGYe3SaUv8H9o7cjhVHj1dEBqFihEONajdZz8/V/fege/p2Y10FvB+1OJBnmZQ62eofdHTI6hbl2YXXh6O9726EoufXhbbEAGtH2dkIUm6EJOrh4quOBzfn9aOT1dmDnAroHST1dxzkZtL1+Mwj6z3SkHva2j2WDqL0oY5sq8/HNweH+9laxKzQSUDvf7uGE6TKf1kJv7+PWYW8L3gNS3EWOQHKEMvvh9q4hOTbzIrhAwxzU693u3o4AkxfahV7uhtv7e0fAJrp7238vdrlQxJBUdWDvtg53wrcHO0UY8k3JaNRr4Hc/swxSfKcJX873QOyHxywTKuNOd3P9eOcdSYTreDQ+8/DQZX02R/Ep8FD042qP9aOcyBvHN8BqYNtNUOP4K9o/ukcf3nfZwDyNR7ALZsSVptdiO4O1m6CIP51PZvCou+lN52MSg6AYyLto6aKTVaULbmQgDA7moFhvHMJmG9+CXDy8y1d68AakyuMPe45Vl3ecjK/S7l2tuooAKR7vo3TkKnbc3QLh87Aczrvu1g5qbu8/7B73YDXTChSG3QNgUTDWw7evN/Z6h8jbjuEDdxnY6JhveW9JSvQAsxdjOo+GjTYa3kR38HEdJUPkln9ldgnyLOxEsIWh/J4BwujoaBDD7rvO6g80tnm7iQYsYNAj/FfudWI0vcMQN7ze7i6aoPeKmMMSb3f3XwNJ68umYZZgmtfpfNNV4Odu90AZu4GiNSgoJXwgS2r3qHv4sWsvGlDuQCWMpkm6Ht0gy7mMpgPk/rN0djeJPSGueVdxPMm8LLlVlrCN6wSoU5XEjRDlQ8TTDA1lSHIjoPKMQY7jC9p/ZIEEXoBKgdv+7BKIdjAHtt/HvZ+FzcDBZMoXtllEx+izskJijZe+19Z5oxzI1oclJUx2sOko9hqkXOuAj6gaHTbWYY0WzOtKoAQ9Zxpd4PQkyAXQxwQoM4vR52GGOz05ovByR+lxQBORrpPnBMxcP87I8sJin7nigaze7PYOwuNjx/YBD0M+eTwK3/SAowvL0WwWhaAATxN0fcmuqxpT1hmXubKPtoAs6aS9C0rU3605wZevWS2hzU29cbUv2g5BM0QjLPch78KHPZjVvd4bBmf0oXt0BOs03AEus4tK9Ie93n/nh3Fyx8VTOrGO3vf2Phx3WdjQC2kqNA1HK7hpFDwGWSmk0qKgNFXoTAAqk9gNzb7f6u2BMqTDe2b2Dla6iY4M5zcdhzD3s3kW/JKl42pBgBATAxvrm95bieVvINS+T7K+1Ka+iYguVMPcskEsCDQUWBPD9IJtcZbauP/h+OCDtPwDQTyM/xe7GmQbjOe70fBP39v/r/H0xWbD9v9rNDZ/+P99jz8SYtoVz7P8aHQXHP0tMkV498tteJ3MQpT3w0nzedhqPV1/2Yj75z8NBsFkdol1bH8PqHYzJWimA0Rb+EfQc83Bpc3+LZ6HPKJteUTBU+mT0WY+4HnKzart1dYaa3V4ZDslABjV72SMYDSfhHbukgAjNj1d2mxi9TzdxaXNHi50Soo4zI+02/qJtHwBvNx6jofGbRLsPU+cIcuf4tC1jTwWfqnT4Tae4tLRMP9zqt4eHe8UX1bk4V1bIPIIULD1dv0w7u0E1y3EgDxQhBcbV6SZb9ykUxSlNibX82gQRhfTOBmEdNCI86pOAaE5OgQUzfCRFCGCFc+2ONWClrVjqrb3VDwRR2b4oMJ2SaxsnvIAjKO3O9SuOsMBpLQQK+KUhuam8RIJSLfrtdHk6XmGsRqgSXO2eiNhIta1w5q2kCQ8r2BqFmWV8Rh+Y3c0q7CYNv0ooe15TTxLMp/SAUNbvjHPfNpei5pR64cMtU8m/ejJxWQAEgtRlGhYrQILB0BuTFzCQpkPSxL2Gk2QNAvm1kN4qgx3wqENV5SyrwHaKxXaN6gPyqYCZbsNXlpbb3H+yDSyxguUtKa8D5otpE2mEH6U20DabALhxwXbB9ShpVIweeQtWKaO/IVt4mBYRVOFQqywUOQQnJYJuX4dFgn5ymGJaJMhwvNcFghZrWBVyHtSZnBos7zveVIdyatY9gXZiGFXEFRs2RParP1pzzXFQVSRerhGbQ79W9Bemd4tXhf1bfGiqGe3Sc32PFupzbtRUGbVaGwlts06rP4iV17brLvyCnEorQrxBYVQo0yHIthmPdB+yZNRfJ5PiKMxUPhK3hjztam/NhS8Nut3NJuajqUh06Fb4UZtqla0x+QqlZg8S5USo5MqlFp0DvAOzYma0FQm2YZLVSKc0Eovqkht1pAMlm+oRm3WjJAoXCqRoP5yVajNmhDxRl0FaqOTc0EDWssZkqH6COxUcpUA6gcboDkIQX5tZe1A+iNtiE3+uvXwV4CW3f/ZfPrCkv9bjUbzh/z/Pf4eefG4n6JnUtubz87XX1bEBSA8qpbfkRbl9zTLvwXoFoeecmk2kU+ncYVMOf10OIz7pELLO0XieGiQ9GcVLhSgQKPeo0cOXTaQDoGVSn8YZZm39fawC7vox1bNLlJH0cMDdbiay7TkaiVcr9BEGsXTJBquv7qYojMdmwGhd0GFqh5DCXEe1U8nd2xrHaY3oHqDho73GMQ1IDrQmiYXKMyA5g6F4vFFjO4+6XzG3fC8M2wCkBmepbche9SJN/HtZDPkroSzNOTObPw6j6d3i4uYIONsJotfYBemd2E0GITpeMNdG8rV2JIRDetUke4cSWdRtDcYA6A+hwB5A+oJf8iNunhp9FY0v8Fo3I5ALYvUaRDa+ycTtPDxqZ04lCQ7LLCppE8nd4jdyEO73jAmz7rsMh0OZFcUsrdb3g2I7Gj2RoN5w6vx4OqFgpve9vbxR3oIBZvlBRvehy0uhwVbXo0RV5ckMeUj78Ix2AjYBR7JNwNJdzx8wUbDQTIltzRFjFV6LQ3RId0KgwKgNfGbcAJMd4rPpnHQT0eTZBjXptWD2j8GT+rH9O8W/Vv1sQTImvuHoDccdbmrYT8aOapvU5U3yyrCHEHNzy3YEn1vEzYvUBpB4P4ixhSfe2GIhzxhWMMrOAAoTWedKkC8jqdnaRZ3cB/yPRzDWQyo7QAcMdYkzjro/u9XPPuPtcr++QUX8ID8JnPCnXjw+PHVTTS9yOptVTmbT+JprR6oDtXVq7xBGMwQhIKa9gRo+OQ0L5uc68X/3PFOcGCBMT+nbaPLsAKATMlFujudptNaYUA674kG0WTG7kd4GtafZZ7DfbYj9Gbfu0hn3ucv1QDtGtGsCNscYOF1veL+ZY5qiJhxQKFSJukCJw9+SZNxDafaL5QwMIkOylg+yeBNrVDUhcbD+RiPCRiR1bXPX9bY1WSWn2wpXBQAWsNTVAfdTsazmvpdr5gFmacBBDEeYmPab8lI4Qkiip7BosrQ6TVk9qiR2zS6Yc6uiorjCapfOzGbhCkmJ4FOlR7RYqS7Qh0SonOwXAPGQF2g45Ha52QWj06ap+zlD9/RFV217yLdLzlAANXiW0mwxI2pgDdtcWHpiY1KbIle0arG9uLxHFn7LK7lXcxb+WIOoNBWsY9t76RAxjUUJPy8yyfwDTAHPCoZEEdJBvVCJeyqqmcWXoonA9ipNhr1lYhk0RQrKsqnmB6VT7GgMzfQAiUqqOJhEW4l98fojgEb/VJZx4uv4zEuWWPn5+1c9opvC2gwhZthJl3qSGI7S0Hi46sDKNoFJr5cqMZ7JyZJkGu88MmirzBb5dWTc1HspAWwOmQTs+dNjOHrm18EwOjA3zpkJpId0NC1Ew9gj/KksKVmG8SzddgN8N73GbCU+Swmqg00HhUzL9G5zICgDbD3+TBX7rPJeq/iO8HZp3E0xMZrYkCNU3NZwVCxMPJjaAA71i4sO9GzAOW78UBAKq5OrBzA2GsAsL7iRAnQ2iJkdujkg6UUk7OkiwXVF/QkBzBK+NRZcWTq0DoBNoUKLrh0y3PIDuaKZbajOR7ILtDqE51uLxcZuNZJu9U4XSo06AMRgp05kMkU99dq55Vna1kDKTmjGC2E7WrdVVnuEO2qb+3KZcUJFaq4YrdlxSVuqo5dvV7ck6hiKMULNLqgD04/413O59Z9CdUpUgBZ0Kf5Sm4c9Gm+yjcA8c18DRttmO+xvv0wGV0UH8KuV3x4LaQIahNGRwwchwrC83nKI6wX22YUW23zQ6ttfmi1zQ+XtE2FHG3L2bJal4+t9uVjqwfy8ZI+FOcUWXxxBlA/eNl48RWLukuiP6wOqK6vGSYbUJILgr+j+TLZXu9sPmXc2Zeo8DiRKt7/tsG8ZAd51PJhHCQLGEIED4sedT5/kVTeWcatFlOgPop78bJcrzRHnWbBKLqKSezKy/igsKGzd3pFWq3FZqI75HcF8ZYQJJhItW0o/kXFtyrFMSxpW2pc5RWLhAqWJlMsrBikLJyrOcXCOnOU5Q3hs6wzMAeyvMWuSmuQ9FisREu6bBhWMxpdlNYoNKNxrnIEWA0ZbGhBrUJjBqMqVuyTeSwksxhU+1zdbsl5J+NLdXsz/93E3w1hy6uiQcaE+MX4RbdVUpDFimtLKfM6lVeVpV/otuxsVXf0+gb2Umke7lTJPFw11xsafy+j8WAYFwVFBBsM5qNJTaweXxT1gXmggNNpifX6H7T99vk+Wm57IiyHfcDKjBREzaJQrVa38bnUTUAfmU8zcWdAXTvQOO8Y+FaGQrh0+qwHaLwrtWZY7RGzjGfz6dhrqIfUM/S8MwR0NpwIFe48GcbEK4Hn3ETDKxdcBvME9qv5yD2HpAjGt7Maiqd1kGQDNFBPa3WE/LmK97RhpvAz5i+T8UX1i1NhJgMk6vnYsZINRgyU+qWZAs9hRLOQmCSao6XNh9VS9JfV7XWECfGctHFZxho7EARer4t105Nt+MlbKGgr+YQpSHX2pSMNW6cgrcArr1EkVzlqWcxGB5omNWxY9iFsTxu+YtRK2Xdgz9RLq8WzA2tPqCrjvPOF9lBT69QusHpP1ERUnWcKSGFs6bB4hlVvq/W2tKg0lbh6DJL5KII+2+aSh+h34TBlyRhcMKQ9ZqXR37dBUa2kjdwWtIh0sBUnZgWXy4mTbuDNNBoRD6wp+AqhcZuiWyAssVAKYvCGaX7i+BRoEQ686gIhtPQIzpPHVXR6ZQAPVhA/NX6zspXdMhyfWGg7LeWGZXRrHukhIbipsJSGSgAgVWl1Tv9tmbCOUWlhyuvYLFkz7Gs2fR2GxrAn0TSLycAjti1rKxZHczgYPJWmglREt6iHdIMmt+DS4V3ANy15d86lAzpg00vzWZ27NKAxB59ktNtQAEIFRTxccjhV/TCO5VLRVhxu92x813Qx6oE2PN8DwSWC7qqeBEhvk0yzS6JzPDZk3u8ULYmT9zaajvF+zBhp6mDjeGMLz9Ip8mQMymOgY1Qe3nhPPBCCvChvSq50xJsopbDBHas16wYGjRrKiClRD6L3vU/23Nhkad7bBhUXBbAco3oHfM+cYZN10GmFQRnQvRO9/qlN7fkph07V9hmCrwL7JLE8Q7BPDnI0XHNAqYKVOQ9bBAPUAFp2QYyKZFaWAEBaxaq16mMpnT5W4uljkk/py38evJVfuuLbwR7wqiJnoLYCusw8cLNx9FgJ8B/3a4NRasGPqo8fo5pzO3NoQPkMCPWCD7yd5epLtg15XEVEydZkNPnTuOquAavpztlNzsJMzmROp2ScteLpmLVgcI1wna/Y4vdSdTJEpmscoLZIOMoUH/GOlxqsBZ1qpLbyLiyWx2fXUSMP7kvlTz/+lvj/kSfWNwn/vcT/r9loPdu07/+0Ws9++P99t/jfB71d6YNHznU+f7wBoUE46sGShE13PkuGGQmFsrj01HO7BCooAV4NCY8PP+xtbx13d8Le+623dC+Q/VgruJVhXDWWFWvJ6CLUpLNqtfpzHE+oBN0gpXiHyJyGXjbv9+N4EAjHLRCS0LEsuk6Bbfb2iXVhpN75dMqxty/j6PoO3nhi41RWoIsUzwku1AVSyypEamdm9yznlaKtWhVkgkEas08LVVJ8T9Vl1nVzCYihYqJp3XpgqVzcMUJnQKY+BQvDtl/H0xlH4zNZZD4k4Uwt3Qz78WQme+w86Stg7uYyHiv8s5L2CSOzwLs08HbS8drMu0mnoGp5/4kucn0Y3DAoG3q+p2fM5gULh2LK5xM9PQV11dKzX2BXyKmBPil+G5dNkXpgwgUzs1zzgLYch0BCVoLf2lzqgmlGmyb8C1pG/4rFHF/8nysN8xGZfMkKaEhQVyQ5AfjgKr4DCdrEs6z3pANyeQ2LnVydFuWF0Ny9qSfs3SKqOMWGDI2J5EJTeIsjorcEsfhejBVLiMZODZwIPwXzeIqA8gv8avg0MebwFf+oG6gTIBEHJkh8KcDiSxMsvkRPUvnWhiyoSTbgK2z7Cq6fA8mppPRI2DLu8YrfS2c9dH3ACA3xgNaLQby6m3JNo+aFZMysbTExL+ym77nPr9sG9vRTZvuA2T5b1o+VGecrnivbB3r2abJ9kLx6Q9YhcvH8uHh0XDw1Xr254nmxYJNiRr18DtrVeqXgmrDq3XBX3Wx+hi143v8DqjeuFvpksRu/siqaPXSzfFBNzX5uPxt8oc+X4vOngWZDuBc11R1Nsb/Eik2tTk+upqStcaWm7ktR9d82BYJzGFzD5BgOf2zBBHSna2IAfE+avKm1lf9Ilm97eAejpgIFr78iv2lkQGqrLnhVslqVDGw3XBlEuWNwLNv30+mdXS841XDH2bGGv+u+6MDsxdB1bszcHg/PcDPQ+3QyOq1zgDhlCdIb1yDDqkfHMIVYPKC81RoBSTDJZEDeGr0FRM/R860gqTksIoRFx3O2f9HJkr31w441uM0Rb3ri2kMpigH5NIIEF+pTGUpOp5Akmjg9oXGdUMunRdmATZRuO6Q5INGkq1N0U6Eo6LuKKjsGfK+7JBlAaW4jHtkuwtJNJqcq4Wnu7n1CUmI0mwlPdlXN99agkSGgWRrgJ2u+ZxvSHDRggsFRZMVhxMMsXgjlpAimLqK+XyBRYLFT1zk1c6l85jMXi8HAPfdnM3erMZkVecpX8ZO7/EbD3QNykQIHMdoUEvpv5RuwORS5xgIE2QvW7BOv2tPKVyy0+y4RguqgR5N5iaMG+yzF3YWcWN1j9xW8Hza8b2r/G0YXk3j6e+T/e95sPi3m//th//vD3v+9193e3a23B/Hhgou9XAAjJsqLveTxttV66214b1tb/O/b/K7LNKbg5dN5n8PAqmu+03gYY4DSDXHfV/gNiFCTzRc/eQe9nc56k8IxTinkeqaHqBOe3oazhfQw8A7mZ7DfXcYDpWVgEhV5G1b1CN5HM4xziScrksXiWLy213zmb/70kyfv7qRZQh5T3hPxaJ2uz45TtD50sPSzzU0BAfEAELwX/vMXLXELyIAgLgYZEF74L5ovcgBvAYCjZqE78S0mPkNDIGtbXMDaLZ7gLWrCqWyt1fBbjacLr83yVC+9Mit3hMLF13w3r9b+98HfYD95tf6/8Q5suI2/aWt5Rb/x5zkmeBIPNH8Z47IsPxZXZtVRsO4FXEXfirZX22w8xbhOz2BOtIPEKuA1f/sC8G291Oq2GoAf8frHFdx7HtQLLvHHu36L8ynoH7/+z7+ba93CEUwbRxfE4+tkCiwbpOpalQKZhDivGO8JAwNt7++iiwA5MwXzCVFj4VaEgmj4f8ile2+6cvZChQEgJ51zoKDVKEkd++tdqvtmx1e/4jCKJiRRF0mjytJcKNzOoaBw8naTCDLUmoRW/wpXgPfiktrnLwEW1ZNrrUewV8y8fkyZcDmRALn/oZviEsc82aWV113uCy+rAi6mDi/2Usd1gbH8vgd5seP3Ghe3CDjHcOFuCNL9NLqpt+kbx8MoHvFACd8TwTKSsdX+SZVuMaehjKdRPQ1Q39Q9sr5Yd8xoN4YO3YbSeUR4Thlw7WLVU42wdO/lBQ6BLo9l2/FYuC4uh6UXL0ARvV0VivSSVFBEL6QMc++hAakWuyY69ZuAFnpK0tJ9QSlv4cpqUQpqmuNk1Z43ZyACk7DvG5WAzCCi0iv9vsQXgyGJszx5/Q1lg9aL33ZlDesLFWPB5Tur4TLu8iOiwqoRFTRzsTHfpdEWCrt3pyMka6NuaVCGms1tyjmKuXSdwBwrG33yzaeZBVPqOUVwak0DEP6eL1iX87NyyixSdt6HlebgiYMy5Ao2li91ayWQ0qqJy5njITi3nUK900r5Bm770Tvxr7CoRV2Ih07CIaXrXoSTbzDlm4i5kTiBOfYZX131/F0JJ+/DvwnhvPoGdONEv5tuMuCa3iMye/xhCOXfh2tVzKxIOh4ogJ50WwDdqEzmCbwu2ZEogZYFj/K6iKng+CKZyg/h9dPRGUXGl3a2szvOJEV5ZeRxQ1Cc1ZAT4bqucJsHFUihDXFyvDTayIKbuQL1nPuGw4gUV1VhRd2TxYv7N8XeC/1XG3qlfF19Cw5iD99RZDXu8RWLfuUdJL9k6PQf52XBcWlqJpLqmvgidfnwVz//rg7LlKp/YmxVp7bsW0pjJArnbXyFQPz5i1hOyoaJd1fIjWhF04Xec98Y8OKur6y7CyQsiMtjosEKtsOTK69kO69SSxXkbyL54AqhgBbQ4ap4lxRWjnmPeW3n85f6103ChftGyjJ0+jrSVjc7qQgNRYvHfcI0lSuFhfuVq7a1JIrXktb0VRhKBbT5rLX5detNzTeCEKvPpXyuMtNmv1ZeUsXwVWrq1nXkPlAoK8VkMD6MbFuSvxJA2vcd/LeKZSXMAjKOlb76jB7UF8azEk8x7NRqEa20CsXhF4xmpYoxybAF85iJjSWhsvC2VYb9KA+VxXWKU60BIR7SdoSvQR78FSzXuob3I3TXj9BdS0J3PWCcp3sH0xEHLexKEH7+wucsJXzkG4bY+ezkpHpoKmZ360eb27u9g6pbYtAjVJlc2F1cD1C1IDZVIT5V+Q1dmwGWFixljKU1ljNMhfOSIVhRsxYHzPq6oFlfHTjLDJ4VjtNxSJwZ6pvSw+Kq94qi9ZtiYhmVWRDNQbjE94cS45fOsn001nabqkqq5yeCsmL+pFjly32DYgldVOig7cVRZDlbZvF6v0SZ6+73IykYSTebjBlUjN5RGzyWDfKdoRgf6N80HydAJt4ZlLscRdMrDCKbBSUxaAuWintHoBU5QKV3OIBZNfys8DZlAA8aG8SM9KF5KJWG+/jaqB7W7CyM6KGOf/WgGVV4XK2bAc3zEBtGSaZ/M2aALK77V+QUfm8Hi+08loYR6pZOvK3IAaLpxZE19GgZVudOBIBTdwANK37GnYieYbpzm441quxv8ZoQM6oFTIjM2KBmbIS70vPJYjgOPRSHGTJqcVyOs9GEv9zEZxM72lRp2A768vr9AX/51H2tyxl1R+wQGc8jD92xJEKHFYlDo8yySCarhty4b7iN3z3URpFq7h9m4+5HkI0f/v/s/4+aEunU7GT9kBcBlsT/eNpqPrf8/zdbm40f/v/f40+451N8j4r+4zrBbHT5RZ8M9dDj5dFAdol8nHcAdP9+v3ANTYBORiOCGUDDg3QU4u1mDvpBMA7paZcfikb4iHAqixz8/P6In4j37OxslWL+eBABJxx8TOKbvJbvfLqzc8B7GT5+HQ3xQtdAr+R+TtXqRkc0lIq+HN2B4DxNx5iVg9s+VhfXuObN5RwEmKmq8endB0z+eCReq5C+8r3KmCYKsJlCvuWtw8ReOBhMihgMof8GWQR0NyI5m9NNhoyuSlQqYXgecbgwaaZfgx6uYw/X2qqzjD89+3A776h4yV2DF/zFr3wR4WGEzSwdDqNZHJ6Pa2coqIpNHDXMcMjXHTN535H9rv+VTGqPuWxFBgsw3dU5nAoWV9qIvHvJQwYO0b+qnYicGaNTKw+HqHyK2+qo09BuHMMkXsQ1s8U6iyfCv44bABkIxJMad34wu5vEHX4BAvnzp9yl/AqxUae0VwoHpy6QK/XRvkia5TdJaUquMVBd+YSYdYQfGXzKi4Cu2aGyMxsxEkIJamQ0SG2yuH2eD7sf3IajP2JY1k5Y659fyFGde/AjIJ/wwE4sbDlQaqu8s2iBm3Ia3hnqYBuUUzzIE4qbIvj5MJmg5nKmlcXk4b4lYg/IrKiV4aTiZrFRHI31MirVuFksmw0KpY6Od8xCyK1ju2cis7mmClSKV58dWDsOtlNgPVlsxfkFiDEiquZEFGqx8XSSDukaSGfTMvNAZdpC3qXT5F+Y4Wj4BpBZm1iYLNQ6iAa1AiJLYG9P04mzc4Xyx+kxk3jhzZ7M01Qrn5+yObGAGXtmDScnOktQfnfMEa6KuLM2SW7j4Ro6pt/y8XCnCcspvk768LI/ma/VjQDDFaERLZ+/0rnrHh1rMN2YeRCsyO4iy8M89zG5kWD5PId9oGWnr7gvOMkK1tWiunGxDQqrrfHEqIFJf49OtRtreK3LKHG4v0+pfX3HLauOFu+jUrzTpZhU/lK74IVv88zB8oZbJV+E3HEjEokYTyBO2Nw90YIC2Ks533vp1iehUcI0TeJyGwjhsbMQHhwxvYHAVVrqmrYpjWlrkytyxMsrRHjMvwYiz5od4anMblXdHw/vUEjylEyZ4e24CZkYfA+EI/uQ392DesU6uBZ9pUznASYwZ7bRtiLLrOWvPMrlvaaf+Y+TkHbUENeZIO2j/d2P0G7v/VGIF5lebx1vv/M2Nkh8o3M2WAnDAdUw71Tl+53Y6ijpveh/25FYbQoz7HYgKxWQXT5txcVC5g1dePSVtPjFGVajTIxfcLxMB41yUjv6iIrDMZdEMT5JCdbdJS3W09uDad3b7hYLL+EBluuhOqvIWUJg57R1HNxjfvWZVkXkIBcUgH0tO6MvhjOxUGqqFn8grOZjFItLDcnWhqVGFbzGgmK0NR0Pvr1Kfc88imYeJq67O1rIFW0Tg4p/+4Vog2Kr62jfzULGsDrGL9/KVyJF/o6tlFnyJ7wbxSPY+6ywyS7573vwmu/JaBY5sfxgMA/IYFy85Q/JV6xFf881njOTzmqDkSvducZX4hgrMQJNOeChaWc0yr9APKuo4Gda1LMccUbYetLQ0dwky7bVHBNIukSeRxE6Oa17T1QJGbWjUOaL0URREKZ4WbJ1PUqRqfwYx1LLp1S0tXBCUUFaOJ2X8/PzYcwR/n/bZJp2HZttW7MpT8DyR44IoKqUjHa7YJrqgmKm8XlYDPYFZHAi3ECZ5jifsaIGvVbbXPXUlP5em3G1qAQ817QX2vM9E5qLBvRFncN2EYLdBb/yFZRQQgVLKWDJ7Jt2Nm1IvmuAvk4fWlxOGX+XNUBfanm+0uR+nCD+fud/xiHJw4YBW3z+9/T580L8r014/OP873v8VatVll55Fa5HN+jQpdk2MtqQ5WlOUKnsj2PvLomH6DTPfmR44Y9ioeJ9P8kO17NJ3E/Okz76tSX9OAu8reFQ/sCNHe/9cTVgo7A/zlK635ehr1VNpmn0RUQM3yOXs7qPcfPZb2qSZllyNkS/s340z+KK7OR6E6iIStDIvKg/haIYQWxjr3e4cdw7DLxenmE7PRN3B2VKWw4LDhCB87IK4b0lcXeDk3V7nBXpr3qabh1IiuYhDA1D0bb4/lslEYwTzzJnlwDg4pKGyiG5RE8ZcFChAFni2K2fTu7k9xEGQ5GB1siqq4Vdo+M85NwxBT5TZ4WD+DyaD2cY8rey/CzPecBrH7FKHaf8CDG7BDoahOIQN4sxq3slfHMIClZ42DXDdk2r4XmNo3CZ0bfq4kQmpLkPr+I7mW6eRUF2ujGj23K0AqlaVXTfPNW89MnLvXrK/fGKvnjb0Zhy5KF3kFoYTJ5AEeS9ZjjlaYkP5IkaB2RJMPaP7XOHbkNi1P27/jAe1CYp3oIhKzzgZ6wdRlE34G0hjOmJPMAz3T855QTKYPym7v2N4eYAqE1p40bYmgvQ+CIQ8kWNitl+ptKbS3tpOFyetKmxUxX7LzQUZwwBWBOUtTgWbZil82k/9j3dgkJB/kWk1cyIiF30hCpor099qZRyODVtZRRyZiHi9bYAiS1KnGg8/IvXWubUyaNnLkHkirxhGv86TzAeYTT24ut47OkaJl5da1XtGy0aSoQtXPwyixlGYSS7/IHjVkc+Ei5sPKt/dYzvkvBE9mOrFs8NlD0DiqzxLztssMbLRDntkVU4nqTEERoWJnMrOCLSZRtX9w709sgI1LTiukXjKx0I/l5UvVGIhaLN11/s7i0jrbfDFPYuXh90qKxClg0S9OyhbfPOI4D0vmphaJj2QYY3SMbu1MaG3avCEApQ/uIgsKXLJJ6uvz34IAbjHIe+RqoOYsaDpZDu6eQdkiMq9FGOy+hkRQtwjW7V6688PXw+79/r6LquvVkn2OowkAI151od3ZhCEsn359owGp0NorbxDP/RfElt+4i1AtuFCGMi6nTuGmLFkdcYRh4L3hHaXI9QHS7Ybotu/8X922WJxbIoghFeKF5R3h13iPQireyAPJlg6kkpUSFQcgMGJo8u5gIgfodXnWX+ssozONfyoZr7OklxUM6hnACAU2J7SA1WOETudAfEhyLbnKjb7drbfnoNU3kRh9P0xvJ+voyG55LITY4OFN4ynaQ5wJPwkeZuF7KUj0bpuDRbwaoEKYhCJgVyYsgR7F82TlXRas8PZKJU4qDi2f+iQu6+iwGK31Zg0lwwQDxKwhFUKRskMj1plAc+OnWEgVkF3qsycM6I7WJDxAs4NUohxv0W6Zu5VccSXsXZnO8B8nIZUv4mQZUyEouhJrVF0x2Mgcntrr6oKEABVa/zD9Hxr8qvKeRhRmzbQUIw6PE8NvF5GWUhDkblACLBQWCTrjc5egQtmfXazuORCYV9jW7dSGi6r48JdeAy6MfJsKYhyNvwzocpoBSXdb1eX7W6GMDy6o47VCCPDmMaYjF1iTtxxSNvJ6VpAPmmH01ZuM1NAXz3OlebA6FJ4rWGqQPYgHK992cbrApJSqTtJA8JlEzzCLXUoI9T5wA3hE3445v1g2m6vQUzk12RwWE+zmuTpYBV8lk8HQVLcEKybr72ysj3AalBaz+f0yKLX2GGtQ2H+K8zMFJ1FE3wQuZnUGkNXn1amlfni+OWswiRJZmFo4QI0ycjkDtKaCPHi5X5L0dZc3lCcfOBvyBok73dStzwHFrbirb35jeBJGdjTlQvZ3O+AFq3FToz+KY2UYVoOao4qvILxd3lEZ/3MGPlmAxTmmELpxm3WDQJEiA9AippGZhQ5YKiEOO1XRt/Ad8OqtXr3mOXXG1qHRKSCbmoaZTrUUZNE/r5fKh3Nm/QVjaj6SxMZigiJyQ2NMwCZM6yJSFx8TMFKXrgLDCYQ7fopEPMrn3HGRe7vShPbFIWYcmkwCan33FG5wjdUTXsLWikolAtNcxZOhfZAXx8yquLfgOVmlfqq5/b/hdTJvCyYTrLNkirpvoHvR3vlgIdKZkTrx+AFlcuGZjk7Jv48m1qX7feF3muTgf+4rXhOwiz7JReSxuGZ3U0ZmGaou+a1CWtDDgP/E5fvvz2zx3NItEucqJFFJVTLIdB0am21igxedCnOQa7qkhlJH8bl8yd6wO3tQabMvNa9ZKlXdgDG35xea67m3rsVtmdkzPDA0xSoK1UTwKV2lKWzET8ynMgMUspTEThVqS5QAjF1Xa+oHnyrVu0CEgVAtbOvXC1X8zhULUQozdmvdKa1ZJK4OFsaKHIZ5wVrzvT47YjbZObwqgnWIXj+DM2fK2MQRo8F3lxQkt9IVtdEWWVpWtEb9ZCqO816nqGQLoUgkGdecuWyTiUNf4eCreyymtqvIunWynCxuepBK5tEKajR6gkTacYY2sxCLO4w7RLnL3QkCOOJLiikOpO/bzhx4QERkxJBMkCGCH6rQwGFOZ8nO4wtdyzEx5/MrgVANu1/MkTr1kXj93hQWTOnN8GBSc2L57ftxIjqC+Jd+vWskwlRGKzRINAFOuys4lnx8aHWF9BO1xhGrRmT0otATp6lxmH9b/iLCyQLssx/EATlWPitGAcY6PVWMOYwzKjHa5h+TIlUqoZbnzScbpYVqS5oabGBsfyNKhl2BCWqoI1TVyiKeu9C1/i/M+tSpUFZYlQHMh3+lgyXWL9bf1YEo+T6aBZ3L+q5TsEkEaj8ZMkDksKy/m5kgdsPm9woNxO0KFj+WAQxxP8okmmptdWrHs2mkewClgdT/XuobtBUZmGivBOIngObomsWy86GbqpNt+OHJlzVF155pujjGY5mKSTWt1p5qdDa7O0e5GrEQXTeASqNrZRMMQhJnlcSpS2pcOVzKDVHt4aHGPuMz7KkR4PBGeddM4YS1YdCMzjgFgoFqQtChk5vaC1YhZSJYjqAk9pTk5DkHWJpytpEQ6Pai5V3FCKTh015xTbmrnba14sWfzA9QpqQMt7/NjbbIL031yYWasgCDoWHRd08RDLjGJ31sTFPBPrXRFaTNqn8fMvpQehZp/Et5M2Qz09USfF7bYFQQtik4z5BCGTplJBlGSIF7DNu9/09HSR8QO7T4A1zF4lE4m3++pdiEas/qrQ1lcEuzmEjQBdaVTrFEy3D/MmjyLW0RjF6oYY0UohZa1R+eUldWRJ45M9eH/l2DlyBunzBBHVPi1Rjh3zIn2GoNvy1aop0TULl3S5cV1VqRX9cMr9bx5jVkBnfkB+cFLV1lIVt3vynynPImgDXNhVvDP2bXuL/j9f0dnQunHkcGaqVqtHbFdTp6X6HVLlayjcFVmH2RBKE+lmIpdpNwLCVy6YeIzMPpjA1ddhtx7F45nwx8xSw40dZLkYZB089KAUC+wdB1JXorq0jk55sDzOiJMAzZ1H/Ri4IKZWgP5+XMfrOt4bdCsoOj+yX5p+POh7MXbW8GGijZ/O4yIQ1Flr1k7c6DePupLfU8GjotwoqTeO/qpX8WTm8KqU7pQC+5Xv61PWVD5l7I2/zKkM174ml1P08XuH07PIUGXBpPkWbqm5L8M3Sn/5UB5yy4e3grdcWYDw+7jOafdQbPe2k8bp93Kz++E798N37n6+c458pvd0plskhi/wrKsVdZAV/ewcK9XtKQdEYDrF3cfPzVjVtrNbWAzmuMjPTTsXV4fAoi+5o3fhjFfYc1d29HpYb67cz4nlBw1/zFpMR7wSIxw6YlHp+zpDPUijr1Zp83dxmHK6R/3u3lEFr6b/gW5Li+zlwvKou+qU2ae4gtsspRzJvhHySokid/9Z6PlT4py6kjsQWY7LnYEezo1HwcjnYoEbD5Qu8cv7DZ48S11uEBn/Jg4338HjxqS7Zf43lSUWv0W+OPV/B68cwy1HIFIdoatlkB+OljneLPa3sdSV3+Rx841dbUo8bJY51lSc9rNSR5vy4j8cb34Hx5vKIsun8fJ+Djn+D4+cHx45fxyPHIYQKj3zqx1z1MbxgG45KznkLPD9WOyls4KjR8FtZ0Fji315VmiszI9iFRcNt7wur610FmSdegh/oYfzGXKL8LqPhRhTvdT5SXMUIbGG1Oy6X891bqJoBnN6Lx1qZXcjoAJnmcXeR2Vj939n4uEx/du7MX03Klnm8mPw1MWeP0bRHw5AX+kAVCn1n1niEbQgUuEP96CFRj/lM2QfSxWchpYwrx9eRD+8iH54EX03LyK6lPrDh+hrfYjcwXVrLheYfwc/otK449+8x/f0Jfo3iP+Xh698wBCAi+P/NTabTzft+H/PWs9+xP/7TvH/9OQ03kWcjmI8K/Wi+QV6kjHz5EyKdOVTC6MnLuIHerg6EZZucS4xYI5jClIHPA3Tir356uRfJbnKZMYxPRXM+3QAonCeoUUxiAXZeZTn3tZkMrwTxzQY0wcz8Gz0AYrE2B0dS6HShCIcuuDJzqM5XroaBMoNDUS9YRJn4SxlUVeyizLuww5pKvGPL7P7+JS/h5Ke+Fr6nYLtmP1Q+IKIwxdJAcY9ho4W1ZO6HaOG2hWCk/hlBwSDLilfKfhecEkayLfwtV5w/tGnvmOlrzEjzGu5bLjXGgZELpsq5bKpunPZVPuTedVlrA7DPkp9EvucfbNoiAXCE0p6jYv4Hnmm+Izpel16GPBblxxzfDeRB4ILCFE58kUAbrwejyYYbAeBEh41+yxneincyTp+A3oS+WFRLT8nCztjUmHRBK972x/g/3oxtBR1gHKg4fAqRdsEJQxWEjpo5urcVNGXiZS8+9DjSyzEHa6bDXKx04IILqnzlddYABdKGWiQVLy4jVk6wVOyc5jdyzi5uITPm2RAMlfOVchhbRIBY8xqDOCkcaph2zVR0CNkJbJLZe0s6Z4Bb6wSJcEP4DEikxqj0s9Xqa9W5BLoMrKkY43WGDgD4O86hB9Blv8I8Z+1GK4PG/15mfy32Xix+cyS/1pPN5s/5L/v8XevcL+rRBh2RC0ez0eTO5TzxhNXIOPyWMSu5LSTpH81BDEpfLu7/3prFz/2Q0w5cqBcO2j/RjYsXBXgQwhZtfwqBn0eMlOLPJEFXtxNwKy1Aw/EXqwJv/pXINL58soCbi8gG9A1CrS68LZ3jL/4Zn+Sef2ofxkPAqMx7o1X7LgM56v8nUWLsFd2Ol513O8Pq4bk4Rh7IW4xObK6cEStjOMbgRHRVqeKY60WTAYlvTXNfaIs9x+hBp/2D3d3xExkdCQGW1GY70OcPoHKiikR/dDdviUauBhLzRlAm6nCsMuccMd9gadTIcGhdKcyJ/HPGgl7iD/VFmCXarMpsdqfDyLpbXU2Pz+npB1McMEAiDijfquI0WS9o2J1kDeajdZTsjy2F7oEHaJv++cvHmgMFAo8RVpav4D1AK19bget8y/e29cYSZ1SWgARisEsMk9ZnvK+0bUNr6b6VpeSb6mTDXs0z+Iwmk4jvPAwngS47hmaACpTscK7OQzxpch1wVu/lbw1B2YmcKWKShDnDzPPBNUXRDRB40QaDqMpyJkzSUb8YRKSubY1kRvl5BNo9LTNXv2AYlzCEgZgmu4qIQrzjJP0sk3KFrAEMcLZZTTDkGJUH9QKT5kxZeNLL0NQjztFyjbnVgPzqiNuSaB7GIYWC5hmNlBNEeQj3flRdYk5EjlzKJAfZ5ccct+7SPCeDLX8Z+4sWyWlhmhkF+ZPPDqKh7W6K5WwmkFRVJ9IBBki2g1thCv/K56mWe2keQ+YJF+G+dltjh1uTqx9xHaOlJrqhK8NVJCMPgFGZ+lMAB4EmOEAPSnJNE6Bx8Z5SXGsh4qlwB76WKnXgpM88m4wHO1AozaZsoBx4WlTOEhjPqgR+SQFBH5LDIMAZMQgElyLaGrILqOJUL+QL+Xz+eeO6p3GlpQGr09FTQ1jXUdUfdGqdcy5gxH0gWWppSpVLZmdWV/x2lTpi1+bTG3f6OB+Z6/5+VhHJizpaHqWzKbR9I75OB3DEGOlWwDjGHf9aJoM7yRi67xpb00vNNaBNdpeNNahpGe/xOIKpTrvbmMmDJpSQ6AIvNd3UkhCXQ6EB5z8SIgblNGiYvuY0+VIlDN4BVvSSLCAx2FvgckRLct9hDEimYLJ6CT2dBHEuLfVMW4iSk2QmqlolwsmRSlEmrbKxLFF7fLaXNi4ue0slTQq5kL3taqr7C+rLfYp0FRyjeuLNw/GuJpIrctlrJGMO/l6vM8SzFmk6tgC1qh1w/eMsXZ0hNHFKdnXU5Wkjfloru9jLvcCbhk3+fwpsUr0G0SyWj0gDQE+ZylKC1mtftI2jy9VF+QRuZDK0Gsyk5KOShzG0qiswkzEdeq8RGAAPOOC5iqoxZzFYu9PsjxVjbiujRMs0mqZUWN75/I5sBtUbkRXvMO9tz6CuYP9ekwMAfboTL6lw+lZarKFaYyhzWGFCSaVt8l7f5/1EoAiDewg1+BU36ClMZkx7xnE0QA4/JWpnsBoMxb3rCN1cZ4uxBSgHlFSIyR8YnByWQxvxworO5vIRN6dOz0JbOGaPE8HlQfGLE6k97RLEoQ3PpUgVqayBXEfrJo/e9odbmKDUDHWL3gi33r8s8351/ULwWzXredstZaMLgo3BcXusW5ddUYEQVVBQum55awvu4+rKBKOMwKOdl+yACS+zSNyG9V++113+/jga1KMOE74V7wovPia9ILbLMXk1/e4eFt0kjLyRNiwF19fFe7Ag/gW3bmdd1ddl1droUywAP/VF19irbddF7hEi8Z1VPbrc1544kMYo2qAEb9q+oXVRx7sickIeU8J9Y3F9Qa3R0LjPu7Ug9ssd6fWR2PntBSuDlihGAkeXv9tJT9MBrTE51IfzhOiQF7izjvZlVUus+e4/ao1ofxKOgVyXuoeJh2+Frlh5bsAvTDdnZZ4T5GDSajPI/Nh2oy1NhR5FG9/5iDQIbYZNLzCstW8Bx8ZLeY/cscoACIciWr5M+Fuyy9OF3Q/DM9jXPb9+RS1rXCcDmIqoPXTF3Dqy5xyQpNeC5454r0+jWWtM0N39KGtCZQzeJkvFlcXzlAWEGVqlsOSxfQ0lzdamjMUl2emgyhxs1xJb/haA4/tWfQL02pfrkAn5I6A5eTDjz19SkuKJJRy/TcAqCVPmnU/x6flvKqjQ/q8WlxXLxKOJ8K0Roaxmv6uZCHR4lEVtHk8sQGfFqgrL63Rlb4oLQ7xqLD85YI3XaFDsYms5gpNHaDLTXzFxn4rMkMaxGR6S4d8M9HpLb3AT1p2Mx9V/zJFg7CC6ZcBxISEk2HUFxl1UUOxuFiJP3RY3NnE1oQFySNgbKPF7ecs5t+BY3N7dLv5CzM1s9K/3etmgmi4gDVmNZSO2Bk9ViAMvVlK8OXYZcRNguJmXkJC8kYBE7XLN1wuHFdF5+0QzbLouFbfXtQrkeFUiFuqdXJzb+iSlDUtqmTJ3OSrzHByd3qGy158lWeniLimvCMdetmDxM36oVd8pV6xomLhSB9HyoY7YeNdOCzP2OhMOBeOKcvpuACmNO3cfTSaE6MZVw46B9+zKq2g84ggDwtUHztYj0OTkQBD5VZGVNfXed1ybQcrs+TVKM2ptiLO2W7M/VBX+Reiql5aHy2bIuHsKhFG8lFgRfFLpKytO8e73lFf/7KS8mVgWjJ/AWKRqiaL3EsnW6ZifU38ijxs2jcPa/EjRMLvmJvEYuc/AiH8CITwjQMh3PMWYPkNwEUGodL7fb/x3uBCQ9Mj749jhHpQs1HJNTvLcLPCXbsybvTdrtr9HrfsrEHf85Kdy4640nW7FS17Srb+Ydz7n2PcMyjnRCOd5DTHmQ7ndJGNbgUTXdGidk89cLluMtYYfFH8Lqorq6koq5qzTkYu/WQ+LT31kbFBocirDnV+oT1tkVkLK9uWP+ftc3cLV1CXtItrwESNgUG33HYtpifYHXU7r9x0rspsetPiBZdyoE8Wj3a6mpHTwp/RROVrLXt5xBZeLe3kSVEbPPVKB+riSIo8nMrraWUVyyImuC1GilxgqL6XOfx/mlV7Fo8ogk3WKQm8syJv0D3GSmZFmFTd2a9kN6QNSHPbKjfaCoaO3kuPFQR3bBIVrsHulz20k8bpKXmuNcpjl3wHs+597v/cXM6Bw0+zh778s/T+T/PZs9ZT6/5P88XzzR/3f77H3yMvHvdT9Mhte/PZ+fpLdXMbvTXl91+ydCy/p1n+LUD/J7yuk2bqas80XumekOtyEFcM8PqNqoMxGfQcJurW9qd3H8L3W4dHNbtE7kcGRdaxCNkU4il5waOvSjoRd88pH/16bwedKeNhOqHUKdkEVrFItfKGwm7gPWJUnfGe7JirDu88TD1xHQ0p20pK/oDp+XnSx1h53F7g7eRg2XkUAV2mQ2Dc6XxmRP0VuexzGNQ3dCOFIfmYyQUqz2HbkKntb+hqqMdMH30Lr2GE7EWoQ4kzvR3bP4wxBpwMBRaFr3LvsWmazjrVqu9BY2dpxqd8ZOAPz+KLZNxp6Kc9naJ5iB3QKdZE//yCC4ibotgL8cARY6MQPsMwWOZtuk0cxSwPO1vHW0fd46Pg/f7O1m7vuNc9olQyZFWKZ9WvODHRD7VyrMLSCH5JQT9B3PmFElZdmnW7pl3H96pUzu7kr/N4erdCZSpnV77ASyMrVUeaKtjB+pcx6IFn5FoZTufjWvHshUmErlSJ79qWF92ENCZlPREe9NhmzURNDhmWbUhrSmQtAcUqms2mNUVg0Nud7scQ5rgLRMvSDtnmVImigY7jzOjUJZsxaQrWvjr4oVAIEmSATX7c2g17O0dWkHVkLbrRyqxzdACEGB51uztmNZ5XFN+kdFSs+18fuod/Dw+6h+FBbyfc3npvgkCHXPP46zNrlydN1lA5aDgL0mIqVCBxKzAUP/5SdLoDNDa8v2mI+RsLuaLt0vwKxrrMcafuM53Fs5s4HntNirGB8izTAsBcb1YLcQkNoZjdiI9mdN6o0F8vzKSJHIyrJ8Vp0XuhLanBlQrRTthhRqYU+LcmWzPL8YhEL1Cq1OVvNXum/4gG+7RShJZbZ5MhmogBE+E0HkZn8bCmJtnXWnZQne8JvmAGSMQVwVQpXtccU6ta0Prp28RcWZKSILyZJjNucBSNk3PgPcW28g3E19aYPjTVicy3BragA477m7R9chq0otDQ5oudiHqM8r6BP6HZZMBmUXi22PaJi0WbDVZl3eSyyIxZtEx889V/H3pT7KBIbeXMX21tVpRRizgL9bRdrW7wdCHAtB0TXu288kzRcVB1UCYVDuXWiAc2sPyTflYT4zTJzHYpkBijT8c2Dq/o07lJo23Col6l6us0bz1MRhfFh/1oVHx4LYiF2oTRUVgQ8tTACL88Qoc7jVjbZtv80GqbH1pt88MlbVMhR9typq3W5WOrffnY6oF8vKQP5pySnFyQfyz1nCNozSjeokOoMiUc35Ln/IKIZpvSefdFqS2+BTLMatjWagmNqmufv6xJMUhFVVWcigDpI7XXGN7knIZWe2JwZjB1KIMBU9HkHweYaDIZxrVptfaPwZN62KePqmmhHgkvooIvjOVEpInnvte0xq1eWqKt7LYF3pJrxC0fjXeiZhzgPzUFSm8CZM7HwS+Ti2q97hSRFMTVZmcv9QCYiLAESJlz3AOcNDVHevNF+WMelySmlz3hCE6lvRoJdzUxfUEWR9P+JQ0eVXXEmboM5TacMQSnZlYuCX4Yc8wrEJYVN4adhdpr6+eIC9rOb2aRd8cE71D53J1ABHh21GKc5cncHBe9MLqsL8jTgiBI33K2gvYZbCFqhrRrqAXm2D6F9h3d+KYtVqN0+Nmiwrjm4Efb419PbP0LZ55e+VK81BaTyn+ktVE3ctTJ0NMoyprlipGorEQKeeJRQ96gS/ZZre4K2KWweFqIaEbR09W88NjJHKuy9lHSvrrTIl1M8ccZ/pSAU+a6rVnDK+5w7GJeuf92woqi4KxNrSWi5kKyhpqCVP75i/+b8KyOYMqzK6obv5YQWFzJZWh1Jk40sSoHv+BYIDupaVctlasng7bEyZC7CJgKNRbou9jgVXyn5UsszQeg5QLQS55AdYAL/3b42BWP/Edt+vek4TjEnAEdIDeCbcOaZl96q5H/pojeT3GsnVyVAXVA50a1WJR3o++RdzCNKUkzRh0QtMM1Au+/oBeGDVLeR13LSoDRnWKcBowA54HUOxxixAOQmmKPrkOv8zsvRtyT9hO4p1VMjjyFKU1ZUH7a+qsbxEkb0VNyK6Kk2ROs0j51KCYGG5ItujQRo6BsJhf9f5VqWKn+Rc0t0b3y8ApLwYlurQpwlGQi6qbo6bpowzC2cqHlCe408zeNC4lMtiCJMLdNG3u6WGKitC5JCfZqKfE5m3XYC5jFGkaClc0DRZ/DHM5Cx8M0C5DjQzEZCJKbJvk8TK/4gowmG9+hqllIvFjN7Rm6S6bldKnsYVCGgtfggaJuQcqHamVlqeYGikX1JXrs2lK5Q+EU6n4GxkdGC648ArzmRC22ny8WiFxDWwxEknIRTE6/dMKTwq6Qi+Y67qtIFny+g0daVYyldFP11RlYp0pnYNU6HkhdAle1k4BiLQoFVhPz5YtiPnn3jGedVv0PFfASzdrDDQwqcwaiebZxDbQ2ueNAIw91Erz4/PdZs9ls2PG/XzSf/zj//U7xv72PFD7bU7GGYWuvfUyO6bLOwd0xRV+sbMmveDA7jImnp+eOuhmFb4yz/jQ5Q4/jcWVta+zRAa3Xy7xPwNgvveZz7xb/gV8g8ZnVcc1z8cO4n16MEzKeRjPvqB8N4zXYki5ns0nW3tiIprfJdZBOLzais2yj1Wg2gmbzp9ZPlcqxfgb6S3Tr9cURLihUMUV3pCSyKp0PxnMTQC+AhczP0DyxcZGmmJQTJSfUeDc4zngeJD+eVip4sjDPNo73d/bblccexkseZt58AiyVArhQPLZ0BIIx5VdnBiV7hqgMKOKIJwLMpTLwFwV6uommA1Gb88IOB2oa+Pw3C6DRT/zVm9CmyXKcMXpshwBsvnx6C/9ThEuWGkcYMoa4AFpOnt/CpODzzdbtZgvFecpLA20c4wYCwGt0EAuY4AiZNFF78Wy9eVX3RndeH9YTtL5GcNcYAIPHsb14Efzke2vY+hr9/il4iuGO15uMGApdg1OFLb4DPo7uvXfoGznA4PDc5bcHH5hIjo52Mbz2fKx1aQK7sDw4h+7tw1bQY8vJzYbqLAKM12fzMclA53PYt6HFylb/apzeDOMBBb7PcDqRjiYRxmiJ5rPLVFAnExE2QWSFnRKzgfFlMMrTn6FuD5q5hS4hVshjYZZexWOeCxVh9OAyGXqfovHFWuaiwOG8nwxwPMSZ1wVn9oIg8MjgiDF9YIOrkFSXAoLiZJxOsg34yOYjjAIEHTmiFetpZAsi+x0JgNmEYvqf3Xlb48E0/sX7OZqiDnfn7s6VeLsBysvbg2OA/Tomlw+KQ9ePGR/UM6DoC+z3zHs3v7gAXJ1H8N7kE4A3jpF1PkxvCFSl8g7jm+FCuIhJyYCubXjb6eRuSu4OrUar4R1iwKVP+BtEvAp6M+hhZYn8Kf5Rmg6VH8kkms4w4ze9Rads4+00nsTRrOKMOMub4XhMTipj+6mVyuBNHgBXub8E0Vkf34mobmjaOevjVfxH3hvsjWKsIp1UxiEvxxysf6zdv4VBZHHt1pRJtRj0t77VSNBDH3rMMeaSVb1bW6rmJhkbCE1elRKvqf1Kpfd+6213r3sc7nTfbH3YPQ7fd7f20MG8ETx9+cz34OPZc/poPK8XSx8d73DhVusnLNVqPeWPZ/XKLA1b1AkMyiYwACIVYWQwTSdkiMOe8Q8MH8/5CvDmXOArrxnOGC6zxuQuQTuYsoHtubWjWdq/jPDMxtuJJxhfHRe6UI5qNxhhirM0kAQ8wvMaspbCtoeh9ClzNLm/Y9BAEQQ4yczgYPwdW91Ox2MgCF7/PRHLi095u8Srgefs4QFpPOt743iGgb2An1ymN+jZw8IuufbAQiCvJDaFk0YF7IgiOkJzazRC0RiZ9SMtUCSlEkgZleSBhJGjshjj1c8EpwPeQm0dxTFekASGjpte28UOZmrxboCMvQG6GiiTG09/evqIvmKUUmh0/dlm66fnL3969pz4Vm/tOkYPLB47NQWzML6g4JYwvmF0h+wWt+fpxZzkDBwpsk9vbSCnbw0UTuIPyG8BBbcGjiMcNQMiLCG0uUgetJbNYa8AfQYhwDYkpkg2JmZSj4koKY1sLYHM6KAoreJcVFdxrBJqYC4yBaUicqBNkMRrtwF9xRwBmKuw1vTR7xsejwfJiEw/FEAUaIF3SJxKjJwpw1X61Jdf0FGitYPTfg00lGlh0EIV4zDv0RPBvbBEjdqXEQZvA/pU0QVvjdieBsQA5j2dhjXq4BlQ5FReMFLmX6idXNdUuzgyA0TFYS7lrRIn8wBXOjDY9+T39hVL+N5rWJ94V7gDOYV66NHcN032mQ/rnJ5qfO6X05NGFapRWBQo9ok2b4sevgYbNCHq54iUlUWgs/d6r4BJxwAnw2gcF53uoPaCMWEe26Z0SSIAGy1rxCINM5U06rXwVInqoFRvvKaKPdxVoOM9scHtAftqDWpU0veic5TjLDsK1Xst6r1G8VOr1KqvgmcyEKjotfRLoZpzGTeNs46mPCnu7bGLEazmAPfh5GKezo0TJijdkqVfy9LNBaXNILrYGBmyWnWjE/kakjP+fjhZZcaTcXgO+xDIv7jVJKCD5A9y50z7UdSfhcRdO9DE2+7uB14bnUawmsOmDhIPZPWfFDlC/cypxewbUpP1pKQi3xLsN5kgdoFgIoxXWT5si5QiulylRmwv5vN+y4BsATPR52AEXHmHt+MaPlmJRG8lEcHIato9NPUcOux8ji04X8BAVqqgNjlJaVsz4RS9Cr3BzsXRYS5BYsk6L33v16vr8CyJMvaiw99hhnq+JLXZbBwK4vLxjOGX8F6kpjw7qEER5YW+56QFv0LcUju0sW5sOMo88vb2j7se9cwDTQbWpHcDksPNNMX0ZGNU8pRgBuJaRqFXMa4rOkGAljInl3HdHMD7Oeir11J5tG6FU1sdhRAkcNXVx4+99UbwzPIpAlwaxEjYpuLepu8RliW6bSqXaDbpUT22nXlhHpwtOco5wKrHK9H6a9+D/Web5AkSVvLTFBqvHDpQKaa4whI1rrPpW/OPYPT4OvSwHgD1jOYzUDR8DPgAtYDJPs2H8quPV/quaS6uKZsTfjbFZ+uU6ANt/cyq0fI1wfwAk8mdVwMaQAmNHPNZEkOBk5KD5bOHeEZp8FfvP7wrzmM3SUHTW4cerTfrKis4EYJdCz+CLD2f4eEhBlVf13YGUcacZJpXrXlc7PQMmr+ua+0DHlo2UrcdTAIn1Mk91EwvZCGvUQAz2Mdq/MP3RsNJSHfEO0+DpbxEsRGDqRQPCJWAxYWLmx0m18qf7eIXFDLuw5GgOG1JClKtuHrE3OUM1nQzMVmphhSFBvlFw4T8oiNBfdMZrLnqmf+1PaV/8TliLn0PUPr2MdMB0MpwiAdsdEQtFOKzGF2HWFmTuicGYnZJxhFdq1cagHpYz5UxLPIKdTFy2EcBUZxYu/DcWoBnpB+xZfMOgFIsc0xFWvZNkCFyM5SvNCmiQ7NhC1AmdJ2U1DdBlffa+G+lT0+uCSh6qeXkBUuuXl+pIvQzr9cy6xUW6wHK1N3RWTxwKWfCcg8bHZXzqCDZJtjyDXvjEBgj5cUU+cyXaF3ofUWe92Qmmqh7+53mcwwLM00GsXhPYX5CNCZkHWDiMTaNiO+8eP5yxZtEoi2SuoUhqiYf6me1WiS4vODEEUpB62Ao7Vp5De2tQ2Qhtixbx6P9da1l+F2nvcxuAAs+8ZpFcHcGuIYFrlEGrmGCYxfptTmZv7l0m3yQ0MbC5n4RIxo9SrHZz19gNdF4Pn9ZU+f7eTvaJn2nfdfd6ugKs5mUnRH0WKtrhcjLp1J+tfOYapM4KYkpaDas/aqUCURogmlhfAgmRI0M0UdoOo45r0pnooVLZGR0nNRQuD4Ny63gw2VagXFfkB1x+DFRVKxA6wtO8WPrUZMfofaC44DnRV+gUcCCK+eM44yTIbovURyd7NfprNYKvA1vbLkvxUNXfzVd3dFps63zZAgtNR2R6ALc77gQprUJa6s0bZoXHrb11QTcbd9753ufNBlX23rf9P77fdcbpukVnlOiS+gtLT4k3X4KfUdzj6Y+iFRS79BeaawFnGhcpp+Kb1Ca/YfpGVftjdGMxxlBOQPB53dfHn/+9KVOaYrGazPh2Mvne7XPdmNQ2G7lSz2olsuP5m4VnA/R43hcaxVkUsDKCeaJAgUSmPupY7eyN6uwt330FRsW1HqwDQp//9ig/kduUI7N4tvuUhXbMsbi6/On2sTGo5BHAS9argk3QBo/EKmEbAXD7BawHWFqOIp/naPsHQ1N9cS1FeqysL4XvtC2QNWgShUGSyVX6izHNzRs51Ctl9CFw3j3A3RAi0jtl/RS71tZPzdVP5u+7FzzD9o52zr+lf3Ug4bxNOemWQD2zcWk+9hKkWhLrRT2i9+2+4jth9wdDuPejnPn0Zwh1tkhZJ9yynmH8TortOdJnzwzv9kWhCyJugraarPRaFibks96fafZcphJctsDvL6/JQZLx6Y5Jn/E7uMYTeI6iW/gc4GVJq+V9LMwlvu3bLrEWCOzQQplXZbOkji8TbLLeacZQOuXN2JQzXuamwVShdIgfhWLaecZHIRUYh8jbKnvQG9GYdQJUPBLgF2O+3dCteYUoOTJZYUq1AeK0Sv034YniY4/R8BfJiwqAWAs2ap4Q0ESpfxiUGZxYfNzY99VpOrgEx31bXGU0gX9/l37vEi51ToclCud/WEWsk8ZsdSDaAqrBsNN6mk9m2TNztu1LfRpphCzCIbeyScLIcLSFfEmeRGbb3E5i9f41TrykIsP8SC/W0fJYkHiLiO+appSD51FKQOkd9Tr5rK8TuTiZsorEU0Ce4E/HGSDXViKGwHuMQEqxTXfkZ+P+6FUk80WkJ4GnaDRcgUgWBNt5GIrBRqQvZ+kyXhmvVRiLFdlNlp3AmdBGdAV7orrSxYINRN1faEZmPxtyPueWLMQ89Ao+a3U9A2JaCmpPBCJFPmL4wCwo7Z7LZjPBL2UTm5FzmXa5W7p7gohaIjeqiCBooHJ3PuFlFI/RRZgn0nAv/3ozpuC6GV1jd1+uGMsm+1i/BbzkikfTTkSrmu8vOQYJpeI1LcVz2YqLlknR5nz7EZiQp1dATpPklNT/lFfi3c7tRiaApv2VGJt8yjFtZs98rZR2AHRNebzattfwjg3tnAo5KS6SOGnpKhXXmPRUY9jUai90bEoHMXVNqgVtw7jJpOhCObJYp84tNcjI+jPhWQ+KvXVZdMj48EyOZodlMbHkuW9ACptEWyU1MNcOUzC4wD7HpA1MRrPsFEmzobF4IpNOU4/VwZZVlAOGGRwgd//YCbwCxRMLgAzscL6OBUoD2mll4TF/LympnjN99YUeaxpmQcw0EdfEe+i+JpE16oe3g8p1DQI2vdE7utJmg47a2t22ooVNQZr8Zgaw1etIFt9VjqG1KOlKhaKu9wUo5rFCfrCWGFcSkODZtnODdqYCbioeOdyrmH+VdOjJGL1JIhvJ+i2+ho9I8g7QnD9YaxX4xsv5F0vb1jIuxmmlTn3rjvJq8PATzlBfdOMGmRIuK/kzWtDsC0EZjZOXnN5+4kt8z625IQThXn5SrXxRE7Aqbk67e49dEdczX2DgTsGZ+t1btgVB4kJAYTsO8ap2tnwSp2rsSxQbALKFM4l1GZovMGg3PpacN+3OGkD/wPSoi/NdtF0xAVKzVq0HEMKdSFMKbwm9SeEPe1BMcrMwjWbewTaLMHEjtYVoxd6B/xKebvGL5dBMbemGalh8K7CSO6uaO2wQw9RARkVX8iOULGWF8YTykmIZhA0rnXW+pP5mi+98MJ0PLyzg75TxL9OQ5/tNYK35pFHuWzRCiem9yT/cSKqnhrg8pQ3XwdTq28CnmGK9HhqQ/UePXpE6wAUZDPNfHr2iwm7KkBUT13aAZpy8bwR4fCMBPS3Zu3z8Q2fExphYVQMDnHJG9p2hykRo7ni3CAZmrxqVT4OD6ol2Rkxx9dVIMI05qV9r1p1BtRAAclsQF6MLm2CHLfH82Jgk3Q4CKn9ypJe5U24+yXxdnJFMYQcIVc0gpCFKy7c5iXdKEZiQcmGKOUK/U3XMEOa9nMyjWHZXCSzjB+6MtA58IGAdZMW2tuFjCeA4zZKV/5ZWMB0mE+LwB95b8QlWDZz4oY+83p8FYcufybwfpZ6dDzFJnVq1zSk63/7vtdTZ+8F25vWUcv1VIWKwjlRHpL7LJQgOIffwRUeu2tyKFtwGLBKtqZe83MXEo5Turvyr9iDwl6cH1jjbRfW1XmlRTPt6hdVIIlI3pGNBwXPY33GcO6T4TBmesi5p3shCGYgKnHyEJyJyzQFqZMvb/aH6hLsmC5dgZ655o7Qcm2KZte0L7bRS4G+ttqnuYDmqssIChU2a9e+V9D0XKbWu5Ln6gLIje0VyBrbXUmySi2TWR2WcIA5IcLadVnuxSedpkk4t33Qxh2BlhjdnfK/7uHh/mHpWwfaBUgmx0FK3FAEbsMl2v78pa2xEAxtmhWHqBmFkO0E4naZExW81Ov2yf0uhkH5y8DbwH/I0JAFa38R+ShVZksdmErbiXnThUZmzj6e3Y3OfI8/wzFa2S5Zx7xJBigRFE56HnmHMTveI6VeTEEMT88RAMcjUMsu43WHIgauPFpheecCb2sQTeStfAH4q0INbICMerbRaLx8uTkYPP+p2X++GT1/udl48az57Pnmi6cvnz/ffNZ6Hr9sNvtxTIE8foluN+gyNtn9gsndo91Wiz0ExrAOEQ240SucCE2tKeRP8UKYUcQvQoSshEuRFqX42ciFWtXAesdrMrwLkK1gVzSyrZGXGE6qBr7+WC2yul4RO6tgbGyYBwCCeA5p5geOeRIzA2/bGKU35a9oSKfjs0vihG36CQRhmDe5b5KWbXyZlCS67MIW/VJ7BewTcjDq2w0ptOo+grqM0HIBfRPQhfFJOsTIfdo7Eam6ZnSLheXO2lkyJOvB2rJ+ap1ocT/qet8JOKhuYvnIOwcMwWTepXRksnB5x5zei4WMVIz7eJiMlWdQp9bC2+XN1st68XBbP0ZuOI6WC8ZjeNZ0nDcvPx1+VkhTIMXb/NS/stq5on1Kb5wnlh3Il5+/a1ZmSs+Q+/WJYeqHQh0+crCQUjCwKxS6rND8xjZFO0/j875odmkRm6Fmns/HExhZvP68ruNdfbNnyPils3Ntmio6nbGcrKgMezucT35Q2R+ayjgdyXcnstYSIhMBPVLgetEgNM37fCsMUBtHfFgBQ/a9MyWFbM9n3v+CecxmQnyX4UJUhJ8RvsM4OCB5e8lsLeOwDuew+aoyIu4R3rM+/CQgv49nl+kgj0UjxZJJnGJcyKwfnGfzIB7MN/7fX87m06toOphtTFBEGc9Im8o2aCgYx0IMJ5gMzjXLPCC/Pzg3ApbAgNLRBDYWjBsJChBGOOK6Xn8+msNellxT4AmgzrM5beEywoptGao1A+8JO5vHU2gFJEbd8xzEQXjSEgEdQKOpIYpBs4wACS20Os4GdVRr+fkrDwMjyOdtSyqtUhmMtpFOY77H1MKCPCUnOGOniHZ5mmHMceBVSzLYVTHAkDFYkDFF9MZRdIe3RZNxP51OYxAlq74gLo6VxAFomKZqBoY/MgBMZ3MRjymyL8X4Yd0w8tSsAc0kFBLE6ILMMMTAZrlWSbFB0dgDGt32zhsyLuAzMX86kECD8DaeefPJRET1GKY3GDt0cG4H2h3Kw0UkmRpOEuIc5xAnRBWbG8XO7GJaux94cBRAajiU1y8JeQLFPHlD35uf+jxQErhRoAL8aqBOWkNU7Fvz9eZpPjQRCEMgMawh8Qw5MjR+nVP8DqNHWY5AxIAS7wmVDjSinIpJWNWMacCs5WP3CpYENKWuIAjTgWoQAE+Ai6LLmGQ8NgRYjWENafyxta7sgtFgENIiss+BRxNsBwqh45nkTKT4c9N03mxD62M9gJeMOxFFxO2cFYzCIn4IM9ZyfkpegXhq2kQ3w856Cz7OOq1AMVcMdtL2aseiDkUScn7UvfVXIlgV8/dqtfoGqCoTiwJvShwXCWwwjW7GTGaRNYmuRUPxxq7z1Rufn2MMqesYaFgDBU2WgfDaOFXtf/4DP2Cz+rz3pfaPWXw7+4z4+AJ7I/0AnHz5v636P3N2IlpN57MMPcYFGGZs/wS0c/O8x0D7d9Q/rCmyVyAazjA4fcajGPHmMs9EjCPBiCQb4TgwslWKdURgzjBfGSnUogeR949h/KunjYEfnP2T1yEGz2tbJNTGJG/jdZBm4CeH5vons0ueon/m9z8BYJs6RPw9PS/jZ5r7/IArqOWHEXIiybuXVY9Ea7BJjOYj2PJmsEUzGvI0o6JMdOsu0721Qz2/evXKu1FKVzyazO5qoLE9qxslnHtT7aZueBeLBXZPYaXypx9/f8g/jv9Koen56Obh038uif/6tNF6/szO//ms9SP/53f50wMnPkDwQ5XBU8QTDrR4wjLWombT8XXVW6pJ8/HNNJqEueGScivFMuKy2LtNXyQVjRltrqbLVZXousoHYBxjG8XQYuUTUfK0AMWMz20XN30iqrntd6U2teIrN6zXqeiZZZYjpJhmRdkRvBzjdL+TQIpwkhglMG/UsNeBLDGtXcV39ZKD1jbvXDLTgshJoaFGBfSWBJCMz+NpiCoPiIegEU7JWFjTXNBBWAddO56h6VR8u8kv1vSwPu/R6Xzaj713t5/EzT+ycwpxTNzv0YzFQMXKlBBoEQB15/e/GUmdi+jUy8r8hQz/OhaIEz2WfuwkX9bkgFCRMZ6I/bkPBIRx2vVcPsNklMjsk3q7jx97jUBs/uckkQ44yQ/7d4J6wjWfGKmSrIH+RRjCKwuPd9lsbt6NR9s81TVOoTE6CCW/ql3GpmG6Jo9g6HndDlVqoEnDz42Vk62f0u2W6Czjo4VhelHDkDjC87YZrzdbWFtHv+XvnCNZJf8hsD5BvQR9Lp+mJ/TsJn92A0PBQQqYYk3mIBdRzTZHCRKRpXJ6XM+PL5iA6RRM0FEo+haipImrXqJQoFYkGcl7YKxbJBqBcZ9+8HTIRSiO0PRVmB+n8bqSa2/xauQTGVhvJ9u7R6dPaAW6Fhx2oj+c01hbzdtmAzWu5vPbl/pKFLeSqXnpKtDpiMfctnhcdNykShKQAEFRNv/c8TY9CqCcg8ULsH/GyJ328/UmvdDbwmcLJtfMdqBltXJhgSODti2D0XmV+9D57EDAF4l1+dbAw5eq5VrFddXFIf4pDvL0AuJIKH8vT/bEe4xzyd9Q8yhj2tr10FlNg6yOGgXxqXVl/BRLvF7aL/NITTXW9B299AsTycBLj9vMBs3jtlwfzAvlTmx8gLBoXNoVWjqXq54l/Tn8X82fR8PkYhzCEgfFWV6kXAkdi07udBQZ/fMemx0sw5ZgIXzKahzz6YTl6x0yj/nUKhZA5DL+87JlXEwwY62RA9d6Ep4y51EyjEFz/+xq+ws2bq+4lRaT4C0CnOCd5KZIHjYYeZvP8Kcx5l8TYnFNfvE1mUt3Y5QcT7vPphkWXjx/ub7jYQbaj8mxJ2FJsUbz7sHo+RyXWsp46/958F5rEzaKS8ALhQaWlhkeMIFHTwQQzvp0bxSKw+4krOk9EuUjlBRjkA+HbfLdk4cN2IiMQevT+YJ5B5WOadBneyKNPudsVcfozyAy6ZkoyDOXTUqP5bjYmf4xhvGX4Xs3EDdCKLom6fKsSbWmAjaPisp6zSbs3lyZLrVEVAD5IeHwrOkL89osz4k1SrPZ8G59PiaLFo2JnYaDZnODfhKofjpJMGGCPouGc1AuzmuuqaYQYpKE5axa7U/mVZezqkWZ7DjkHd9NeLEs6cEKjepsBzn+Mj1Nk3XRk1q6OeqOO0xMnGI3F2uzqwSEr0GomhLPR0lG/kh6WbHyQv0eK3o9c4WI4OAchuICxhmQFiWzPNGcrMknS4lJcpsiZUXww1xx0TjSGJCPZF3sRMXI0iYhyLTd/MS6ImiMWWW2Uz2pL0o1pbouk0yWtA+SUlX1sUoqKTM5BaCEGZ/kQE4LjNnuwWLRsej3Jqv6jkx5duPFMoquio58q5e99RdkAXeR2OdiUnAxV4SdatujXPA0GQJhxe5UxcCMKqUIL6+Peyzm7XKeMeKmXo4jB9SllW4dlayJ+WIQ4MOQWL765eoonwQAAgjR1nEp7riktspXm1h7NA87uV8WrnYHEHYqVZ3KqzNrlQjLqwjO+wjzC9Bui1HYZ2wzuYwoJYycfhBCcEP3RZh8rxEEoJtFYr/m0gKYTARPKZXw4AA27k8xsNhhckan0HiMxY6llLtSMPijXtdXO7Ofw1Kql5fvr7ihB8qwoXNqZVYSLLTg4t4f4hFPR6tkhAXAt5bvf1b0+9e5Kdc5Qe9FVdiyBnKbJTy/CGtRIAvnBkG16m4TzYJNQF21qv7WRpxtmGiUUhKgB6e0pBjObgHb6INLNkWgxxhzBJ3dsYxqCIIkb4qNHaS+xR219noam2ublwukVff2pVxritHUCT7/Ff3Q5FEQMFm0zFSXiKbfRxN80Ageo3lDl0oJRY9pU4YCTaMAIefx96J77N5CutfnFAaqLwNR17UM7EaaSxphiijAb9rw7ZVSmHKhXnTohglzxPr96UHDmQYH3YYIvLVZlUmepax4Gv86p1xcunBRVVdSNbuAJsLpD93XVvQiYtYaFCgYI6aXl2muVKi5qBBNn/H4S0VLMRtqAxbJXtWTdUouLjCsrAZ2xdVNA9oZRyI1aj6xx+jUY4zHP4xn8V9VclrVE6Vc29YBoX9hslKrWwUbgSAYfUje37zm02f3sW3sg57nfbbhfMlZUt5VkRkIVEQgei75V6v/VWWDRFfwITNVtBagRWH9db7562Ohr9F8QEcOOo0qBRBlrtnU1iU14abK3RHpf0I2ZnNWW3toei2xWEpq8VujgpQVC2VzIdIoXxDxoUrhmVZeioQJXofD/kJ5zUCnl/llMgrZ+MEMIM7KqwhOgVW4cIjGhhDYSyhQQDtMSOuvimkz547qoqpgQQtQXcqkTOwrWxq6BwMIdBDWeIEgldzgVeyYmHW5Qkg0N1Z8XWcQwuEyp2zcB5VYiXYpRermam5XfaZPnWWI6S74c75JptLSRI3wtSdVIUNgefWT9rNTw+JH7Qh7n7TFUPiPqygZAa5qMh4GBWCgJGQYdTnkgAxhCN/wYRhW1D4sygWY7bJW5RgPVdKT1rV4QtKJR7TjiBJCDuZsVD6PxmE6n1WN3WtZQJAFkTsCEbtDbOpmj/Ee8AP0Nxl/n+6q6JeyzyJaCmeVKg6gND7Jih1x0IoWMmTkdGsoiREjW3JHiIHWGs2HRKGMZnkoEqb1xtfRNIFyfLVt6gpu+X/iabqulidsNCrbWsSV/ioXL+w+vKZYlMb1LczEdPC3MBPIWTqbATeD7YauLjR/at0jTOMgvRkXk9iYIEXWHCsagJYYSuQEsWHPJwZkG2gp5LLVojqsZrpsgUsIFE9MVJxPRLX6PdLMqegac5EcAlNKqX5wkghJGWfzZDjQLyuukgvKiI8jQozAMxE/gr71zy98cSh+t9rM5teUUac+vwje7+90d4ODw+7x4VZvLzzYOn6nbQV8VBL2L9OELM2OGtvv9nvbXTv8cca3Sowq2/tH4e7W37uHVnAfzNOrl9vrbv9cLEKHI6LccffomIqFb7pbx1bI6HEoUuZ1cCu26C6Lw+tzkP/7Edrc03RYQ3gHH2FZBR/fHBzub2/Vi1VYQNFDihYq70LN3XB7f++od3Tc3dv+uwPMLJmG4gI4i9cFKMe9w3AHAPR2d7eOe/t7DiCsyKjoP7ViJD13j1EtLuuII7oIJ0qMsxnQkGBnIFeBavb/tfetzW0cy6H3M37FBi5fATYIkZLtJPSBK5AIySyTFENSPkkY1tYSWFI4AgEcLCCJR6Xz2+/0Y2Z6XguAx45TdYmyRWB3pufV09Pd0w9jaiJ6rZYjPzz5tX922D+5yF8cDU4OIjFfMQiKomm4NCgjoqpQgTnoX/TPBxfngAD9o8OLw8F5LHh4NSwhjeYM6j+TUcMt5IbPx5Bnhrgxy8mmHQJEQhZUzSs1TeBDg4cKv0/OX705Ox6c5Rf/eTqQwfvQQM9uShPNE3/AaWqgQFjAl30Fo08BpnZdGF7Az3j9Xw8Hf/ZrU1weyFPe0yTgMt33KxdPjCcc1Dg8OX17odr5r0GOW9pVtlq3L29MbwYd744D3dq8mXHLoK+bM26vMeF/J5q7ODs8GOTQQ7e45y9naxycvTlFWhYpHyv65u2FW9LzqrPF+xcXOVY5618MOr74Z3eOudRGEqzFQnP1xpxHQGF7WRMTSkzLZTMSJJPvik2YHxHgJxJ6pnnETvfizlsEoMG7289fDOYLYF5Uu1g3zQhj/UwMf/3NfzxIBAxbRjOquY2ikYfXDYeC1wIeiowEQgMBMVVG+Pkx4p/WRIcOXXVR3qGyE/dPXxFA8BcU1gKQ8kSJlN1moufRWebr0M/NKdAnMBb94pv++XZyb6fq7J+j8JhFz+l9ueCREBdOD9zOBvEuNwvKZ5n4MDifOas7AcgaztJC5KiTCaHBq2aZTC/57d7I602yIuWvYam8IgeQVqyLokqki8y9RkLnCf4ksqvsScxCghpIUuhIDSkC7SEzUwtmk3mqB1A3azUQEsgWpyobYl8NsUm2vg4xPctcYms4rr2S0iLRkXUZ0F2XaAVbm16ERZ3UZhMtOhutEwPioIOoGS9N4l5n3ayFA9puzU39jZfcGXPIU26z5JHGN1rxiGDJQQllgELFPI1HlY1fWPZ2XTN0eAZncCSepLU3ROb6U5tsC72YssiBmTT05ogNJ+2TH8E0KobUTJckbLJKGLGJNawg5emwDEbIEf31woZV5YMhdYgbcy8SSMb0aHhLQPTueSdVrg3rvbOpRaX92YhsU3XM+8Q/KAS6N6dgIOCtr5KU+nDZYpHUfinLObIxxnQRWCdtMD6+nVLKDLhyLT+BwmewCyGwxsv7biKqpp2xjrtO8K87WcUKEPpzU65gc99Z0C9JXIseomS6o6m1XOvgZE0vuQvkehqCEIjjthYCUmPsruZ4s/o5amnUdCHgDYV80FlXC+cabhRSR1VLDiZh79Q0BI+iG2p4ETrYSkRySJL9+plG1Aw7FbUAqsUtuPr4ZBFMvHco4Kd2HU9mwxlHNSNBhF+tMAE3E8yXA/42GP4mCcTzuPmH0dUdKPQi26F+gUm7fPstd/cbr9HGQ4ijnjyhuVMyY3Gj+tqMhv51WuJnAjJHOQfj2PGQfOet3hQPPbw2bHmxboO4gzo+grXs3caGWAhsSfPh7Vpp10TvZTm0Nn4vBdwXE+BUSoTWtxCiHpW+U2g80G5dsN3A9bPG/fMB0AP/TmvK19E2WqqK2mZWXTZcLTDMZy+MtegGg/VcMOtDwmrbIbDW2iCOLkyAJZU4AQghEhuTR/FtL9vbOIissabTgwVyxd8v8SXbU8JmFLa3kTC1biUOyuka+rgTH/Y0zpxFB7ZGXZWxpipj64cepKtkQOp7O67QkDuh46NHw1druDsQDAnUHp6WGwfSDjZiTDW32c7aeFfh6pBJVBoB6/yLfeT+4idGU/Mhdgq3R2HShkvKdbj5IqoO8LSacJMp7WOjkees1M4vUGNvbGqawj9e8SHSW96+Z5d5fs+/Og3tQm3jObTwCs1I/vGLNi+yXHib5+QqqwHEN3b+2ITnGE+iiESLraHzkW1QvHadzSme2mPYjt/sA2xfWVWzxVPz7TcPAVIb/+PZ7vPnz5578T+ePf9h9zH+x/9g/I9h9UHH9oCzUH//SzUzMT+UZHQLqfT456zS3yiUk/6FUvPEBAoZ35UN/UMRiPk9BhKZ18QaMWGTFGFVZeHnA4ORkO8eKYxWkLWMyhd3c45TslqOJ1UXs7Dpl/0PiqjdlsfwzCukjoRKFzvby+/6p3mpzhomuacv+y2Sw7RTvHtxq0S2xWw1p6u/76yhzBupeThdzG4XahOCC+PLEtyNsz54Ad8Bs9N6Dxw5nDKD3aeDPVZEtI17PGlXoQ82jjMpw2QycOm3zil5oEp+fa87e6+haJ9hfyDXIg2mSb85xO6K4BTQUQPRxJ5wYUkrdcO/vmK7JgW/5XftUn8Jo79TB+CimiCZ7kPgPjv31OUuBLBqBbVN2AfZB3ql2+OI1CS5mTZleSucIeop+qKESIavtZXU/i5rL/fYER18aYfvmGGfzCrMfrS6sxAZjJJwnQ60u/PZR8hTDIX3KHMelwRmmZrmNrBhCIPh2RUg+zaqLIrEp69NCWoU6zS9bTlHM/S3AyA6budMJGfFIhBbQGa1oG/wdgwphut2Tiepfcmw1HSU3xWfcgTEbAlbPpkNhxsqE7YaEIhwdl2Viw8lpwPVmTU5tPv1bPkOHZ6KD8V4Aje77AX955/f7hz3z86zd0VlcH1nXqDp+A3kd6RcvaUiKvfEr6sJouRbahutFLWc3XFICnoM/ZkNFQajPzXYfL/GUYF1C/7slwtFLMCzGdIqiFqo9mxo6YkIqN1/haYiHav82Dk8wJG+Pj3AxSurbvZyob7smMysphrYDsIFwBgjxYLB+MyMhJan0qGCgJXDGVuUiqrhNLru0A+mU0q6EGW+FmhRF1rl9JdjqkYZMNgIcjSGCPtgUHx9n528Pc4PT84v+icvB8xvAgryuHqy1adPRbMNjXZgRh3dPBaMs4lkgBiiEsVk0hKQuuVf5U8Oz9GuD4eAQ50tRgpF1BqYdTaxD/wFA5TWMZ7Gt6vZqtLqGpGWOkrZtjoeiMbtaCKXqhafKnHC0I7sOWTV9OiyZbLR+nSgzcSKyCKVArKIxIbPkd0HdY5nyx59OC9TRXQom2sA5pkLyaZ3VXzE2HrkU21L9WvBwPyCkNWjumBw18GYlMOyh/2h70IG2/JkhuJIFk3RZ75rblG9Z/uuyp7QgMOYU7YRpjnpYR08ryJJXHA2DCCi45D8COt2b5ct77qPSDwqCkL1vMZl2zGMZ6taX02rv67K8m9wxrW7y1lLF+3ihLpttFOdNTyA6cVT7igFskXdeFs0Fq1fRYabZkIaFmlyNFYkx//xCEahWRkxCA0717Mvqppx7dptlmt8dCuKqWfiZQt3i+k9g0FitkXkluavCsrOK8MbABv8sq/Oj2E5hjO5mHqkiyLWTmfusR34KmHn7OaMUjI9W5DAW8yJgxptf4rg89Sfm8Rqq/qWaSFCKKP4EMunqDx2lk6PSttKmpVkvlCA3fUWVocAc7aAHttOvBkd/sjyjjqLhwHLTGhL2ld7DToT17BbBXhMH83azizJVdJ4afEpwGR/FTROrOHCW4GBZi45Yv35pr5tZ0EbIVFwMMMO6YFYgQCiS+rg9I4/BzWYEl1nMKwilDC8jtzRahvL+b4JyuOmFzudMj8SzjhjAAbGr3zFskgjVKZLOMQoIkJBWEM6qZezZTGR9AkLf8uW25Lv1wsLBYSQ4zFXUYkGG2GRJjXRHbcLHdEYyT0kDYTmDC15zx+KPJaJEpH0Xr94enJ4lhW3i7JErnw+WVWZevwtPOYkjZk0ioez+0K948iMflBLIQVBELxaNpqkGgp4I5tgcRvdeMgeLuOOPlUt65CX2j5FjjoMSlbHSjo1teAQffzMCVV2e61md6yOzuUY88tLIkHVLsfTUakT/u6w/IzPLMvzvH2lweVTBEQ3zS31QKGYemRpgd5dekEShGm3+72qCQAMNkHUgLFFLo91JqDjRW4BcydgaN/o9sKOMD7bBmEIWhPwrQTJD00USJpdjOSHc0VULRZqVUT7QatjSkQ1X5SqwELHFmMz4SdV9mx/LyuqOaa1YJyMRTiNRy/FQHW2OzreaRjPVBb6WgfFDOzKTAxTWTyIYZqID4qBQQmACUyKgTQhyUgXNDxuuNOHBwfFCItOHFs1OZjKDC2H9D2TXCeOE/o7xAdlsuabXHkGQe72DKhcjTInc/Y+xKfjVDtqoXct/kFCDda3GOoIXi+a3zF7kAkhK24ubMwORczvSM+hUzlosdlm+KPwc0T6sPwNOA8jJOhZpckrqIuUTK16gooVQ6s5t8gEWDvojyXJnGCR7OGef3pu+juFmb+erRbvZjNMpAkJzsFVI6sUHZlkFeWauBtXi/IWNOaFzbrycCIP/XIcuGIknbJdVE2DyY4J4rjyHExjiop0O0A6aGYYrZlLFOkWE+TUxbyNtBPAhYUUFugjIQceHOb70nxXXbD9kfrgjSk+A/IIv/801jtuSTPm9gDQffvG64xzHGj9b8M9laO9rT+q1xzX3oX/5ke3cDmq45BhDg1VgfOLvy/Nd03PK9amD7daH+6Vtz7e09j6WOasF4f0TRSSc2YbymJihPsGdt9zWpqWLdVmao9PrJblkz4wUSvWMt0z66A6FAJRDN4NsLxwZuSKFRoPS6t6W87m7y0gRZ17tk3nWmb5DtAG8jX3BETgt3f29q/c645FORljgIeencKuOu4NDNTQLMXUWfUG5BRDi6HZqhINZcWHGXD7BUYpm1N6mmJxnxV3itfH0Cc7y7HOEa2jdrJVHOYQ5i4pnLDjBS5DnesZ8RxCwINl4bXzj1nJRzmYaMMgS44RYnegN5ksGexAScmcBjtZrI318Y7d1l9152BuZ591MkAl/k/nE22CUQ4k19bB7Z2Di2jLanqj1k/ci0mY78vFtJzQtehzoAmUyE8rZNEoBFKCtrCfm8yCTUqamIZO9q/hTOzhZOjIz+O78QSuV8mXV3Td4p+VsJ/hpnbG3XC1A5oRh+xGuQEOF62ypS7sViiuxilyo9EoAk2MNnV1QUJXZFJvq4vhp6EeRsewcI1SSZq1bTPfxyrSHNMALj4Q01ctVyAem5NS/zZHcg2np5HBnLL829S1zJ6x1v9YLO52MJqY6rRMSAhJKmDDjlYkcqCeC+7ixtNyh+yyjLjhdto7EvwRCaIWDC5R1Q7eIYnOcL2q7kuhY4gASDUfvI+DcdkI5iK8KfnG622gArcslwtHJMvy5+qbcACNqHrdlVlFd63c6jYvRFcKSnG6mC1ncEi8KKbvtw5IgZYH6Ep1NwOyv7pTosczc7PSBIuS5hbRRjb0JtXNsuILvroF7lDrRT1y35AgoGb2enVz4zsqNOd6Nqpmx7lmSoyax0l/2r5q/d+87JNmStnZgyZUHb6k+OpoVbT+ORrNybpSiOu6MCQ00d/hzMfB2e7zfVa7a68tW4Edh4Hk/N4aGqg8R3MU5kBc6Y6r3NgAKBSUz0WsG9+I+uNsgSwQFsXo+vAAz6yWZz8N41alQAEicrmpZ+/LlpkUUlDlViWC8NpXkWulNDRnYjaCiN1Xsmd+WygivGjpzop1btdWEF3yECKcBZBxpbefbSzi7qdh+ZWcBr16ofU2N9vxwKWQWEbiUNiUVxjjQuwsmmcP39peLc2oRy9+Y8TD7Mw4IkcinZjudVGnmWO2zt1OdLzR7sl6Tt8kEBoA5Pyy2Iov6HJagvNuV0XwHrpHljPzk3BxmDrXeZvPtKh3CU1cBffEZor4/VPZB3oWv8BtJzonT2TxJjBaI9nI6zk16BJ3/21KhCXOECNowmEB7CC08a0+PL4JZ0PaoDGJ5xP0nJ3Z6k9SxVAd84GU2W6SAp3yDpvbW3QvG3+yhlPGO7k21peD/p5TszmxQhbz9zi4daotfrImiI8ubZ61k6c9FNU/2+GRT9K+HlH7oSe/60CSojlxuhNzKXdGES6Bw0R4LvOdVFCm+tHglvztRxJ2XdjUwNVgZ+PBbMUgafs9fcSYHukH2iaFf/v9jDJSLlA8w9xHwAiFp0zNYcK3o3EuyeszEDT3yW/bnDsjdYTQLWkvx9NsYEAL/7fwhXb9mKELk2WE/KK76AkmzwF0FQ3csU2r3tJv36hdtI3bdNd5+yZDztaZ7nCf1vO57rQFe7q+sjN8f/unsMJjlb3eRzhmeUjZmn7HIxWFZait5/V5A05b91BMTkfCDqn41qTSC9phycekAIUE3O5LwijD7dnZ+da24gJgM+WAQ4hB8SlXKCp4ZEs3UHu+0gEV0DH4s0ZGiJ28umtr5RHRueQRubFoIibEE07sKtl1TfS2TjyRYHwJRb7zhxLj8LVNpNu4a42qzSKNRWR7vy6Vy5RsrVZpS2tvli4RMggoTi/4sSOjhGy9s4SCUw8EkC4YMbVSaOgBIobMxIfBXx4AR96xA/b6wYMQF7o2ol1PtqVHi1Mfl8vuxp/KUb2MhKpKR0rSPfOEJXq68XTqJdJ7CG0CvOiUdmQd6mpHtJRqwhk8+JfHUIDV9CYMybtiMcpv5yNDozsp6nutZLuUnh5u/Hrfw+3j4nY87dEF5LJY4TcrBp7fzcDxA9rcmZbqQAM/NnUGvwdl/OwDuCOJtoezyaSYQza9YghuJ54wSKGDePFGEb8wGo0QqB2UlqVhaAK9jaGXY3qPhRh97ab2boKY9RhPQVvdvB51htVo56frIShVbWc7ma+G8MB4tz7VewjDP56IGGd/JxIizTj1lW9zZzy9aerMqMJ1Rh9q7FFCzI/IVqe7Z7xqDMEW7wJvAZ282hFs5QAuResSu666wwmEvNR3tMfjKWaFKjNc7h0Nz7RQ/ahtecBOLLtdwRCWpZqxQhFVtY0YkPFdmMElL8WpnL5HJyy4GVL1V/MuJFeYYABLtJ6BVFUQhF832k2MrVsNISv4IneTyZrXLoWNLYiEC8qssAl9zbfnXPPdqP5id3vZ32kFx9UNUIqypWEYixtd1j9idMFLXeDKX6tGaGKFC2dryCWUT03/7cOGZaddi+xtrzgjFeMLYbu24UoYsSzXBMluYzO/keaD+6j3bIVBtofz92wUF4HfhWJtDDnRakv/nnwx+xhp3axu9n9j3XWdLt5jAnpwBzR8BoL1MUFEHUKPFt+AGs8FQ6Mdyw5fkSCn5dK2eIWGH64Dq1jSyBaQlcNjWx0nbLBCa6l+tzFr+3fWH5YpezW7WYLps7gMZ/0Ynk9wN+iObyezkwwJ4FfUX7iN5O/CibWsjJEUG8FqYp7fFcvF+BOeJ2wXzppUnnnnBPJOHYcaAsGttKqbXsMjiXA6F1GPCl+CsxrkDSp3fvAyIgVUwPIiYN7Opa6u7HWYeSbHLk9M/7CELRbvK6An9EnP1uvTA8+rN5yt0NydeYnnPArOdrMo59Klcq7A+m5q69kEh0VAxyFPNRebuE6Wo9nOBivPyAlh40BwFX35NzllS0ULBO6ZOcezMFewFrP5fYvgdMQE6Hl1GLmtJrcRsnJ7u4KX29v93zPrRCGcbbT5InhMVs1K+BTKOaJYEbMnVwFs1sCsle20+KKq9Xe/vw7D1u6Wn+bFdJQXVUu20HZIATlC6sMu3mons6GI5DmW5CPhu3coJo8xYSMYDIeMhfgoU2RUxz9AbDSCnDg8TO/k6eDyOXjqhcegAOnYyNPrmvMtONvESbEoJ6v42cCdFydDeA5cUttX3nkAKrt8NoXQStwjriU872z4/cPzC0o70JCBSyNq4+h7R30clvC1xtlPmTZG5c6C+BX21FTG122Ya2dYOhkDA+FU3xRRCv91wVHQfQrLBbAUK67weUFFOxkH7GoyWAri1Gjk5xeQZ2Dw728H5xeDA1gwDE7Mjb5To1SMEKSJzymqTAv+QJSpHIMrcB/YWsmDRp4PQQuwjzTFhnA2MAlH6qva8DbifxdDNTTbXSVOgM2YXdfmmXZKpR5lXyuhpYDkRqs7tDyzue8U1QMBpMw+qv25LKdZQfl1p+WnpZJFbpQssizn4iKLB+cuH8Y0nExoFmhGFiZKH6YCxVqg7G5Rl7rnh68PTy46mf15MTg7ljee9MKf03C+TS8oaL4SoOaqeQrBSFnsdFYq13fHRiEtl4gHsoZCBwbUJOomLs90+UQ9tvX0aifgWQcifk1O/6HDDYTy1CVshiwbXpjeRVK3yYSm7iWljVp+zl1rJOIQ61jDVEzuKQrerDnQcl6ABjCyAp2snM+G7zoaBgW04+ja2MNc0TDyDzGBtvWAe7Vr2winx/XtgHduC7EEDp7vh87fa8AOyb8JNxE44FRK8ACnbxyXiDAplKeCxjAUQANFz7iOQHZePvOyhf/6Y6NZw0UPAXtxAmPg/VCCDth2fZ+9KUz13ivW8n6LVHfJNVmfKPWdWuP4uijyZSDKuIbRbjg0zJmLGPV4MDY6mzUyudElc7dcGCk1sv+K5exuPOTol1XxAULM3kO30IlFx8xUXNJ8tgAHA/RzfadYjWZ3eTdvWiZ4NoeEpbqc6uLHa3UqFlVGxHffjx3lNEVl7ATT7+6NkoTfCeZgVnVvqvvpsKXfjyfldNZizm1WmTiaoh8UxtMdLQR/+40Hqyh0OR3O0MK/uVre7PxLfPTQdHe0upv7g++gWdF02Xv2+0/DYnrLKOsyOyL17fx++W4GUTopBh4wE1xDJkKGsHeqzHTetcXysBwuuSpHS4/Mme2BLfdVdr6EgPwUhgn268HBKWrZn1QmitrLtwf9DLIsqU05W3Szf1+Vi3vQJmAoKgFLR0F6ffqWIpZSrCoOBgkkIBsuSiCNigcEbeyItbfQIDYjgIGthOJuKtyOHwvF32QX32V35d1sIQLmkwXWvnfHa+P0eUMXL3h0OemoW+0g+LAom+Ct9YW0m6nK5J/VS19WMMfQixZR8H0pkuCj/di5xAtcaTzAfy81nrD0aBGhMojABQlXrkTM3uF8lV/fKwpFiXwpSDHn0/CdnUmeckrG2Q2KjSztYVKmWxwqXN6PrhRz+y9ebJyUlYwIys0dV4MHJ6xFcd+uiSmOOYlxMiL5JOZdRekBgoZJvVPPsWvtB/etBRMNV2HqD3Wxro88zZiHhOY6Mk9t7+w1AdW9g/fzl+zs5DVhVna3qpYgOVALT3m+nnLvbhUG1iW5QtToZNAT7pebbDi8XmR0+0oGdHdCuf8JttRPbdjgijyoDT5VG0SRgpeKakC3dcrx5QxJQpfBnd5fAEBFl6AgEAWkSzjQcommshwpDr1/sdQLNcgLAtdtiJPQoQn+puDdQxT0Sp00ClLTutonyQIZpEJlIDottg2NJ8qFd8wl9jJuEMtfJZDKVlCYRZYxy5ViOXyk+ip7UQzfQ86cDDLRqxm/HuP1Fh6iH/aETFl1UzTTmR8wvG6FdlP+rIFaB+ZKrUmTg16oJxRfXXfdtZqqM+pJdaa1th9yorg3SVPSmtPAT8mkuRklPcNhlc+uISFHRRGxJXFkqh7R64g9f4k1rvRtDim+LpH59MzNoooZ9qXwrL24Ty1tYiAi0EtKXUlljq5jhwGmU3wlh2JfNJW0LuliIoW6xFfBiOnxJWgLrRapg4lNWU2HCkHnDkH3w7D+igHLbybFreiuvnXWSgz11uoQCSMu96D3FMidNFFXLm1Ve+H5s6iT0vgmtZBm7hflaDVE+x/Vpdm8hy/O8OGbefe4/x/OCmAGWyir1aB6bBhkHVO/VcMCpBXNGcucHM6JoSSO7mtV4ZzKM7lpiHwbrf6SY3fiIdGx50WIkR400y/cTsVqqYi3Opk26pQpTTOJQdvZUh44diCWIxEN/4GdNa24EC3PpcTM3GRdEqtnN5JjGlhvNws2utvY5jqkLXMCQgR8f/lpXi7GYIsPmYKUzGlzBQ/+43Rwdng8OLmQvL3ahLdlUPb8ov96IItBzEpUT1SYCImS9Z6/Ofp1cAZ4mQ9O37z8+VzWsEPnGvaBLMb+k6hAC0EfHp/nqtf5i/7Fy59lNUw8MFmoGjYlMtd50T8f5EdnsvRsvhzfqYYXYqBc+s3pxeHx4X+pNk76xwNPOso1kRI9g4zJR2/6B6qujM7qzGlZjsKxnA8GB7IUaPIRn8NOHb05P6fEx6L8fFigOynHD3OGzhlHX/ZzrPrnweHrn51lvp2Pcu2jEan5+vQgP34DuPH22Fl2c7OmKtUmjZYdpQg8GG9MK0D3/Xzbp/3Ds8EB5lfOz/vHp0eDsxSM+WwyHoKc2sRAbQpdYEkAlaa3E0huR0X3mg5aQ54M/Q6sdsIuQHLjlxc59wQG5cyYF6xVLChVf3325u2JmjaF/S/7x4fO2uLpwo0Xq9tI2/958lK33H/7WtbljFdhHZ0lPSyb8625P1988UY3uRQ/z5klfGRCKccQi1uGVVIr/foEUCSCXtbheTxKg7GJyg8PIkBETrMqDeT85eBEQXmTvzyKIXoss1cESjRxurM5vah44XKEeefr6vsDct1E00B5iLHYM0198x727ef+2UGuNnWsdHpqda3ItJrKcJcabAVT8eLN6S/RanTHWdfmcf/s9eFJtDIpckmBnmxakeGzCzqHJBCdTiico1eHJ4OLtycOjX1XKqZpssjvVpPlGIKKL2JdHvQP1AGTH789ujg8PTp0KZcfeCxs+OLwLIfL18Ojo/7F4ZsTvzYficllgvqvj968UIgSwX8FgJCvtj7hWV11G3qnFsQvgwFmZD9848y6G4yj3BD7Xw36F2/PBvnp2eB8cPbroA75A0PiCJHVpCK2Hdz668kNwqghWggmujtcEP4WcQEk94kLJNwsXj+K1VoYF/23aQDhlkssmQtTbML6RQNLmZAhWdfGi/7JL4ZPSepI0VYElA0xxh1uIz+UI09tCo/2RUK7h9zA4wCPytsCQo/ay3Yw/p3O9F2V6cuPmPMMFN+oTFH8ymqonkMIU6hboRa9GbG4Fzpdm5kkLqOwYA++qhB1qjKZvCga1/1+9rlpewpsKMwDKpzUW7i/5hbUK527RL/84ufuE9nv3AtsCRLi/PmQePGMZGS6axfkrqwqJaao/jfPaB4xltbtii/9FPuD4Qr3k+pHc29TtUQLChlmCs1VLyovpZojrQUsoyJPb48HcEy/Ony99mKZe99+GH6Z2triwSS6y4fzlUy7mZakH5huM51qc6s0m6yUwCxzpAVEJTpfoOmLtKhuyFyyYbJMFJGdNH74VuYFxAd48Yff3Mx9eAW9BnqQJXN9E0FSTKYqyZbqAl0eY6o73QrrewtWv0NtSCO1uG8mFAAgSMKmqk9JWJt3E1vWeQldyopYRwsJl5baiorzPIqLH54BvH5li/BZ1YWfaFY3Kf10sTQRr9Sbk9nyFUhePB+fv5CtHTxytjdfJnDaQndpopuEY2SRmnw9OpKZVsS+LLSoIAVxkJpxo20+nt6IOy7M4ViOsq8ruvNUf1tfj/QtRrvZycSwSeMp7DjazjqBxwke43Ts6bXC8CFw/LpLFfLF0WvEAAVk/H2Ab+H8uX92TPwA6hiUtHvxs0LCwTMZJY22p5OGUdvUIvL0PMWUBapk4Ys3oCNBwDbkq1N/3/d/9LHQKd2OkfIQJ4MbABiTgSTP/jjmeo0mrr5qsDlRH49aywJYEkVXSD6LoJDp85d2cFYLAEAQvfAIbgkCLHSOeMCr6Wg6tZgCRCtrbUcn8/I8t9eeq+E6/NkillgFQ0ThEmuCYfcGz57++mqHs3msps3UGpiZ1nTDmVH7GvZT05lLv2pgobbxoBRyheyk2/SPWbGEG/OsGVaff1iBTFtUy9yC6c6X71KD1p1HyPEbRxuZCF1JfILojT2RtfYB5FGSSDUtbF9rtx72mAlns+PRgtD8C/tN24JoJDMxRMmM0lh8zXW2mwpieK/AmCt0TKVLF0lqrY8a/3TumcRhaad4Qxruc2Sf3bnSAtye280mmPoKu779bLcTqZjrDaMK4O70CplJyMFgeI5K72g59bbKFZEwAiXagLqFWOuBpsdhfzCY6F3/VL3agXDDkbcatv8SouGDbhRSYq70eCMdwC2yrpBjMRgv8hFu8mBD51WpxJRRlWO6DuhZ0PEKUmrOpuTp6K7Tl0bNsbUh86SFpbUnkmWivspgfynpE20eMJx8N0Om9KndZ96Gx4PC7BEG45eB7K1gZj5eSKMMsDuffcTUfGiBgZmxS/IW+vhOjYihSVuO4WwBOR0wr8cdmOtGrTPEoOsYQrbwwFTevF06WsboyJsjsNrEjd38kmDybYtaouCDT7ehlq9aXVfq6LBF64QBF1eIAWLRE3gessahIaqpTBL6jncsNOk0xDHuoLGeexww67tGjSLaiLMX7S1YaAvMSGyRU8MsRm19u2RXhiv0O+sTdGmF67/brDENKN2moZaOGbV+WNuKrcrgCRPX1CkmTn/ihzruXb+rPmPjucTFT33ZuAcgtpjjG/dQXNspUzrdOwdg0EFXu+hMVRyy221vf6DFywLdYB3rF+lpFdkl6iC6vscKzXb0teMk7th76hbZKG7OKZnBeTZcP3zVlIuPT/Y9aQEpHgf502UumQ5KoyqHHQAXYtC06wosBrgsg2boZSBKyXR4jRIMjy/pZLttyeIghdFdlgP4NkO7HK+baC8hikkW1y3qsrZBR3cjmcC+8gzgso+QYUW7VCFZLZZC5KCOcqT/cSkM5sKVkMi5fi0c5Ez0ff38yS2u8erzl4Z0gzBS0BYIr6vWIL3LU7Xr7VuYyZNjkTYbPl/rPug00gyu+8C5swi53Aj6h8XMDnDsEnxW2IPivY+YyjCH7OIJ1ZYlcO9IixnLQfO9kFfZFOggix1Wdi5gY5U1++TWjfLfAcUKCznX6QFv7gPwSziT7jHtzm9pspTk3GPXU14HUpU7wPa347dhHvcfm1i3DM4t7Fbvygv2MnkowSRaGNRl2JjOkdGxOR/UgotfYj+RrOnyXd5PLQ03HE6mIziUTsNlGvQ7KQzz3YXwG5R5AACXGUqAIvTcW3ndpJKwZ6sqN8vCTfN0olBdgiZT8Ryz6XjovqaQQUZjvOIZW5RFBS1otxt7mANRjNvzSl+ZtkNN11et8U9rO/0tOV5VL4Ohds2oWm0MJZYYs01YKQAQqofz18boY05zhA2r5Xy11NpaLaj+ZTZGK9fum7cXp28v8oPDs06dLsqayBqDXi8fntWHejoOkmHzD0pmJNLwrONZsf8Ct1iYYztqxa5WdQQJVbNXqkgBIijYXvKBDX5MHrgx5WPTt69Y7sesWC3fzdTpT3Fd6KScYDQEuFXRRD6unolzX50gWjIxdfuZ1rLh73atIgVAiyfttF6FFl4/aNepWACofdDeROGS2r01JD66saVpYgmkOSpfStdJr560BbUC5SYVtIi3H4qINdWt7LYvpL3aCoUuXawp6skr+5HopEJgk4BqBMLQCc07t1xLjg364IplgVur5yqXlgo365kUsfYljU6o8mxZ74kP11dw7CfMLjbWBzqkd41mELac8yxYEGTnFSFcTcdQAQ8C+CdEMDzR2OqYfgRziAcdF6EffhGywABOTFF59Iht+8pLlGBrPJTF0SFusbBDeZLc/za954UD0g+mnSBC+eOThjGip76ifEuD+y2M7n9/qg+CxpC6Hu7avV3FuGbf+OcCbFH9I/sJQr5tti3rDhADk85cA/APOVi233kuV5S/m60WiKAec/Y0e/7DbngHYOkDVoxTh1TljXZ9uButB717vevsPbepWs7OQeKLt+f5q8OjgedQsZEX1HWxWIylzxBKNmRvADoV5x4MHedtuJ1NWFBTpZEgTuvZCS8kAWZbzu9KUBQy376YfdyiS3bujgdgXiYmj62w1MRUAoq8BPJiGtAFZhOu06flx8l4Wvaam4Y2ANUVhroYVh+6B2qsf8YHLR3f4GZcTkYwd1UPPUHUKLtgOWdCSYpbEeqzl1QAwXXxzztkucX5L18qwADcTDHv1NJZ+w+YdA0Zd4or91cIJICJAeEuGUKMjef5clmwQRv1hUHNYJhne0gC4ZGwYik+4dnf+17sNIwvDUHberBW4DqAlsr5yZuz445Qr3FAYVvqbJCf9U9+OTx53RHxM+b5e1sEwkD9kg9+7R91nJvxctHjkQh9mOk+ZJssNf9EMa5wHG3jy0nub2g+IrebUV1rLZ596viyxWN4seeahi380ehC23hLsuerdtSrjZTAN3wm8w5YOEBu1dKG0zULXdGNoZLJFMgxJNmwKzospgzK9jH7+G42MYAg+h5HdIahK4mv/3rnrDw86H54hs2Wnwq8V9RnmY3o+5S6oGpUwOxR2vhiyT3jkBczmtndbFIWIPjhrz1QAxemZ2R7qhjaly+PMNC0EvdBYMTLTl1fHcs3GIezyCDme2bPqh9h/NqJnUJhvF7MVnME9xFsYEezW0rqXVzPwCG+uIFd/fe9XYiut1pqxfNXDIRkXnKlyvjKDxTHOoTTizcXP9Ns6V6UNmYxRkOe6Wmny93ZxynG7FhVNEkYn2MBZHKUsS1ihsF81LkKkahmU3X+3WejFWdrrRgaJpXHZLkKBd9najU5pTmclzvDyQziJ6uDDq+M1TRO4NJIUdPFajgGiB1OssvgIOYyhCNR88oO7Xrqq6eUzie7XqgxgxtopdN02nnvZi9mbELyFU8HuEmXNxDwZIGp02Go81m13LG1Mj7OFGqovQSpXlmNxGM1PmyMRj1ne8ElGPs0a1KHSpE9QwvolHJcT2Pnl6TOqbZdJ1MKhOec2slOQzeJojj6GqJeMQOe/mvGtx2GAOtiJ23fNAVLYNFATSeFgPFus7FtCuTpI5uaG7UpEQ8yb4cozFFMfdOPNAFaIqjYycS0iwOmDdqcUv3ElPd2YH8bz1uJI6nNwc50LGI7RZacQ1wCLA2hRVrUAdumXL9WkKOF0cV5rkPErV1tXRjbRK/57Gt5EvxTD9c2ZZU3pOzWrkHx+E5JN4pNGsN2BNfJTgYulBxUAU9wfIbM0XgqjnKPYbDBWQ0WIF77uStwau7IQQD/QtwYziiipmGaXwO1gJPZtUDz0lio2nZTtXgUmEsa/onqKjSTsR9NTwBv5xD4NAY/mXiY48youroPo/Fd1bt8ftUW3YlWb8e7YZqPJCrQgVCzb9MpKWrG5CefSPfGIjsnGrM9kJiCyMED5T0ptonC5iXGEOFk8HdDVbIspjkk7NZnNTreqi34Tc4zTpVB+QsptdsNLygI5WsaQvJfN9BaHXhmTkczunZxeFPO7jlEZhYETPd6w+Fd3Znb0OYQo8DmN1OH83UhkRPfwtp5Ez3G5O3r7S4bPgVvklWtvmLiEqkgoNGrFpBQ9QUFSaj1NzKRy4wNWE0xbsEcG3oQi7zDoSUwwwYFqiX7k0ik3H3X3N10YjrtajZEiU6GJh8o/uiUn7tbijGFm1ZsSu/S9vwKhK0pzNgK9AnWJi5mh+JGIgJ8AOa5GFWtvR9goBYsHtB0vn/HW4sEawW8AHkgxTqIZJA6/qmt2AHv73w+KaaYwPmff+DIUm52ymg9UUTV/H5318bTx8AIIItGgiJ0J7OPmBgT5nnOWKFmKi9Wn3JiMSvEcw0GbNIhYETTu410GCc3lahrD2L72ZPpGoNcSDBJvXhSLJPyMx50wcugFU/o6DAC/oBdLZxdAyv75KppmBfFUtaGcrB1bSIzqvoMEg8FMMM7XWdi47lat59gp0O9oHsPX406J9Pt16XG/Ti6RnTLgy5JQdiehjXbgQLSXt2xummEPrPCTrTj+eiElo6dpPFjJ7RUlI8K57d/z5+467czKXUbSxCiVLuasJppcuY04SEO2ZgDXx8Z7aH/8ufBmXBEeoAfRk3T2sK3ysKWUm4W/njBPlodReUcvgg62fYPr3o3rAB0J+FUHfbUUy3fLGZ/K6fgZ8HwmjGMd9rqAlEKQl+Y8OnpOn7QhA2qzDHk9nL2XkkVa4oL1ZiWUcyZCgKIW9oet76cYd509XrTdm0J1yXhOM/GfLRhPUM+vn/yrSF1Wc+Oza0UWJppe0xdOzRF8wB45nymnmMndeWb4Xh9lDdODN/cC2kzEl3WmBnIgrFJErdEXDS83xE9jtwIXelcDsVEa+VFBf8y6CphLRSMIHWLe9UODYe8MbkXSjqEqkPWBLXeRIPCfh0MOPt6BDpGmk713SKV+sHXgBjSX/3u4NRnsEZfd7+7aXvpqiP2T+JuaLH0DS5jqOy+Dcy4TIovx/pMqGC0az/EbVJ8LFximNUQh+vg/PzwzUl+MOgfHB2eDPK3J4cmPB7FHOGFUpV/kDeZ8q4KczAQNT8+PHl7obgfNtG64XwDLLWI8zbSvR2/TYchiFT4SZjlxpgCuFNWgvBw/RgUDX/5y+mbw5OLfKC45P90x4F0xABzXGJaDX/RQwns26Ajjpeg38lgVJzmxU99hv3ISZnXk1leZIAZiK8AY+NhnV8MTjVreqdk0DvF/6E2JTFDEZZIzQxetKglP1ay3OHJaz1ZMmNhnQ1aekf+UtyCAl3vSMgQONrPeEbVVtu96WB2l8ygAD3DdBtiXQDn8FViY0phuuOr4nw080C4OK0OwZ29YPPRwedYXcCV337WV6tV3JbH8L5FMVnhBab38O7bldwF3lLFcLhaFMN7+D4Ga+gmiGuTcokvddAx+AHBe0LrLlK2YEEoZGOVIcDph5yAagbTh4BsCBQw8YE6MryS/sXFPNbHC18k28H4OAErRFfsEDNurq/QaoIF2iDa2pyjxakyPHv1zLMH7yTN1LOAT9eHPyk99zf0FIVtGLXqC0zroaT7sL3W7zOSPRusK9xybcre4Tx7gB1YYOGPPJL7tL2BRytWC1445hVmOdFaQZhf6+W1jtBoTKwNiTVzI4PjIntfb88tSFsvkHx1kz2v7ejh2wtPYZc96/lm4Y4o2YtIGEaC7EXEy5iI2UvLnA4+9xI+1ySF9nxh1BVIezHZNJBPewlp1bdQ74Xm6hF+p5fkfUK2tceP3HIet9pzuFp/qD4L20vZwK8993trrOSj3GKvnndUaN+TpvSWGsFO6GnLeu84gj2FNiGQYvyuWNy3gh3kYLmbd0Cc4//knONeUBPsIsH/vewNf28zQU7Nt1WI3lr7Qp7P38i2XNsSGgExbURYZzYoxEbFf2zkw1+zZbQRqGvpKU21wgDxm3s0pM6mzY3xCCM7a3wqzCnB5bsArtmO7SRk/kB1gTkSpHaDdDbIfPai+erinDFlKXD5ymTAEKcN8UOtpLgTAmxwIfqMix+63YIycTUEfxXKPvloVYZjVw8doYi8b53RBpfmga+N6ntK4kpG8kuMZyTC0dvhaBOcHJJ3LpTksxgxt7Yv0qlPEYSVsKVvl7shrJTkXHXm7l0n4IQxwvM5kE0t8uLa8hhCqb6ksWgx+xjQ6JDCxqhryCsbAusR10jJdewxCS0OrePknjSnseJnaug7e0ENNfzL3atkhe+jFb5LV9jbjdb4V7/GFxf3U4at3p5OCMTY/K/WnEwrp/ZZ9fTsJjvb47/f69+7+KUZDiTCfzIuXOKkXyXe8QzXvv5+Te1d/707A4GicfbRz/3EKJD9ZHZkaC4SaE413sRLStWpyBroNSzQuv/rIH+hyHncUKXWyprPOOohaciX79xgVwmL7phVN1nQHd6QuZwiYSUGQdWKEyDjoNH+CyUaQvO6wsgAo8y32v9KWiWCEhQsOLWvPVUfviumt9oWkW5bblYLa42HmqxAxxwlQKacjJoQ1G0H5YVLvRH44wJBiOi7MW3rWmdx+IROLe4TEZlhplBqOlvdvtPK7+0OwjQLsK7ojnP2/ymq2kucHN6x6Y3BHJ7AX6QZHx1/ISljx5YxQmnnBZpq4AXBREmzywgVa3pdzBV65pEbjE6qA70aNGmHtvZGZvqDupuYr3adGObYHJ2tpmhprTifcrFwdj8qIPWh0uy4G6jtW1g6/FKiaPSeyUHhWjypH3NzQUORsoZXQg9SdMCoqXz1qFQbRe5PuJLkeXVcEnlRaqfQZIiSlzxZVH6E4APShBXVaWQcFtp2GYtafdNK6mVOuu7vQ321Sp4NDc/GFCeXXLMN/XWXgJ/25FVVwipW3MhaDeFVaBUbXNPCZb8aUOomNhpAWlfOZzc3amzmNlKA1QFpvN7rZOcWA2MXt959bi0sB6GD7M1JhVensYYdc1M8JwJs2GtEm/fZn52EVQ3acyQQYT+uL+zCmvjcka9W9nHIubf1jterIKtndJ7RHj4FInk24uoEqPItWmuFyYbFdreTupbLiKxbevojs+W+jER6jN89JJb0HzyU3TE/9EjWSku8sMuJY9RxbJLHcKh4+odP3/qeeINdf5y6Fl9k1StpahiKy8MDh3yTRkLcSpFhuhLtx5DyeLy8Z/PtynOPiGTUDhAv0jigvdtk/AKhq/6foQlOC2xfl7N8qlYmYuQfxGvYtCKNE/IpbuBXYJ0fYBaoqnum0CQBOPVNDW0DeFQQkytgZRcgqX1hCnkhtvB8cA052TCUet2ONKK2Kiju6AeEly+VlOrCEAhm/DfiSf/cgCqKz0PhjC3O2ByLgo+Cy994WYms3gV4bSFWVJk6vCLwFuWkLMBpmiVAgA2LPVZztDNUsigmnK6WK5g04xE2L/z4LNKSjM1oeuaByTHls4mCxLk2fkmdVsThZcro2d5P+4kwcIpNIHom/FfUFqUFMxs0CQ5MxTEruoSKFyffpfuwqfFkaEzpGxdSMNPy03wGMVB1bG6+iK+atRDTg8r1cCrF+qst4a5mx76/ntqXxepTwBfUT35j+57F0Eh04FKkVINJUMxpAMos/HYLzgutF1hxL8/jCwxp2Hje+JYHeqImDf6AP3p67DSFn7+EmrwgO+9GrXUYIjcZZpaeVXga5fSFDU3wl/YEuJm2tmrXUr3G+lUlueYS7FyutH8T94aTs0qA3epdMS9ByZsEpE1lDDQ5pHqQ4YLjkUMnX5WiVjaMD6+umIwYCnnuB/E1dXSQnL4wTUyCLsT3Qao62gblGhMq7YZVoSKTLIc6mbUiWrvFseiNOm1mC8jDmmOegvWkLdrpztpqvGvXlqNdvb6cezKvL29NlzboQzIH5jZ1o0klOw8k9Ok3ekd5FmVmYxnkMLtqbz0wYYxmANln6yCliWAdHiuEPX3Zr0fACAXr+KgglnrL6dSjt8Z7ZvC203LwUSiQ0ZEJ8+vTg9aG5MAOR6ZVcPZ5Y8O9oCCtervd3eedxvZjB0NCM2o9lHULruggpO/FjFLGLS2NAeLYUqKQndrsmyyZ7DfZLnT4Qe3qwTXS8dxoSaoaDnhD8i/zx6KfMqWsVQu7AG+YxobEFs9xCNtdc3inlzgyLPYSVZLOZbIPLSLJl5rAXGU/1VBIiH0/vW2lSYzvYadWQkNOO2VT1AIKlmKUub5wFqt5tWYqGCW2WxBR+1bJbhhH3ZvbLZaFu9CqRdvky2+z2vzDarol7m0EJpKBWIFxpuwBhIUtmi37KLq1jr5oGMYW2kBxelVLmp3NGqQh3k8szRCNPkjnSOmuA/evNcgi/bgAU0JijQoHzd/+IYiTysqslt1OwQPWnIzPzWJZWJuvlJ9MOL5QIq0wS0gmz6+7er4j3sakdx2fG1vrTQ/sRj3TbHAjXdAmM+7VJzHu/CH4FWR0VojlLdnGcGRmZwbzD+GocJmwwqjbt03Jk/W3cCBtjvZb6tNM9mleKc+tYw2CS176t9oFnv5pc+3QH4OXKZfnb9ypfQBWBR42BiNq5AHRpMWUROMx9EkogIJc8nGV1lTn8Pipl9Xnnw8VRnH8RM8kXi3tpfQHyEM1kYjm73uRoUIK83QtSmEeq0dZyx+AyiyRREAahDRzWYt2xhfMoJupt472rEOeINrDNli0Pov6GlSScbO1+MIpJ9EAyo+pnSaaD1HpN3WMD/JxhFAXJiKC0eXrPsBiFBA5sLml+sHNUM+o4T7cZgOt4SpAeEyX8Sd7g5KhS1HNXnMRYssN51au23U03FW64f7bP+bkcbtRo+IgkTlEjQecSa6H5/oDKWx0u1NJx/eHPy2o3u5eF8P3cBnp6Qe45GqKX/KWuc/2Lmp1LKqV4t+r7hCC02GACojrlrfC8BYdjHeLkW33ZJIa2Tswokm0p7tF8+SNbpM7gs0vPEUag3XL4ur+R6N5LxbJawv8qMtJsL/Zvl/b6U3pzna0ZxuqB5/UZHVqKLVrNMc+31EiYG7auujy377cu+qWf23ZYbe7ZPve7oL1e6tdY+diJeiqkgL0NvdtRp2tHdWtNpufpAQbGRTl256329O2NZhmzd8kXvGv3ZBnr3NwX3lz4AUiiJnLRteoOQBm4/Lr0VV2qNtQv57CgyOg1l93n99k/eGQvsSP5ObhAb2+ODvkCniDhl/hsK+rq2TSnddcXX09oq+/lBCOBL6d7/wMPAN+PzoDD5CyGce3DV3k12hcEF+KD+DfEK4/PK/X0o382vamdm1leW/iwCCOdG19RxR3OyEk67VgIrLX2jr+2ZisYM0vc9h9kwVbYEbVM+0NdoOMFRLdA2A4ot0KfZvCkAY5boCg90o5CMZkANsUWGY5FRJGDRztfK1p5hozzTR9qWE8N9kXCUPObYw6NzpAzczVHJjrLD7rJrb+XNvIFtSpoK0xbY18tqA8P5M1ddNWoptdWK+xHv3DxrX5lKfH5nl7PGj5N+/Heq8LdzI1KRhPc3YN2KTe+vWOz8dGsZlCRb7nclwToilBaesCHK3lKYifgMBiI1AtjIEJ2LupfiTRD0KK/QhMIH5LOnI6Pl870oek0/itDm7HgUQ7xDzEQt7zvwPWNQjKUxsGJ6SWm5vJa/8luBRnbyfJH2I0K8EgNn5D+/pw1n4bG3vMR7HWxJ79km7EDCQiRPzmpvdOByPTsIX1vey/l2J6jcclfOq8LrUucUPPy0Txrbwvw+Fu4YUZHvsb0ftNkHCrg7ApvOuMxx04NmocqKvsIGdnA7PQDY7y/5mebzKPYfcjp3U6AEXD9ZOMxdPQFMwN9Ye+6Uf9cw5gGEF246fY68WdEiOUcyOpYHxjOztbpJhURQ7uwMvf0OBUN4yDoQH0O5Bc6xNKN6LcN6SOG6OYK8xg3RizFOJIpEM2TNn2PYtSXutavFaaSJpX2lBuo5CX22RYm/p6rfG21bPQWC8L/SY+22smtLM1ztUfcJEwxrv+y1i4YjdacyIssXOKpXx2VTknKULa85IBivDAtexgdIfbuRFsoYsiLitXx+qZXBTk3JrGo/3NXNDdQQXpWuOu5LHtu5mz+TpZYpOgIhg4yw8qsnGKyHDXyGHGh+bNUtvmcTE5hjbJM7hdUhV17sRyqgym5BZP7dq0KnUZTjZLYBLmKZlOu042EpHeI5oixQsIVRMHatsYUJGJEIGCILT1ZFnFpgsC52Sf97vPvv7S7FLWdxMmp20iGmCmE4hKu9fJvu9ke7vtePze5svjl6BL+KCYVIz083n/T8+/7HvwMQ80TMYlwt3J9q7a7UhagsMTJYm9Ojo8zS8u+vv14SwgTfzfZtNlMdmBbEomP1OBIXYtGiDvsSxyXAr4codLAd9+u7BcIlFmIrmMM4ZXqvCOGmIWWwzuY9sN/lC3IOv1DaZBtVx1C9WI2zHA6vEc2hVcw/qKCG2RYGNNJ7xg0y5mricyiGUcCQump8ormggJpkcQhAVLhQTTFb6LV4iEBNM1nLBg1n8vlsg2SCwRz2qrFi/3M9tG0CxIYvvxIUlszZHwjyaytYASGWv9AiZrreWTMlozoh/fXTX+z+Nn8w8e3t35/e/Zxq76/PDdd/hXfby/e8+++/6f9TN+/s/ffff9/8l2/ycmYAUaUdXk/6frf7OY3WVkyMJc1hgiACyzSu2tec4MBZYCY7IKLd6oBCZSgoec7BILsc2wKEFJTvFlNZt8sC3gW2PzIkt0LT9PnqH3us5wUYJaxLynWqgVl1DRNAlfzSl778y0qlMJNvi3Oq5Gszv9C9k9/UMd4/N7IH/TuX40q/S3YnE7LxZKvPoqw4bUMO5sv+v7S0kETJmbW2aPac4xlMOHcTW+npScwLkSHHo5/aCf0lGhHowXsykGq3vy8u1BP//18PzwxdEgPxj8evhycP6EqKXi/opqu6pPDBMmWvVj3OsiDnxbyDZzGe8dyIxOXRrmhFk/tpLBwvnhwZaAIxB4spVcAsiW28x9LbWmlZhlmdMvmC1yAIC84+4kiUpRAyY+szCkpFPcQIFedONgUPXlv//JkQcFfK+gc2buGozLq7KEAC3liIdOIs9dMV2helq/9PN5blMAk4naQtN5l7Zd16sdf0owwWhPycgVAFdi1qgkpQ940QyleiJa+lqxNe+U7Ppel6ThF/P55D5XsqqalKlChUV+p8Si8XwyBsM9yd9b2zyapGZT8Xhgvnt0RmnJgQcfPMuKUTFXHXsKjIzNZFXpGCmWQCBlgJTXpCq5eFdms5ubMWTVto1l16vxZFRBpnSRSws9i+FCMqNcv93sWA2EY2/aDBn8NoOpgATNEN8Fk4loixRMrp0pzvoWNYjXags+/ViOb98td0blsCBHyAWmPaS86WoVZx+hnQJIGDt3fCixhWvoo5oMmIePxeJux01l2tWz5mhjpGQ3uHh7MojSFrsmkQxFPw/6B/nRWX789uji8PTocHBmNpKo9yd3j+DK/Qrh8cjsupmCRfFSrjHl+BjGykIj8rUgtIxHLbMw7X2aX521pePmPyMFALyQyUZbbWL/AWFsnjXL9TcxS+NYcdMLULZcz5bLSTkth+85Pwu7xDDeCaFIvHQrGSMjdTb+pYTjtdlx0gaBW+vI6BhhNIRPagw2KBSOIMcXgtgLjO9RLYqhis8hX83llXMvMEFBRNfBODh7a3Jf4xT3aAUQuFyCCoU3hWdOK8X0voVTC0MwS2SeiKn3hGYcwWVzskDFJqGeeNZWcp1FMv/STi3AGMPnqaLQDFYMb+gYnigctCXf1bSpV87YSsIJqlczsgEcz4PmK0UFd4AMwi4WW2c05tsW8CqEqWQez8w5z/V84ahKBTyDNPsOpfi8331efung9MsGQeVwo57bC4Tm5y8++asUpYXoxeUorpuwZIK1yy/65wO1t8EY2zTV0dPjCcrtRgO0ozmgSp7D3D3J8zsIspY/2Sd6jbwf0CPNB3b7i9sVWB2e4pvWqKyGi/Ecoy82z8rDg+yF4p4xJ9WFm96ZQHWLkTomGYaYxp0d4hYxAWUTbnpvCjUAlNXflZN5r4lKA0XfmavkcmCL3KuWC5l0K9ZSU61OZWAdK9n/5l6Dms0p/teq0oGdh7M7dayPdmAcojP1RlhTYER6ZqIoL9iBJtTRTu3sWL5FtLOzxwNTqJau/YRr70DtJ7YGwKmWvScWtOaMVf/QORdh4R+AVrVssjLkpcRKYLbj5r5zj3FXLm7LHDh8yhbq12H66pZE3QiWhIWwRW4WZfk3Y+6/RjIwo+g6PGuKxTUwiXsTu+R8MDhwMyemc3MLVg9Asf48YDqxPEWUykfjBfPkVomlGxNF9AWv1oOVn9QkVS1bou1IASDyqYdOgYZ7cSClWXFnoFDL1umoXpBsKML4OWrZ8+IDbASWcSmaHu6+/c9WReqOrh2CEUuwAWI5HTgCSXtkktBxjGaoJToQoJ09C78S+j+/WCd7sniC2r7hzb6owYcwFFPkRM1l87+nTfQi6kIC9FbbKys7bOu1fb7PxyuwDPBwp9fbXaPjx9FQI/v/PXUXoV2PxwbJ+PbHppPvjqucT1yISCVNuiJlVcGclQzEDbVY9Og9mQ6HkyeQclEVUUfXu5l6pmS+/adPn3Dflot7AVxGAnZ+oe9QUXfLINN5czBLSFLPkbjUN8wA6ehriHAEN1hWZ8OmRhpyL9FGL9Gc/iraoAhxq+lQew7lQ9Tp0pW20dx4DbvZygU4m/ksCD2qwZnnjjDnNy5gPkQibIT30EDlPNUPVY7V0iqp8HYpzAXnZaP0BtLZMLS0xKN4CNf6ZHIJQ0svrZpZ7SAgqkZbb8N7bBjeIU/unWRj0d1afCjGk0Idiq02ZQzaYkvHtzUwCovZvbez2493C4+fx8/j5/Hz+Hn8PH4eP4+fx8/j5/Hz+Hn8PH4eP4+fx8/j5/Hz+Hn8PH4eP4+fx8/j5/Hz+Hn8PH4eP4+fx8/j53/P5/8BYvmGnwBIAwA='
overlay_bytes = base64.b64decode(OVERLAY_ARCHIVE_B64)
with tarfile.open(fileobj=io.BytesIO(overlay_bytes), mode="r:gz") as archive:
    members = archive.getmembers()
    for member in members:
        destination = (UAD_DIR / member.name).resolve()
        if not str(destination).startswith(str(UAD_DIR.resolve()) + os.sep):
            raise RuntimeError(f"Unsafe overlay member: {member.name}")
    archive.extractall(UAD_DIR)

OVERLAY_HASHES = {'config/defaults.py': '839faddc24b14d21f073c0a2b588406cd24ac50651304c7d7dcdbe8d7416b89e', 'configs/PVUAD.yml': '2ce61c2c87eced2377c6b290fa5cfc14dc17511eb85dbeee4c18e6054c727440', 'datasets/agreid_v2.py': 'f2dc8f1bb9f85ae5ea7b6d2602c38ddf22bec14b935853773e337b588e27c051', 'datasets/bases.py': '7712bac25aee214f38a913cf3aad1ce4ef33b9a713d7e177ad67ec17932c016d', 'datasets/lagper.py': '18b559e7c14b86070f65cf7792684ba14861c72ff25d0499419f33faae385f4c', 'datasets/make_dataloader.py': 'e2d6a35e71f2f32d0d26da9a7a4bbb862cb34ebffe056a433989f072b07133c9', 'datasets/pvuad_sampler.py': '93d21613c90372d10fca9d4b1a0ffbb34ec1a6f4849c9f6eb10671d736261d75', 'datasets/pvuad_transforms.py': '056fc9f25aba6361d4612bcc313f0cc2d175e2b695757f6912e09fc7b5fc61c0', 'datasets/sampler_ddp.py': 'e4c455f7c7afbfac09a503a924c7b09586dbdb8eda6c88735ad1a3e37599bf7c', 'datasets/whu_mars.py': '11d3a0c501912a9887d78601df01afb6495d2f859835a6b69d2079135dba24b3', 'model/backbones/vit_pytorch.py': '723305c1a05e204b744ddb0ff7873b5e02840329e01787200173c9064ed3ad05', 'model/make_model.py': 'bcdfef10d3a75cbb25da27eb688bb6834e97baec8b4221bbef15cf9bf472e3b5', 'processor/processor.py': 'e9a5dc613a374fde37874a4bf838789c7b359ff44c2e0d051db4e7e8fb987d7c', 'train.py': '8da1552749d67272ca6d8078ac3dd8c1df4183924d7795a6e7b0355eecf18ff5'}
for relative, expected_hash in OVERLAY_HASHES.items():
    actual_hash = hashlib.sha256((UAD_DIR / relative).read_bytes()).hexdigest()
    if actual_hash != expected_hash:
        raise RuntimeError(f"Overlay hash mismatch: {relative}")

# LAGPeR uses conventional person-ReID junk removal: discard only samples
# with the SAME identity AND SAME camera as the query. The released UAD
# evaluator removes the entire same-camera gallery (WHU/SYSU-style), which is
# equivalent for A2G/G2A because views use disjoint cameras, but not for G2A+G.
# Patch eval_func at runtime so all LAGPeR protocols use the benchmark-safe rule.
METRICS_PATH = UAD_DIR / "utils" / "metrics.py"
metrics_text = METRICS_PATH.read_text(encoding="utf-8")
if "import os\n" not in metrics_text[:2000]:
    metrics_text = metrics_text.replace(
        "import numpy as np\n", "import os\nimport numpy as np\n", 1
    )

LAGPER_PATCH_SENTINEL = 'PVUAD_LAGPER_MARKET_EVAL'

if LAGPER_PATCH_SENTINEL in metrics_text:
    # Session 2 can reuse the entire source tree saved by session 1.
    # In that case metrics.py is ALREADY patched. Reapplying the textual
    # replacement would wrap the fallback `remove = ...` line a second time
    # and corrupt indentation. Validate it and leave it byte-for-byte intact.
    compile(metrics_text, str(METRICS_PATH), "exec")
    print("LAGPeR metrics patch already present; reusing it without modification.")
else:
    metric_patch_count = 0
    for old_line in (
        "        remove = (g_camids[order] == q_camid) # sysu dataset",
        "        remove = (g_camids[order] == q_camid) # sysu metric",
    ):
        if old_line in metrics_text:
            # old_line has 8 spaces in the pristine evaluator. Once wrapped
            # by if/else, its fallback copy needs 12 spaces.
            fallback_line = "    " + old_line
            new_block = (
                '        if os.environ.get("PVUAD_LAGPER_MARKET_EVAL", "0") == "1":\n'
                '            remove = (g_pids[order] == q_pid) & (g_camids[order] == q_camid)\n'
                '        else:\n'
                + fallback_line
            )
            metrics_text = metrics_text.replace(old_line, new_block, 1)
            metric_patch_count += 1

    if metric_patch_count not in (1, 2):
        raise RuntimeError(
            "Expected to patch one or two pristine UAD evaluator branches for "
            f"LAGPeR, but patched {metric_patch_count}."
        )

    # Validate generated Python before writing.
    compile(metrics_text, str(METRICS_PATH), "exec")
    METRICS_PATH.write_text(metrics_text, encoding="utf-8")
    print("Applied LAGPeR same-PID+same-camera evaluator patch.")

# Final validation applies to BOTH fresh and reused source trees.
metrics_final_text = METRICS_PATH.read_text(encoding="utf-8")
compile(metrics_final_text, str(METRICS_PATH), "exec")

# The pinned UAD metrics.py can contain more than one SYSU-style evaluator
# branch. Session 1 legitimately patched TWO such branches, so requiring
# exactly one sentinel is incorrect.
sentinel_count = metrics_final_text.count(LAGPER_PATCH_SENTINEL)
if sentinel_count < 1:
    raise RuntimeError("LAGPeR evaluator patch is missing after source preparation.")

market_line = 'if os.environ.get("PVUAD_LAGPER_MARKET_EVAL", "0") == "1":'
market_block_count = metrics_final_text.count(market_line)
if market_block_count != sentinel_count:
    raise RuntimeError(
        "LAGPeR evaluator patch sentinel/if-block count mismatch: "
        f"sentinel={sentinel_count}, if_blocks={market_block_count}."
    )
if sentinel_count not in (1, 2):
    raise RuntimeError(
        "Unexpected number of LAGPeR evaluator patch blocks: "
        f"{sentinel_count}. Expected 1 or 2."
    )

# Validate only the actual inserted LAGPeR if/else blocks. Do not compare
# against the global count of the same-PID+same-camera expression because
# upstream metrics.py can use that expression in other valid functions too.
patch_block_re = re.compile(
    r'(?m)^\s*if os\.environ\.get\("PVUAD_LAGPER_MARKET_EVAL", "0"\) == "1":\s*\n'
    r'\s*remove = \(g_pids\[order\] == q_pid\) & \(g_camids\[order\] == q_camid\)\s*\n'
    r'\s*else:\s*\n'
    r'\s*remove = \(g_camids\[order\] == q_camid\)'
)
valid_patch_blocks = patch_block_re.findall(metrics_final_text)
if len(valid_patch_blocks) != sentinel_count:
    raise RuntimeError(
        "LAGPeR evaluator patch block validation failed: "
        f"expected {sentinel_count} valid blocks, found {len(valid_patch_blocks)}."
    )

print(
    f"Validated LAGPeR evaluator patch blocks: {sentinel_count} "
    "(local structural check passed)"
)
LAGPER_METRICS_SHA256 = hashlib.sha256(METRICS_PATH.read_bytes()).hexdigest()

patch_manifest = {
    "base_repo": OFFICIAL_REPO_URL,
    "base_commit": PINNED_UAD_COMMIT,
    "overlay_variant": "lagper_s3clip_transreid_lastonly_768_v8_session2_structuralfix",
    "overlay_sha256": OVERLAY_HASHES,
    "lagper_metrics_sha256": LAGPER_METRICS_SHA256,
    "lagper_eval_rule": "remove_same_pid_and_same_camera_only",
}
(UAD_DIR / "PVUAD_patch_manifest.json").write_text(
    json.dumps(patch_manifest, indent=2), encoding="utf-8"
)
subprocess.run([sys.executable, "-m", "compileall", "-q", str(UAD_DIR)], check=True)
print("Pinned and patched source:", UAD_DIR)



TRANSREID_MODEL_NAME = "vit_transreid_msmt.pth"
TRANSREID_GDRIVE_ID = "1x6Na97ycxS0t2Dn_0iRKWe1U5ccIqASK"
TRANSREID_SOURCE_STRIDE = [12, 12]

def find_named_file_without_images(base, filename):
    base = Path(base)
    if not base.exists():
        return []
    found = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if filename in files:
            found.append(root_path / filename)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
    return sorted(found, key=lambda item: str(item))


def torch_load_cpu(path):
    try:
        return torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        return torch.load(path, map_location="cpu")


def unwrap_checkpoint_state(payload):
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("Checkpoint does not contain a state_dict")
    return {str(key).replace("module.", ""): value for key, value in payload.items()}


TRANSREID_CACHE = Path("/kaggle/working") / TRANSREID_MODEL_NAME
checkpoint_override = TRANSREID_CHECKPOINT_OVERRIDE or PRETRAIN_PATH_OVERRIDE
if checkpoint_override:
    source_checkpoint = Path(checkpoint_override)
    if not source_checkpoint.is_file():
        raise FileNotFoundError(source_checkpoint)
    if source_checkpoint.resolve() != TRANSREID_CACHE.resolve():
        shutil.copy2(source_checkpoint, TRANSREID_CACHE)
elif TRANSREID_CACHE.is_file():
    pass
else:
    attached = find_named_file_without_images("/kaggle/input", TRANSREID_MODEL_NAME)
    if attached:
        print("Caching attached pretrained TransReID checkpoint...")
        shutil.copy2(attached[0], TRANSREID_CACHE)
    else:
        print("Downloading official MSMT17 TransReID* ViT checkpoint with gdown...")
        try:
            import gdown
            result = gdown.download(
                id=TRANSREID_GDRIVE_ID,
                output=str(TRANSREID_CACHE),
                quiet=False,
            )
            if not result:
                raise RuntimeError("gdown returned no output path")
        except Exception as error:
            raise RuntimeError(
                "Cannot obtain vit_transreid_msmt.pth. Enable Kaggle Internet, "
                "or attach the official checkpoint as a Kaggle Dataset and set "
                "TRANSREID_CHECKPOINT_OVERRIDE."
            ) from error

if not TRANSREID_CACHE.is_file():
    raise FileNotFoundError(TRANSREID_CACHE)
if TRANSREID_CACHE.stat().st_size < 300_000_000:
    raise RuntimeError(
        "TransReID checkpoint is unexpectedly small; this is likely an HTML/"
        "partial download: {} bytes".format(TRANSREID_CACHE.stat().st_size)
    )

payload = torch_load_cpu(TRANSREID_CACHE)
tr_state = unwrap_checkpoint_state(payload)
required_transreid_keys = {
    "base.cls_token",
    "base.pos_embed",
    "base.patch_embed.proj.weight",
    "base.blocks.0.attn.qkv.weight",
    "base.blocks.11.attn.qkv.weight",
    "base.norm.weight",
    # These two are validated only to make sure this is the official full
    # TransReID checkpoint; they are intentionally NOT transplanted into UAD.
    "base.sie_embed",
    "b1.0.attn.qkv.weight",
    "b2.0.attn.qkv.weight",
}
missing = sorted(required_transreid_keys - set(tr_state))
if missing:
    raise RuntimeError(
        "Attached/downloaded file is not the expected full MSMT17 TransReID "
        f"checkpoint; missing keys: {missing}"
    )
if tr_state["base.cls_token"].shape[-1] != 768:
    raise RuntimeError("Expected ViT-B hidden dimension 768.")
if tuple(tr_state["base.sie_embed"].shape) != (15, 1, 768):
    raise RuntimeError(
        "Unexpected MSMT17 source SIE shape: "
        + str(tuple(tr_state["base.sie_embed"].shape))
    )
print(
    "Validated pretrained TransReID source:",
    {
        "path": str(TRANSREID_CACHE),
        "size_MiB": round(TRANSREID_CACHE.stat().st_size / 2**20, 1),
        "source_pos_embed": tuple(tr_state["base.pos_embed"].shape),
        "source_SIE": tuple(tr_state["base.sie_embed"].shape),
        "source_has_JPM": True,
        "target_embedding_dim": 768,
        "target_stride": TRANSREID_TARGET_STRIDE,
        "target_SIE": False,
        "target_JPM": False,
        "backbone_will_be_trainable": True,
    },
)
del payload, tr_state

TRANSREID_PATH = TRANSREID_CACHE
PRETRAIN_PATH = TRANSREID_PATH
print("Persistent TransReID initialization checkpoint:", PRETRAIN_PATH)


if RUN_TRANSREID_INIT_SMOKE_TEST:
    print("Running LAGPeR-S3CLIP trainable 768-D TransReID-initialized UAD smoke test...")
    TRANSREID_INIT_AUDIT_PATH = Path(
        "/kaggle/working/transreid_trainable_init_audit.json"
    )
    smoke_script = r"""
import json
import sys
from pathlib import Path
import torch

uad_dir = Path(sys.argv[1])
checkpoint = Path(sys.argv[2])
audit_path = Path(sys.argv[3])
sys.path.insert(0, str(uad_dir))

from config import cfg
from model import make_model

def load_state(path):
    try:
        payload = torch.load(path, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(path, map_location="cpu")
    if isinstance(payload, dict):
        if "model" in payload and isinstance(payload["model"], dict):
            payload = payload["model"]
        elif "state_dict" in payload and isinstance(payload["state_dict"], dict):
            payload = payload["state_dict"]
    return {str(k).replace("module.", ""): v for k, v in payload.items()}

cfg.merge_from_file(str(uad_dir / "configs/PVUAD.yml"))
cfg.MODEL.PRETRAIN_CHOICE = "transreid"
cfg.MODEL.PRETRAIN_PATH = str(checkpoint)
cfg.MODEL.STRIDE_SIZE = [16, 16]
cfg.MODEL.SIE_CAMERA = False
cfg.MODEL.SIE_VIEW = False
cfg.DATASETS.NAMES = "LAGPeR"
cfg.DATASETS.MODALITIES = ["RGB"]
cfg.PVUAD.GROUND_MAX_CAMID = 13
cfg.PVUAD.VFPROCA = True
cfg.PVUAD.LOCAL_CONSISTENCY = False
cfg.PVUAD.TIR_DISTILLATION = False

model = make_model(cfg, num_class=2708, camera_num=12, view_num=0).cuda().train()
if model.transreid_init_audit is None:
    raise RuntimeError("Missing TransReID initialization audit")
if model.in_planes != 768:
    raise RuntimeError("UAD backbone must remain 768-D")
if hasattr(model.base, "sie_embed"):
    raise RuntimeError("Source-camera SIE must not be copied into target UAD")
if not all(parameter.requires_grad for parameter in model.base.parameters()):
    raise RuntimeError("TransReID-initialized backbone is unexpectedly frozen")

source = load_state(checkpoint)
source_qkv = source["base.blocks.0.attn.qkv.weight"]
target_qkv = model.base.blocks[0].attn.qkv.weight.detach().cpu()
init_qkv_max_abs = float((source_qkv - target_qkv).abs().max())
source_global_final_qkv = source["b1.0.attn.qkv.weight"]
target_final_qkv = model.base.blocks[11].attn.qkv.weight.detach().cpu()
global_final_qkv_max_abs = float(
    (source_global_final_qkv - target_final_qkv).abs().max()
)
if init_qkv_max_abs > 1e-7 or global_final_qkv_max_abs > 1e-7:
    raise RuntimeError(
        "TransReID weights were not transplanted exactly: "
        f"shared_qkv={init_qkv_max_abs}, global_final_qkv={global_final_qkv_max_abs}"
    )

SMOKE_BATCH = 2
images = [
    torch.randn(SMOKE_BATCH, 3, 256, 128, device="cuda"),
]
output = model(x=images, mode=0)
cls_score, global_feat = output[0], output[1]
if tuple(global_feat.shape) != (SMOKE_BATCH, 768):
    raise RuntimeError(f"Unexpected UAD feature shape: {tuple(global_feat.shape)}")
loss = cls_score.float().square().mean() + 0.01 * global_feat[:, :16].float().square().mean()
loss.backward()

qkv_grad = model.base.blocks[0].attn.qkv.weight.grad
patch_grad = model.base.patch_embed.proj.weight.grad
if qkv_grad is None or patch_grad is None:
    raise RuntimeError("No gradient reached the TransReID-initialized backbone")
qkv_grad_norm = float(qkv_grad.float().norm().detach().cpu())
patch_grad_norm = float(patch_grad.float().norm().detach().cpu())
if not (qkv_grad_norm > 0 and patch_grad_norm > 0):
    raise RuntimeError(
        f"Backbone gradients must be nonzero; qkv={qkv_grad_norm}, "
        f"patch={patch_grad_norm}"
    )

audit = dict(model.transreid_init_audit)
audit.update({
    "smoke_test": "OK",
    "feature_shape": list(global_feat.shape),
    "smoke_batch_size": SMOKE_BATCH,
    "batchnorm_train_mode_checked": True,
    "init_qkv_max_abs": init_qkv_max_abs,
    "global_final_qkv_max_abs": global_final_qkv_max_abs,
    "qkv_grad_norm": qkv_grad_norm,
    "patch_grad_norm": patch_grad_norm,
    "backbone_all_trainable": True,
    "source_sie_used": False,
    "source_jpm_local_branches_used": False,
    "source_jpm_global_final_branch_used": True,
    "target_stride": [16, 16],
})
audit_path.write_text(json.dumps(audit, indent=2), encoding="utf-8")
print("TRANSREID_TRAINABLE_INIT_SMOKE_OK", audit)
"""
    smoke_env = os.environ.copy()
    smoke_env["CUDA_VISIBLE_DEVICES"] = "0"
    smoke_env["PYTHONPATH"] = str(UAD_DIR) + os.pathsep + smoke_env.get(
        "PYTHONPATH", ""
    )
    result = subprocess.run(
        [
            sys.executable,
            "-c",
            smoke_script,
            str(UAD_DIR),
            str(TRANSREID_PATH),
            str(TRANSREID_INIT_AUDIT_PATH),
        ],
        cwd=UAD_DIR,
        env=smoke_env,
        text=True,
        capture_output=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(
            "Trainable TransReID initialization smoke test failed. "
            "Do not start E2 until the initialization path is fixed."
        )

Attached UAD source candidates:

,path,base_commit,selected
0,/kaggle/input/notebooks/thienbao1604/pvuad-lag...,3e2a07314119402586c76096e87d40420894ad30,True

Reusing attached UAD source: /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/WHU_MARS_official_pinned
LAGPeR metrics patch already present; reusing it without modification.
Validated LAGPeR evaluator patch blocks: 2 (local structural check passed)
Pinned and patched source: /kaggle/working/WHU_MARS_official_pinned/CVPR26_UAD

/tmp/ipykernel_23/3429726758.py:127: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  archive.extractall(UAD_DIR)

Caching attached pretrained TransReID checkpoint...
Validated pretrained TransReID source: {'path': '/kaggle/working/vit_transreid_msmt.pth', 'size_MiB': 399.8, 'source_pos_embed': (1, 211, 768), 'source_SIE': (15, 1, 768), 'source_has_JPM': True, 'target_embedding_dim': 768, 'target_stride': [16, 16], 'target_SIE': False, 'target_JPM': False, 'backbone_will_be_trainable': True}
Persistent TransReID initialization checkpoint: /kaggle/working/vit_transreid_msmt.pth
Running LAGPeR-S3CLIP trainable 768-D TransReID-initialized UAD smoke test...
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
TransReID -> trainable UAD backbone initialization: {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed']}
Initialized UAD 768-D ViT backbone from pretrained TransReID; the backbone remains TRAINABLE on the target dataset.
===========building transformer===========
TRANSREID_TRAINABLE_INIT_SMOKE_OK {'checkpoint': '/kaggle/working/vit_transreid_msmt.pth', 'loaded_tensor_count': 152, 'target_tensor_count': 152, 'mismatch_count': 0, 'resized_pos_embed': {'source_shape': [1, 211, 768], 'target_shape': [1, 129, 768], 'target_grid': [16, 8]}, 'source_sie_loaded': False, 'source_jpm_local_branches_loaded': False, 'global_jpm_branch_used_for_target_final_block': True, 'global_branch_mapped_tensor_count': 14, 'embedding_dim': 768, 'backbone_trainable': True, 'loaded_required': ['blocks.0.attn.qkv.weight', 'blocks.10.attn.qkv.weight', 'blocks.11.attn.qkv.weight', 'cls_token', 'norm.weight', 'patch_embed.proj.weight', 'pos_embed'], 'smoke_test': 'OK', 'feature_shape': [2, 768], 'smoke_batch_size': 2, 'batchnorm_train_mode_checked': True, 'init_qkv_max_abs': 0.0, 'global_final_qkv_max_abs': 0.0, 'qkv_grad_norm': 0.004461345728486776, 'patch_grad_norm': 0.02284904010593891, 'backbone_all_trainable': True, 'source_sie_used': False, 'source_jpm_local_branches_used': False, 'source_jpm_global_final_branch_used': True, 'target_stride': [16, 16]}

## 4. View audit + multi-session state machine

Notebook audit số identity có cả ground/aerial trong train set rồi tự chọn:
**E3 resume → E2 completed → E2 resume → E2 fresh**.

Pipeline tag mới hoàn toàn tách khỏi output WHU-MARS và reranking cũ, nên sẽ
không resume nhầm checkpoint dataset khác.

In [5]:
FILENAME_RE = LAGPER_FILENAME_RE

PIPELINE_ROOT = Path("/kaggle/working/pvuad_runs") / PIPELINE_TAG
E2_RUN_DIR = PIPELINE_ROOT / "e2_final"
E3_RUN_DIR = PIPELINE_ROOT / "e3_tdh"
PIPELINE_ROOT.mkdir(parents=True, exist_ok=True)
E2_RUN_DIR.mkdir(parents=True, exist_ok=True)
E3_RUN_DIR.mkdir(parents=True, exist_ok=True)
PIPELINE_STATE_PATH = PIPELINE_ROOT / "pipeline_state.json"

INIT_AUDIT_SOURCE = Path("/kaggle/working/transreid_trainable_init_audit.json")
INIT_AUDIT_DEST = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if INIT_AUDIT_SOURCE.is_file() and not INIT_AUDIT_DEST.is_file():
    shutil.copy2(INIT_AUDIT_SOURCE, INIT_AUDIT_DEST)


def read_json(path):
    path = Path(path)
    if not path.is_file():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as error:
        print("Ignoring unreadable JSON:", path, error)
        return {}


def write_pipeline_state(status, active_stage, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "status": status,
        "active_stage": active_stage,
        "updated_at_unix": _time.time(),
        "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
        "session_deadline_unix": SESSION_DEADLINE_UNIX,
        "remaining_minutes": max(
            0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0
        ),
        **extra,
    }
    temporary = PIPELINE_STATE_PATH.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    os.replace(temporary, PIPELINE_STATE_PATH)
    return payload


def remaining_minutes():
    return max(0.0, (SESSION_DEADLINE_UNIX - _time.time()) / 60.0)


def copy_if_present(source_dir, destination_dir, filenames):
    if source_dir is None:
        return
    source_dir = Path(source_dir)
    destination_dir = Path(destination_dir)
    destination_dir.mkdir(parents=True, exist_ok=True)
    for filename in filenames:
        source_path = source_dir / filename
        destination_path = destination_dir / filename
        if source_path.is_file() and source_path.resolve() != destination_path.resolve():
            if not destination_path.exists():
                print("Preserving:", filename)
                shutil.copy2(source_path, destination_path)


def status_progress(status):
    return status.get("progress") or {}


def candidate_sort_key(candidate):
    status = candidate["status"]
    progress = status_progress(status)
    path_text = str(candidate["root"]).lower()
    return (
        int(PIPELINE_TAG.lower() in path_text),
        int(status.get("status") == "completed"),
        int(progress.get("epoch") or 0),
        int(bool(progress.get("epoch_complete", False))),
        int(progress.get("next_iteration") or 0),
        int(status.get("global_step") or 0),
        float(status.get("saved_at_unix") or candidate["checkpoint"].stat().st_mtime),
    )


def scan_stage_candidates(base, experiment):
    base = Path(base)
    if not base.exists():
        return []
    candidates = []
    for root, dirs, files in os.walk(base):
        root_path = Path(root)
        if root_path.name.lower() in IMAGE_SPLITS:
            dirs[:] = []
            continue
        if "pvuad_last_checkpoint.pth" not in files:
            continue
        checkpoint = root_path / "pvuad_last_checkpoint.pth"
        status = read_json(root_path / "session_status.json")
        summary = read_json(root_path / "training_summary.json")
        manifest = read_json(root_path / "run_manifest.json")
        declared = status.get("experiment", summary.get("experiment"))
        lowered = str(root_path).lower()

        # This LAGPeR pipeline must never silently bootstrap from WHU/AG outputs.
        manifest_tag = manifest.get("pipeline_tag")
        manifest_dataset = manifest.get("dataset_variant")
        if manifest_tag not in (None, PIPELINE_TAG):
            continue
        if manifest_dataset not in (None, "LAGPeR-S3CLIP"):
            continue
        if manifest_tag is None and PIPELINE_TAG.lower() not in lowered:
            continue
        legacy_match = (
            experiment == "E2" and "final_e2" in lowered
        ) or (
            experiment == "E3-TDH" and "e3_tdh" in lowered
        )
        if declared != experiment and not legacy_match:
            continue
        if status.get("stage", summary.get("stage")) not in (None, "final"):
            continue
        # Reject a manifest that clearly belongs to a different batch/LR
        # recipe. Missing legacy fields are tolerated, but contradictory
        # fields are not.
        recipe = manifest.get("recipe") or manifest.get("effective_training") or {}
        expected = (
            {"global_batch": E2_GLOBAL_BATCH, "epochs": E2_EPOCHS}
            if experiment == "E2"
            else {"global_batch": E3_GLOBAL_BATCH, "epochs": E3_EPOCHS}
        )
        incompatible = any(
            key in recipe and int(recipe[key]) != int(value)
            for key, value in expected.items()
        )
        lr_value = recipe.get("base_lr", recipe.get("backbone_lr"))
        expected_lr = E2_BASE_LR if experiment == "E2" else E3_BASE_LR
        if lr_value is not None and abs(float(lr_value) - expected_lr) > 1e-12:
            incompatible = True
        if incompatible:
            print("Skipping incompatible stage candidate:", root_path)
            continue
        candidates.append({
            "root": root_path,
            "checkpoint": checkpoint,
            "model": root_path / "pvuad_best_model.pth",
            "last_model": root_path / "pvuad_last_model.pth",
            "status": status,
            "summary": summary,
            "manifest": manifest,
        })
        dirs[:] = []
    return sorted(candidates, key=candidate_sort_key, reverse=True)


def candidate_table(candidates, label):
    if not candidates:
        return
    print(label)
    display(pd.DataFrame([{
        "root": str(item["root"]),
        "status": item["status"].get("status", "legacy_checkpoint"),
        "epoch": status_progress(item["status"]).get("epoch"),
        "next_iteration": status_progress(item["status"]).get("next_iteration"),
        "global_step": item["status"].get("global_step"),
        "best_mAP": item["status"].get("best_mAP_percent"),
        "selected": index == 0,
    } for index, item in enumerate(candidates)]))



# View-coverage audit is invariant across sessions.
PAIRING_AUDIT_PATH = PIPELINE_ROOT / "pairing_audit.csv"
pairing_frame = None

if RUN_METADATA_PAIRING_CHECK:
    by_pid = defaultdict(lambda: {"ground": 0, "aerial": 0})
    for row in train_frame.itertuples():
        view = str(row.view)
        if view not in {"ground", "aerial"}:
            raise RuntimeError(f"Unknown LAGPeR view in audit: {view}")
        by_pid[int(row.pid)][view] += 1

    pairing_rows = []
    for pid in sorted(by_pid):
        ground = int(by_pid[pid]["ground"])
        aerial = int(by_pid[pid]["aerial"])
        pairing_rows.append({
            "pid": int(pid),
            "paired_frames": int(ground + aerial),
            "ground": ground,
            "aerial": aerial,
            "view_coverage": (
                "Ground+Aerial" if ground > 0 and aerial > 0
                else "Ground-only" if ground > 0
                else "Aerial-only" if aerial > 0
                else "No sample"
            ),
        })

    pairing_frame = pd.DataFrame(pairing_rows)
    if len(pairing_frame) != LAGPER_TRAIN_ID_COUNT:
        raise RuntimeError(
            f"Expected {LAGPER_TRAIN_ID_COUNT} train identities in LAGPeR view audit, "
            f"got {len(pairing_frame)}"
        )
    pairing_frame.to_csv(PAIRING_AUDIT_PATH, index=False)
    print("LAGPeR-S3CLIP train view coverage:")
    display(
        pairing_frame["view_coverage"]
        .value_counts(dropna=False)
        .rename_axis("view_coverage")
        .reset_index(name="identities")
    )


if E3_RESUME_PATH_OVERRIDE:
    E3_CANDIDATES = [{
        "root": Path(E3_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E3_RESUME_PATH_OVERRIDE),
        "model": Path(E3_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "last_model": Path(E3_RESUME_PATH_OVERRIDE).parent / "pvuad_last_model.pth",
        "status": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E3_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E3_CANDIDATES = scan_stage_candidates(E3_RUN_DIR, "E3-TDH")
    if AUTO_RESUME:
        external_e3 = scan_stage_candidates("/kaggle/input", "E3-TDH")
        external_e3 = [
            item for item in external_e3
            if PIPELINE_TAG.lower() in str(item["root"]).lower()
        ]
        E3_CANDIDATES += external_e3
        unique = {str(item["checkpoint"]): item for item in E3_CANDIDATES}
        E3_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_RESUME_PATH_OVERRIDE:
    E2_CANDIDATES = [{
        "root": Path(E2_RESUME_PATH_OVERRIDE).parent,
        "checkpoint": Path(E2_RESUME_PATH_OVERRIDE),
        "model": Path(E2_RESUME_PATH_OVERRIDE).parent / "pvuad_best_model.pth",
        "last_model": Path(E2_RESUME_PATH_OVERRIDE).parent / "pvuad_last_model.pth",
        "status": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "session_status.json"),
        "summary": {},
        "manifest": read_json(Path(E2_RESUME_PATH_OVERRIDE).parent / "run_manifest.json"),
    }]
else:
    E2_CANDIDATES = scan_stage_candidates(E2_RUN_DIR, "E2")
    if AUTO_RESUME:
        external_e2 = scan_stage_candidates("/kaggle/input", "E2")
        if not ALLOW_LEGACY_E2_BOOTSTRAP:
            external_e2 = [
                item for item in external_e2
                if PIPELINE_TAG.lower() in str(item["root"]).lower()
            ]
        E2_CANDIDATES += external_e2
        unique = {str(item["checkpoint"]): item for item in E2_CANDIDATES}
        E2_CANDIDATES = sorted(unique.values(), key=candidate_sort_key, reverse=True)

if E2_COMPLETED_DIR_OVERRIDE:
    override_root = Path(E2_COMPLETED_DIR_OVERRIDE)
    E2_CANDIDATES.insert(0, {
        "root": override_root,
        "checkpoint": override_root / "pvuad_last_checkpoint.pth",
        "model": override_root / "pvuad_best_model.pth",
        "last_model": override_root / "pvuad_last_model.pth",
        "status": read_json(override_root / "session_status.json"),
        "summary": read_json(override_root / "training_summary.json"),
        "manifest": read_json(override_root / "run_manifest.json"),
    })

candidate_table(E3_CANDIDATES, "E3 resume candidates (highest priority):")
candidate_table(E2_CANDIDATES, "E2 candidates:")

SELECTED_E3 = E3_CANDIDATES[0] if E3_CANDIDATES else None
SELECTED_E2 = E2_CANDIDATES[0] if E2_CANDIDATES else None

# Preserve compact E2 evidence even when a completed legacy E2 is used only as
# the warm-start for E3. Large model/checkpoint files stay at their selected
# input path until E3 has created its self-contained teacher/resume artifacts.
if SELECTED_E2 is not None:
    copy_if_present(
        SELECTED_E2["root"], E2_RUN_DIR,
        [
            "metrics_history.csv", "session_status.json", "training_summary.json",
            "pvuad_last_model.pth", "pvuad_best_model.pth",
            "pairing_audit.csv", "ablation_summary.csv", "effective_command.txt",
        ],
    )

if SELECTED_E3 is not None:
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None and SELECTED_E2["status"].get("status") == "completed":
    ACTIVE_STAGE = "E3"
elif SELECTED_E2 is not None:
    ACTIVE_STAGE = "E2"
else:
    ACTIVE_STAGE = "E2"

print("Selected pipeline stage:", ACTIVE_STAGE)
write_pipeline_state(
    "ready", ACTIVE_STAGE,
    selected_e2=str(SELECTED_E2["root"]) if SELECTED_E2 else None,
    selected_e3=str(SELECTED_E3["root"]) if SELECTED_E3 else None,
)

(PIPELINE_ROOT / "RESUME_NEXT_SESSION.txt").write_text(
    "PV-UAD LAGPeR-S3CLIP TransReID-init E2 -> E3 LAST-only multi-session pipeline\n\n"
    "1. A partial session ends normally with e2_paused or e3_paused.\n"
    "2. Start every run with Save Version -> Save & Run All; Kaggle then commits "
    "the output automatically after this notebook exits cleanly.\n"
    "3. In a new session, add the immediately preceding version output as Input.\n"
    "4. Use this exact notebook, keep Settings unchanged, and Run All.\n"
    "5. The state machine resumes E3 first, otherwise completed/partial E2.\n\n"
    f"Pipeline folder: pvuad_runs/{PIPELINE_TAG}\n",
    encoding="utf-8",
)
print("Pipeline output:", PIPELINE_ROOT)

LAGPeR-S3CLIP train view coverage:

   view_coverage  identities
0  Ground+Aerial        2708

E2 candidates:

,root,status,epoch,next_iteration,global_step,best_mAP,selected
0,/kaggle/input/notebooks/thienbao1604/pvuad-lag...,completed,60,0,136860,26.982922,True

Preserving: metrics_history.csv
Preserving: session_status.json
Preserving: training_summary.json
Preserving: pvuad_last_model.pth
Preserving: pvuad_best_model.pth
Preserving: effective_command.txt
Selected pipeline stage: E3
Pipeline output: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix

## 5. Train E2=60 → E3=25 → LAST E3 evaluate 3 LAGPeR protocols

Training chỉ dùng protocol A→G cho epoch-end diagnostic (chỉ epoch cuối). Sau E3, **cùng một last model**
được test bằng Flip-TTA trên A→G, G→A và G→A+G. Nếu hết giờ Kaggle giữa các protocol,
save output rồi Run All phiên sau; training sẽ được skip và chỉ chạy TTA còn thiếu.

In [6]:
environment = os.environ.copy()
environment.update({
    "CUDA_VISIBLE_DEVICES": ",".join(map(str, range(NUM_GPUS))),
    "PYTHONPATH": str(UAD_DIR) + os.pathsep + environment.get("PYTHONPATH", ""),
    "PYTHONUNBUFFERED": "1",
    "OMP_NUM_THREADS": "2",
    "PYTORCH_CUDA_ALLOC_CONF": "expandable_segments:True",
    "TORCH_NCCL_ASYNC_ERROR_HANDLING": "1",
    # End-of-stage training evaluation is A->G. Final tests override protocol.
    "PVUAD_LAGPER_PROTOCOL": "A2G",
    "PVUAD_LAGPER_MARKET_EVAL": "1",
})


def stage_status(run_dir):
    return read_json(Path(run_dir) / "session_status.json")


def display_stage_status(name, status):
    progress = status_progress(status)
    display(pd.DataFrame([{
        "stage": name,
        "status": status.get("status"),
        "reason": status.get("reason"),
        "epoch": progress.get("epoch"),
        "next_iteration": progress.get("next_iteration"),
        "epoch_complete": progress.get("epoch_complete"),
        "global_step": status.get("global_step"),
        "best_mAP": status.get("best_mAP_percent"),
        "remaining_minutes": round(remaining_minutes(), 1),
    }]))


def run_command_checked(command, run_dir, stage_name):
    command_text = shlex.join(command)
    (Path(run_dir) / "effective_command.txt").write_text(
        command_text + "\n", encoding="utf-8"
    )
    print("\nLaunching", stage_name)
    print(command_text)
    if not RUN_TRAINING:
        print("RUN_TRAINING=False — command prepared but not launched.")
        return {}
    result = subprocess.run(command, cwd=UAD_DIR, env=environment, check=False)
    if result.returncode != 0:
        # A DDP/NCCL process can abort after a periodic checkpoint has already
        # been written. Treat that as a resumable session rather than throwing
        # away hours of work. A missing/invalid checkpoint still fails hard.
        checkpoint = Path(run_dir) / "pvuad_last_checkpoint.pth"
        status_path = Path(run_dir) / "session_status.json"
        recovered_status = stage_status(run_dir) if status_path.is_file() else {}
        if (
            checkpoint.is_file()
            and recovered_status.get("status")
            in {"running_checkpoint", "paused_time_limit"}
        ):
            print(
                f"{stage_name} subprocess exited with code {result.returncode}, "
                "but a valid resumable checkpoint exists. "
                "Ending this notebook cleanly so the next Kaggle session can resume."
            )
            write_pipeline_state(
                "recoverable_stage_crash", stage_name,
                returncode=result.returncode,
                run_dir=str(run_dir),
                checkpoint=str(checkpoint),
            )
            display_stage_status(stage_name, recovered_status)
            return recovered_status
        write_pipeline_state(
            "failed", stage_name,
            returncode=result.returncode,
            run_dir=str(run_dir),
        )
        raise subprocess.CalledProcessError(result.returncode, command)
    required = [
        Path(run_dir) / "pvuad_last_checkpoint.pth",
        Path(run_dir) / "session_status.json",
    ]
    missing = [str(path) for path in required if not path.is_file()]
    if missing:
        raise RuntimeError(f"{stage_name} ended without required outputs: {missing}")
    status = stage_status(run_dir)
    if status.get("status") not in {
        "paused_time_limit", "completed", "running_checkpoint"
    }:
        raise RuntimeError(f"Unexpected {stage_name} status: {status}")
    display_stage_status(stage_name, status)
    return status


def make_stage_manifest(run_dir, stage_name, recipe, resume_path=None, **extra):
    payload = {
        "pipeline": PIPELINE_NAME,
        "pipeline_tag": PIPELINE_TAG,
        "stage_name": stage_name,
        "recipe": recipe,
        "dataset_variant": "LAGPeR-S3CLIP",
        "dataset_protocol": "A2G_training_eval__final_A2G_G2A_G2AG",
        "dataset_root": str(DATA_ROOT),
        "dataset_counts": DATASET_AUDIT,
        "source_commit": PINNED_UAD_COMMIT,
        "overlay_sha256": OVERLAY_HASHES,
        "resume_path": str(resume_path) if resume_path else None,
        "python": sys.version,
        "torch": torch.__version__,
        "cuda": torch.version.cuda,
        "gpus": gpu_rows,
        "seed": RANDOM_SEED,
        "session_guard": {
            "notebook_started_unix": NOTEBOOK_SESSION_STARTED_UNIX,
            "session_deadline_unix": SESSION_DEADLINE_UNIX,
            "hard_stop_hours": SESSION_HARD_STOP_HOURS,
            "stop_reserve_minutes": SESSION_STOP_RESERVE_MINUTES,
            "checkpoint_every_minutes": CHECKPOINT_EVERY_MINUTES,
            "time_check_every_steps": TIME_CHECK_EVERY_STEPS,
            "min_eval_remaining_minutes": MIN_EVAL_REMAINING_MINUTES,
        },
        **extra,
    }
    manifest_path = Path(run_dir) / "run_manifest.json"
    manifest_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    shutil.copy2(
        UAD_DIR / "PVUAD_patch_manifest.json",
        Path(run_dir) / "PVUAD_patch_manifest.json",
    )
    return manifest_path


def e2_command(resume_path, strict_resume=True):
    # Fresh E2 receives pretrained TransReID backbone initialization exactly
    # once. Resume sessions reconstruct the model from the saved UAD checkpoint,
    # so they must NOT apply the source initialization again.
    pretrain_choice = "none" if resume_path else "transreid"
    recipe = {
        "experiment": "E2", "stage": "final", "epochs": E2_EPOCHS,
        "global_batch": E2_GLOBAL_BATCH, "base_lr": E2_BASE_LR,
        "view_balanced_sampler": True, "vfproca": True,
        "local_consistency": False, "hard_gpd": False,
        "dataset": "LAGPeR-S3CLIP", "protocol": "A2G_training_eval",
        "initialization": "MSMT17_TransReID_trainable_backbone",
        "pretrain_choice_this_session": pretrain_choice,
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
        "source_sie_used": False,
        "source_jpm_local_branches_used": False,
        "source_jpm_global_final_branch_used": True,
    }
    manifest_path = make_stage_manifest(
        E2_RUN_DIR, "E2", recipe, resume_path=resume_path
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", pretrain_choice,
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "LAGPeR",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E2_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E2_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E2_BASE_LR),
        "SOLVER.EVAL_PERIOD", str(E2_EPOCHS),
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E2_RUN_DIR),
        "PVUAD.EXPERIMENT", "E2",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.SYNC_PAIRED_AUG", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "False",
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "False",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", str(bool(strict_resume)),
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


E2_STATUS = SELECTED_E2["status"] if SELECTED_E2 else {}
E2_RESUME_PATH = None
E2_MODEL_PATH = None
E2_CHECKPOINT_PATH = None
E2_STRICT_RESUME = True
E2_COMPLETED_THIS_SESSION = False

if ACTIVE_STAGE == "E2":
    if SELECTED_E2 is not None:
        E2_RESUME_PATH = SELECTED_E2["checkpoint"]
        selected_hashes = (
            SELECTED_E2.get("manifest", {}).get("overlay_sha256") or {}
        )
        selected_processor_hash = selected_hashes.get("processor/processor.py")
        current_processor_hash = OVERLAY_HASHES.get("processor/processor.py")
        # E2 v2.3 checkpoints predate E3's gated fields in the resume
        # signature. Their known E2 structure is compatible; disable only the
        # signature-key comparison while retaining strict state_dict/optimizer
        # structural loading. New combined checkpoints remain fully strict.
        if (
            selected_processor_hash
            and selected_processor_hash != current_processor_hash
        ):
            E2_STRICT_RESUME = False
            print(
                "Known legacy E2 overlay detected; structural resume checks "
                "remain enabled, signature-only strictness is relaxed."
            )
        copy_if_present(
            SELECTED_E2["root"], E2_RUN_DIR,
            [
                "metrics_history.csv", "pvuad_best_model.pth", "pvuad_last_model.pth",
                "pairing_audit.csv", "ablation_summary.csv",
                "training_summary.json",
            ],
        )
    else:
        print("No checkpoint found: starting E2 from pretrained TransReID ViT weights; backbone is TRAINABLE.")

    write_pipeline_state(
        "e2_running", "E2",
        resume_path=str(E2_RESUME_PATH) if E2_RESUME_PATH else None,
    )
    E2_STATUS = run_command_checked(
        e2_command(E2_RESUME_PATH, E2_STRICT_RESUME), E2_RUN_DIR, "E2"
    )
    if not RUN_TRAINING:
        write_pipeline_state("dry_run", "E2")
    elif E2_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e2_paused", "E2", e2_status=E2_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E2 PAUSED SAFELY. Save Version and continue in a new session.")
    elif E2_STATUS.get("status") == "completed":
        E2_MODEL_PATH = E2_RUN_DIR / "pvuad_last_model.pth"
        E2_CHECKPOINT_PATH = E2_RUN_DIR / "pvuad_last_checkpoint.pth"
        required = [E2_MODEL_PATH, E2_CHECKPOINT_PATH, E2_RUN_DIR / "metrics_history.csv"]
        missing = [str(path) for path in required if not path.is_file()]
        if missing:
            raise RuntimeError(f"Completed E2 is missing: {missing}")
        E2_COMPLETED_THIS_SESSION = True
        ACTIVE_STAGE = "E3"
else:
    if SELECTED_E2 is not None:
        E2_MODEL_PATH = SELECTED_E2.get("last_model")
        E2_CHECKPOINT_PATH = SELECTED_E2["checkpoint"]
        if E2_MODEL_PATH is None or not Path(E2_MODEL_PATH).is_file():
            raise FileNotFoundError(
                "LAST-only policy requires completed E2 pvuad_last_model.pth; "
                "best-model fallback is disabled."
            )


def create_teacher_cache(source_model, destination):
    source_model = Path(source_model)
    destination = Path(destination)
    if destination.is_file():
        return destination
    if not source_model.is_file():
        raise FileNotFoundError(source_model)
    try:
        payload = torch.load(source_model, map_location="cpu", weights_only=False)
    except TypeError:
        payload = torch.load(source_model, map_location="cpu")
    if isinstance(payload, dict) and "model" in payload:
        payload = payload["model"]
    elif isinstance(payload, dict) and "state_dict" in payload:
        payload = payload["state_dict"]
    if not isinstance(payload, dict):
        raise ValueError("E2 model file does not contain a state dictionary")
    teacher_state = {}
    for key, value in payload.items():
        clean = str(key).replace("module.", "")
        teacher_state[clean] = value.half() if torch.is_floating_point(value) else value
    temporary = destination.with_suffix(".pth.tmp")
    torch.save(teacher_state, temporary)
    os.replace(temporary, destination)
    del payload, teacher_state
    return destination


E3_STATUS = SELECTED_E3["status"] if SELECTED_E3 else {}
E3_RESUME_PATH = SELECTED_E3["checkpoint"] if SELECTED_E3 else None
TEACHER_CACHE = E3_RUN_DIR / "e2_teacher_model_fp16.pth"

if SELECTED_E3 is not None:
    copy_if_present(
        SELECTED_E3["root"], E3_RUN_DIR,
        [
            "metrics_history.csv", "pvuad_best_model.pth", "pvuad_last_model.pth",
            "e2_teacher_model_fp16.pth", "tta_best_metrics.csv", "tta_last_metrics.csv",
            "training_summary.json", "TRAINING_COMPLETE_BEFORE_TTA.json",
            "FINAL_TTA_FAILED.txt", "effective_test_command.txt",
        ],
    )


def e3_command(resume_path, student_model, prototype_checkpoint, teacher_cache):
    recipe = {
        "experiment": "E3-TDH", "stage": "final", "epochs": E3_EPOCHS,
        "global_batch": E3_GLOBAL_BATCH, "backbone_lr": E3_BASE_LR,
        "head_lr_multiplier": E3_HEAD_LR_MULTIPLIER,
        "tir_global_weight": 0.0,
        "tir_local_weight": 0.0,
        "feature_preserve_weight": FEATURE_PRESERVE_WEIGHT,
        "scenario_hard_weight": SCENARIO_HARD_WEIGHT,
        "initialization_origin": "MSMT17_TransReID_then_LAGPeR_S3CLIP_E2_epoch60",
        "dataset": "LAGPeR-S3CLIP", "protocol": "A2G_training_eval",
        "tir_distillation": False,
        "embedding_dim": 768,
        "backbone_stride": [16, 16],
    }
    manifest_path = make_stage_manifest(
        E3_RUN_DIR, "E3-TDH", recipe, resume_path=resume_path,
        e2_model_path=str(E2_MODEL_PATH) if E2_MODEL_PATH else None,
        e2_checkpoint_path=str(E2_CHECKPOINT_PATH) if E2_CHECKPOINT_PATH else None,
        teacher_model_path=str(teacher_cache),
    )
    opts = [
        "MODEL.DIST_TRAIN", "True",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "LAGPeR",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "SOLVER.SEED", str(RANDOM_SEED),
        "SOLVER.MAX_EPOCHS", str(E3_EPOCHS),
        "SOLVER.IMS_PER_BATCH", str(E3_GLOBAL_BATCH),
        "SOLVER.BASE_LR", str(E3_BASE_LR),
        "SOLVER.WARMUP_EPOCHS", "1",
        "SOLVER.EVAL_PERIOD", str(E3_EPOCHS),
        "SOLVER.CHECKPOINT_PERIOD", "5",
        "INPUT.RE_PROB", "0.0",
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.SYNC_PAIRED_AUG", "True",
        "PVUAD.VFPROCA", "True",
        "MODEL.PCA_LOSS_WEIGHT", "0.01",
        "PVUAD.VIEW_ALIGNMENT_WEIGHT", "0.5",
        "PVUAD.INVARIANT_ID_WEIGHT", "0.5",
        "PVUAD.SCENARIO_CLS_WEIGHT", "0.1",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.LOCAL_CONSISTENCY", "False",
        "PVUAD.HARD_GPD", "False",
        "PVUAD.FINETUNE", "True",
        "PVUAD.WARMSTART_MODEL_PATH", str(student_model),
        "PVUAD.WARMSTART_PROTOTYPE_PATH", (
            str(prototype_checkpoint) if prototype_checkpoint else ""
        ),
        "PVUAD.TEACHER_MODEL_PATH", str(teacher_cache),
        "PVUAD.HEAD_LR_MULTIPLIER", str(float(E3_HEAD_LR_MULTIPLIER)),
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.TIR_GLOBAL_WEIGHT", "0.0",
        "PVUAD.TIR_LOCAL_WEIGHT", "0.0",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", str(float(FEATURE_PRESERVE_WEIGHT)),
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.SCENARIO_HARD_WEIGHT", str(float(SCENARIO_HARD_WEIGHT)),
        "PVUAD.SCENARIO_HARD_TOPK", str(int(SCENARIO_HARD_TOPK)),
        "PVUAD.SCENARIO_HARD_MARGIN", str(float(SCENARIO_HARD_MARGIN)),
        "PVUAD.SCENARIO_HARD_TAU", str(float(SCENARIO_HARD_TAU)),
        "PVUAD.SCENARIO_HARD_START_EPOCH", str(int(SCENARIO_HARD_START_EPOCH)),
        "PVUAD.SCENARIO_BANK_MOMENTUM", "0.2",
        "PVUAD.FINAL_FLIP_TTA", "False",
        "PVUAD.SAVE_LAST_EVERY", "5",
        "PVUAD.RUN_MANIFEST", str(manifest_path),
        "PVUAD.SESSION_DEADLINE_UNIX", str(float(SESSION_DEADLINE_UNIX)),
        "PVUAD.STOP_RESERVE_MINUTES", str(float(SESSION_STOP_RESERVE_MINUTES)),
        "PVUAD.CHECKPOINT_EVERY_MINUTES", str(float(CHECKPOINT_EVERY_MINUTES)),
        "PVUAD.TIME_CHECK_EVERY_STEPS", str(int(TIME_CHECK_EVERY_STEPS)),
        "PVUAD.MIN_EVAL_REMAINING_MINUTES", str(float(MIN_EVAL_REMAINING_MINUTES)),
        "PVUAD.STRICT_RESUME_CONFIG", "True",
    ]
    if resume_path:
        opts += ["PVUAD.RESUME_PATH", str(resume_path)]
    return [
        sys.executable, "-m", "torch.distributed.run", "--standalone",
        f"--nproc_per_node={NUM_GPUS}", "train.py", "--config_file",
        "configs/PVUAD.yml", *opts,
    ]


can_enter_e3 = (
    ACTIVE_STAGE == "E3"
    and (E3_STATUS.get("status") != "completed")
    and RUN_TRAINING
)
if (
    can_enter_e3
    and E2_COMPLETED_THIS_SESSION
    and ALWAYS_START_E3_IN_NEW_SESSION
):
    write_pipeline_state(
        "e2_completed_e3_pending", "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action=(
            "Kaggle will save this completed E2 output. Attach it to a new "
            "session and use Save & Run All; E3 will start automatically."
        ),
    )
    print(
        "E2 COMPLETE. This Kaggle version now ends cleanly by design. "
        "Attach its output to the next session; E3 will start there."
    )
    can_enter_e3 = False
elif can_enter_e3 and remaining_minutes() < MIN_E3_START_REMAINING_MINUTES:
    pending_status = "e3_paused" if E3_RESUME_PATH else "e2_completed_e3_pending"
    write_pipeline_state(
        pending_status, "E3",
        e2_status=E2_STATUS,
        remaining_minutes=remaining_minutes(),
        next_action="Save Version; attach this output and Run All in a new session.",
    )
    print(
        "Only {:.1f} minutes remain. E3 will start/resume in the next "
        "session.".format(remaining_minutes())
    )
    can_enter_e3 = False

if can_enter_e3:
    if E3_RESUME_PATH is not None:
        teacher_source = (
            SELECTED_E3["root"] / "e2_teacher_model_fp16.pth"
        )
        if not teacher_source.is_file() and E2_MODEL_PATH is not None:
            teacher_source = E2_MODEL_PATH
        if not TEACHER_CACHE.is_file():
            if teacher_source.name == "e2_teacher_model_fp16.pth":
                shutil.copy2(teacher_source, TEACHER_CACHE)
            else:
                create_teacher_cache(teacher_source, TEACHER_CACHE)
        student_model = TEACHER_CACHE
        prototype_checkpoint = None
    else:
        if E2_MODEL_PATH is None or not Path(E2_MODEL_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs a completed E2 final model. Attach the "
                "previous combined/E2 output or use E2_COMPLETED_DIR_OVERRIDE."
            )
        if E2_CHECKPOINT_PATH is None or not Path(E2_CHECKPOINT_PATH).is_file():
            raise FileNotFoundError(
                "E3 needs E2 pvuad_last_checkpoint.pth for prototype warm-start."
            )
        create_teacher_cache(E2_MODEL_PATH, TEACHER_CACHE)
        student_model = E2_MODEL_PATH
        prototype_checkpoint = E2_CHECKPOINT_PATH

    print("Frozen E2 teacher:", TEACHER_CACHE)
    write_pipeline_state(
        "e3_running", "E3",
        e2_status=E2_STATUS,
        e3_resume_path=str(E3_RESUME_PATH) if E3_RESUME_PATH else None,
    )
    E3_STATUS = run_command_checked(
        e3_command(
            E3_RESUME_PATH, student_model, prototype_checkpoint, TEACHER_CACHE
        ),
        E3_RUN_DIR,
        "E3-TDH (LAGPeR RGB adaptation)",
    )
    if E3_STATUS.get("status") in {"paused_time_limit", "running_checkpoint"}:
        write_pipeline_state(
            "e3_paused", "E3", e2_status=E2_STATUS, e3_status=E3_STATUS,
            next_action="Attach this output to a new session and Run All.",
        )
        print("E3 PAUSED SAFELY. Save Version and continue in a new session.")


def run_final_tta(model_path, protocol):
    """Evaluate one LAGPeR protocol using ONLY E3 last model."""
    protocol = str(protocol).upper()
    if protocol not in FINAL_PROTOCOLS:
        raise ValueError(protocol)

    metrics_filename = f"tta_{protocol}_last_metrics.csv"
    metrics_path = E3_RUN_DIR / metrics_filename
    if metrics_path.is_file():
        print(f"{protocol}: already evaluated -> {metrics_path}")
        return True

    test_opts = [
        "MODEL.DIST_TRAIN", "False",
        "MODEL.PRETRAIN_CHOICE", "none",
        "MODEL.PRETRAIN_PATH", str(PRETRAIN_PATH),
        "MODEL.STRIDE_SIZE", "[16, 16]",
        "MODEL.SIE_CAMERA", "False",
        "MODEL.SIE_VIEW", "False",
        "DATASETS.NAMES", "LAGPeR",
        "DATASETS.MODALITIES", "['RGB']",
        "DATASETS.ROOT_DIR", str(DATA_LINK_PARENT),
        "DATALOADER.NUM_WORKERS", str(NUM_WORKERS),
        "TEST.IMS_PER_BATCH", "256",
        "TEST.RE_RANKING", "False",
        "TEST.TOP_K_EVAL", "0",
        "TEST.WEIGHT", str(model_path),
        "OUTPUT_DIR", str(E3_RUN_DIR),
        "PVUAD.EXPERIMENT", "E3-TDH",
        "PVUAD.STAGE", "final",
        "PVUAD.DEV_MODE", "False",
        "PVUAD.PAIRED_VIEW_SAMPLER", "True",
        "PVUAD.STRICT_PAIRED_DATA", "False",
        "PVUAD.GROUND_MAX_CAMID", str(GROUND_MAX_CAMID),
        "PVUAD.VFPROCA", "True",
        "PVUAD.TEST_INVARIANT_BLEND", "0.5",
        "PVUAD.TIR_DISTILLATION", "False",
        "PVUAD.FEATURE_PRESERVE_WEIGHT", "0.0",
        "PVUAD.SCENARIO_HARD_GPD", "True",
        "PVUAD.FINAL_FLIP_TTA", "True",
        "PVUAD.TTA_METRICS_FILENAME", metrics_filename,
    ]
    test_command = [
        sys.executable, "test.py", "--config_file", "configs/PVUAD.yml",
        *test_opts,
    ]
    (E3_RUN_DIR / f"effective_test_command_{protocol}.txt").write_text(
        shlex.join(test_command) + "\n", encoding="utf-8"
    )

    test_env = environment.copy()
    test_env["CUDA_VISIBLE_DEVICES"] = "0"
    test_env["PVUAD_LAGPER_PROTOCOL"] = protocol
    test_env["PVUAD_LAGPER_MARKET_EVAL"] = "1"

    print(f"Running LAGPeR-S3CLIP {protocol} with E3 LAST model + flip-TTA")
    print(" ", model_path)
    result = subprocess.run(
        test_command, cwd=UAD_DIR, env=test_env, check=False
    )
    if result.returncode != 0 or not metrics_path.is_file():
        warning = (
            f"{protocol} final TTA failed; E3 last checkpoint remains valid. "
            f"returncode={result.returncode}."
        )
        (E3_RUN_DIR / f"FINAL_TTA_FAILED_{protocol}.txt").write_text(
            warning + "\n", encoding="utf-8"
        )
        print("WARNING:", warning)
        return False
    return True


E3_COMPLETED = E3_STATUS.get("status") == "completed"
if E3_COMPLETED:
    if SELECTED_E3 is not None:
        copy_if_present(
            SELECTED_E3["root"], E3_RUN_DIR,
            [
                "pvuad_last_checkpoint.pth", "pvuad_last_model.pth",
                "session_status.json", "training_summary.json", "metrics_history.csv",
                "tta_A2G_last_metrics.csv", "tta_G2A_last_metrics.csv",
                "tta_G2AG_last_metrics.csv",
            ],
        )

    # LAST-only policy: pvuad_best_model.pth is intentionally irrelevant.
    last_model = E3_RUN_DIR / "pvuad_last_model.pth"
    last_checkpoint = E3_RUN_DIR / "pvuad_last_checkpoint.pth"
    if not last_model.is_file():
        raise FileNotFoundError("Completed E3 is missing pvuad_last_model.pth")
    if not last_checkpoint.is_file():
        raise FileNotFoundError("Completed E3 is missing pvuad_last_checkpoint.pth")

    protocol_status = {}
    for protocol in FINAL_PROTOCOLS:
        metrics_path = E3_RUN_DIR / f"tta_{protocol}_last_metrics.csv"
        ok = metrics_path.is_file()
        if RUN_FINAL_FLIP_TTA and not ok:
            if remaining_minutes() >= MIN_TTA_START_REMAINING_MINUTES:
                ok = run_final_tta(last_model, protocol)
            else:
                print(
                    f"E3 complete but only {remaining_minutes():.1f} min remain; "
                    f"{protocol} TTA will continue next session."
                )
        protocol_status[protocol] = bool(ok or not RUN_FINAL_FLIP_TTA)

    all_done = all(protocol_status.values())
    final_status = "completed" if all_done else "e3_complete_tta_pending"
    write_pipeline_state(
        final_status,
        "DONE" if all_done else "TTA",
        e2_status=E2_STATUS,
        e3_status=E3_STATUS,
        checkpoint_policy="last_only",
        e2_to_e3_weights="E2/pvuad_last_model.pth",
        e2_to_e3_prototype="E2/pvuad_last_checkpoint.pth:prototype_bank",
        final_test_weights="E3/pvuad_last_model.pth",
        final_protocols=protocol_status,
        next_action=(
            None if all_done
            else "Attach this output and Run All; training is skipped and pending protocol TTA resumes."
        ),
    )
elif ACTIVE_STAGE == "E3" and not can_enter_e3 and not RUN_TRAINING:
    write_pipeline_state("dry_run", "E3")

Frozen E2 teacher: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth

Launching E3-TDH (LAGPeR RGB adaptation)
/usr/bin/python3 -m torch.distributed.run --standalone --nproc_per_node=2 train.py --config_file configs/PVUAD.yml MODEL.DIST_TRAIN True MODEL.PRETRAIN_CHOICE none MODEL.PRETRAIN_PATH /kaggle/working/vit_transreid_msmt.pth MODEL.STRIDE_SIZE '[16, 16]' MODEL.SIE_CAMERA False MODEL.SIE_VIEW False DATASETS.NAMES LAGPeR DATASETS.MODALITIES '['"'"'RGB'"'"']' DATASETS.ROOT_DIR /kaggle/working/pvuad_lagper_data DATALOADER.NUM_WORKERS 4 SOLVER.SEED 1234 SOLVER.MAX_EPOCHS 25 SOLVER.IMS_PER_BATCH 24 SOLVER.BASE_LR 0.0001 SOLVER.WARMUP_EPOCHS 1 SOLVER.EVAL_PERIOD 25 SOLVER.CHECKPOINT_PERIOD 5 INPUT.RE_PROB 0.0 TEST.IMS_PER_BATCH 256 TEST.RE_RANKING False TEST.TOP_K_EVAL 0 OUTPUT_DIR /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh PVUAD.EXPERIMENT E3-TDH PVUAD.STAGE final PVUAD.DEV_MODE False PVUAD.PAIRED_VIEW_SAMPLER True PVUAD.STRICT_PAIRED_DATA False PVUAD.GROUND_MAX_CAMID 13 PVUAD.SYNC_PAIRED_AUG True PVUAD.VFPROCA True MODEL.PCA_LOSS_WEIGHT 0.01 PVUAD.VIEW_ALIGNMENT_WEIGHT 0.5 PVUAD.INVARIANT_ID_WEIGHT 0.5 PVUAD.SCENARIO_CLS_WEIGHT 0.1 PVUAD.TEST_INVARIANT_BLEND 0.5 PVUAD.LOCAL_CONSISTENCY False PVUAD.HARD_GPD False PVUAD.FINETUNE True PVUAD.WARMSTART_MODEL_PATH /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth PVUAD.WARMSTART_PROTOTYPE_PATH /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth PVUAD.TEACHER_MODEL_PATH /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth PVUAD.HEAD_LR_MULTIPLIER 5.0 PVUAD.TIR_DISTILLATION False PVUAD.TIR_GLOBAL_WEIGHT 0.0 PVUAD.TIR_LOCAL_WEIGHT 0.0 PVUAD.FEATURE_PRESERVE_WEIGHT 0.05 PVUAD.SCENARIO_HARD_GPD True PVUAD.SCENARIO_HARD_WEIGHT 0.15 PVUAD.SCENARIO_HARD_TOPK 5 PVUAD.SCENARIO_HARD_MARGIN 0.05 PVUAD.SCENARIO_HARD_TAU 0.05 PVUAD.SCENARIO_HARD_START_EPOCH 3 PVUAD.SCENARIO_BANK_MOMENTUM 0.2 PVUAD.FINAL_FLIP_TTA False PVUAD.SAVE_LAST_EVERY 5 PVUAD.RUN_MANIFEST /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/run_manifest.json PVUAD.SESSION_DEADLINE_UNIX 1789704274.4606638 PVUAD.STOP_RESERVE_MINUTES 15.0 PVUAD.CHECKPOINT_EVERY_MINUTES 30.0 PVUAD.TIME_CHECK_EVERY_STEPS 10 PVUAD.MIN_EVAL_REMAINING_MINUTES 25.0 PVUAD.STRICT_RESUME_CONFIG True

[W917 19:04:55.510527909 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

2026-09-17 19:05:07,942 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh
2026-09-17 19:05:07,942 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'LAGPeR', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_lagper_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '25', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '13', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.0', 'PVUAD.TIR_LOCAL_WEIGHT', '0.0', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1789704274.4606638', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '25.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=1)
2026-09-17 19:05:07,942 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-17 19:05:07,950 transreid INFO: Saving model in the path :/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh
2026-09-17 19:05:07,950 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'True', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'LAGPeR', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_lagper_data', 'DATALOADER.NUM_WORKERS', '4', 'SOLVER.SEED', '1234', 'SOLVER.MAX_EPOCHS', '25', 'SOLVER.IMS_PER_BATCH', '24', 'SOLVER.BASE_LR', '0.0001', 'SOLVER.WARMUP_EPOCHS', '1', 'SOLVER.EVAL_PERIOD', '25', 'SOLVER.CHECKPOINT_PERIOD', '5', 'INPUT.RE_PROB', '0.0', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '13', 'PVUAD.SYNC_PAIRED_AUG', 'True', 'PVUAD.VFPROCA', 'True', 'MODEL.PCA_LOSS_WEIGHT', '0.01', 'PVUAD.VIEW_ALIGNMENT_WEIGHT', '0.5', 'PVUAD.INVARIANT_ID_WEIGHT', '0.5', 'PVUAD.SCENARIO_CLS_WEIGHT', '0.1', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.LOCAL_CONSISTENCY', 'False', 'PVUAD.HARD_GPD', 'False', 'PVUAD.FINETUNE', 'True', 'PVUAD.WARMSTART_MODEL_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth', 'PVUAD.WARMSTART_PROTOTYPE_PATH', '/kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth', 'PVUAD.TEACHER_MODEL_PATH', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth', 'PVUAD.HEAD_LR_MULTIPLIER', '5.0', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.TIR_GLOBAL_WEIGHT', '0.0', 'PVUAD.TIR_LOCAL_WEIGHT', '0.0', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.05', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.SCENARIO_HARD_WEIGHT', '0.15', 'PVUAD.SCENARIO_HARD_TOPK', '5', 'PVUAD.SCENARIO_HARD_MARGIN', '0.05', 'PVUAD.SCENARIO_HARD_TAU', '0.05', 'PVUAD.SCENARIO_HARD_START_EPOCH', '3', 'PVUAD.SCENARIO_BANK_MOMENTUM', '0.2', 'PVUAD.FINAL_FLIP_TTA', 'False', 'PVUAD.SAVE_LAST_EVERY', '5', 'PVUAD.RUN_MANIFEST', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/run_manifest.json', 'PVUAD.SESSION_DEADLINE_UNIX', '1789704274.4606638', 'PVUAD.STOP_RESERVE_MINUTES', '15.0', 'PVUAD.CHECKPOINT_EVERY_MINUTES', '30.0', 'PVUAD.TIME_CHECK_EVERY_STEPS', '10', 'PVUAD.MIN_EVAL_REMAINING_MINUTES', '25.0', 'PVUAD.STRICT_RESUME_CONFIG', 'True'], local_rank=0)
2026-09-17 19:05:07,951 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-17 19:05:07,951 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB',)
  NAMES: LAGPeR
  ROOT_DIR: /kaggle/working/pvuad_lagper_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.0
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: True
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.05
  FINAL_FLIP_TTA: False
  FINETUNE: True
  GROUND_MAX_CAMID: 13
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 5.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 25.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/run_manifest.json
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 1789704274.4606638
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 15.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: True
  TEACHER_MODEL_PATH: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.0
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.0
  TTA_METRICS_FILENAME: tta_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH: /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth
  WARMSTART_PROTOTYPE_PATH: /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth
SOLVER:
  BASE_LR: 0.0001
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 25
  GAMMA: 0.1
  IMS_PER_BATCH: 24
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 25
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 1
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT:

[W917 19:05:07.409303493 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W917 19:05:07.418134319 socket.cpp:207] [c10d] The hostname of the client socket cannot be retrieved. err=-3

=> LAGPeR loaded (A2G)
   train       : /kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_train
   query       : /kaggle/working/pvuad_lagper_data/LAGPeR/query_aerial
   gallery dirs: ['/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_test_ground', '/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_gallery']
   gallery noise: 134
=> LAGPeR loaded (A2G)
   train       : /kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_train
   query       : /kaggle/working/pvuad_lagper_data/LAGPeR/query_aerial
   gallery dirs: ['/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_test_ground', '/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_gallery']
   gallery noise: 134
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |  2708 |    40770 |        12
  query    |  1523 |     3046 |         3
  gallery  |  1524 |    15533 |        12
  ----------------------------------------
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |  2708 |    40770 |        12
  query    |  1523 |     3046 |         3
  gallery  |  1524 |    15533 |        12
  ----------------------------------------
DIST_TRAIN START
DIST_TRAIN START
ViewBalancedPKM: 2708 IDs (2708 dual-view, 0 single-view), 54,756 sample slots/epoch, 3 PID x 4 instances per GPU
ViewBalancedPKM: 2708 IDs (2708 dual-view, 0 single-view), 54,756 sample slots/epoch, 3 PID x 4 instances per GPUusing Transformer_type: vit_base_in as a backbone

using stride: [16, 16], and patch number is num_y16 * num_x8
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
===========building transformer===========
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-17 19:06:21,008 transreid.train INFO: start training
using WRT loss for training
Fine-tune optimizer: backbone LR 1.000e-04, head multiplier 5.00, 10 parameter groups adjusted
2026-09-17 19:06:21,027 transreid.train INFO: start training
2026-09-17 19:06:22,171 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth (173 tensors)
2026-09-17 19:06:22,183 transreid.train INFO: Loaded E2 warm-start model from /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_model.pth (173 tensors)
2026-09-17 19:06:29,432 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth
2026-09-17 19:06:29,432 transreid.train INFO: Loaded E2 global prototype bank from /kaggle/input/notebooks/thienbao1604/pvuad-lagper-s3clip-e2-60-e3-25-last-onl6ec07fd7f2/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e2_final/pvuad_last_checkpoint.pth
2026-09-17 19:06:29,730 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
2026-09-17 19:06:29,735 transreid.train INFO: Kaggle session guard: started 1789671981, hard deadline 1789704274, safe checkpoint stop 1789703374
2026-09-17 19:06:29,767 transreid.train INFO: Loaded frozen E2 teacher from /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/e2_teacher_model_fp16.pth (173 tensors)
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
2026-09-17 19:06:41,321 transreid.train INFO: Epoch[1] Iteration[50/2281] Loss 0.906 Acc 0.973 ID 0.391 TRI 0.014 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:06:41,322 transreid.train INFO: Epoch[1] Iteration[50/2281] Loss 0.867 Acc 0.983 ID 0.365 TRI 0.012 Align 0.045 GPD 0.007 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:06:49,529 transreid.train INFO: Epoch[1] Iteration[100/2281] Loss 0.938 Acc 0.976 ID 0.403 TRI 0.019 Align 0.047 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:06:49,530 transreid.train INFO: Epoch[1] Iteration[100/2281] Loss 0.885 Acc 0.980 ID 0.379 TRI 0.013 Align 0.045 GPD 0.007 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:06:57,859 transreid.train INFO: Epoch[1] Iteration[150/2281] Loss 0.928 Acc 0.977 ID 0.397 TRI 0.017 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:06:57,859 transreid.train INFO: Epoch[1] Iteration[150/2281] Loss 0.884 Acc 0.983 ID 0.377 TRI 0.014 Align 0.045 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:06,054 transreid.train INFO: Epoch[1] Iteration[200/2281] Loss 0.921 Acc 0.979 ID 0.392 TRI 0.016 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:06,055 transreid.train INFO: Epoch[1] Iteration[200/2281] Loss 0.886 Acc 0.981 ID 0.379 TRI 0.014 Align 0.046 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:14,421 transreid.train INFO: Epoch[1] Iteration[250/2281] Loss 0.916 Acc 0.981 ID 0.388 TRI 0.016 Align 0.047 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:14,421 transreid.train INFO: Epoch[1] Iteration[250/2281] Loss 0.882 Acc 0.983 ID 0.375 TRI 0.014 Align 0.046 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:22,846 transreid.train INFO: Epoch[1] Iteration[300/2281] Loss 0.917 Acc 0.980 ID 0.391 TRI 0.015 Align 0.046 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:22,849 transreid.train INFO: Epoch[1] Iteration[300/2281] Loss 0.880 Acc 0.982 ID 0.375 TRI 0.014 Align 0.046 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:31,286 transreid.train INFO: Epoch[1] Iteration[350/2281] Loss 0.920 Acc 0.980 ID 0.393 TRI 0.015 Align 0.047 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:31,287 transreid.train INFO: Epoch[1] Iteration[350/2281] Loss 0.877 Acc 0.982 ID 0.373 TRI 0.014 Align 0.046 GPD 0.008 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:39,790 transreid.train INFO: Epoch[1] Iteration[400/2281] Loss 0.896 Acc 0.982 ID 0.383 TRI 0.015 Align 0.046 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:39,790 transreid.train INFO: Epoch[1] Iteration[400/2281] Loss 0.923 Acc 0.978 ID 0.395 TRI 0.014 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:48,311 transreid.train INFO: Epoch[1] Iteration[450/2281] Loss 0.909 Acc 0.982 ID 0.389 TRI 0.015 Align 0.046 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:48,311 transreid.train INFO: Epoch[1] Iteration[450/2281] Loss 0.917 Acc 0.979 ID 0.392 TRI 0.014 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:56,926 transreid.train INFO: Epoch[1] Iteration[500/2281] Loss 0.916 Acc 0.979 ID 0.391 TRI 0.014 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:07:56,926 transreid.train INFO: Epoch[1] Iteration[500/2281] Loss 0.910 Acc 0.982 ID 0.389 TRI 0.015 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:05,553 transreid.train INFO: Epoch[1] Iteration[550/2281] Loss 0.910 Acc 0.979 ID 0.388 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:05,554 transreid.train INFO: Epoch[1] Iteration[550/2281] Loss 0.912 Acc 0.982 ID 0.390 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:14,218 transreid.train INFO: Epoch[1] Iteration[600/2281] Loss 0.913 Acc 0.979 ID 0.389 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:14,218 transreid.train INFO: Epoch[1] Iteration[600/2281] Loss 0.910 Acc 0.982 ID 0.389 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:22,954 transreid.train INFO: Epoch[1] Iteration[650/2281] Loss 0.916 Acc 0.979 ID 0.391 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:22,954 transreid.train INFO: Epoch[1] Iteration[650/2281] Loss 0.911 Acc 0.982 ID 0.389 TRI 0.015 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:31,682 transreid.train INFO: Epoch[1] Iteration[700/2281] Loss 0.918 Acc 0.979 ID 0.393 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:31,683 transreid.train INFO: Epoch[1] Iteration[700/2281] Loss 0.907 Acc 0.982 ID 0.387 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:40,249 transreid.train INFO: Epoch[1] Iteration[750/2281] Loss 0.919 Acc 0.978 ID 0.394 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:40,249 transreid.train INFO: Epoch[1] Iteration[750/2281] Loss 0.900 Acc 0.982 ID 0.383 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.020 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:48,813 transreid.train INFO: Epoch[1] Iteration[800/2281] Loss 0.918 Acc 0.979 ID 0.393 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:48,813 transreid.train INFO: Epoch[1] Iteration[800/2281] Loss 0.903 Acc 0.982 ID 0.385 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:57,336 transreid.train INFO: Epoch[1] Iteration[850/2281] Loss 0.908 Acc 0.982 ID 0.388 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:08:57,336 transreid.train INFO: Epoch[1] Iteration[850/2281] Loss 0.919 Acc 0.979 ID 0.393 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:05,825 transreid.train INFO: Epoch[1] Iteration[900/2281] Loss 0.907 Acc 0.982 ID 0.388 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:05,826 transreid.train INFO: Epoch[1] Iteration[900/2281] Loss 0.916 Acc 0.979 ID 0.391 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:14,354 transreid.train INFO: Epoch[1] Iteration[950/2281] Loss 0.912 Acc 0.979 ID 0.390 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:14,356 transreid.train INFO: Epoch[1] Iteration[950/2281] Loss 0.909 Acc 0.982 ID 0.388 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:22,935 transreid.train INFO: Epoch[1] Iteration[1000/2281] Loss 0.911 Acc 0.982 ID 0.389 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:22,935 transreid.train INFO: Epoch[1] Iteration[1000/2281] Loss 0.910 Acc 0.980 ID 0.388 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:31,528 transreid.train INFO: Epoch[1] Iteration[1050/2281] Loss 0.913 Acc 0.982 ID 0.390 TRI 0.015 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:31,528 transreid.train INFO: Epoch[1] Iteration[1050/2281] Loss 0.908 Acc 0.980 ID 0.388 TRI 0.013 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:40,107 transreid.train INFO: Epoch[1] Iteration[1100/2281] Loss 0.913 Acc 0.982 ID 0.390 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:40,107 transreid.train INFO: Epoch[1] Iteration[1100/2281] Loss 0.906 Acc 0.979 ID 0.387 TRI 0.013 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:48,750 transreid.train INFO: Epoch[1] Iteration[1150/2281] Loss 0.910 Acc 0.979 ID 0.389 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:48,750 transreid.train INFO: Epoch[1] Iteration[1150/2281] Loss 0.912 Acc 0.982 ID 0.389 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:57,357 transreid.train INFO: Epoch[1] Iteration[1200/2281] Loss 0.918 Acc 0.979 ID 0.393 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:09:57,358 transreid.train INFO: Epoch[1] Iteration[1200/2281] Loss 0.913 Acc 0.982 ID 0.390 TRI 0.014 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:05,937 transreid.train INFO: Epoch[1] Iteration[1250/2281] Loss 0.910 Acc 0.982 ID 0.389 TRI 0.014 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:05,937 transreid.train INFO: Epoch[1] Iteration[1250/2281] Loss 0.915 Acc 0.979 ID 0.392 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:14,500 transreid.train INFO: Epoch[1] Iteration[1300/2281] Loss 0.912 Acc 0.979 ID 0.391 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:14,500 transreid.train INFO: Epoch[1] Iteration[1300/2281] Loss 0.916 Acc 0.981 ID 0.392 TRI 0.015 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:23,112 transreid.train INFO: Epoch[1] Iteration[1350/2281] Loss 0.907 Acc 0.979 ID 0.388 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:23,112 transreid.train INFO: Epoch[1] Iteration[1350/2281] Loss 0.915 Acc 0.981 ID 0.392 TRI 0.014 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:31,665 transreid.train INFO: Epoch[1] Iteration[1400/2281] Loss 0.914 Acc 0.981 ID 0.391 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:31,665 transreid.train INFO: Epoch[1] Iteration[1400/2281] Loss 0.907 Acc 0.979 ID 0.388 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:40,209 transreid.train INFO: Epoch[1] Iteration[1450/2281] Loss 0.914 Acc 0.981 ID 0.391 TRI 0.014 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:40,209 transreid.train INFO: Epoch[1] Iteration[1450/2281] Loss 0.909 Acc 0.979 ID 0.389 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:48,724 transreid.train INFO: Epoch[1] Iteration[1500/2281] Loss 0.911 Acc 0.979 ID 0.390 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:48,724 transreid.train INFO: Epoch[1] Iteration[1500/2281] Loss 0.913 Acc 0.981 ID 0.391 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:57,281 transreid.train INFO: Epoch[1] Iteration[1550/2281] Loss 0.910 Acc 0.979 ID 0.389 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:10:57,281 transreid.train INFO: Epoch[1] Iteration[1550/2281] Loss 0.914 Acc 0.981 ID 0.391 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:05,811 transreid.train INFO: Epoch[1] Iteration[1600/2281] Loss 0.911 Acc 0.979 ID 0.390 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:05,811 transreid.train INFO: Epoch[1] Iteration[1600/2281] Loss 0.916 Acc 0.981 ID 0.392 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:14,414 transreid.train INFO: Epoch[1] Iteration[1650/2281] Loss 0.912 Acc 0.979 ID 0.390 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:14,414 transreid.train INFO: Epoch[1] Iteration[1650/2281] Loss 0.917 Acc 0.981 ID 0.393 TRI 0.015 Align 0.047 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:22,951 transreid.train INFO: Epoch[1] Iteration[1700/2281] Loss 0.912 Acc 0.979 ID 0.390 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:22,951 transreid.train INFO: Epoch[1] Iteration[1700/2281] Loss 0.916 Acc 0.981 ID 0.392 TRI 0.015 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:31,480 transreid.train INFO: Epoch[1] Iteration[1750/2281] Loss 0.914 Acc 0.979 ID 0.391 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:31,480 transreid.train INFO: Epoch[1] Iteration[1750/2281] Loss 0.918 Acc 0.980 ID 0.394 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:39,977 transreid.train INFO: Epoch[1] Iteration[1800/2281] Loss 0.917 Acc 0.981 ID 0.393 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:39,977 transreid.train INFO: Epoch[1] Iteration[1800/2281] Loss 0.914 Acc 0.979 ID 0.391 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:48,477 transreid.train INFO: Epoch[1] Iteration[1850/2281] Loss 0.915 Acc 0.979 ID 0.392 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:48,477 transreid.train INFO: Epoch[1] Iteration[1850/2281] Loss 0.916 Acc 0.981 ID 0.393 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:56,955 transreid.train INFO: Epoch[1] Iteration[1900/2281] Loss 0.916 Acc 0.981 ID 0.392 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:11:56,955 transreid.train INFO: Epoch[1] Iteration[1900/2281] Loss 0.915 Acc 0.979 ID 0.392 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:12:05,450 transreid.train INFO: Epoch[1] Iteration[1950/2281] Loss 0.915 Acc 0.981 ID 0.392 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:12:05,450 transreid.train INFO: Epoch[1] Iteration[1950/2281] Loss 0.916 Acc 0.979 ID 0.393 TRI 0.015 Align 0.047 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:12:13,919 transreid.train INFO: Epoch[1] Iteration[2000/2281] Loss 0.913 Acc 0.981 ID 0.391 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05
2026-09-17 19:12:13,919 transreid.train INFO: Epoch[1] Iteration[2000/2281] Loss 0.916 Acc 0.979 ID 0.392 TRI 0.015 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.000 LR 9.96e-05

/usr/local/lib/python3.12/dist-packages/torch/distributed/c10d_logger.py:83: UserWarning: barrier(): using the device under current context. You can specify `device_id` in `init_process_group` to mute this warning.
  return func(*args, **kwargs)

2026-09-17 19:36:31,992 transreid.train INFO: Epoch[5] Iteration[1350/2281] Loss 0.869 Acc 0.982 ID 0.369 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:36:31,992 transreid.train INFO: Epoch[5] Iteration[1350/2281] Loss 0.860 Acc 0.984 ID 0.364 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:36:40,566 transreid.train INFO: Epoch[5] Iteration[1400/2281] Loss 0.859 Acc 0.984 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:36:40,566 transreid.train INFO: Epoch[5] Iteration[1400/2281] Loss 0.869 Acc 0.982 ID 0.369 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:36:49,200 transreid.train INFO: Epoch[5] Iteration[1450/2281] Loss 0.872 Acc 0.981 ID 0.370 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:36:49,200 transreid.train INFO: Epoch[5] Iteration[1450/2281] Loss 0.856 Acc 0.984 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:36:57,861 transreid.train INFO: Epoch[5] Iteration[1500/2281] Loss 0.878 Acc 0.981 ID 0.373 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:36:57,861 transreid.train INFO: Epoch[5] Iteration[1500/2281] Loss 0.858 Acc 0.984 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:06,450 transreid.train INFO: Epoch[5] Iteration[1550/2281] Loss 0.877 Acc 0.981 ID 0.372 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:06,451 transreid.train INFO: Epoch[5] Iteration[1550/2281] Loss 0.855 Acc 0.984 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:15,026 transreid.train INFO: Epoch[5] Iteration[1600/2281] Loss 0.878 Acc 0.981 ID 0.373 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:15,026 transreid.train INFO: Epoch[5] Iteration[1600/2281] Loss 0.854 Acc 0.984 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:23,602 transreid.train INFO: Epoch[5] Iteration[1650/2281] Loss 0.878 Acc 0.981 ID 0.373 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:23,602 transreid.train INFO: Epoch[5] Iteration[1650/2281] Loss 0.853 Acc 0.984 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:32,159 transreid.train INFO: Epoch[5] Iteration[1700/2281] Loss 0.877 Acc 0.981 ID 0.373 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:32,159 transreid.train INFO: Epoch[5] Iteration[1700/2281] Loss 0.857 Acc 0.984 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:40,695 transreid.train INFO: Epoch[5] Iteration[1750/2281] Loss 0.855 Acc 0.984 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:40,695 transreid.train INFO: Epoch[5] Iteration[1750/2281] Loss 0.877 Acc 0.981 ID 0.373 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:49,253 transreid.train INFO: Epoch[5] Iteration[1800/2281] Loss 0.857 Acc 0.984 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:37:49,253 transreid.train INFO: Epoch[5] Iteration[1800/2281] Loss 0.876 Acc 0.982 ID 0.372 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:57,821 transreid.train INFO: Epoch[5] Iteration[1850/2281] Loss 0.876 Acc 0.982 ID 0.372 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:37:57,821 transreid.train INFO: Epoch[5] Iteration[1850/2281] Loss 0.856 Acc 0.984 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:06,391 transreid.train INFO: Epoch[5] Iteration[1900/2281] Loss 0.875 Acc 0.981 ID 0.371 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:06,392 transreid.train INFO: Epoch[5] Iteration[1900/2281] Loss 0.857 Acc 0.984 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:14,979 transreid.train INFO: Epoch[5] Iteration[1950/2281] Loss 0.874 Acc 0.982 ID 0.371 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:14,979 transreid.train INFO: Epoch[5] Iteration[1950/2281] Loss 0.854 Acc 0.984 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:23,562 transreid.train INFO: Epoch[5] Iteration[2000/2281] Loss 0.871 Acc 0.982 ID 0.369 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:23,562 transreid.train INFO: Epoch[5] Iteration[2000/2281] Loss 0.853 Acc 0.984 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:32,168 transreid.train INFO: Epoch[5] Iteration[2050/2281] Loss 0.853 Acc 0.984 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:32,168 transreid.train INFO: Epoch[5] Iteration[2050/2281] Loss 0.873 Acc 0.982 ID 0.371 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:40,731 transreid.train INFO: Epoch[5] Iteration[2100/2281] Loss 0.873 Acc 0.982 ID 0.371 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:40,731 transreid.train INFO: Epoch[5] Iteration[2100/2281] Loss 0.856 Acc 0.984 ID 0.362 TRI 0.015 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:49,295 transreid.train INFO: Epoch[5] Iteration[2150/2281] Loss 0.855 Acc 0.984 ID 0.361 TRI 0.015 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:49,295 transreid.train INFO: Epoch[5] Iteration[2150/2281] Loss 0.872 Acc 0.982 ID 0.370 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:38:57,849 transreid.train INFO: Epoch[5] Iteration[2200/2281] Loss 0.858 Acc 0.983 ID 0.363 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:38:57,849 transreid.train INFO: Epoch[5] Iteration[2200/2281] Loss 0.870 Acc 0.982 ID 0.369 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:39:06,431 transreid.train INFO: Epoch[5] Iteration[2250/2281] Loss 0.870 Acc 0.982 ID 0.369 TRI 0.014 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 9.05e-05
2026-09-17 19:39:06,431 transreid.train INFO: Epoch[5] Iteration[2250/2281] Loss 0.859 Acc 0.983 ID 0.364 TRI 0.015 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 9.05e-05
2026-09-17 19:39:11,834 transreid.train INFO: Epoch 5 done in 397.6s; loss 0.8705; acc 0.9817
2026-09-17 19:39:26,335 transreid.train INFO: Epoch[6] Iteration[50/2281] Loss 0.833 Acc 0.985 ID 0.352 TRI 0.011 Align 0.047 GPD 0.016 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 8.65e-05
2026-09-17 19:39:26,335 transreid.train INFO: Epoch[6] Iteration[50/2281] Loss 0.917 Acc 0.973 ID 0.396 TRI 0.012 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.023 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:39:34,996 transreid.train INFO: Epoch[6] Iteration[100/2281] Loss 0.833 Acc 0.986 ID 0.347 TRI 0.012 Align 0.046 GPD 0.023 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:39:34,996 transreid.train INFO: Epoch[6] Iteration[100/2281] Loss 0.861 Acc 0.980 ID 0.367 TRI 0.012 Align 0.046 GPD 0.009 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.005 LR 8.65e-05
2026-09-17 19:39:43,717 transreid.train INFO: Epoch[6] Iteration[150/2281] Loss 0.841 Acc 0.984 ID 0.352 TRI 0.012 Align 0.046 GPD 0.020 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:39:43,717 transreid.train INFO: Epoch[6] Iteration[150/2281] Loss 0.861 Acc 0.979 ID 0.363 TRI 0.012 Align 0.047 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:39:52,389 transreid.train INFO: Epoch[6] Iteration[200/2281] Loss 0.864 Acc 0.979 ID 0.365 TRI 0.012 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:39:52,389 transreid.train INFO: Epoch[6] Iteration[200/2281] Loss 0.810 Acc 0.984 ID 0.338 TRI 0.011 Align 0.046 GPD 0.017 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:00,963 transreid.train INFO: Epoch[6] Iteration[250/2281] Loss 0.835 Acc 0.982 ID 0.349 TRI 0.012 Align 0.046 GPD 0.017 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:00,963 transreid.train INFO: Epoch[6] Iteration[250/2281] Loss 0.855 Acc 0.979 ID 0.362 TRI 0.012 Align 0.047 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:09,523 transreid.train INFO: Epoch[6] Iteration[300/2281] Loss 0.854 Acc 0.980 ID 0.361 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:09,523 transreid.train INFO: Epoch[6] Iteration[300/2281] Loss 0.837 Acc 0.983 ID 0.349 TRI 0.014 Align 0.046 GPD 0.017 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:18,074 transreid.train INFO: Epoch[6] Iteration[350/2281] Loss 0.839 Acc 0.983 ID 0.350 TRI 0.014 Align 0.046 GPD 0.016 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:18,074 transreid.train INFO: Epoch[6] Iteration[350/2281] Loss 0.854 Acc 0.981 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.005 LR 8.65e-05
2026-09-17 19:40:26,636 transreid.train INFO: Epoch[6] Iteration[400/2281] Loss 0.860 Acc 0.981 ID 0.365 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:26,637 transreid.train INFO: Epoch[6] Iteration[400/2281] Loss 0.838 Acc 0.984 ID 0.352 TRI 0.014 Align 0.046 GPD 0.015 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:35,169 transreid.train INFO: Epoch[6] Iteration[450/2281] Loss 0.866 Acc 0.981 ID 0.368 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:35,169 transreid.train INFO: Epoch[6] Iteration[450/2281] Loss 0.832 Acc 0.984 ID 0.348 TRI 0.014 Align 0.046 GPD 0.015 TIR-G 0.000 TIR-L 0.000 Keep 0.021 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:43,706 transreid.train INFO: Epoch[6] Iteration[500/2281] Loss 0.842 Acc 0.984 ID 0.353 TRI 0.014 Align 0.046 GPD 0.014 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:43,706 transreid.train INFO: Epoch[6] Iteration[500/2281] Loss 0.865 Acc 0.981 ID 0.368 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:52,283 transreid.train INFO: Epoch[6] Iteration[550/2281] Loss 0.850 Acc 0.984 ID 0.358 TRI 0.014 Align 0.046 GPD 0.015 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:40:52,284 transreid.train INFO: Epoch[6] Iteration[550/2281] Loss 0.866 Acc 0.981 ID 0.368 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:00,863 transreid.train INFO: Epoch[6] Iteration[600/2281] Loss 0.847 Acc 0.983 ID 0.357 TRI 0.014 Align 0.046 GPD 0.015 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:00,863 transreid.train INFO: Epoch[6] Iteration[600/2281] Loss 0.865 Acc 0.981 ID 0.368 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:09,438 transreid.train INFO: Epoch[6] Iteration[650/2281] Loss 0.864 Acc 0.981 ID 0.367 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:09,439 transreid.train INFO: Epoch[6] Iteration[650/2281] Loss 0.844 Acc 0.984 ID 0.356 TRI 0.014 Align 0.046 GPD 0.014 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:18,005 transreid.train INFO: Epoch[6] Iteration[700/2281] Loss 0.845 Acc 0.984 ID 0.357 TRI 0.014 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:18,005 transreid.train INFO: Epoch[6] Iteration[700/2281] Loss 0.861 Acc 0.982 ID 0.366 TRI 0.014 Align 0.046 GPD 0.010 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:26,597 transreid.train INFO: Epoch[6] Iteration[750/2281] Loss 0.861 Acc 0.982 ID 0.366 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:26,598 transreid.train INFO: Epoch[6] Iteration[750/2281] Loss 0.852 Acc 0.983 ID 0.360 TRI 0.014 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:35,173 transreid.train INFO: Epoch[6] Iteration[800/2281] Loss 0.857 Acc 0.982 ID 0.364 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:35,173 transreid.train INFO: Epoch[6] Iteration[800/2281] Loss 0.851 Acc 0.984 ID 0.359 TRI 0.014 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:43,766 transreid.train INFO: Epoch[6] Iteration[850/2281] Loss 0.856 Acc 0.983 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:43,766 transreid.train INFO: Epoch[6] Iteration[850/2281] Loss 0.847 Acc 0.984 ID 0.357 TRI 0.014 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:52,345 transreid.train INFO: Epoch[6] Iteration[900/2281] Loss 0.845 Acc 0.984 ID 0.356 TRI 0.014 Align 0.046 GPD 0.013 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:41:52,345 transreid.train INFO: Epoch[6] Iteration[900/2281] Loss 0.860 Acc 0.982 ID 0.365 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:00,939 transreid.train INFO: Epoch[6] Iteration[950/2281] Loss 0.849 Acc 0.984 ID 0.359 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:00,940 transreid.train INFO: Epoch[6] Iteration[950/2281] Loss 0.857 Acc 0.983 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:09,562 transreid.train INFO: Epoch[6] Iteration[1000/2281] Loss 0.853 Acc 0.983 ID 0.361 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:09,562 transreid.train INFO: Epoch[6] Iteration[1000/2281] Loss 0.854 Acc 0.983 ID 0.362 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:18,196 transreid.train INFO: Epoch[6] Iteration[1050/2281] Loss 0.850 Acc 0.983 ID 0.359 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:18,196 transreid.train INFO: Epoch[6] Iteration[1050/2281] Loss 0.850 Acc 0.983 ID 0.360 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:26,810 transreid.train INFO: Epoch[6] Iteration[1100/2281] Loss 0.844 Acc 0.983 ID 0.356 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:26,810 transreid.train INFO: Epoch[6] Iteration[1100/2281] Loss 0.854 Acc 0.983 ID 0.362 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:35,389 transreid.train INFO: Epoch[6] Iteration[1150/2281] Loss 0.845 Acc 0.983 ID 0.356 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:35,389 transreid.train INFO: Epoch[6] Iteration[1150/2281] Loss 0.851 Acc 0.983 ID 0.360 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:43,971 transreid.train INFO: Epoch[6] Iteration[1200/2281] Loss 0.846 Acc 0.983 ID 0.357 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:43,971 transreid.train INFO: Epoch[6] Iteration[1200/2281] Loss 0.851 Acc 0.983 ID 0.360 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:52,572 transreid.train INFO: Epoch[6] Iteration[1250/2281] Loss 0.846 Acc 0.983 ID 0.357 TRI 0.014 Align 0.046 GPD 0.012 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:42:52,572 transreid.train INFO: Epoch[6] Iteration[1250/2281] Loss 0.851 Acc 0.983 ID 0.360 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:01,125 transreid.train INFO: Epoch[6] Iteration[1300/2281] Loss 0.852 Acc 0.983 ID 0.361 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:01,126 transreid.train INFO: Epoch[6] Iteration[1300/2281] Loss 0.847 Acc 0.983 ID 0.358 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:09,704 transreid.train INFO: Epoch[6] Iteration[1350/2281] Loss 0.844 Acc 0.983 ID 0.356 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:09,704 transreid.train INFO: Epoch[6] Iteration[1350/2281] Loss 0.856 Acc 0.983 ID 0.363 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:18,305 transreid.train INFO: Epoch[6] Iteration[1400/2281] Loss 0.842 Acc 0.983 ID 0.355 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:18,305 transreid.train INFO: Epoch[6] Iteration[1400/2281] Loss 0.855 Acc 0.983 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:26,880 transreid.train INFO: Epoch[6] Iteration[1450/2281] Loss 0.844 Acc 0.983 ID 0.356 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:26,880 transreid.train INFO: Epoch[6] Iteration[1450/2281] Loss 0.854 Acc 0.983 ID 0.362 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:35,419 transreid.train INFO: Epoch[6] Iteration[1500/2281] Loss 0.846 Acc 0.983 ID 0.357 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:35,419 transreid.train INFO: Epoch[6] Iteration[1500/2281] Loss 0.853 Acc 0.983 ID 0.362 TRI 0.013 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:43,978 transreid.train INFO: Epoch[6] Iteration[1550/2281] Loss 0.845 Acc 0.982 ID 0.357 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05
2026-09-17 19:43:43,978 transreid.train INFO: Epoch[6] Iteration[1550/2281] Loss 0.856 Acc 0.983 ID 0.363 TRI 0.014 Align 0.046 GPD 0.011 TIR-G 0.000 TIR-L 0.000 Keep 0.022 S-Hard 0.006 LR 8.65e-05

,stage,status,reason,epoch,next_iteration,epoch_complete,global_step,best_mAP,remaining_minutes
0,E3-TDH (LAGPeR RGB adaptation),completed,training_completed,25,0,True,57025,27.169722,370.5

Running LAGPeR-S3CLIP A2G with E3 LAST model + flip-TTA
  /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth
2026-09-17 21:54:09,055 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'False', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'LAGPeR', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_lagper_data', 'DATALOADER.NUM_WORKERS', '4', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'TEST.WEIGHT', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '13', 'PVUAD.VFPROCA', 'True', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.0', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.FINAL_FLIP_TTA', 'True', 'PVUAD.TTA_METRICS_FILENAME', 'tta_A2G_last_metrics.csv'])
2026-09-17 21:54:09,055 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-17 21:54:09,056 transreid INFO:
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'wrt'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_in'
  STRIDE_SIZE: [16, 16]
  PCA_LOSS_WEIGHT: 0.01
  GPD_MOMENTUM: 0.2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: 'AG-ReID.v2'
  ROOT_DIR: '/kaggle/working/pvuad_agreid_data'
  MODALITIES: ['RGB']

DATALOADER:
  SAMPLER: 'PKM'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  LOSS_TYPE: "base+pca+gpd"

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TOP_K_EVAL: 0

PVUAD:
  EXPERIMENT: 'E0'
  STAGE: 'final'
  DEV_MODE: False
  DEV_VAL_IDS: 100
  DEV_SPLIT_SEED: 2026
  DEV_QUERY_PER_PID_CAM: 1
  PAIRED_VIEW_SAMPLER: False
  SYNC_PAIRED_AUG: False
  GROUND_MAX_CAMID: 1
  STRICT_PAIRED_DATA: True
  VFPROCA: False
  VIEW_ALIGNMENT_WEIGHT: 0.5
  INVARIANT_ID_WEIGHT: 0.5
  SCENARIO_CLS_WEIGHT: 0.1
  TEST_INVARIANT_BLEND: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  HARD_GPD: False
  HARD_GPD_WEIGHT: 0.5
  HARD_GPD_TOPK: 10
  HARD_GPD_MARGIN: 0.10
  HARD_GPD_START_EPOCH: 10
  FINETUNE: False
  WARMSTART_MODEL_PATH: ''
  WARMSTART_PROTOTYPE_PATH: ''
  TEACHER_MODEL_PATH: ''
  HEAD_LR_MULTIPLIER: 1.0
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.10
  TIR_LOCAL_WEIGHT: 0.03
  TIR_LOCAL_KEEP_RATIO: 0.50
  FEATURE_PRESERVE_WEIGHT: 0.05
  SCENARIO_HARD_GPD: False
  SCENARIO_HARD_WEIGHT: 0.15
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_BANK_MOMENTUM: 0.20
  FINAL_FLIP_TTA: False
  TTA_METRICS_FILENAME: 'tta_metrics.csv'
  RESUME_PATH: ''
  SAVE_LAST_EVERY: 5
  SAVE_BEST: True
  METRICS_FILENAME: 'metrics_history.csv'
  RUN_MANIFEST: ''
  SESSION_DEADLINE_UNIX: 0.0
  STOP_RESERVE_MINUTES: 10.0
  CHECKPOINT_EVERY_MINUTES: 30.0
  TIME_CHECK_EVERY_STEPS: 10
  MIN_EVAL_REMAINING_MINUTES: 35.0
  STATUS_FILENAME: 'session_status.json'
  STRICT_RESUME_CONFIG: True

OUTPUT_DIR: './logs/PVUAD'

2026-09-17 21:54:09,056 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB',)
  NAMES: LAGPeR
  ROOT_DIR: /kaggle/working/pvuad_lagper_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: False
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.0
  FINAL_FLIP_TTA: True
  FINETUNE: False
  GROUND_MAX_CAMID: 13
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 1.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 35.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST:
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 0.0
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 10.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: False
  TEACHER_MODEL_PATH:
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.1
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.03
  TTA_METRICS_FILENAME: tta_A2G_last_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH:
  WARMSTART_PROTOTYPE_PATH:
SOLVER:
  BASE_LR: 0.008
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth
=> LAGPeR loaded (A2G)
   train       : /kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_train
   query       : /kaggle/working/pvuad_lagper_data/LAGPeR/query_aerial
   gallery dirs: ['/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_test_ground', '/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_gallery']
   gallery noise: 134
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |  2708 |    40770 |        12
  query    |  1523 |     3046 |         3
  gallery  |  1524 |    15533 |        12
  ----------------------------------------
ViewBalancedPKM: 2708 IDs (2708 dual-view, 0 single-view), 54,756 sample slots/epoch, 16 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
Loading pretrained model from /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth (loaded=170, skipped=3)
2026-09-17 21:55:19,555 transreid.test INFO: Enter inferencing
2026-09-17 21:57:53,889 transreid.test INFO: => Split mode 1: query 3046, total query 3046
2026-09-17 21:57:53,912 transreid.test INFO: The test feature is normalized
2026-09-17 21:57:53,938 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-17 21:57:57,943 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1)], Gallery mods: [np.int64(1)]
2026-09-17 21:58:01,964 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 27.64%, Rank-1: 38.21%
2026-09-17 21:58:02,034 transreid.test INFO: Validation Results
2026-09-17 21:58:02,035 transreid.test INFO: mAP: 27.64%
2026-09-17 21:58:02,035 transreid.test INFO: CMC curve, Rank-1  :38.21%
2026-09-17 21:58:02,035 transreid.test INFO: CMC curve, Rank-5  :52.86%
2026-09-17 21:58:02,035 transreid.test INFO: CMC curve, Rank-10 :60.83%
2026-09-17 21:58:02,035 transreid.test INFO: Running horizontal-flip feature averaging
2026-09-17 22:03:08,325 transreid.test INFO: => Split mode 1: query 3046, total query 3046
2026-09-17 22:03:08,348 transreid.test INFO: The test feature is normalized
2026-09-17 22:03:08,375 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-17 22:03:12,438 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1)], Gallery mods: [np.int64(1)]
2026-09-17 22:03:16,420 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 27.71%, Rank-1: 38.08%
2026-09-17 22:03:16,494 transreid.test INFO: Flip-TTA mAP: 27.71%
2026-09-17 22:03:16,494 transreid.test INFO: Flip-TTA CMC, Rank-1  :38.08%
2026-09-17 22:03:16,494 transreid.test INFO: Flip-TTA CMC, Rank-5  :52.95%
2026-09-17 22:03:16,494 transreid.test INFO: Flip-TTA CMC, Rank-10 :61.10%
Running LAGPeR-S3CLIP G2A with E3 LAST model + flip-TTA
  /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth
2026-09-17 22:03:22,391 transreid INFO: Namespace(config_file='configs/PVUAD.yml', opts=['MODEL.DIST_TRAIN', 'False', 'MODEL.PRETRAIN_CHOICE', 'none', 'MODEL.PRETRAIN_PATH', '/kaggle/working/vit_transreid_msmt.pth', 'MODEL.STRIDE_SIZE', '[16, 16]', 'MODEL.SIE_CAMERA', 'False', 'MODEL.SIE_VIEW', 'False', 'DATASETS.NAMES', 'LAGPeR', 'DATASETS.MODALITIES', "['RGB']", 'DATASETS.ROOT_DIR', '/kaggle/working/pvuad_lagper_data', 'DATALOADER.NUM_WORKERS', '4', 'TEST.IMS_PER_BATCH', '256', 'TEST.RE_RANKING', 'False', 'TEST.TOP_K_EVAL', '0', 'TEST.WEIGHT', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth', 'OUTPUT_DIR', '/kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh', 'PVUAD.EXPERIMENT', 'E3-TDH', 'PVUAD.STAGE', 'final', 'PVUAD.DEV_MODE', 'False', 'PVUAD.PAIRED_VIEW_SAMPLER', 'True', 'PVUAD.STRICT_PAIRED_DATA', 'False', 'PVUAD.GROUND_MAX_CAMID', '13', 'PVUAD.VFPROCA', 'True', 'PVUAD.TEST_INVARIANT_BLEND', '0.5', 'PVUAD.TIR_DISTILLATION', 'False', 'PVUAD.FEATURE_PRESERVE_WEIGHT', '0.0', 'PVUAD.SCENARIO_HARD_GPD', 'True', 'PVUAD.FINAL_FLIP_TTA', 'True', 'PVUAD.TTA_METRICS_FILENAME', 'tta_G2A_last_metrics.csv'])
2026-09-17 22:03:22,391 transreid INFO: Loaded configuration file configs/PVUAD.yml
2026-09-17 22:03:22,391 transreid INFO:
MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: 'jx_vit_base_p16_224-80ecf9dd.pth'
  METRIC_LOSS_TYPE: 'wrt'
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('0')
  TRANSFORMER_TYPE: 'vit_base_in'
  STRIDE_SIZE: [16, 16]
  PCA_LOSS_WEIGHT: 0.01
  GPD_MOMENTUM: 0.2

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5
  RE_PROB: 0.5
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]

DATASETS:
  NAMES: 'AG-ReID.v2'
  ROOT_DIR: '/kaggle/working/pvuad_agreid_data'
  MODALITIES: ['RGB']

DATALOADER:
  SAMPLER: 'PKM'
  NUM_INSTANCE: 4
  NUM_WORKERS: 4

SOLVER:
  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.008
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'linear'
  WARMUP_EPOCHS: 5
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2
  LOSS_TYPE: "base+pca+gpd"

TEST:
  EVAL: True
  IMS_PER_BATCH: 256
  RE_RANKING: False
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TOP_K_EVAL: 0

PVUAD:
  EXPERIMENT: 'E0'
  STAGE: 'final'
  DEV_MODE: False
  DEV_VAL_IDS: 100
  DEV_SPLIT_SEED: 2026
  DEV_QUERY_PER_PID_CAM: 1
  PAIRED_VIEW_SAMPLER: False
  SYNC_PAIRED_AUG: False
  GROUND_MAX_CAMID: 1
  STRICT_PAIRED_DATA: True
  VFPROCA: False
  VIEW_ALIGNMENT_WEIGHT: 0.5
  INVARIANT_ID_WEIGHT: 0.5
  SCENARIO_CLS_WEIGHT: 0.1
  TEST_INVARIANT_BLEND: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  HARD_GPD: False
  HARD_GPD_WEIGHT: 0.5
  HARD_GPD_TOPK: 10
  HARD_GPD_MARGIN: 0.10
  HARD_GPD_START_EPOCH: 10
  FINETUNE: False
  WARMSTART_MODEL_PATH: ''
  WARMSTART_PROTOTYPE_PATH: ''
  TEACHER_MODEL_PATH: ''
  HEAD_LR_MULTIPLIER: 1.0
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.10
  TIR_LOCAL_WEIGHT: 0.03
  TIR_LOCAL_KEEP_RATIO: 0.50
  FEATURE_PRESERVE_WEIGHT: 0.05
  SCENARIO_HARD_GPD: False
  SCENARIO_HARD_WEIGHT: 0.15
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_BANK_MOMENTUM: 0.20
  FINAL_FLIP_TTA: False
  TTA_METRICS_FILENAME: 'tta_metrics.csv'
  RESUME_PATH: ''
  SAVE_LAST_EVERY: 5
  SAVE_BEST: True
  METRICS_FILENAME: 'metrics_history.csv'
  RUN_MANIFEST: ''
  SESSION_DEADLINE_UNIX: 0.0
  STOP_RESERVE_MINUTES: 10.0
  CHECKPOINT_EVERY_MINUTES: 30.0
  TIME_CHECK_EVERY_STEPS: 10
  MIN_EVAL_REMAINING_MINUTES: 35.0
  STATUS_FILENAME: 'session_status.json'
  STRICT_RESUME_CONFIG: True

OUTPUT_DIR: './logs/PVUAD'

2026-09-17 22:03:22,392 transreid INFO: Running with config:
DATALOADER:
  NUM_INSTANCE: 4
  NUM_WORKERS: 4
  SAMPLER: PKM
DATASETS:
  MODALITIES: ('RGB',)
  NAMES: LAGPeR
  ROOT_DIR: /kaggle/working/pvuad_lagper_data
INPUT:
  PADDING: 10
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  PROB: 0.5
  RE_PROB: 0.5
  SIZE_TEST: [256, 128]
  SIZE_TRAIN: [256, 128]
MODEL:
  ATT_DROP_RATE: 0.0
  COS_LAYER: False
  DEVICE: cuda
  DEVICE_ID: 0
  DEVIDE_LENGTH: 4
  DIST_TRAIN: False
  DROP_OUT: 0.0
  DROP_PATH: 0.1
  GPD_MOMENTUM: 0.2
  ID_LOSS_TYPE: softmax
  ID_LOSS_WEIGHT: 1.0
  IF_LABELSMOOTH: off
  IF_WITH_CENTER: no
  JPM: False
  LAST_STRIDE: 1
  METRIC_LOSS_TYPE: wrt
  NAME: transformer
  NECK: bnneck
  NO_MARGIN: True
  PCA_LOSS_WEIGHT: 0.01
  PRETRAIN_CHOICE: none
  PRETRAIN_PATH: /kaggle/working/vit_transreid_msmt.pth
  RE_ARRANGE: True
  SHIFT_NUM: 5
  SHUFFLE_GROUP: 2
  SIE_CAMERA: False
  SIE_COE: 3.0
  SIE_VIEW: False
  STRIDE_SIZE: [16, 16]
  TRANSFORMER_TYPE: vit_base_in
  TRIPLET_LOSS_WEIGHT: 1.0
OUTPUT_DIR: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh
PVUAD:
  CHECKPOINT_EVERY_MINUTES: 30.0
  DEV_MODE: False
  DEV_QUERY_PER_PID_CAM: 1
  DEV_SPLIT_SEED: 2026
  DEV_VAL_IDS: 100
  EXPERIMENT: E3-TDH
  FEATURE_PRESERVE_WEIGHT: 0.0
  FINAL_FLIP_TTA: True
  FINETUNE: False
  GROUND_MAX_CAMID: 13
  HARD_GPD: False
  HARD_GPD_MARGIN: 0.1
  HARD_GPD_START_EPOCH: 10
  HARD_GPD_TOPK: 10
  HARD_GPD_WEIGHT: 0.5
  HEAD_LR_MULTIPLIER: 1.0
  INVARIANT_ID_WEIGHT: 0.5
  LOCAL_CONSISTENCY: False
  LOCAL_CONSISTENCY_WEIGHT: 0.05
  METRICS_FILENAME: metrics_history.csv
  MIN_EVAL_REMAINING_MINUTES: 35.0
  PAIRED_VIEW_SAMPLER: True
  RESUME_PATH:
  RUN_MANIFEST:
  SAVE_BEST: True
  SAVE_LAST_EVERY: 5
  SCENARIO_BANK_MOMENTUM: 0.2
  SCENARIO_CLS_WEIGHT: 0.1
  SCENARIO_HARD_GPD: True
  SCENARIO_HARD_MARGIN: 0.05
  SCENARIO_HARD_START_EPOCH: 3
  SCENARIO_HARD_TAU: 0.05
  SCENARIO_HARD_TOPK: 5
  SCENARIO_HARD_WEIGHT: 0.15
  SESSION_DEADLINE_UNIX: 0.0
  STAGE: final
  STATUS_FILENAME: session_status.json
  STOP_RESERVE_MINUTES: 10.0
  STRICT_PAIRED_DATA: False
  STRICT_RESUME_CONFIG: True
  SYNC_PAIRED_AUG: False
  TEACHER_MODEL_PATH:
  TEST_INVARIANT_BLEND: 0.5
  TIME_CHECK_EVERY_STEPS: 10
  TIR_DISTILLATION: False
  TIR_GLOBAL_WEIGHT: 0.1
  TIR_LOCAL_KEEP_RATIO: 0.5
  TIR_LOCAL_WEIGHT: 0.03
  TTA_METRICS_FILENAME: tta_G2A_last_metrics.csv
  VFPROCA: True
  VIEW_ALIGNMENT_WEIGHT: 0.5
  WARMSTART_MODEL_PATH:
  WARMSTART_PROTOTYPE_PATH:
SOLVER:
  BASE_LR: 0.008
  BIAS_LR_FACTOR: 2
  CENTER_LOSS_WEIGHT: 0.0005
  CENTER_LR: 0.5
  CHECKPOINT_PERIOD: 5
  COSINE_MARGIN: 0.5
  COSINE_SCALE: 30
  EVAL_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 64
  LARGE_FC_LR: False
  LOG_PERIOD: 50
  LOSS_TYPE: base+pca+gpd
  MARGIN: 0.3
  MAX_EPOCHS: 120
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  SEED: 1234
  STEPS: (40, 70)
  WARMUP_EPOCHS: 5
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
TEST:
  DIST_MAT: dist_mat.npy
  EVAL: True
  FEAT_NORM: yes
  IMS_PER_BATCH: 256
  NECK_FEAT: before
  RE_RANKING: False
  TOP_K_EVAL: 0
  WEIGHT: /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth
=> LAGPeR loaded (G2A)
   train       : /kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_train
   query       : /kaggle/working/pvuad_lagper_data/LAGPeR/query_ground
   gallery dirs: ['/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_test_aerial', '/kaggle/working/pvuad_lagper_data/LAGPeR/bounding_box_gallery']
   gallery noise: 45
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |  2708 |    40770 |        12
  query    |  1523 |     3046 |         6
  gallery  |  1524 |     7717 |         6
  ----------------------------------------
ViewBalancedPKM: 2708 IDs (2708 dual-view, 0 single-view), 54,756 sample slots/epoch, 16 PID x 4 instances per GPU
using Transformer_type: vit_base_in as a backbone
using stride: [16, 16], and patch number is num_y16 * num_x8
===========building transformer===========
Loading pretrained model from /kaggle/working/pvuad_runs/lagper_s3clip_e2_60_e3_25_transreid768_b24_lastonly_v5_metricsindentfix/e3_tdh/pvuad_last_model.pth (loaded=170, skipped=3)
2026-09-17 22:04:34,529 transreid.test INFO: Enter inferencing
2026-09-17 22:06:05,705 transreid.test INFO: => Split mode 1: query 3046, total query 3046
2026-09-17 22:06:05,721 transreid.test INFO: The test feature is normalized
2026-09-17 22:06:05,737 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)
2026-09-17 22:06:07,712 transreid.test INFO: Starting modality-pair specific evaluation. Query mods: [np.int64(1)], Gallery mods: [np.int64(1)]
2026-09-17 22:06:09,673 transreid.test INFO:   Pair (Q:1, G:1) -> mAP: 30.87%, Rank-1: 31.81%
2026-09-17 22:06:09,739 transreid.test INFO: Validation Results
2026-09-17 22:06:09,740 transreid.test INFO: mAP: 30.87%
2026-09-17 22:06:09,740 transreid.test INFO: CMC curve, Rank-1  :31.81%
2026-09-17 22:06:09,740 transreid.test INFO: CMC curve, Rank-5  :44.68%
2026-09-17 22:06:09,740 transreid.test INFO: CMC curve, Rank-10 :51.74%
2026-09-17 22:06:09,740 transreid.test INFO: Running horizontal-flip feature averaging
2026-09-17 22:09:07,605 transreid.test INFO: => Split mode 1: query 3046, total query 3046
2026-09-17 22:09:07,620 transreid.test INFO: The test feature is normalized
2026-09-17 22:09:07,635 transreid.test INFO: => Computing DistMat in q-chunks (chunk=4000)

## 6. Tổng hợp kết quả paper-ready

Report phân biệt rõ E2/E3 epoch cuối và ba final protocol. Không đọc/không chọn `pvuad_best_model.pth`.

In [7]:
def metrics_history_last(run_dir, label):
    path = Path(run_dir) / "metrics_history.csv"
    if not path.is_file():
        return None
    frame = pd.read_csv(path)
    required = {"experiment", "stage", "epoch", "mAP", "Rank-1", "Rank-5", "Rank-10"}
    if frame.empty or not required.issubset(frame.columns):
        return None
    frame = frame.drop_duplicates(
        subset=["experiment", "stage", "epoch"], keep="last"
    ).sort_values("epoch")
    frame.to_csv(path, index=False)
    row = frame.iloc[-1]
    return {
        "method": label,
        "protocol": "A2G epoch-end diagnostic",
        "epoch": int(row["epoch"]),
        "mAP": float(row["mAP"]),
        "Rank-1": float(row["Rank-1"]),
        "Rank-5": float(row["Rank-5"]),
        "Rank-10": float(row["Rank-10"]),
        "checkpoint_used_for_next_step": "last",
    }

def tta_metrics(protocol):
    path = E3_RUN_DIR / f"tta_{protocol}_last_metrics.csv"
    if not path.is_file():
        return None
    frame = pd.read_csv(path)
    if frame.empty:
        return None
    row = frame.iloc[-1]
    return {
        "method": "E3 LAST + horizontal-flip TTA",
        "protocol": protocol,
        "epoch": E3_EPOCHS,
        "mAP": float(row["mAP"]),
        "Rank-1": float(row["Rank-1"]),
        "Rank-5": float(row["Rank-5"]),
        "Rank-10": float(row["Rank-10"]),
        "checkpoint_used_for_next_step": "final_test",
    }

state = read_json(PIPELINE_STATE_PATH)
print("Pipeline status:", state.get("status"))
print("Active stage   :", state.get("active_stage"))
print("Next action    :", state.get("next_action"))
print("Dataset audit  :")
display(pd.DataFrame([{
    "dataset": DATASET_AUDIT["dataset"],
    "train_ids": DATASET_AUDIT["train_ids"],
    "train_images": DATASET_AUDIT["train_images"],
    "A2G_q/g": f"{DATASET_AUDIT['A2G']['query_images']}/{DATASET_AUDIT['A2G']['gallery_images']}",
    "G2A_q/g": f"{DATASET_AUDIT['G2A']['query_images']}/{DATASET_AUDIT['G2A']['gallery_images']}",
    "G2AG_q/g": f"{DATASET_AUDIT['G2AG']['query_images']}/{DATASET_AUDIT['G2AG']['gallery_images']}",
}]))

init_audit_path = PIPELINE_ROOT / "transreid_trainable_init_audit.json"
if init_audit_path.is_file():
    print("TransReID initialization audit:")
    display(pd.DataFrame([read_json(init_audit_path)]))

comparison = []
e2_last = metrics_history_last(E2_RUN_DIR, f"E2 LAST epoch {E2_EPOCHS}")
e3_last = metrics_history_last(E3_RUN_DIR, f"E3 LAST epoch {E3_EPOCHS} (no TTA)")
if e2_last:
    comparison.append(e2_last)
if e3_last:
    comparison.append(e3_last)

for protocol in FINAL_PROTOCOLS:
    result = tta_metrics(protocol)
    if result:
        comparison.append(result)

comparison_frame = pd.DataFrame(comparison)
comparison_path = PIPELINE_ROOT / "combined_results.csv"
comparison_frame.to_csv(comparison_path, index=False)
if not comparison_frame.empty:
    display(comparison_frame.round(4))

checkpoint_policy = {
    "policy": "last_only",
    "E2_fixed_horizon": E2_EPOCHS,
    "E3_fixed_horizon": E3_EPOCHS,
    "E2_to_E3_weights": "e2_final/pvuad_last_model.pth",
    "E2_to_E3_prototype_bank": "e2_final/pvuad_last_checkpoint.pth:prototype_bank",
    "E3_to_final_tests": "e3_tdh/pvuad_last_model.pth",
    "intermediate_checkpoint_selection": False,
    "E2_eval_period": E2_EPOCHS,
    "E3_eval_period": E3_EPOCHS,
    "final_protocols": list(FINAL_PROTOCOLS),
    "final_flip_tta": bool(RUN_FINAL_FLIP_TTA),
    "reranking": False,
    "lagper_eval_junk_rule": "remove same PID + same camera only",
}
(PIPELINE_ROOT / "final_checkpoint_policy.json").write_text(
    json.dumps(checkpoint_policy, indent=2), encoding="utf-8"
)
print("Checkpoint policy:", checkpoint_policy)

REPORT_ZIP = (
    Path("/kaggle/working")
    / "pvuad_lagper_s3clip_e2_60_e3_25_transreid_reports.zip"
)
if REPORT_ZIP.exists():
    REPORT_ZIP.unlink()

report_suffixes = {".csv", ".json", ".txt", ".log", ".yml", ".yaml"}
with zipfile.ZipFile(
    REPORT_ZIP, "w", compression=zipfile.ZIP_DEFLATED
) as archive:
    for path in sorted(PIPELINE_ROOT.rglob("*")):
        if path.is_file() and path.suffix.lower() in report_suffixes:
            archive.write(path, arcname=str(path.relative_to(PIPELINE_ROOT)))

    extras = [
        Path("/kaggle/working/lagper_s3clip_dataset_audit.json"),
        Path("/kaggle/working/lagper_s3clip_split_audit.csv"),
        Path("/kaggle/working/lagper_exp_txt_preview.json"),
        CAMERA_MAP_PATH,
    ]
    for path in extras:
        if path.is_file():
            archive.write(path, arcname=path.name)

    patch_manifest = UAD_DIR / "PVUAD_patch_manifest.json"
    if patch_manifest.is_file():
        archive.write(patch_manifest, arcname="PVUAD_patch_manifest.json")

print("Report zip:", REPORT_ZIP)

if all(tta_metrics(protocol) is not None for protocol in FINAL_PROTOCOLS):
    final_table = comparison_frame[
        (comparison_frame["method"] == "E3 LAST + horizontal-flip TTA")
    ][["protocol", "mAP", "Rank-1", "Rank-5", "Rank-10"]]
    print("FINAL LAGPeR-S3CLIP:")
    display(final_table.round(4))

Pipeline status: completed
Active stage   : DONE
Next action    : None
Dataset audit  :

         dataset  train_ids  train_images     A2G_q/g    G2A_q/g    G2AG_q/g
0  LAGPeR-S3CLIP       2708         40770  3046/15533  3046/7717  3046/20204

TransReID initialization audit:

,checkpoint,loaded_tensor_count,target_tensor_count,mismatch_count,resized_pos_embed,source_sie_loaded,source_jpm_local_branches_loaded,global_jpm_branch_used_for_target_final_block,global_branch_mapped_tensor_count,embedding_dim,...,batchnorm_train_mode_checked,init_qkv_max_abs,global_final_qkv_max_abs,qkv_grad_norm,patch_grad_norm,backbone_all_trainable,source_sie_used,source_jpm_local_branches_used,source_jpm_global_final_branch_used,target_stride
0,/kaggle/working/vit_transreid_msmt.pth,152,152,0,"{'source_shape': [1, 211, 768], 'target_shape'...",False,False,True,14,768,...,True,0.0,0.0,0.004461,0.022849,True,False,False,True,"[16, 16]"

,method,protocol,epoch,mAP,Rank-1,Rank-5,Rank-10,checkpoint_used_for_next_step
0,E2 LAST epoch 60,A2G epoch-end diagnostic,60,26.9829,37.8858,47.2095,52.7577,last
1,E3 LAST epoch 25 (no TTA),A2G epoch-end diagnostic,25,27.1697,38.2141,47.1766,52.8562,last
2,E3 LAST + horizontal-flip TTA,A2G,25,27.7150,38.0827,52.9547,61.0965,final_test
3,E3 LAST + horizontal-flip TTA,G2A,25,30.8546,31.7137,44.4517,51.8056,final_test
4,E3 LAST + horizontal-flip TTA,G2AG,25,18.0829,21.8976,33.4865,41.0046,final_test

Checkpoint policy: {'policy': 'last_only', 'E2_fixed_horizon': 60, 'E3_fixed_horizon': 25, 'E2_to_E3_weights': 'e2_final/pvuad_last_model.pth', 'E2_to_E3_prototype_bank': 'e2_final/pvuad_last_checkpoint.pth:prototype_bank', 'E3_to_final_tests': 'e3_tdh/pvuad_last_model.pth', 'intermediate_checkpoint_selection': False, 'E2_eval_period': 60, 'E3_eval_period': 25, 'final_protocols': ['A2G', 'G2A', 'G2AG'], 'final_flip_tta': True, 'reranking': False, 'lagper_eval_junk_rule': 'remove same PID + same camera only'}
Report zip: /kaggle/working/pvuad_lagper_s3clip_e2_60_e3_25_transreid_reports.zip
FINAL LAGPeR-S3CLIP:

  protocol      mAP   Rank-1   Rank-5  Rank-10
2      A2G  27.7150  38.0827  52.9547  61.0965
3      G2A  30.8546  31.7137  44.4517  51.8056
4     G2AG  18.0829  21.8976  33.4865  41.0046

## Cách chạy trên Kaggle

1. Chọn **GPU T4 ×2**.
2. Attach dataset **LAGPeR-S3CLIP**. Không cần đúng một Kaggle path cố định:
   notebook tự tìm root có đủ `bounding_box_train`, `query_aerial`, `query_ground`,
   `bounding_box_test_aerial`, `bounding_box_test_ground`, `bounding_box_gallery`.
3. Phiên đầu bật Internet để tải official `vit_transreid_msmt.pth`, hoặc attach
   checkpoint đó làm Kaggle Input.
4. Chọn **Save Version → Save & Run All**.
5. Nếu notebook dừng an toàn vì giới hạn phiên, phiên sau attach **output của chính
   version ngay trước đó** làm Input rồi chạy lại **Save & Run All**.
6. E2 train cố định **60 epochs**. E3 nhận **LAST E2 model + prototype bank từ
   LAST E2 checkpoint**, rồi train cố định **25 epochs**.
7. Final inference dùng **LAST E3 model + horizontal-flip TTA**, không dùng
   `pvuad_best_model.pth` để chọn checkpoint.
8. Notebook tự chạy ba protocol: **A→G**, **G→A**, và **G→A+G**, rồi xuất:
   `/kaggle/working/pvuad_lagper_s3clip_e2_60_e3_25_transreid_reports.zip`.
9. Nếu cell audit báo camera-view inference không khớp, điền
   `AERIAL_CAMERA_IDS_OVERRIDE` ở cell Settings bằng **7 raw aerial camera IDs**
   của LAGPeR-S3CLIP rồi chạy lại từ đầu.